### ISSUE TITLE
[BUG] Export CSV - Submitted and Updated data column not in EST zone.

### ISSUE THREAD

**Issue by lakshman-anusha** [formio/formio#1001]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 6.9.34 (Application: 7.0.8, Renderer: 4.9.27-rc.4)
- Formio.js version: 4.9.27
- Browser: Chrome

## Steps to Reproduce
1. Create a form with test fields
2. Create some submission
3. Review on Data tab Submitted and Updated column
4. Export to CSV

## Expected behavior
3. Submitted and Updated date column shows the time in EST zone.
4. CSV Created and Modified date column shows the time in EST zone.

## Observed behavior
3. Submitted and Updated date column shows the time in EST zone (same as expected)
4. CSV Created and Modified date column shows the time in UTC zone.

## Example
**Data tab**
![image](https://user-images.githubusercontent.com/53343602/82587239-cd351900-9b66-11ea-89ed-34e7d3cfb276.png)
**CSV**
![image](https://user-images.githubusercontent.com/53343602/82587902-f86c3800-9b67-11ea-97ef-74f6be61e94e.png)

**Comment by cmcortez** [comment]
@lakshman-anusha Suggest you use a formula function within the Excel file to customize the data.

**Comment by lakshman-anusha** [comment]
Thanks for your reply!
Formula for excel processing is fine, but what happens if the form submission JSON feeds into a different system?

**Comment by randallknutson** [comment]
Time is always stored in UTC and it is up to the displaying system to decide what timezone to display it in. We don't make any assumptions about where the user is located when formatting the data.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
