### ISSUE TITLE
[QUESTION] Permanently delete submissions

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#1021]
Currently the formio server when performing a delete operation, it updates the mongo document and sets the `deleted` property to the current timestamp.  When requesting a submission, the formio server filters out all documents with `deleted` property not null, this way, to the user it seems the submission does not exists (although you may still access deleted submissions using the export endpoint and the `x-query` header). 

The problem is the following:

When the rotation of deleted submissions is high, because these submissions are not deleted form the database, just updated, the mongo collection keeps on growing and using more memory / disk space.  On the long term this could bring some performance issues.

For example, if on average, the submission / document size is 10 Kb, and you have 200.000 deletes / month, we are talking about 2 GB of unnecessary data that you cannot get rid of.

Is there a way to avoid this or plans in the future to implement a workaround?

**Comment by randallknutson** [comment]
You can manually delete this in a cron task in mongo directly. We do have plans in our next gen server to automatically delete items after a month (this timeframe can be adjusted). This will basically be done with a cron task that looks for the deleted timestamp older than that timeframe.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
