### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by gag29** [formio/formio#1022]
Is their anyway to get the form from the json code directly ? anywhere on your next portal  we have seen that for individual components

**Comment by jhen1422** [comment]
@gag29 On our 'Next' you can click the 'JSON' button next to the form name to retrieve the form JSON https://share.getcloudapp.com/L1upJo1p.

**Comment by gag29** [comment]
can we have the reverse of that , getting the form out of json @jhen1422

**Comment by jhen1422** [comment]
@gag29 You can use a tool like Postman to post JSON to a form within your project.
