### ISSUE TITLE
[BUG] Field masks are not working. Reports no match.

### ISSUE THREAD

**Issue by alanm101** [formio/formio#1031]
_**Update: Safari only - See comments below.**_

## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: formiojs@4.10.5
- Frontend framework: node 12.18.1
- Browser: Safari on MacOS Catalina
- Browser version:

## Steps to Reproduce
1. Clean install of MongoDB 
2. Clean install of formio 2.0.0-rc.5. It will fail.
3. Manually install  'request-promise-native' (left out of latest package.json)
4. Redo npm start and install basic app.
5. Create a simple form with a text field of mask, say, '99-99-99' and Phone number field. 
6. Enter values as per masks.
7. Submit fails on text field: ValidationError: Text does not match the mask.
8. Refresh to clear the text error.
8. Enter phone number field.
9. Submit fails as well. ValidationError: Phone Number does not match the mask.
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

Screenshots attached.

This behaviour started about a week ago. Might have been after an npm update.

<img width="610" alt="CleanShot 2020-07-02 at 20 01 32@2x" src="https://user-images.githubusercontent.com/2248721/86394855-824b0d00-bc9f-11ea-945d-a93680d371c2.png">
<br>
<img width="625" alt="CleanShot 2020-07-02 at 20 02 19@2x" src="https://user-images.githubusercontent.com/2248721/86394869-8840ee00-bc9f-11ea-87b5-44ec6bbd8aee.png">

**Comment by alanm101** [comment]
Update: I was incorrect about the browsers. Works fine on Chrome and Firefox. Seems to be limited to Safari. And, yes, I'm testing on a Mac. Please ignore this until I have explored whether it related to my Mac or whether it's a general Safari issue.

**Comment by alanm101** [comment]
Update: Here is the browser console log. Unauthorized. I noticed also that the problem now happens also with formio 2.0.0-beta.4. 
<img width="889" alt="CleanShot 2020-07-03 at 12 30 23@2x" src="https://user-images.githubusercontent.com/2248721/86461140-d3074800-bd29-11ea-8e99-ca7a7ceeaf29.png"><br>
<img width="796" alt="CleanShot 2020-07-03 at 12 29 41@2x" src="https://user-images.githubusercontent.com/2248721/86461176-ddc1dd00-bd29-11ea-9b9c-363c95e8762f.png">

**Comment by randallknutson** [comment]
Thanks for the info. The 2.x branch of the server is a ground up rewrite that is currently undergoing testing. This bug is that the server is returning the error format differently than before when it shouldn't be. I'll add this as an item to get fixed before we do a release.

**Comment by alanm101** [comment]
Thanks mate
