### ISSUE TITLE
Override the default value of the enableTime flag on the datetime component

### ISSUE THREAD

**Issue by ishake** [formio/formio#1032]
Is it possible to override the default value of the enableTime flag on the datetime component?

I'm essentially looking to provide users with a Date picker, but not a DateTime picker, in the form builder. I found a way to remove the time tab easily enough by passing
{
key: 'time',
ignore: true,
},
into the editform.dateTime options. However, so far I haven't found a way to both disable this tab and default enableTime to false.

Thanks in advance for any help!

**Comment by travist** [comment]
You could always override the schema for the DateTime component like this...

```js
var dateTimeSchema = Formio.Components.components.datetime.schema();
// Make whatever changes you want to make to the default schema here.
dateTimeSchema.enableTime = false;
Formio.Components.components.datetime.schema = function() {
  return dateTimeSchema;
};
```

You can actually run this in the console when browsing @ https://portal.form.io to try it out.

**Comment by ishake** [comment]
Thanks! Here's my current (hacky but working) implementation in case it helps someone else...

```
import {Components} from 'formiojs';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const origDateTimeComponent: any = Components.components.datetime;

const dateOnlySchema = origDateTimeComponent.schema(null);
dateOnlySchema.label = 'Date';
dateOnlySchema.enableTime = false;

const dateBuilderInfo = origDateTimeComponent.builderInfo;

class DateTimeOverrideComponent extends origDateTimeComponent {
  static schema() {
    return dateOnlySchema;
  }

  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  static get builderInfo() {
    return {
      ...dateBuilderInfo,
      title: 'Date',
      schema: dateOnlySchema,
    };
  }
}

export default DateTimeOverrideComponent;
```

Then...

```
import {Components} from 'formiojs';
...
Components.setComponents({
  datetime: DateTimeOverrideComponent,
});
```
