### ISSUE TITLE
[QUESTION]: OR Query Submission

### ISSUE THREAD

**Issue by lailapfit** [formio/formio#1035]
Hello,

Is there a way to query submissions like the following:

Search input = Roadwork
 
/submission?data.fieldOne=Roadwork&data.fieldTwo=Roadwork

The above call will search for submissions with both fields equals to Roadwork, and I am looking for a way to call one API that will look for if fieldOne equals to Roadwork OR fieldTwo equals to Roadwork.

Is that a possibility?

Thank you

**Comment by randallknutson** [comment]
Unfortunately our api assumes an AND conjunction for all query parameters. One thing you can do is create a hidden calculated field and write some logic to set its value to either of those two fields and then filter on that field.

**Comment by lailapfit** [comment]
Thanks for your response @randallknutson!
