### ISSUE TITLE
[BUG] Multiple admin user submissions

### ISSUE THREAD

**Issue by AudreyCb** [formio/formio#1044]
## Environment

- Hosting type
  - [x] Form.io
    - Version: 1.63.5

## Observed behavior
Every times the api is relaunched, we have a new admin@example user that is created. We tried to save the email admin field as unique but no change.

## Expected behavior
Every times the api is relaunched, if the admin user exists it doesn't need to be created.

**Comment by wag110894** [comment]
Hello @AudreyCb, can you provide a video of the issue taking place as well as your project json?

**Comment by tiberiu89** [comment]
This is still an issue, at least on docker. Everytime I start containers giving the admin credentials as env variables, it seems a new admin user is created

![image](https://user-images.githubusercontent.com/42996791/123605780-e21dba80-d804-11eb-9dc1-0d6cee9c6caf.png)
