### ISSUE TITLE
[Question] File Upload Minio Handling

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#1045]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment: On-premise Portal 
    - Version: 6.9.34

Hi, 

Please correct me if I am wrong - from my understanding Form.io uses the presign URL for PUT operation when it uploads to Min.IO file storage. I'm just wondering what are the values for Upload/Download token expiry period?
Are we able to customize these values ourselves?

Thank you

**Comment by travist** [comment]
This is only if you use the "S3" upload mechanism which actually has the Expiration as a parameter when setting up the S3 connection settings (which are found in your project settings). This parameter is then passed to the provider (either S3 or Minio) to determine how long the signed upload url should be valid. Is this what you are asking for?

**Comment by phucduong86** [comment]
@travist  yes it is the mechanism that we use. Once the file is uploaded the server returns a presigned URL for downloading the file. I want to know how is the download expiration period being set or at least what is the current value?

Thank you

**Comment by randallknutson** [comment]
This is currently set to 15 minutes and doesn't appear to be configurable right now. The idea is that we don't create the signed url until the user is already in process of uploading or downloading the file so after that it can immediately create the signed url and use it.

**Comment by phucduong86** [comment]
Thank you @randallknutson
