### ISSUE TITLE
[BUG] Getting Response in console using FETCH API call, but not able to set into a component as value.

### ISSUE THREAD

**Issue by NiteshNagar** [formio/formio#1048]
## Environment
- Hosting type: Local deployment
    - Version: 
- Formio.js version:  4.11.0
- Frontend framework:
- Browser: Chrome
- Browser version: Version 84.0.4147.105

## Steps to Reproduce
1. Add one text filed component.
2. In Default Value (write below JAVA Script)
      var obj; var d;
     fetch('http://10.0.116.247:8090/equotes/ajaxRule?rulebookName=TestRB_Ajax&score_input=nitesh')
     .then(res => res.json())
    .then(data => obj = data); 
     d=obj[0];
    value = d;
3. Go to console tab in browser. 
4. I am getting response in array form.

## Expected behavior
It should get response from the URL. 

## Observed behavior
showing Error message. "Uncaught TypeError: Cannot read property '0' of undefined
    at <anonymous>:5:9"

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:
// JSON Template
{
            "label": "Text Field",
            "tableView": true,
            "customDefaultValue": "var obj; var d;\nfetch('http://10.0.116.247:8090/equotes/ajaxRule?rulebookName=TestRB_Ajax&amp;score_input=nitesh')\n  .then(res =&gt; res.json())\n  .then(data =&gt; obj = data)\n  .then(alert(obj));\n   d=obj[0];\n  value = d;",
            "key": "textField",
     "type": "textfield",
            "input": true
        }

![JSON Issue](https://user-images.githubusercontent.com/40713206/88669818-00190180-d102-11ea-8d71-c884aa0a7944.png)

       

```

**Comment by travist** [comment]
The calculated value section is not intended to be asynchronous.  I can also tell by your code that you are setting ```d=obj[0]``` when the response has not yet been received.  Try the following.

```js
fetch('https:........').then(function(res) {
  return res.json();
}).then(function(item) {
  instance.setValue(item[0]);
});;
```

**Comment by NiteshNagar** [comment]
Thanks a ton.. It works for me..
