### ISSUE TITLE
Not able to save FETCH API response into a text component as value.

### ISSUE THREAD

**Issue by NiteshNagar** [formio/formio#1049]
Hi Nitesh here.

I am getting response from url by using fetch API. 
**I used below syntax.** 
                      var obj;
                     fetch('http://10.0.116.247:8090/equotes/ajaxRule?rulebookName=TestRB_Ajax&score_input=nitesh')
                     .then(res => res.json())
                     .then(data => obj = data)
                     .then(() => console.log(obj));
                     value = obj;

I am getting response in console but value not set on a particular filed.

**Comment by randallknutson** [comment]
The fetch is occurring asynchronously while the value return happens synchronously. You will need to use instance.setValue() instead of returning the value directly.

**Comment by NiteshNagar** [comment]
Thanks it works.. Cheers!!
