### ISSUE TITLE
[QUESTION] Field conditionals within a dataGrid

### ISSUE THREAD

**Issue by tmman2** [formio/formio#1058]
Is there an easy way to use a conditional within a dataGrid element so that the logic is independent for each row?

E.g. If a radio button is selected in row X then display a text field in row X.

**Comment by wag110894** [comment]
Hello @tmman2, do you mean something like this: https://liwcktjpuzmmsgc.form.io/advanced ?

When you choose "yes", then the text area will show. You will see that this is independent for each row.

**Comment by tmman2** [comment]
Wow, that was too easy.  Thanks for the quick reply... I am about 2 hours in with formio and still sorting through it :)  Thanks again!
