### ISSUE TITLE
[HELP] How do we setup our Data Grid as a Menu, thru the tooling available (portal.fom.io)?

### ISSUE THREAD

**Issue by MalkyTheKid** [formio/formio#1059]
Hi there,

We are exploring the multi-step form functionalities of FormIO by setting up our form as a "Wizard"
(https://pro.formview.io/#/vopxbjfifjgomcz/formiodevjustenergyplansandprices?header=1&reset=1) (please type in any zip code)

On the second step(offers), we've setup this datagrid as a sort of menu that when a user clicks on "SELECT" on the grid. The data of that row should be submitted on the third step (Service Address). How does one do that thru the portal interface? 

On this datagrid we setup [planName], [rateKWH] and [termMonths] as text fields

We've tried to follow this: (https://formio.github.io/formio.js/app/examples/customwizard.html)
and we see the event "wizardSave". We've tried setting the "action" on the button of the datagrid into "EVENT"  and we setup the "Button Event" as "wizardSave"

Initially we thought that if we trigger that event, then we could call in the selected row's data anywhere on the form {{data.planName}}, {{data.rateKWH}}, etc. but... we're not able to get the selected data.

How do we go about to properly do this?

**Comment by travist** [comment]
In order to gain access to data within a Data Grid row, you must use the ```row``` variable instead of ```data```.  Please try this again but using ```row``` instead of ```data``` like ```{{ row.planName }}``` and ```{{ row.rateKWH }}```.

**Comment by MalkyTheKid** [comment]
Hi, 
Thanks for the assistance.
We did try this, but unfortunately {{ row.planName } returned nothing.
Also tried {{ productGrid.row.planName }} and {{ data.productGrid.row.planName }} to no effect..
(productGrid being the name of the Data Grid)

Are we executing the correct event, "wizardSave"?

**Comment by MalkyTheKid** [comment]
in the row's button, how should we setup our "Action"? We see Save in state, but even if we set it as draft it still submits the entire form...

**Comment by MalkyTheKid** [comment]
He are images to illustrate what we are trying to achieve:
Below is a data grid we're leveraging as a menu named (named: [productGrid]):
![image](https://user-images.githubusercontent.com/15683727/89911718-bf1ff300-dbbf-11ea-84d9-829a047bda93.png)

How do we set it up so that if we click on the purple "Select", the values are passed on the next page?
![image](https://user-images.githubusercontent.com/15683727/89911888-f393af00-dbbf-11ea-8680-58a98cee8fcb.png)

**Comment by randallknutson** [comment]
If you need to access data in a datagrid outside of the datagrid itself, you will need to refer to it by the index. For example, data.productGrid[0].planName. If there are multiple rows there will also be a data.productGrid[1].planName and so on.

**Comment by MalkyTheKid** [comment]
Thanks Randall this works. Tested data.productGrid[0].planName and got the plan... but only the first row

What we did is a mix of {{row.}} to select the current item with a "Custom" setup button,
and then we pass that to a hidden textfield, then we call it on the next page with {{data.}}

Quick question.. is there a way for us to not use a hidden textfield, and then directly call that value?
can we set the script for '0' in 'data.productGrid[0].planName' to be dynamic/what the user selected?

**Comment by randallknutson** [comment]
The key to this is going to be in the code of the "Select" button, you are going to grab the rowIndex value and set it in a hidden field outside of the datagrid. For example, you can have a hidden field with the api property name of "selectedRow" then in the button you can set data.selectedRow = rowIndex. The exactly syntax of this may be different.

Then you can get the value for the selected row with data.productGrid[data.selectedRow].planName

**Comment by MalkyTheKid** [comment]
Thanks Randall, sorry for the late response. 
You have been very helpful. Grateful for the support
