### ISSUE TITLE
[QUESTION] Pre-Populating field with value from remote mySQL DB

### ISSUE THREAD

**Issue by tmman2** [formio/formio#1060]
Is it possible to connect my form to an external mySQL DB so I can pre-populate a field with a value on load of the form?

**Comment by randallknutson** [comment]
We don't pull data directly from a database into our forms. If you can make the data available via a rest api you can pull the data in with the datasource component.

**Comment by tmman2** [comment]
Thanks for the quick reply.  Based on your comment, I wrote a quick API via PHP to grab some data via SQL and transpose it into JSON.  However, I am not able to get it to load the data into the form.

In my troubleshooting I was unable to figure out the "data source" component (also couldn't find any documentation on it) so I started messing with the Select Component based on this documentation (https://help.form.io/userguide/form-components/#select).

I could not get it to load my data so I attempted to troubleshoot by doing 2 things:
1. I used the example URL given in the documentation: https://cdn.rawgit.com/mshafrir/2646763/raw/states_titlecase.json.  This worked perfectly
2. I then coped that JSON over to my server and tried to access it there and it failed to load.  However the data seems publicly visible and has a 755 permission value (https://pettyquick.com/app/pq-api/example2.json).

Ultimately, I want to use the following URL: (https://pettyquick.com/app/pq-api/pq-api.php?date=2020-08-10) where the date parameter would be dynamic based on the date chosen within the form to load a single 'Balance' value and then compare that with some other user input form values.

Any idea what might be going on here?

**Comment by travist** [comment]
It is giving you any errors in the console when you try to load that API into the browser?

**Comment by tmman2** [comment]
Hey, yeah... after looking through the console more this morning it appears it is a CORS issue.

"Access to fetch at 'https://pettyquick.com/app/pq-api/pq-api.php?date=2020-08-10' from origin 'https://pro.formview.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

It's currently set as a wildcard (*) in the settings of form.io

**Comment by randallknutson** [comment]
We don't have good documentation on the datasource component yet but it is really powerful. The trick to populating data into a form is the following:

1. In the Datasource component under the Trigger tab, add a "Fire Event" event like "fetchedData". Take note of the API Property Name for the datasource (is dataSource by default)
2. In the component you want to set the value, go to the Logic tab. Add a new Logic item and set the trigger type to "Event" and set the Event Name to what you set in the "Fire Event" of the Datasource. Add an action and set the type to "Value". Then in the value set it to "value = data.dataSource.myproperty" where dataSource is the API Property of the datasource and myproperty is whatever you want to get from the API result.

Also be aware the the Datasource is a premium component and only available on paid plans. 

In addition, you can load data with something like this http://formio.github.io/formio.js/app/examples/externalload.html

**Comment by tmman2** [comment]
I will definitely take a look through this today and see what I can sort.  I appreciate the response.

I am currently on a trial, will premium components be available during this or do I need to switch over to paid now?

**Comment by randallknutson** [comment]
The reason is that fetch runs asynchronously so value is no longer there by the time you set it. You can do instance.setValue(data[0].Balance) instead.
