### ISSUE TITLE
[BUG] Using Day component causes moment.js error that breaks logs

### ISSUE THREAD

**Issue by tvhweb** [formio/formio#1063]
## Environment
Self hosted Formio enterprise - docker formio-enterprise:7.0.0-rc.12

Running 3 containers on an ec2 instance:
- nginx
- formio
- logspout (shipping logs to Papertrail)

## Steps to Reproduce
1. Create a form using the day component
2. Create a submission
3. The submission is successful but a backend error occurs that prevents any further formio logs being created.
4. Restart the container and logs will work again.

## Error log

`Aug 19 15:55:19 formio 08439e9a3674 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Aug 19 15:55:19 formio 08439e9a3674 Arguments: 
Aug 19 15:55:19 formio 08439e9a3674 [0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 07/25/2018, _f: undefined, _strict: undefined, _locale: [object Object]
Aug 19 15:55:19 formio 08439e9a3674 Error: 
Aug 19 15:55:19 formio 08439e9a3674     at Function.createFromInputFallback (/src/node_modules/moment/moment.js:319:25)
Aug 19 15:55:19 formio 08439e9a3674     at configFromString (/src/node_modules/moment/moment.js:2536:19)
Aug 19 15:55:19 formio 08439e9a3674     at configFromInput (/src/node_modules/moment/moment.js:2978:13)
Aug 19 15:55:19 formio 08439e9a3674     at prepareConfig (/src/node_modules/moment/moment.js:2961:13)
Aug 19 15:55:19 formio 08439e9a3674     at createFromConfig (/src/node_modules/moment/moment.js:2928:44)
Aug 19 15:55:19 formio 08439e9a3674     at createLocalOrUTC (/src/node_modules/moment/moment.js:3022:16)
Aug 19 15:55:19 formio 08439e9a3674     at createLocal (/src/node_modules/moment/moment.js:3026:16)
Aug 19 15:55:19 formio 08439e9a3674     at hooks (/src/node_modules/moment/moment.js:16:29)
Aug 19 15:55:19 formio 08439e9a3674     at ValidationChecker.check (/src/node_modules/formio/node_modules/formiojs/validator/Validator.js:766:42)
Aug 19 15:55:19 formio 08439e9a3674     at ValidationChecker.checkValidator (/src/node_modules/formio/node_modules/formiojs/validator/Validator.js:921:43)
Aug 19 15:55:19 formio 08439e9a3674     at ValidationChecker.validate (/src/node_modules/formio/node_modules/formiojs/validator/Validator.js:954:34)
Aug 19 15:55:19 formio 08439e9a3674     at /src/node_modules/formio/node_modules/formiojs/validator/Validator.js:1037:25
Aug 19 15:55:19 formio 08439e9a3674     at arrayMap (/src/node_modules/lodash/lodash.js:639:23)
Aug 19 15:55:19 formio 08439e9a3674     at Function.map (/src/node_modules/lodash/lodash.js:9580:14)
Aug 19 15:55:19 formio 08439e9a3674     at /src/node_modules/formio/node_modules/formiojs/validator/Validator.js:1036:32
Aug 19 15:55:19 formio 08439e9a3674     at arrayMap (/src/node_modules/lodash/lodash.js:639:23)
Aug 19 15:55:19 formio 08439e9a3674     at Function.map (/src/node_modules/lodash/lodash.js:9580:14)
Aug 19 15:55:19 formio 08439e9a3674     at interceptor (/src/node_modules/lodash/lodash.js:17046:35)
Aug 19 15:55:19 formio 08439e9a3674     at thru (/src/node_modules/lodash/lodash.js:8817:14)
Aug 19 15:55:19 formio 08439e9a3674     at /src/node_modules/lodash/lodash.js:4388:28
Aug 19 15:55:19 formio 08439e9a3674     at arrayReduce (/src/node_modules/lodash/lodash.js:683:21)
Aug 19 15:55:19 formio 08439e9a3674     at baseWrapperValue (/src/node_modules/lodash/lodash.js:4387:14)`

**Comment by travist** [comment]
Thanks for letting us know. We will take a look asap.

Are these just warnings in the console, or are they causing the server to crash?

**Comment by tvhweb** [comment]
Thanks. These are error logs from the server container. Formio continues to run, but something breaks that prevents any further logs routing until the formio container is restarted.

**Comment by wag110894** [comment]
No longer an issue from mtvh.
