### ISSUE TITLE
Disabled a field using logic is not working.

### ISSUE THREAD

**Issue by NiteshNagar** [formio/formio#1064]
![Disabled Logic ](https://user-images.githubusercontent.com/40713206/90763297-116dbc00-e304-11ea-87ec-dc697909babc.jpg)
 Hi Team. Nitesh here, 

I am writing logic to mark a components as disabled but it won't for me.

**Comment by wag110894** [comment]
Can you provide a video of this not working as well as a form embed or json?

**Comment by wag110894** [comment]
@NiteshNagar 
Thank you for providing the video. We are able to replicate this issue on our side and have added this to our backlog. We welcome a pull request and we also have a process to expedite this issue if you are interested. 

Please let us know if you are interested in expediting and we can get the process started. For reference, the ticket number is FJS-1185. 

We will let you know once this issue has been resolved.

**Comment by jhen1422** [comment]
@NiteshNagar 
This issue should be resolved in formio.js version 4.12.0-rc13 >
