### ISSUE TITLE
Data map Label not changed.

### ISSUE THREAD

**Issue by NiteshNagar** [formio/formio#1068]
I have drag and drop a data map component. 
When I change the label of Key It won't change.. Only Value label got chan
[Data Map_Key Labelis not changed..zip](https://github.com/formio/formio/files/5108047/Data.Map_Key.Labelis.not.changed.zip)
ged

**Comment by wag110894** [comment]
Hello @NiteshNagar, 

We have created a ticket and have added this to our backlog. We welcome a pull request and have a process to expedite if you are interested. For reference, the ticket number is FJS-1179.

If you are interested in expediting, please let us know and we can get the process going.

**Comment by jhen1422** [comment]
@NiteshNagar 
This issue should be resolved in formio.js 4.12.0-rc19
