### ISSUE TITLE
When I Change Edit / Data Grid in model edit than it's showing complex data.  

### ISSUE THREAD

**Issue by NiteshNagar** [formio/formio#1071]
Hi Team, 
Nitesh here, In model edit view Data Grid, Edit Grid and Data map is show as complex data. In last version it works fine for me. 
[DataGrid_ComplexData (2).zip](https://github.com/formio/formio/files/5119636/DataGrid_ComplexData.2.zip)

**Comment by NiteshNagar** [comment]
[dataGrid.zip](https://github.com/formio/formio/files/5119647/dataGrid.zip)

**Comment by wag110894** [comment]
@NiteshNagar, This is working correctly as this data will show complex data.

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
