### ISSUE TITLE
Datagrid not triggering JS in calculated value of it's children

### ISSUE THREAD

**Issue by purviR** [formio/formio#1072]
value = rowIndex + 1 is the calculated value for a text box field. In the image, we added 4 rows in the grid, and deleted row 2 and 3. The 4th row did not recalculate itself to show the new index as 2. When we add or delete a row in this data grid, the onChange event is also not being fired. Tried using RefreshOn and RedrawOn options, but they did not help. 
Is there any other way for us to calculate and show indexes in a data grid ?
![datagrid](https://user-images.githubusercontent.com/32067408/91127540-1647bc80-e6c4-11ea-9921-bae4b8ede5de.png)

**Comment by wag110894** [comment]
@purviR can you provide a jsfiddle of the issue occurring as well as the version of formio.js that you are running?

**Comment by PrajwalK** [comment]
This issue has been fixed in the latest version of formio 4.11.3

Please upgrade to the latest version

![image](https://user-images.githubusercontent.com/13089873/91634653-85e4e100-ea0f-11ea-8233-5fc1869d1681.png)
