### ISSUE TITLE
[BUG] Need to send an email to the specified address mentioned in a hidden field of Email form.

### ISSUE THREAD

**Issue by shobhitvdb** [formio/formio#1074]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. create a form on form.io and add an action for emailer.
2. After filling the form, not able to send an email on the address mentioned in the form.
3. 

## Expected behavior
We need the ability to send emails to the specified email address in the hidden field.
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
Can you provide the action settings that you are adding to the form in order for this to occur?

**Comment by shobhitvdb** [comment]
Hey Wag,
I want to change the submission format of date into my email template. Can you help me in that.
For example currently I am getting 2020-09-08T18:30:00.000Z.
But I need a format like Monday 15 September in IST

**Comment by randallknutson** [comment]
You should be able to send an email to a hidden field. Just make sure there is actually a Hidden Component field on the form and it has the value of the email address. Give it a property name like "hiddenEmail" and then you can send the email to data.hiddenEmail.

As for formatting dates, you should have a moment variable that can use the moment.js library to format the dates.

**Comment by shobhitvdb** [comment]
Hey Randalf,
Please help me in a scenario,
We are using a Date time box in one of our forms and we have disabled time from that. and we are getting time 1 day before the time provided. For example:
We have selected the date as "Sep 12, 2020 (Sat)", and we are getting the date in data as "2020-09-11T18:30:00.000Z".

How can I get the exact date that was put in the form.

**Comment by randallknutson** [comment]
Set the Display in Timezone setting to "Submitter". That way it will display the date from where the user was when they submitted the form.

**Comment by shobhitvdb** [comment]
We do have four options in "Display in Timezone"

- of Viewer
- of Submission
- of Location
- UTC

We have already selected "of Submission", but we are getting the Date 1 day before in the data, and one more thing we have disabled the time from this DateTime field.

Please provide me the further steps.
Thanks

**Comment by wag110894** [comment]
Hello @shobhitvdb, we are not seeing this issue on our side.  

Here is our sandbox that we are using :https://formio.github.io/formio.js/app/sandbox

Load the following sandbox id to the Load Sandbox section: 5f5f95674b131db3da0b14f9 and then hit the load sandbox button. You will see your form appear. 

Go to the bottom where the form is being rendered and try selecting a date. You will see to the right of the form the submission data is showing the correct date. 

I hope that this helps.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
