### ISSUE TITLE
In render Mode HTMl form feilds alignment is not proper. [BUG] 

### ISSUE THREAD

**Issue by viswateja1992** [formio/formio#1077]
In render mode html form fields are not aligned properly. Form Label and value are rendering horizontally instead of vertically. 
 
<img width="311" alt="Capture" src="https://user-images.githubusercontent.com/9268673/91701723-5233c380-eb95-11ea-8783-c78abc24d9d6.PNG">

https://jsfiddle.net/gxmwhr6n

How to render those form fields vertically.

**Comment by wag110894** [comment]
You can place these components in either a Table Component or in a Column Component. Both are located in the Layout section of the builder.

More documentation is available here: https://help.form.io/userguide/layout-components/

**Comment by test3698741** [comment]
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.form.io/formiojs/formio.full.min.css">
<script src="https://cdn.form.io/formiojs/formio.full.min.js"></script>





<div id="formio"></div>




<script>

    const formJson = {
        display: "form",
        settings: {
            "pdf": {
                "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
                "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
            }
        },
        components: [
            {
                label: "Select",
                widget: "choicesjs",
                tableView: true,
                multiple: true,
                dataSrc: "json",
                data: {
                    json: [
                        "apple",
                        "banana",
                        "orange123",
                        "apple333",
                        "banana4444"
                    ]
                },
                key: "select",
                type: "select",
                input: true
            },
            {
                label: "Number",
                mask: false,
                tableView: false,
                delimiter: false,
                requireDecimal: false,
                inputFormat: "plain",
                truncateMultipleSpaces: false,
                key: "number",
                type: "number",
                input: true
            },
            {
                type: "button",
                label: "Submit",
                key: "submit",
                disableOnInvalid: true,
                input: true,
                tableView: false
            }
        ]
    };
    const element = document.getElementById('formio');


    Formio.createForm(element, formJson, { renderMode: 'html' })
        .then(form => {
            debugger;

        })
        .catch(error => {
            console.error(error);
        });


</script>




@wag110894 
I have the same problem even though I added table components

**Comment by daneformio** [comment]
@test3698741 your components list does not have a table component in it. Can you add a table component with the form builder, and then add your components to the table component?

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
