### ISSUE TITLE
Updates to Validator.js and new usage?

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#1078]
The usage of Validator.js in src/resources/Validator.js was typically like:

```js
const Validator = require('formio/src/resources/Validator.js');

const submissionModel = function(doc, field, skipId) {};

function validate(req, res, next){
    const validationRequest = req.body;

    const body = {
        "data": validationRequest.submission.data,
        "owner": "",
        "access": [],
        "form": ""
    };

    const token = "";

    const validator = new Validator(validationRequest.schema, submissionModel, token);

    validator.validate(body, (err, submission) => {
...
```

Noticing that new updates with Formio with the legacyValidator, and the updated Validator.js.

I see in the new validator, there is the "hook" variable.  

Any direction you can provide on proper usage of the new validator?

The use case here is the Schema and submission are sent to the validator on each validation request, rather than looked up from the DB.

Thanks!

**Comment by randallknutson** [comment]
I think you've pretty much got it figured it out. The hook is primarily there to make a few changes within the validator which is also used in the browser. For example, the unique validator needs to know what the submission model is so we need to pass it in. We don't have good documentation beyond the example in formio so your best bet is to look at the code like you are already doing in how it is working.

**Comment by StephenOTT** [comment]
@randallknutson I was hitting issues related to hooks.
had to add: `const hook = require('formio/src/util/hook');`

and then rewrite similar to your new code:

```
const _Validator = Validator
    _Validator.setHook(hook())
    const validator = new _Validator(validationRequest.schema, submissionModel, {}, {});
```

is there something to do to create a ~blank hook?

And then wehn rewrite as:

```
    const _Validator = Validator
    _Validator.setHook(hook())
    const validator = new _Validator(validationRequest.schema, submissionModel, {}, {});
```

I get 

```
`TypeError: Cannot read property 'hooks' of undefined
    at Object.alter (/app/node_modules/formio/src/util/hook.js:30:16)
    at Validator.evalContext (/app/node_modules/formio/src/resources/Validator.js:40:17)
    at TextFieldComponent.Validator.Formio.Components.components.component.evalContext (/app/node_modules/formio/src/resources/Validator.js:27:42)
    at TextFieldComponent.evaluate (app/node_modules/formiojs/Element.js:668:46)
    at TextFieldComponent.calculateComponentValue (/app/node_modules/formiojs/components/_classes/component/Component.js:2374:34)
    at TextFieldComponent.calculateValue (/app/node_modules/formiojs/components/_classes/component/Component.js:2432:19)
    at /app/node_modules/formiojs/components/_classes/nested/NestedComponent.js:688:21
    at Array.reduce (<anonymous>)
    at Webform.calculateValue (/app/node_modules/formiojs/components/_classes/nested/NestedComponent.js:687:35)
    at Formio.createForm.then (/app/node_modules/formio/src/resources/Validator.js:106:12)
    at <anonymous>

```

Any ideas on how to handle this?

**Comment by StephenOTT** [comment]
What is the difference between the form schema and the submission model?

Previously we seemed to be able to pass in the Full schema + the submission object and it would seem to function.  Is there a different flow to be followed?

**Comment by randallknutson** [comment]
The form schema is the definition of the form in json. The submission model is the database model that can be used to load submissions. 

The basic process is like this:
const validator = new Validator(formSchema, submissionModel, hooks);

validator.validate(submission);

**Comment by StephenOTT** [comment]
@randallknutson the constructor does not seem to match your example:
https://github.com/formio/formio/blob/master/src/resources/Validator.js#L19

What we found is that we dont need to pass an actual submissionModel for 99% of functionality.  So it is just a dummy function.

**Comment by randallknutson** [comment]
I'm not sure you need to pass a submission model since it is currently only used by the unique validator. As long as you aren't using unique validations you should be fine passing a dummy function for the submission model.

**Comment by StephenOTT** [comment]
@randallknutson  The issue we are running into at the moment is related to hooks.  Can a hook object be created as a dummy object? What would the hooks be used for on server side?

**Comment by randallknutson** [comment]
You should be able to make a dummy hook. It is mainly used for manually removing some values when hidden. It shouldn't really be needed to do anything with the hooks.

**Comment by ramveeru** [comment]
Hello @StephenOTT , Good day! We're facing a similar issue. have you figured it out?
