### ISSUE TITLE
 Dynamically generate the data grid content

### ISSUE THREAD

**Issue by viswateja1992** [formio/formio#1082]
I have a Data grid with default value as below. Products drop is getting populated from URL data source. If drop down has 5 values 5 rows in the Data grid should get generated and drop down in each row should get defaulted to each drop down value.
How this can be achieved.  

<img width="685" alt="Capture" src="https://user-images.githubusercontent.com/9268673/92414588-8a796a00-f172-11ea-8dc1-dad7978798c0.PNG">

**Comment by randallknutson** [comment]
You will need to pull the Products list into data somewhere instead of just as a dropdown list. Then you can set the default value for the datagrid to the products values which is an array. The will create the 5 rows and set the products value to each item.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
