### ISSUE TITLE
Conditional Wizard, no value in submissions for pages

### ISSUE THREAD

**Issue by Mfryk85** [formio/formio#1083]
Hi,

Don't know if this is a bug or if I'm doing something wrong but when I hide pages based on check boxes no data is submitted when submitting form.  Simple conditional, should show true when component true.

![image](https://user-images.githubusercontent.com/44379843/92590882-4040d780-f29d-11ea-849b-921806ab8f06.png)

![image](https://user-images.githubusercontent.com/44379843/92590950-58185b80-f29d-11ea-8e0c-192a95b5fe10.png)

![image](https://user-images.githubusercontent.com/44379843/92590990-65354a80-f29d-11ea-8209-89cc270fe09d.png)

If I remove the conditional hide it works ok

![image](https://user-images.githubusercontent.com/44379843/92591209-bfcea680-f29d-11ea-9bd3-e597ed4710c8.png)

**Comment by wag110894** [comment]
@Mfryk85m

I see that you are using our old renderer and not our 4x Core Renderer, which can be found here: https://github.com/formio/formio.js. 

Our 4x core renderer has changed how our wizard shows and has provided a lot of new functionality.

**Comment by Mfryk85** [comment]
Hi,

I'm running the docker version from this repository, 2.0.0-rc.13, do I need to update the renderer separately for the wizard form to work? How would I update this?

**Comment by wag110894** [comment]
@Mfryk85, Our open-source portal still runs a really old version that is hard to upgrade for end users. We have created a ticket and have added it to our backlog to improve this. For Reference, the ticket number is FOR-2753. 

We will let you know once this has been completed.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
