### ISSUE TITLE
[HELP] Portal FormIO, Do we keep versions of forms (sort of a repo) when we Save/publish a form?

### ISSUE THREAD

**Issue by MalkyTheKid** [formio/formio#1085]
Is this a feature available right now in portal FormIO? 
If for some reason we have to revert a form to a previous state, are we able to do that?

**Comment by wag110894** [comment]
Hello @MalkyTheKid,

Here is our documentation on Revisions: https://help.form.io/userguide/versioning/

**Comment by MalkyTheKid** [comment]
Thank you very much!
