### ISSUE TITLE
POST https://formio.form.io/project url seems to be invalid (invalid alias)

### ISSUE THREAD

**Issue by Anne-Anq** [formio/formio#1090]
## Environment
local host, react, javascript, chrome

## Steps to Reproduce
I have the following create project function in my react project 

```
export const createProject = async (token: string) => {
  const headers = new Headers()
  headers.append('Content-Type', 'application/json')
  headers.append('x-jwt-token', token)

  var raw = JSON.stringify({
    title: 'New NAME for MY Test',
    name: 'newProjectTest',
    description: 'An example application',
    template:
      'https://raw.githubusercontent.com/formio/formio-app-todo/master/src/project.json',
    config: { API_KEY_TEST: 'thisIsTheAPIKey' },
    settings: {
      cors: '*',
      allowConfig: true,
      addConfigToForms: true
    }
  })
  fetch(`https://formio.form.io/project`, {
    method: 'POST',
    headers,
    body: raw
  })
    .then(response => response.text())
    .then(() => showSuccess('Success!'))
    .catch(error => showError(error))
} 
```

## Expected behavior
This should create a project 

## Observed behavior
I get a 400 Bad Request, with response "Invalid alias"

I am authenticated properly, I am able to get existing projects using GET https://formio.form.io/project/:myProject but posting API url seems to be incorrect?

**Comment by wag110894** [comment]
@Anne-Anq Can you try something other than formio and see if it works?

**Comment by Anne-Anq** [comment]
> @Anne-Anq Can you try something other than formio and see if it works?

What do you mean something other than formio?

**Comment by wag110894** [comment]
This is due to the fact that we have formio.form.io set up on our side, so you will not be able to use that.

**Comment by Anne-Anq** [comment]
So... I don't have access to formio.form.io URL? how do I create a project?

**Comment by wag110894** [comment]
You can go to https://portal.form.io to create an account as well as a project.

**Comment by Anne-Anq** [comment]
Yes thank you, I do have an account and projects created from the portal, but my goal is to create a project from the API, is it not possible? 
https://documenter.getpostman.com/view/684631/formio-api/2Jvuks#a7ca9883-4ec4-5226-f36c-a6dd0d0727f3

**Comment by randallknutson** [comment]
Sorry for all the confusion. Our open source library does not support projects. This is only available on our hosted and enterprise versions.

**Comment by yhrchan** [comment]
@randallknutson I ran into the same issue. I was wondering is there a doc somewhere that clearly specifies the differences between the open source version versus the hosted/enterprise version? like what's missing in the open source version, etc? Thanks.

**Comment by lane-formio** [comment]
https://form.io/blog/formio-open-source-core-vs-enterprise
