### ISSUE TITLE
[BUG]  new stage project stage Read All includes more than Administrator

### ISSUE THREAD

**Issue by duttonw** [formio/formio#1094]
## Environment
Please provide as many details as you can:

security through limited privileges should be done 
Read All should only have Administrator so that export command does not allow evil users from scraping actions and private keys

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version:  Application: 7.0.39-rc.3, Renderer: 4.11.2-rc.4
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Expected behavior

new project only includes Administrator for Read All

## Observed behavior

Read All has all user types except everyone

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

system under
https://api.forms.platforms.qld.gov.au/

```js
// your code here
```

**Comment by wag110894** [comment]
Hello @duttonw,

Apologies on the delay.

We are able to replicate this issue and it has been resourced to one of our developers. For reference, the ticket number for this is FOR-2763. We will let you know once this has been resolved.

**Comment by lane-formio** [comment]
This has been resolved, closing issue.
