### ISSUE TITLE
[BUG/FEATURE REQ]  form.io does not provide post headers (X-Forwarded-For) for user ip from browser submission

### ISSUE THREAD

**Issue by duttonw** [formio/formio#1097]
Given a user is on a form.io form
When a user submits a submission payload to the rest api for the form
Then I want to be able to retrieve the X-Forwarded-For header value from the payload to know exactly the ip address of the user and store it as well as include it in my next action hook.

Current work around is to you https://www.ipify.org/ or similar to retrieve the ip address via javascript in the browser. Problem is that ad-blockers etc clamp down on this behaviour and it is not retrieved.

There is metadata in the payload that looks similar to the headers in the request but they are fully controlled by the browser js inside the body of the payload. It is much harder to change the request headers in normal browsers when submitting. 

- Hosting type
  - [ ] Form.io
  - [X] Local deployment
    - Version:  
- Formio.js version: "version":"6.10.9-rc.10","schema":"3.3.6"
- Frontend framework: Application: 7.0.39-rc.3, Renderer: 4.11.2-rc.4

**Comment by wag110894** [comment]
Hello @duttonw,

Thank you for your patience. We have created a ticket and have added it to our backlog. We would be happy to provide you with a quote for this platform enhancement to provide you with this functionality.

Please let us know if you are interested and we can get the process started. For reference, the ticket number ids FOR-2782.

**Comment by PhilLincolnQLD** [comment]
> Thank you for your patience. We have created a ticket and have added it to our backlog. We would be happy to provide you with a quote for this platform enhancement to provide you with this functionality.
> 
> Please let us know if you are interested and we can get the process started. For reference, the ticket number is FOR-2782.

Thanks @wag110894 , I'm the Product Manager for our form.io implementation. Would you please arrange the quote for this work.

**Comment by lane-formio** [comment]
This has been complete, closing issue.
