### ISSUE TITLE
[Question] - Can templated output be translated? 

### ISSUE THREAD

**Issue by korexus** [formio/formio#1102]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 2.0.0
- Formio.js version: 4.12.0
- Frontend framework: React
- Browser: Any
- Browser version: Any

I have a grid component, with templated header
```
<div class="row"> 
    {%util.eachComponent(components, function(component) {
      if (["fieldName", "fieldRef", "area", "areaUnits"].includes(component.key)) {
    %} 
    <div class="col-sm-2"> 
      {{ component.label }} 
    </div> 
  {% }}) %} 
</div>
```

I'm looking to translate the form. All of the values of component.label are in the translation file, but they remain untranslated in the browser.

Is there any way to get text inside the generated HTML to be translated?

**Comment by randallknutson** [comment]
In order for it to be translated it needs to be passed through the t() function. You can do this with {{t(component.label)}}

**Comment by korexus** [comment]
Thanks, Randall. Doing that results in the output `t is not defined`. Does it need to be imported somewhere?

I can see ` {{t(component.label)}}` coming down in the JSON response, so presumably something on the front end is attempting to evaluate it?

Sorry if this should be obvious, I've taken the project over from someone else and am still finding my way around!

**Comment by randallknutson** [comment]
No problem with the question. It is a good learning question. I thought the t function was available in context but it looks like it is not. Can you try instance.t() instead?

**Comment by korexus** [comment]
Perfect! `{{instance.t(component.label)}}` has worked exactly as expected. Thank you!
