### ISSUE TITLE
Docker compose don't start

### ISSUE THREAD

**Issue by tillg** [formio/formio#1105]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X ] Local deployment
    - Version: 
- Formio.js version: commit 41d06e025f77e03e3568f8fb300ba8c688f82e2b
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. git clone
2. cd in dir
3. docker-compose up

## Expected behavior
It runs and you can visit it in the browser.

## Observed behavior
The formio docker doesn't start - it repeatedly tries to restart. 

This is the error message:

formio_formio_1 exited with code 1
formio_1  | internal/modules/cjs/loader.js:968
formio_1  |   throw err;
formio_1  |   ^
formio_1  |
formio_1  | Error: Cannot find module 'mongoose'
formio_1  | Require stack:
formio_1  | - /app/src/util/util.js
formio_1  | - /app/main.js
formio_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
formio_1  |     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
formio_1  |     at Module.require (internal/modules/cjs/loader.js:1025:19)
formio_1  |     at require (internal/modules/cjs/helpers.js:72:18)
formio_1  |     at Object.<anonymous> (/app/src/util/util.js:3:18)
formio_1  |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
formio_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
formio_1  |     at Module.load (internal/modules/cjs/loader.js:985:32)
formio_1  |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
formio_1  |     at Module.require (internal/modules/cjs/loader.js:1025:19) {
formio_1  |   code: 'MODULE_NOT_FOUND',
formio_1  |   requireStack: [ '/app/src/util/util.js', '/app/main.js' ]
formio_1  | }

**Comment by travist** [comment]
Try ```npm install``` before running compose up.

**Comment by tillg** [comment]
Thx. I know I should read the f**g documentation...
