### ISSUE TITLE
Is storing custom meta data possible in form.io

### ISSUE THREAD

**Issue by 7er** [formio/formio#1107]
In our solution it would be helpful to store a reference to a foreign system in each form definition. 

We first tried to add a field to the form schema json and POST/PUT it to the server, but the field was dropped. As of now we shoe-horn the field into the schema by using the tags field. Is there a supported way to store additional meta data in the schema definition and have the form.io server store it in mongo?

**Comment by 7er** [comment]
### Example:

**Custom field that is stored as is (myDomainRef)**

`{
  "myDomainRef": "idFromOtherSystem",
  "_id": "5f4fb3a1c8d63a0003f006bd",
  "type": "form",
  "display": "form",
  "name": "kraKra",
  "title": "KRA KRA",
  "path": "krakra",
  "machineName": "kraKra",
  "components": <elided>
 ....
}
`

**Pre defined field for "yourReference"**

`{
  "yourRefererence": "idFromOtherSystem",
  "_id": "5f4fb3a1c8d63a0003f006bd",
  "type": "form",
  "display": "form",
  "name": "kraKra",
  "title": "KRA KRA",
  "path": "krakra",
  "machineName": "kraKra",
  "components": <elided>
 ....
}
`

**Comment by randallknutson** [comment]
There is a "metadata" field you can use that it should store it in. This is already populated with some information such as browser information. You can add your information to it as well and it should save just fine.

**Comment by 7er** [comment]
Uhm, isnt that the submission rather than the form definition? Or do both have this field

**Comment by randallknutson** [comment]
That's just the submission. I assumed you were talking about that since only "data" and "metadata" apply to submissions. On forms there is also "settings" and "properties" where you can put anything you want.

**Comment by 7er** [comment]
Aha, awesome. That totally solves the problem!
