### ISSUE TITLE
[BUG] In form preview mode, interpolated values in HTML Component does not display

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#1110]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: Application: 7.0.40, Renderer: 4.11.3
    - from /status:
```
{
version: "6.11.0",
schema: "3.3.6"
}
```
 
- Formio.js version: no relevant
- Frontend framework: not relevant
- Browser: Chrome
- Browser version: 85

## Steps to Reproduce
1. Create a new form
2. Drop in a HTML Component with "div" Html tag and content:
```
<h1>Not interpolated<h1>
<h1>{{ instance.t('Interpolated')</h1>
```
3. Check Component preview and Form preview

## Expected behavior
Both should display 2 h1 headings

## Observed behavior
Component preview mode displays both headings
Form preview mode only displays not interpolated heading.

## Example
Component preview mode:

![image](https://user-images.githubusercontent.com/21692768/95900324-b4b8db80-0d5f-11eb-9722-cc4a618a5416.png)

Form preview mode
![image](https://user-images.githubusercontent.com/21692768/95900498-fb0e3a80-0d5f-11eb-8693-2c81271c40d2.png)

**Comment by wag110894** [comment]
Hello @phucduong86,

Thanks for reaching out!

We are not seeing this on our production portal which is using version Application: 7.0.41, Renderer: 4.12.0.  Here is a screenshot of it working: https://share.getcloudapp.com/qGuvldz7

I hope that this helps.

**Comment by airarrazaval** [comment]
@wag110894 you are missing the closing curly brackets on the HTML content.

**Comment by wag110894** [comment]
@airarrazaval,

I just copied and pasted what was above. I did retest this and it is working correctly with the closing curly brackets on the Use tab.
Here is a new video:  https://share.getcloudapp.com/L1uQyQPA

**Comment by phucduong86** [comment]
@wag110894 
In the video, I can see the portal version at the bottom ```Application: 7.0.41, Renderer: 4.12.0```
I've downloaded the latest docker image today (formio/formio-enterprise:latest) 2020-11-10 and I'm getting version ```Application: 7.0.40, Renderer: 4.11.3```

**Comment by travist** [comment]
Looks like we do not have a docker image that includes the 7.0.41 portal. We are working on a new build that will be the 4.12.1 renderer so I would just wait for that release. We hope to have that out before the end of next week.
