### ISSUE TITLE
formio API server not running as expected - no port 3001 to connect to

### ISSUE THREAD

**Issue by gdmiller-za** [formio/formio#1128]
**Environment**
Please provide as many details as you can:
Hosting type
- Local deployment
- Clean Debian 10 installation
- FormIO Version: master branch

**Steps to reproduce:**
1) Perform a clean Debian 10 installation
-- Image used for install: debian-10.2.0-amd64-netinst.iso
![image](https://user-images.githubusercontent.com/32566712/98159920-0e876e00-1ee6-11eb-8331-27ae4c765f8b.png)
3.	Login as root
4.	Install, start and enable MongoDB Community Edition
apt-get install -y gnupg
wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
apt-get update
apt-get install -y mongodb-org
systemctl start mongod
systemctl enable mongod

5.	Install NodeJS
wget -qO - https://deb.nodesource.com/setup_lts.x | bash -
apt-get install -y nodejs

6.	Install build-essential and git packages
apt-get install -y build-essential git

7.	Download master formio
cd /opt/
git clone https://github.com/formio/formio

8. "Install" and run formio

--- See output.log
--- See netstat.txt
[putty.log](https://github.com/formio/formio/files/5490169/putty.log)
[netstat.txt](https://github.com/formio/formio/files/5490170/netstat.txt)

**Expected Behavior:**
API runs on port 3001

**Experienced Behavior:**
API does not run on port 3001

**Comment by travist** [comment]
I am not able to reproduce this locally. It is connecting to port 3001 just fine. Anyone else have this problem?

**Comment by gdmiller-za** [comment]
> I am not able to reproduce this locally. It is connecting to port 3001 just fine. Anyone else have this problem?

Could you perhaps confirm which environment you have tested on?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
