### ISSUE TITLE
Calculated value using some field in data-grid in another resource into a field in data-grid

### ISSUE THREAD

**Issue by qodrinzo** [formio/formio#1146]
Having a form like this:
![image](https://user-images.githubusercontent.com/9105400/99764679-d3ef1980-2b12-11eb-9feb-538c8810b648.png)
I want to load some field value (_mydatagrid.key_) of the selected resource (_diagnosis_) in the row [into the next text input](https://help.form.io/userguide/form-components/#calculated-value). Providing text field' calculated value with the phrase `value = row.diagnosis.prevalence[0].quantity` doesn't load anything. What is the problem?

**Comment by wag110894** [comment]
Hello @qodrinzo, can you provide a form embed or a JSfiddle so that we can replicate this setup?

**Comment by qodrinzo** [comment]
> Hello @qodrinzo, can you provide a form embed or a JSfiddle so that we can replicate this setup?

Hi. The session expires repeatedly just now and doesn't allow me to provide you with the code! But I succeeded using JSON.stringify() to see the structure of the object selected in the first field.

`value = row['diagnosis'].**data**.prevalence[0].quantity` which equals to `row[resource_component_key].data.remote_datagrid_key[row_number_from_zero].field_key`.

**Comment by travist** [comment]
So this is now resolved?

**Comment by qodrinzo** [comment]
Yes, for now.
