### ISSUE TITLE
Pre-populate Form fields?

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#115]
Is it possible to repopulate form fields/send variables into from the embedding site/system calling the form?

**Comment by zackurben** [comment]
Hey @StephenOTT it is possible to prepopulate form submission as follows.

When using the `formio` directive, you can pass a pre-defined `submission` as a tag attribute, with the data you want to fill out. Note, if you do default data this way, it will overwrite any default data defined within the form builder; Most components allow you to define a default value in the form builder.

Imagine you have the following formio form in your html page:

```html
/**
 * $scope.defaultData = {
 *   data: {
 *     myComponent: "hello world"
 *   }
 * };
 **/

<formio src="'https://yourproject.form.io/yourform'" submission="defaultData"></formio>
```

This will render your form given at the src location, and pre-populate the submission using the data in the defaultData scope variable. All submission data is defined within the `data` key, and is stored by `key`:`value` pairs, where each key corresponds to a components API key, defined in the form builder.

You can find more information on the formio attributes here: https://help.form.io/developer/info/#formio-directive

Let me know if you have any additional questions.

**Comment by StephenOTT** [comment]
thanks 👍

**Comment by StephenOTT** [comment]
@zackurben building on this, is there any capabilities planned for handling Actions/calls to other systems on form load?  So pulling data from SQL or Web service call as the form is loaded.

**Comment by mujtaba1016** [comment]
For Form Builder we can Pre-Populating data by

    ```
Formio.builder(document.getElementById('builder'), {}).then(function(form){
      form.webform.submission = {
          data: prefilledDataObject
      };
    });
```

For CreateForm we can Pre-Populating data by

    ```
Formio.createForm(document.getElementById('builder'), {}).then(function (form) {
            form.submission = {
                data: prefilledDataObject
            };
        });
```
