### ISSUE TITLE
[BUG] Address component uses incorrect Google API

### ISSUE THREAD

**Issue by DanielTurner** [formio/formio#1155]
## Environment
Enterprise version: Application: 7.0.39-rc.3, Renderer: 4.11.2-rc.4

## Expected behavior
Formio address component to use correct google api.

## Observed behavior
Formio address component uses incorrect google api

## Example
The formio address component uses the Geocoding API which is a  backend webservice by Google. It can only be restricted by IP address since it assumes its a server side request. However the address component requests from the browser.
You will only notice this bug once you try and restrict the key to your domains.

**Comment by travist** [comment]
This is currently being fixed and will most likely be resolved in the 4.13.x release. We are switching to using the Google Autocomplete API.

**Comment by DanielTurner** [comment]
@travist Thank you for your response, do you have a release schedule for the 4.13.x release?

**Comment by travist** [comment]
We are still working on 4.12.2 release, which we hope to have released by next week. 4.13.x is a much larger release and based on historical velocity on this kind of thing, you are looking at 4 weeks after that so that puts us at the end of January.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
