### ISSUE TITLE
[BUG] Server throws 'Error: cyclic dependency detected' when calling Webhook action

### ISSUE THREAD

**Issue by frankie-eric** [formio/formio#1156]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: v2.0.0-rc.34
- Frontend framework: running formio using docker-compose
- Browser: Chrome 
- Browser version: 86.0.4240.198 (Official Build) (x86_64)

## Steps to Reproduce
1. Clone https://github.com/formio/formio to local, run `npm install` and then `docker-compose up`.
2. Clone https://github.com/formio/formio-webhook-receiver to local, run `npm install`, rename `.env.example` to `.env`, edit `basic/server.js`, comment out Basic authentication section, and run `npm run start:basic`.
3. Create a new form with one text field, and add a web hook action.  For the web hook action, type in URL as `http://host.docker.internal:4001` (so that the server in the docker container can access the receiver running in host network), and tick the `block` checkbox under Webhook URL field.
4. Save the form change and enter form data.

## Expected behavior
- The server calls the webhook receiver successfully without error.

## Observed behavior
- The server is showing the following error
![image](https://user-images.githubusercontent.com/74298192/100605493-1b1faa80-335c-11eb-812b-c7076c6d7920.png)

- The browser console is showing the following error
![image](https://user-images.githubusercontent.com/74298192/100605554-32f72e80-335c-11eb-938e-54265224d5b4.png)

- Please note that if I untick the `block` checkbox below the Webhook URL field, then the receiver could receive the request, but the server still prints the similar error log.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
Hello @frankie-eric, 
Thanks for reaching out! 
We have created a ticket and have added it to our backlog. We welcome a pull request. We also have a process to expedite the fix as well. For reference, the ticket number is FOR-2888. 

We will let you know once this issue has been resolved.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
