### ISSUE TITLE
"Save For Later" abilities?

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#116]
Any work being done or undocumented support for Save For Later type of actions allow someone to partially fill out form, 'save', and when they return to the form later the values are still populated.

two versions typically: 1. Local Storage, and 2. saved against database, referenced with user and form instance.

**Comment by zackurben** [comment]
Hey @StephenOTT, you could manage this yourself with the information in https://github.com/formio/formio/issues/115 or you can tie into our events system detailed here: https://help.form.io/developer/info/#formio-events

However, this is more aligned with the workflow of editing a previous submission. Using the `formio` directive, you can load an existing submission as follows:

```
<formio src="'https://yourproject.form.io/yourform/submission/[submissionId]'"></formio>
```

Once a submission is loaded, it will display the original form, pre-populated with the submissions details, where you, or the user, can edit the submissions contents.

Let me know if you have any additional questions.
