### ISSUE TITLE
[BUG] SELECT Widget HTML5

### ISSUE THREAD

**Issue by arrowwind** [formio/formio#1170]
## Environment
For the select component, set the widget to HTML5, there is a blank option, which is created by default. But for ChoiceJS this is right. 

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 4.12.4
- Formio.js version:
- Frontend framework:
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Drag the select component
2. Set the widget to HTML5
3. Set the data source values
4. Launch the form

## Expected behavior
The dropdown list should show the items which a set in the data source values. But there is a blank item in them.

**Comment by travist** [comment]
The blank item is expected so that the HTML widget will behave similar to the Choices.js widget where if no items are selected, it will not show any items. The issue arises if you do not have the blank, it will default the "first" item to appear selected.

**Comment by arrowwind** [comment]
Thank you for your reply. If there is no items to show, it should be a blank item. But the behave is not like you said.

Right now, if the defaultvalue is set, there are three dropdown items. The blank item should not show.  
If the the defaultvalue is not set, the blank item is selected. It should be "apple" to show. For the 'apple' is the first one. 
 
  {
  "label": "Select",
  "widget": "html5",
  "tableView": true,
  "data": {
    "values": [
      {
        "value": "apple",
        "label": "Apple"
      },
      {
        "value": "banana",
        "label": "Banana"
      }
    ],
    "json": "",
    "url": "",
    "resource": "",
    "custom": ""
  },
  "key": "dict",
  "type": "select",
  "input": true,
  "defaultValue": "banana",
  "calculateServer": false,
  "uniqueOptions": false,
  "lazyLoad": false,
  "placeholder": "",
  "prefix": "",
  "customClass": "",
  "suffix": "",
  "multiple": false,
  "protected": false,
  "unique": false,
  "persistent": true,
  "hidden": false,
  "clearOnHide": true,
  "refreshOn": "",
  "redrawOn": "",
  "modalEdit": false,
  "labelPosition": "top",
  "description": "",
  "errorLabel": "",
  "tooltip": "",
  "hideLabel": false,
  "tabindex": "",
  "disabled": false,
  "autofocus": false,
  "dbIndex": false,
  "customDefaultValue": "",
  "calculateValue": "",
  "attributes": {},
  "validateOn": "change",
  "validate": {
    "required": false,
    "custom": "",
    "customPrivate": false,
    "strictDateValidation": false,
    "multiple": false,
    "unique": false
  },
  "conditional": {
    "show": null,
    "when": null,
    "eq": ""
  },
  "overlay": {
    "style": "",
    "left": "",
    "top": "",
    "width": "",
    "height": ""
  },
  "allowCalculateOverride": false,
  "encrypted": false,
  "showCharCount": false,
  "showWordCount": false,
  "properties": {},
  "allowMultipleMasks": false,
  "clearOnRefresh": false,
  "limit": 100,
  "dataSrc": "values",
  "valueProperty": "",
  "filter": "",
  "searchEnabled": true,
  "searchField": "",
  "minSearch": 0,
  "readOnlyValue": false,
  "authenticate": false,
  "template": "<span>{{ item.label }}</span>",
  "selectFields": "",
  "searchThreshold": 0.3,
  "fuseOptions": {
    "include": "score",
    "threshold": 0.3
  },
  "customOptions": {},
  "id": "e0stdz"
}

**Comment by arrowwind** [comment]
That blank item is the placeholder...

**Comment by arrowwind** [comment]
That blank item is the placeholder which is set "". If the placeholder is none empty the blank item will not show.
