### ISSUE TITLE
form-io use one field value in other dynamically

### ISSUE THREAD

**Issue by nacool** [formio/formio#1173]
I have a basic form-io form here. One text box and other file upload control. For file upload I am using API URL. I want to pass the "AttachmentID" text box value to the file API URL. I couldn't get it to work. Tried using {{data.AttachmentID}} in the file URL but its not getting value. When the document gets uploaded, the URL should change as per the attachment id text box. Is it possible?

Basic form:

![image](https://user-images.githubusercontent.com/11659630/103265596-f7d83180-49d3-11eb-9b9e-59413a4a2bcb.png)

Form Upload control:

![image](https://user-images.githubusercontent.com/11659630/103265658-13433c80-49d4-11eb-9ca6-902ae55c3c18.png)

**Comment by nacool** [comment]
I tried setting refresh property for file upload control to AttachmentId field. But still no luck.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
