### ISSUE TITLE
[BUG] React Form.io Bug on User Guide URL

### ISSUE THREAD

**Issue by AgileFlex** [formio/formio#1189]
## Environment
Please provide as many details as you can:

The User Guide URL for each FormBuilder is relative to the localhost or project's live url.

React packages installed: 

- "@formio/bootstrap3": "2.6.8"
- "react-formio": "^4.3.0"
- "formiojs": "4.12.1"
- "react-redux": "^7.2.0"
- "react-router": "^5.1.2"
- "redux": "^4.0.5"
- "redux-thunk": "^2.3.0"

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.12.1
![formio-help-bug](https://user-images.githubusercontent.com/16820840/105153599-4c715700-5b11-11eb-81d8-05e4d0e6d1fa.png)

- Frontend framework: React 17.0.1
- Browser: Chrome 
- Browser version: 87.0.4280

## Steps to Reproduce
1. Add a new FormBuilder 
2. Drag and drop a Text field
3. The Help URL on the dialog points to a relative URL

## Expected behavior
The Help URL should point to the Form.io's Help repository

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

**Formio.use(bootstrap3);
Formio.setProjectUrl(AppConfig.projectUrl);
Formio.setBaseUrl(AppConfig.apiUrl);**

No matter what the Project URL or Base URL are the behavior for the Help Link is the same.

```js
// your code here
```

**Comment by wag110894** [comment]
Hello @AgileFlexAgency,

Thanks for reaching out and providing use a reproducible case. We have created a ticket and have added this to our backlog. For reference, the ticket number is FIO-1227.

We will let you know once this issue is resolved.

We welcome a pull request and we also have an option to expedite the issue if you are interested.

We will let you know once this issue is resolved.

Thank you!

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
