### ISSUE TITLE
Create new Role

### ISSUE THREAD

**Issue by sdancer75** [formio/formio#1196]
Hi,

I have created new roles using Form.io API, but I am wondering if there is another way to create or edit roles using an external JSON file or GUI?

Inside  a form.io's resource and under the tab "Access" it says:

"_User Permissions allow you to control who can create, view, and modify form submissions. Here you may assign Project Roles to permissions. Roles can be created and edited in the **config/default.json** file." 

This specific file does not have anything about roles and permissions. Is that valid? Any documentation of how to use it?

Regards,

**Comment by travist** [comment]
For the Open source server, these are created during the installation process (which is where the "default.json" file is used). If you need more roles, then these will need to be added before an installation occurs. Dynamic role creating is something that we have in our enterprise server, but not currently in open source. It may be possible to do it using the API's though.

**Comment by sdancer75** [comment]
thank you but inside the config/default.json there is nothing related to the pre-defined roles. So, how can I do it using the default.json?


```
{
  "port": 3001,
  "appPort": 8080,
  "host": "localhost:3001",
  "protocol": "http",
  "allowedOrigins": ["*"],
  "domain": "http://localhost:3001",
  "basePath": "",
  "mongo": "mongodb://localhost:27017/formioapp",
  "mongoConfig": "",
  "mongoCA": "",
  "mongoSecret": "--- change me now ---",
  "reservedForms": [
    "submission",
    "exists",
    "export",
    "role",
    "current",
    "logout",
    "import",
    "form",
    "access",
    "token",
    "recaptcha"
  ],
  "jwt": {
    "secret": "--- change me now ---",
    "expireTime": 240
  },
  "email": {
    "type": "sendgrid",
    "username": "sendgrid-user",
    "password": "sendgrid-pass"
  },
  "settings": {
    "office365": {
      "tenant": "",
      "clientId": "",
      "email": "",
      "cert": "",
      "thumbprint": ""
    },
    "databases": {
      "mysql": {
        "host": "",
        "port": "",
        "database": "",
        "user": "",
        "password": ""
      },
      "mssql": {
        "host": "",
        "port": "",
        "database": "",
        "user": "",
        "password": ""
      }
    },
    "email": {
      "gmail": {
        "auth": {
          "user": "",
          "pass": ""
        }
      },
      "sendgrid": {
        "auth": {
          "api_user": "",
          "api_key": ""
        }
      },
      "mandrill": {
        "auth": {
          "apiKey": ""
        }
      }
    }
  }
}
```

**Comment by travist** [comment]
I believe it creates a project based on a template, using the default https://github.com/formio/formio/blob/master/src/templates/default.json#L6.

when you install the open source, you are given the ability to use a different template. This is where you would provide some additional roles to be installed.

**Comment by sdancer75** [comment]
thanks very helpful!
