### ISSUE TITLE
API "join" resources 

### ISSUE THREAD

**Issue by sdancer75** [formio/formio#1197]
Looking at the "POST Create EmployeeDepartment Resource Example" at 

https://documenter.getpostman.com/view/684631/formio-api/2Jvuks#94745ed5-6fc5-4bbc-94cc-db6e44044f73

I am wondering, how the resource references ``{{employeeResourceId}}`` and ``{{departmentResourceId}}`` can be found? It worked for the 1st but it failed for the 2nd. Where these variables are referencing inside the MongoDB?

```
{
  "title": "EmployeeDepartment",
  "display": "form",
  "type": "resource",
  "name": "employeeDepartment",
  "path": "employeedepartment",
  "components": [
    {
      "label": "Employee",
      "key": "employee",
      "type": "select",
      "dataSrc": "resource",
      "data": {
          "resource": "{{employeeResourceId}}"
      },
      "template": "<span>{{ item.data.email }}</span>"
    },
    {
      "label": "Department",
      "key": "department",
      "type": "select",
      "dataSrc": "resource",
      "data": {
          "resource": "{{departmentResourceId}}"
      },
      "template": "<span>{{ item.data.name }}</span>"
    },
    {
      "label": "Submit",
      "key": "submit",
      "action": "submit",
      "type": "button"
    }
  ],
  "access": [],
  "submissionAccess": [],
  "settings": {},
  "page": 0
}


```

**Comment by travist** [comment]
The reference should be an ID of the resource which can be found within the db.forms collection.

**Comment by sdancer75** [comment]
So, do I have to replace the ``{{employeeResourceId}}`` and ``{{departmentResourceId}}`` with the actual ID hash of the resource manually by opening the MongoDB and copy/paste the code?

**Comment by travist** [comment]
The template import process should automatically inject these ID's when you import this template into a new deployment. If it doesn't then this is a bug. You should not have to manually change these values in the database.

**Comment by sdancer75** [comment]
Hi,

I am a little bit confused. 

These IDs are just variable names or alias that correspondes  to actual resource IDs right? The API just translate them to actual ID hashes on the fly.

I can easily find the resource IDs looking directly inside the mongodb, but how can I know the corresponding variable name of a specific resource to build the json body for the API call? Is there any name convention that I have to follow? For example resource path name plus the "ResourceId" suffix.

**Comment by travist** [comment]
The variable name is the Property name of the fields that  you drag into the join resource. Maybe this documentation (still not finished) will help in understanding how this works?

https://form-io.gitbook.io/help/userguide/roles-and-permissions#creating-a-join-resource

**Comment by sdancer75** [comment]
Thank you,

Remember that there is not any GUI in the API calls. There exist only RerourceIDs with all properties of the specific resource. Anyway, I will experiment with that, I suppose internally the API decodes the variable name combining something like the machine name with the suffix `ResourceId`. Anyway, I believe the documentation must be enriched to make our lives easier.

Best Regards,
