### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ghost** [formio/formio#1211]
I have a basic form here. 

![image](https://user-images.githubusercontent.com/58280615/109626523-38d6f880-7b73-11eb-99cc-1d64590d55af.png)

I add the Select Component with **Multiple Values** and I add valid = 'failed' in Validation tab -> Custom validation
![image](https://user-images.githubusercontent.com/58280615/109627725-7f792280-7b74-11eb-8ed7-5b238471fa9d.png)

However, **Submission Complete** when I click the submit button without data for the Select Component
![image](https://user-images.githubusercontent.com/58280615/109627891-ac2d3a00-7b74-11eb-95cf-2f57f34fa56c.png)

Expected behavior: Show error message.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
