### ISSUE TITLE
[Question] Skip validation on the server side when state is set to draft

### ISSUE THREAD

**Issue by ALLAOUI-DSI** [formio/formio#1223]
Hello,
I am trying to save a submission as a draft, the form contains a button with the action `save in state` that I set to `draft`. When clicked the form is actually submitted without validation on the client side. However, the server returns an error (`400 bad request`) stating that the submission is invalid (e.g.: a field a required). So is it possible to skip this validation on the server side when the form is submitted as draft?
Thank you.

**Comment by wag110894** [comment]
Hello @ALLAOUI-DSI, can you provide a form so we can replicate the issue on our side?

**Comment by ALLAOUI-DSI** [comment]
Hi @wag110894 , thank you for your reply.
Here is an example of a form that has a required field, the client skips the validation on save as draft action but fails on the server side:
```json
{
  "_id": "6061895abb5e443254e75ced",
  "type": "form",
  "tags": [
    "common"
  ],
  "owner": "604f16171a5c661a4c762a2d",
  "components": [
    {
      "autofocus": false,
      "input": true,
      "tableView": true,
      "inputType": "text",
      "inputMask": "",
      "label": "Dummy input (Required)",
      "key": "dummyinput",
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": "",
      "protected": false,
      "unique": false,
      "persistent": true,
      "hidden": false,
      "clearOnHide": true,
      "spellcheck": true,
      "validate": {
        "required": true,
        "minLength": "",
        "maxLength": "",
        "pattern": "",
        "custom": "",
        "customPrivate": false
      },
      "conditional": {
        "show": "",
        "when": null,
        "eq": ""
      },
      "type": "textfield",
      "labelPosition": "top",
      "inputFormat": "plain",
      "tags": [],
      "properties": {}
    },
    {
      "autofocus": false,
      "input": true,
      "label": "Save draft",
      "tableView": false,
      "key": "savedraft",
      "size": "md",
      "leftIcon": "",
      "rightIcon": "",
      "block": false,
      "action": "saveState",
      "disableOnInvalid": false,
      "theme": "primary",
      "type": "button",
      "tags": [],
      "conditional": {
        "show": "",
        "when": null,
        "eq": ""
      },
      "properties": {},
      "state": "draft"
    },
    {
      "autofocus": false,
      "input": true,
      "label": "Submit",
      "tableView": false,
      "key": "submit",
      "size": "md",
      "leftIcon": "",
      "rightIcon": "",
      "block": false,
      "action": "submit",
      "disableOnInvalid": false,
      "theme": "primary",
      "type": "button"
    }
  ],
  "display": "form",
  "submissionAccess": [
    {
      "roles": [
        "604f15fc1a5c661a4c762a20"
      ],
      "type": "create_own"
    },
    {
      "roles": [
        "604f15fc1a5c661a4c762a20"
      ],
      "type": "read_own"
    },
    {
      "roles": [
        "604f15fc1a5c661a4c762a20"
      ],
      "type": "update_own"
    },
    {
      "roles": [
        "604f15fc1a5c661a4c762a20"
      ],
      "type": "delete_own"
    }
  ],
  "title": "SKip server validation test",
  "name": "sKipServerValidationTest",
  "path": "skipservervalidation",
  "access": [
    {
      "roles": [
        "604f15fc1a5c661a4c762a1f",
        "604f15fc1a5c661a4c762a20",
        "604f15fc1a5c661a4c762a21"
      ],
      "type": "read_all"
    }
  ],
  "created": "2021-03-29T08:01:31.086Z",
  "modified": "2021-03-29T08:01:31.125Z",
  "machineName": "sKipServerValidationTest"
}
```
By the way I recently found [this ](https://github.com/formio/formio.js/issues/1223#issuecomment-531825893) so it might be the answer..I hope there is a workaround. Cheers.

**Comment by wag110894** [comment]
I am not able to replicate this issue on Renderer v4.13.0-rc.25 using https://formio.github.io/formio.js/app/sandbox sandbox ID: 6065ed0cc488684c39f1d700)

**Comment by ALLAOUI-DSI** [comment]
Thank you for your reply. 
I don't know how the sandbox works, but it seems that it doesn't send the form data to the server. In my case the issue arises when the data is sent to the server. It gets validated even if I send it as a draft.

**Comment by wag110894** [comment]
What version are you experiencing this issue on?

**Comment by ALLAOUI-DSI** [comment]
Server : `2.1.0-rc.10`
@formio/angular : `5.0.3-rc.2`
formiojs: `4.12.7`

**Comment by wag110894** [comment]
Can you confirm that version of the server?

**Comment by ALLAOUI-DSI** [comment]
Hi, check this repository I made:
https://github.com/ALLAOUI-DSI/formio_server_validation
Create a form like the one above, set the path to `validationskip`. Verify that `http://localhost:3001/validationskip` is returning the form. Then go to `http://localhost:4200` and save a draft with the required dummy input field empty.

**Comment by edwinanciani** [comment]
Hi @ALLAOUI-DSI to skip validation in the server the submission object should have a state property with the value set to "draft" .   submission = {data:{},state:"draft"};  . where is this submission saved? to a resource? if so, check the resource validations.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
