### ISSUE TITLE
user exists API call, returns HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by sdancer75** [formio/formio#1230]
I am running my services under docker. 

Running the API call  ` curl -i http://localhost:3001/user/login` I get success 

```
HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 1058
ETag: W/"422-LQD2BiMU+fY+bX0aMZFEYjW1qDY"
Date: Fri, 02 Apr 2021 10:39:14 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

Running the API call `curl -i http://localhost:3001/user/exists?data.email=user@yahoo.gr` I get `HTTP/1.1 401 Unauthorized`

```
HTTP/1.1 401 Unauthorized
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Origin: *
Content-Type: text/plain; charset=utf-8
Content-Length: 12
ETag: W/"c-dAuDFQrdjS3hezqxDTNgW7AOlYk"
Date: Fri, 02 Apr 2021 10:37:18 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

What seems to be the problem here?

**Comment by sdancer75** [comment]
Problem solved. 

Newer versions of formio need authentication for these calling APIs while older ones didn't.

**Comment by aryanisml** [comment]
I am using React app login successfully in Form IO but getting the error like unauthorized while creating the form . What additional information we need to pass for authorization

**Comment by sdancer75** [comment]
> I am using React app login successfully in Form IO but getting the error like unauthorized while creating the form . What additional information we need to pass for authorization

Only administrators can create forms if you are using the embedded Formio authorization system. So I suppose the role of the mentioned user is not an administrator. So give the permissions to create all, read all, delete all to your user.
