### ISSUE TITLE
Question: custom logic : fire sequence of events / trigger sequence of logics

### ISSUE THREAD

**Issue by therabreal** [formio/formio#1232]
Hi,

Is it possible to, from javascript e.g. in custom action, sequentially trigger custom logic on multiple components (and wait for each to complete before continuing?

Idea is to automate multiple steps/stages which can be triggered one after another.

Currently we created buttons firing events for each stage. In a custom action - using jquery - we find the <button> html element within the formio-button-component, and do a .click() on that button element.
It kind of works but as the individual steps/stages can take a while and need to be executed in a specific order, we need to use setTimeout() which is not very robust/deterministic.

Ideally we could trigger the logic on an identified component in a promise construction.
I dug quite deep but could not find a way to execute the logic on a component.

Looking for something like:
`triggerLogic(myComponent, 'myLocgicName').then(...)`

Any ideas?
Hints would be welcome!

Best regards,
Rolf

**Comment by edwinanciani** [comment]
You can add Events to a Button Component changing the actions to event  and Listen those events in the Logic Tab of a components settings. Also you can listen these events in the app level because it seems what you want to do is something that it has to be in the app code.

**Comment by dinesh-aot** [comment]
Is it possible to trigger change event for select in the same way. Because, now I cannot add logic to the change event of a specific select box. Or if I listen to the 'change' event in the 'Logic' tab of select box, is it possible to get the 'event args' in the 'Custom Action'.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
