### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by virenderAttri** [formio/formio#1238]
I took a clone from formio git to test, but when I am trying to run with npm start I got this error and I already set useUnifiedTopology: true but I am still facing same issue so please help me as you can because I am new in this technology

[MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

**Comment by ccontour** [comment]
We are aware of the warning being emitted. Is this warning causing any specific issues for you?

**Comment by virenderAttri** [comment]
@ccontour Yes this is the full error with this warning


F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\utils.js:691
          throw error;
          ^

Error: Could not connect to the given Database for server updates: mongodb://localhost:27017/formioapp.
    at F:\SmartSearchX\FormIO-Clone\formio\src\db\index.js:253:17
    at unlock (F:\SmartSearchX\FormIO-Clone\formio\src\db\index.js:77:14)
    at F:\SmartSearchX\FormIO-Clone\formio\src\db\index.js:252:9
    at F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\utils.js:688:9
    at F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\mongo_client.js:257:23
    at connectCallback (F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\operations\connect.js:365:5)
    at F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\operations\connect.js:432:14
    at Server.<anonymous> (F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\topologies\server.js:230:11)
    at Object.onceWrapper (events.js:422:26)
    at Server.emit (events.js:315:20)
    at Pool.<anonymous> (F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\core\topologies\server.js:436:21)
    at Pool.emit (events.js:315:20)
    at F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\core\connection\pool.js:562:14
    at F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\core\connection\pool.js:995:11
    at F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\core\connection\connect.js:32:7
    at callback (F:\SmartSearchX\FormIO-Clone\formio\node_modules\mongodb\lib\core\connection\connect.js:280:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@2.2.0-rc.2 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@2.2.0-rc.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anthem-PC\AppData\Roaming\npm-cache\_logs\2021-04-29T10_49_19_784Z-debug.log
Waiting for the debugger to disconnect...

**Comment by ccontour** [comment]
That error is saying it cannot talk to mongo. Can you verify mongo is properly running in your machine?

You should be able to use a tool like [Robo 3T](https://robomongo.org/download) to connect to localhost to connect and verify the setup
