### ISSUE TITLE
Unable to install form.io via NPM

### ISSUE THREAD

**Issue by babyrace87** [formio/formio#1241]
Hi all, I'm trying to install forms.io in my machine but I'm stucked at this error. 

Already installed Node.js & mongo DB. 

Any ideas on how to solve this? :( 

![image](https://user-images.githubusercontent.com/35227980/116383715-b18fc380-a849-11eb-9fd3-5b202d6bfd65.png)

**Comment by ccontour** [comment]
Cannot replicate issue on a fresh machine - 

I'd start with removing node_modules, and trying again. If that fails, try installing the node modules using yarn instead of npm

**Comment by babyrace87** [comment]
Nice. Yarn works! Thank you so much. :)

**Comment by anumolu111** [comment]
I have encountered the exact issue while trying to run npm from cmd. 
however, when I executed npm from gitbash, module installation was successful. 

I guess the issue could be due to git not being set in the path variable that is referred by your cmd or terminal.
