### ISSUE TITLE
[BUG] (.) in form field key creates wrong submission data after submit

### ISSUE THREAD

**Issue by Vinaythakoor04** [formio/formio#1244]
## Environment
If I create formio form field with (.) in the key of the field when I submit a form, the key break after (.) and creates a new object results in wrong submission data.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.13.0
- Browser: Chrome

## Steps to Reproduce
1. Add a text field in the form builder
2. Add (.) in key
3. Submit form

## Expected behavior
Should create the valid key in submission as provided in field JSON 
## Observed behavior
Create invalid key after form submit if the form field key has (.)
## Example

Create text field using form builder
![image](https://user-images.githubusercontent.com/83650585/117007997-df707e80-ad07-11eb-8a3d-beb658e723ba.png)

Submission of the form
![image](https://user-images.githubusercontent.com/83650585/117008896-d03e0080-ad08-11eb-8f95-3426f4ec36b1.png)

For code or form JSON, please enclose in a code block:

```
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Text field 1",
            "tableView": true,
            "key": "text.Field",
            "type": "textfield",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```

**Comment by wag110894** [comment]
Hello @Vinaythakoor04,

We recommend not having a period inside of the key as it causes issues with the submission as you have experienced.
