### ISSUE TITLE
[BUG] : issue with nested form in local environment

### ISSUE THREAD

**Issue by anumolu111** [formio/formio#1246]
## Environment
Application is developed using formio editor that is set up in the local project.

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 4.12 .0
- Formio.js version:
- Frontend framework:
- Browser: chrome
- Browser version:

## Steps to Reproduce
1. In a  local deployment, I was trying to use nestedform, but could not add that component to form. Form field of nestedform component is mandatory and the drop down does not show any form or provide a form available in the local project. 
2.  Then, I tried creating a nestedform component at the formio and copied that component json to local project, changed the formId to form(component that generates the form fields required for the nested form eg: form: subForm) which is available in the local project. 
EG: subform.component.ts contains below statement:

  this.http.get<FormioForm>('assets/subForm.json').subscribe(data => {
        this.form = data;

      });
updated the apiURL of the project to http://localhost:4200.
While accessing the application, I find that it is calling the URL http://localhost:4200/form/subForm.

Question: Why is the **form** getting added to the URL at runtime? how can we avoid this, so that call goes to the component available in the project> which inturn fetches the subForm json content and sends to the main form to generate to the subform UI components

Objective is to get the nestedform refer to the form from the local project and not to the formio.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code he
```

**Comment by ccontour** [comment]
Can you provide example code to demonstrate the issue?

**Comment by anumolu111** [comment]
Thanks for looking into the issue. Below should help in reproducing the issue.

Project has 2 components
testparent -  refers to json  which used nestedform component, nestform component in here refers to testchild
testchild - loads a json which contains two text fields

Attached txt file contains, package.json, app-routing.module.ts, test-parent & test-child component ts & html files. Also the json referred in both these components.

[project overview.txt](https://github.com/formio/formio/files/6513124/project.overview.txt)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
