### ISSUE TITLE
[Question] : How to access and set value of controls in DataGrid?

### ISSUE THREAD

**Issue by dknangia** [formio/formio#1249]
I am using Angular 11 and I have a requirement under which, there will be a dropdown that will call an API based on the selected option of it, and then after getting the response (there could be multiple rows in response e.g. JSON),  I need to populate data in DataGrid controls e.g. textbox, checkboxes, and dropdown controls. I am not able to get reference to the controls in Datagrid e.g. if I try to do 

```
//try to set value of first row textbox named "DA"
data.datagrid[0].DA = "my value";
or 
data.datagrid[0].DA.value = "my value";
```

it doesn't work. 

Thanks

**Comment by AlexeyDavyd** [comment]
Try calling redraw method on form instance.
That helped me:
![image](https://user-images.githubusercontent.com/47381348/118104734-2d5e4400-b3e4-11eb-8278-3762478a18bc.png)
