### ISSUE TITLE
[Help Needed] Struggling to get docker container to work via instructions 

### ISSUE THREAD

**Issue by boltonto** [formio/formio#1252]
Hi,

I've followed the readme to get the docker container up and running, but it looks like form.io gets stuck in a loop attempting to connect to MongoDB.

Here's the output:

_formio_1  |   formio:db Lock engaged +6ms
formio_1  | Checking for db schema updates.
formio_1  |   formio:db Current database (3.1.4) and Pending code sversions (3.1.4) are the same. +3ms
formio_1  |  > No updates found.
formio_1  |
formio_1  |   formio:db Lock unlocked +3ms
formio_1  |   formio:db Lock unlocked +2ms
formio_1  | Initializing API Server.
mongo_1   | 2021-05-17T11:08:13.741+0000 I  NETWORK  [listener] connection accepted from 172.19.0.3:45238 #36 (2 connections now open)
mongo_1   | 2021-05-17T11:08:13.742+0000 I  NETWORK  [conn36] received client metadata from 172.19.0.3:45238 conn36: { driver: { name: "nodejs", version: "3.6.6" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.4.72-microsoft-standard-WSL2" }, platform: "'Node.js v14.17.0, LE (legacy)" }
formio_1  |  > Mongo connection established.
formio_1  | /app/node_modules/mongodb/lib/topologies/server.js:294
formio_1  |           throw err;
formio_1  |           ^
formio_1  |
formio_1  | TypeError: Object prototype may only be an Object or null: undefined
formio_1  |     at Function.setPrototypeOf (<anonymous>)
formio_1  |     at Object.185 (/app/node_modules/mailgun.js/dist/mailgun.js:2:22463)
formio_1  |     at r (/app/node_modules/mailgun.js/dist/mailgun.js:2:98812)
formio_1  |     at Object.271 (/app/node_modules/mailgun.js/dist/mailgun.js:2:314)
formio_1  |     at r (/app/node_modules/mailgun.js/dist/mailgun.js:2:98812)
formio_1  |     at Object.556 (/app/node_modules/mailgun.js/dist/mailgun.js:2:27322)
formio_1  |     at r (/app/node_modules/mailgun.js/dist/mailgun.js:2:98812)
formio_1  |     at Object.955 (/app/node_modules/mailgun.js/dist/mailgun.js:2:10905)
formio_1  |     at r (/app/node_modules/mailgun.js/dist/mailgun.js:2:98812)
formio_1  |     at Object.765 (/app/node_modules/mailgun.js/dist/mailgun.js:2:2419)
formio_1  |     at r (/app/node_modules/mailgun.js/dist/mailgun.js:2:98812)
formio_1  |     at Object.990 (/app/node_modules/mailgun.js/dist/mailgun.js:2:1871)
formio_1  |     at r (/app/node_modules/mailgun.js/dist/mailgun.js:2:98812)
formio_1  |     at /app/node_modules/mailgun.js/dist/mailgun.js:2:99180
formio_1  |     at /app/node_modules/mailgun.js/dist/mailgun.js:2:99188
formio_1  |     at /app/node_modules/mailgun.js/dist/mailgun.js:2:81
mongo_1   | 2021-05-17T11:08:19.056+0000 I  NETWORK  [conn35] end connection 172.19.0.3:45236 (1 connection now open)
mongo_1   | 2021-05-17T11:08:19.056+0000 I  NETWORK  [conn36] end connection 172.19.0.3:45238 (0 connections now open)
formio-master_formio_1 exited with code 1_

The part where it's throwing the error in code is :

`try {
        callback(null, self);
      } catch (err) {
        process.nextTick(function() {
          throw err;
        });
      }`

Which is in the 'connectHandler' function.

I don't have much experience with Mongo - so any pointers anyone could offer would be very much appreciated.

Thanks,
Tony

Docker Info:

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by PersonalDom** [comment]
I'm getting the same issue.

**Comment by travist** [comment]
This is a known issue we are looking into. For now use a tagged version.

**Comment by travist** [comment]
I just found the problem and pushed up the fix to "master" branch. Will create a new RC release very soon with the fix.
