### ISSUE TITLE
[BUG] API - Patch method always calling validations even in Draft state

### ISSUE THREAD

**Issue by JohnnieLo** [formio/formio#1255]
## Steps to Reproduce
1.  Create a form with 'Required' fields
2.  Create a draft submission, and don't fill in the required field
3.  Use Postman to make 'Patch' Method call update other fields and leave the 'required' field blank.  (I've tried adding in 'state' = draft as part of the patch call)
4. Formio returns validation error with the required field missing.

## Expected behavior
Draft submission updated without the validation error

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:
[
    {
        "op": "add",
        "path": "/state",
        "value": "draft"
    },
    {
        "op": "add",
        "path": "/data/upload/supportingDocuments/-",
        "value": {
            "supportingDocument": [
                {
                    "storage": "url",
                    "name": "upload-c04aa70c-22ac-42e4-a4b0-b82745d3268f.jpg",
                    "url": "",
                    "size": 12895,
                    "type": "image/jpeg",
                    "data": {
                        "baseUrl": "",
                        "project": "",
                        "form": ""
                    },
                    "originalName": "test1-12345.jpg"
                }
            ],
            "documentType": "medicalCertificate"
        }
    }

]

![postman](https://user-images.githubusercontent.com/84777946/119486878-12081700-bd9c-11eb-8a5f-db4c1c179ae5.PNG)

**Comment by wag110894** [comment]
Hello @JohnnieLo, 
Are you still experiencing this issue?

**Comment by airarrazaval** [comment]
If you are using the open source API server then you won't be able to use drafts (only available in the enterprise version).

Also, please remember that PATCH only works over existing submissions.

Now, assume you have this case:

1. Create a form with 2 components and make one required

```json
POST /myform HTTP/1.1
Host: http://example.com
Content-Type: application/json
{
  "components": [
    { "type": "textfield", "key": "firstName", "validate": { "required": true } },
    { "type": "textfield", "key": "lastName", "validate": { "required": false} }
  ]
}
```

2. Create a new submission filling only the required component

```json
POST /myform/submission HTTP/1.1
Host: http://example.com
Content-Type: application/json
{
  "data": {
    "firstName": "John",
  }
}
```

3. Make the second component required as well

```json
PUT /myform HTTP/1.1
Host: http://example.com
Content-Type: application/json
{
  "components": [
    { "type": "textfield", "key": "firstName", "validate": { "required": true } },
    { "type": "textfield", "key": "lastName", "validate": { "required": true } }
  ]
}
```

4. Try to make a PATCH replace operation over the original required value

```json
PATCH /myform/submission/<submission id> HTTP/1.1
Host: http://example.com
Content-Type: application/json
[{
  "op": "replace",
  "path": "/data/firstName",
  "value": "Jane"
}]
```

If you try this, it will fail as the submission validation will kick in before sending the PATCH request.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
