### ISSUE TITLE
[QUESTION] How to configure email client and file uploads.

### ISSUE THREAD

**Issue by multinerd** [formio/formio#1257]
1. Does the free self hosted application support emailing form actions? If so how do i configure it.
2. How do I configure file upload to work with S3 (I am actually using a self hosted Minio server but it should work the same).

I am using the free self hosted version using docker.

**Comment by airarrazaval** [comment]
Email client can be configured using the config file:

https://github.com/formio/formio/blob/dc85bedb75fea0e27066090e03b5df15180d138c/config/default.json#L59-L77

You can add a custom SMTP configuration aside from the default Gmail, Sendgrid and Madrill.  Just add the following:


```json
{
  "gmail": { ... },
  "sendgrid": { ... },
  "mandrill": { ... },
  "smtp": {
    "host": "smtp.example.com",
    "port": 465,
    "secure": true,
    "ignoreTLS": false,
    "auth": {
      "user": "user@example.com",
      "pass": "CHANGEME"
    },
    "allowUnauthorizedCerts": true
  }
}
```

You will need to configure it according your SMTP server settings.  You can also pass a custom SMTP configuration using the `custom` transport.  You may find more information here:

https://github.com/formio/formio/blob/2500a57cd7dc16f9862047c43aefdd41687b49ae/src/util/email.js#L338-L405


Regarding S3 support, unfortunately the open source version of formio does not have the s3 provider included.  You may try to create a simple file proxy server to handle those requests.  There is an example project here: https://github.com/formio/formio-upload.

**Comment by multinerd** [comment]
OK, apparently I configured SMTP correctly, i just forgot to change these lines

https://github.com/formio/formio/blob/dc85bedb75fea0e27066090e03b5df15180d138c/config/default.json#L30-L34

changing `email.type` to `smtp` resolved my first issue but now i'm getting this error

```
formio:error Error: 139759667277128:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

Ive tested my configuration with this code `https://github.com/adonaidiofanes/nodemailer-smtp-tester` and the email came through so I don't think its that.

**Comment by multinerd** [comment]
nvm, I forgot to restart my container. emailing was successful
