### ISSUE TITLE
Request: Docs about how Client Side vs Server Side Validations are supported

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#126]
Hey

looking for some tech docs or notes about how Client side validations and server side validations are supported.  Can see the options for things like Secret Validation, RegEx, etc, but do all client side validations get revalidated server side?

**Comment by zackurben** [comment]
@StephenOTT thanks for the suggestion, we do need this. In the meantime, for anyone else looking:

 - all validations done on the frontend, are also performed on the backend.
 - secret validations are only done on the backend

**Comment by zackurben** [comment]
Validation information is in the docs on a per component basis, please let me know if you need any specific question answered, or if you see any gaps in the docs: https://help.form.io/userguide/#form-components

**Comment by StephenOTT** [comment]
> secret validations are only done on the backend

@zackurben are secret validations supposed to still be exposed to the client's JSON of the form schema?
