### ISSUE TITLE
Help Page - Dynamic Select Filtering Not Working

### ISSUE THREAD

**Issue by CodeChaser** [formio/formio#1267]
## Environment
https://help.form.io/tutorials/walkthroughs/dynamic-select-filtering/

- Browser version:
Chrome #91.0.4472.77 (64-bit)
MSEdge #91.0.864.41 (64-bit)

## Steps to Reproduce
1.   Select a make
2.   Model has no data

## Expected behavior
1. After selecting a make
2. Model "select" should be populated

## Observed behavior
No model data appears for the two makes.

## Example
Just go to your help page link is above.

Besides the sample not working.  The page is difficult to follow

- There are missing screenshots
- Possible mistake entries in the help page examples.
- Bottom of the page "Filter Query" ... it possibly should read " data.makeResource=({data.make}) "
- The confusion can be found mid-way down the page where makeResource gets changed to makeReference, but it is magic!
- no explanation

Finally is there more examples of such as;
- __regex <- where is the help guide on this
- different uses of "Filter Query" and "Refresh On"

Is there a JS way or another way of doing the "Select" to "Select" filtering

**Comment by wag110894** [comment]
Hello @CodeChaser,

We are aware that the current example on our help docs is not working. We are currently working on updating our documentation and will ensure that this documentation has more screenshots moving forward.

**Comment by SimonF89** [comment]
Whats the correct way to configure selects?

**Comment by jeriah-formio** [comment]
Here is documentation on how to configure dynamic select filtering
https://help.form.io/faq/tutorials-and-workflows/cascading-select-dropdowns
 Please re-open if your issue persists. Thank you for your contribution!
