### ISSUE TITLE
Session Expiring post server restart - login multiple times

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#127]
When you restart server (OSS formio version), the user has to login multiple times across app.

Example:
1. Restart server
2. login
3. View a generic form that you created
4. Edit Login User form, and select Actions, and edit the Login action.
And the user will be logged out.

**Comment by travist** [comment]
I am not getting a logout, but am getting a weird bug in the OSS client app where the action is not able to be edited by trying to send PUT to the wrong api url. curious if they are related.

**Comment by StephenOTT** [comment]
It "feels" like the OSS client loses its session for whatever reason when going to certain pages.  Have not been able to replicate with exact steps, but will continue to test as it is a fairly annoying issue.  Have had it happen when trying to Save a Form, Edit a Action, open the Edit Form page, go to home, etc.

**Comment by zackurben** [comment]
@StephenOTT @travist is this still an issue?

**Comment by qodrinzo** [comment]
It seems to me, that clicking on the title of the last being-edited-while-session-expired form (or something similar), causes this repeated logging out. In the situation, other forms opens successfully and also the aforementioned form can be accessed through the "Edit" button next to its title.

**Comment by heather-formio** [comment]
Not able to replicate this issue. Closing this for now, please feel free to reopen with an example if anything persists.
