### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by dalareo** [formio/formio#128]
When installing and trying to test an app from Github I always get:

    Missing config.template.js file

**Comment by travist** [comment]
Which app are you using? Like ```formio-app-todo```, etc.

I think the issue is with that application.

**Comment by dalareo** [comment]
The error shows with whatever repo or option I choose from installation menu. The only way to make it work is to choose 0 (none) and manually copy app files to /app folder.

**Comment by m-t-r** [comment]
When you download from git, the install script is looking for a config.template.js file within the dist folder.  The repositories do not contain the dist folder, so the install fails.
