### ISSUE TITLE
Skip empty steps in wizard

### ISSUE THREAD

**Issue by Defcon0** [formio/formio#1281]
Hello,

I have a simple question (maybe it's a bug report).

I defined a wizard form and in step 2 there's a checkbox. In step 3 there's a textfield and it's only visible if the checkbox in step 2 is clicked.

Currently, the user then sees an empty step 3 if the checkbox in step 2 isn't clicked. Is there any way or workaround to skip the step or proceed directly to step 4 if the checkbox isn't clicked?

Thanks in advance for any help.

Bye Defcon0

**Comment by airarrazaval** [comment]
Please be aware that this repo is for the form.io API server (backend).  The default client that is installed (if you don't provide a client application of your own) is [formio-app-formio](https://github.com/formio/formio-app-formio).  That application is very outdated (it uses formio.js 2.32 if I'm not wrong).  So expect to have some compatibility issues and a lot of glitches.

For questions regarding the form rendering please submit the issue to the [formio.js repo](https://github.com/formio/formio.js).

**Comment by Defcon0** [comment]
OK, I understand. I solved the problem by another way btw ;)
