### ISSUE TITLE
Validation and VM instance creation

### ISSUE THREAD

**Issue by davidbalik** [formio/formio#1283]
I think you can significantly improve validation performance. Now VM instance is created every time validation is evaluated, see https://github.com/formio/formio/blob/master/src/util/util.js#L53. It seems to me like too heavy an operation to run that often.

I suggest to move the VM instance creation out of the Evaluator function, so that it is created only once in the validation process. It also ensures that the VM will have the correct global variables inside the instance because we leave `fm.freeze(args, 'args')` inside the Evaluator function. There is a need to remove `vm = null` and move the instance release to after the validation process.

I did some tests and the processing should be about 3x faster and less memory intensive.

**Comment by ccontour** [comment]
Interesting suggestion. We'll need to verify there are no secondary security implications or consequences that aren't immediately obvious. However, at a first glance I believe this seems like a good change to make

**Comment by travist** [comment]
I also think this is reasonable. If you submit a pull request with this change, we will run some tests on our end to ensure security requirements are met. Thanks!
