### ISSUE TITLE
Changing the panel title causes problems with blank characters [BUG] 

### ISSUE THREAD

**Issue by zpp-andy** [formio/formio#1285]
## Environment
Please provide as many details as you can:

- Hosting type
 -> https://formio.github.io/formio.js/app/builder

- Browser: Chrome
- Browser version: 91.0.4472.124

## Description
My Panel-Title is set by the content of field "Title" (Field inside the Panel).
When writing in the field "Title", the first space is always - continuously - removed immediately when typing, the second space remains.

## Steps to Reproduce
1. Type text with blank characters into the field "Title" 

## Example

{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "display": "form",
            "components": [
                {
                    "title": "Panel Title (Text from \"Title\" field)",
                    "collapsible": false,
                    "key": "panel",
                    "logic": [
                        {
                            "name": "ChangeTitle",
                            "trigger": {
                                "type": "json",
                                "json": {
                                    "!=": [
                                        {
                                            "var": "data.titlefield"
                                        },
                                        0
                                    ]
                                }
                            },
                            "actions": [
                                {
                                    "name": "Panel",
                                    "type": "mergeComponentSchema",
                                    "schemaDefinition": "schema = {title: data.titlefield}"
                                }
                            ]
                        }
                    ],
                    "type": "panel",
                    "label": "Panel Title (Text from 'Title' field)",
                    "mask": false,
                    "tableView": false,
                    "alwaysEnabled": false,
                    "input": false,
                    "components": [
                        {
                            "label": "Title (this Text ist for the Panel-Title)",
                            "tableView": true,
                            "key": "titlefield",
                            "type": "textfield",
                            "input": true
                        }
                    ],
                    "collapsed": false,
                    "reorder": false
                }
            ],
            "settings": {
                "pdf": {
                    "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
                    "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
                }
            },
            "input": true,
            "key": "",
            "tableView": false,
            "label": ""
        }
    ]
}

**Comment by HariVamsiK** [comment]
Hi 
I would like to contribute on this issue.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
