### ISSUE TITLE
Support for Wizard Pages/Panels that only load from server to client when validation requirement is met

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#129]
Sometimes there are "Pages" / panels that should only be loaded to the client when validation is met for that page.  (The page should not be sent to the client from the server unless the validation (server and client side) is met.  

Would be great if there was a way to load the panel to client only when validation is met so the user is unable to see what fields would be shown for pages that they should be seeing.

Example: If you have 3 pages, and the 3 page should only be shown if you meet specific validation rules.  But that 3rd page should not be sent to the client unless the validation rules are met. If the rules are not met, then the server does not send the form to the client.

Edit: Updated with additional information

**Comment by travist** [comment]
This should be the way it currently works. When you switch a form to "Wizard" display, each page will not continue unless the validation on that page has been met. Let me know if you are experiencing otherwise and we will look into it as a regression.

**Comment by StephenOTT** [comment]
:) sorry will update issue text.  "load" was meant to imply load from server.

**Comment by heather-formio** [comment]
Closing this as it is stale. Please feel free to reopen or suggest any enhancement requests you'd like to see in an new issue.
