### ISSUE TITLE
[BUG] Unable to validate URL Component entry in form with a DNS TLD like .network.

### ISSUE THREAD

**Issue by sinewaveinc** [formio/formio#1296]
## Environment
Please provide as many details as you can:

Working on a form that uses the URL Component validation feature, but the form would not accept one of the newer DNS TLDs, like .network.  Was using site https://www.sinewave.network as an example.

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.9.26
- Frontend framework:
- Browser: Brave, Safari, Microsoft Edge
- Browser version: Pretty sure it will give this issue on any modern browser.

- Brave (macOS):  Version 1.27.108 Chromium: 92.0.4515.107 (Official Build) (x86_64)
- Safari (macOS):  Version 14.0.3
- Edge (Windows):  Version 92.0.902.55 (Official build) (64-bit)

## Steps to Reproduce
1. Create form field with URL Component.
2. Set Validation On to Change.
3. Enter URL with one of the longer TLDs ( Feel free to use https://www.sinewave.network)

## Expected behavior
URLs containing valid TLDs should be validated.

## Observed behavior
URLs with longer (>=4 characters) TLDs are not validated.

## Example
Below are two screenshots; one showing a shortened TLD, and the other showing the longer TLD.

Shorter TLD:
![Screen Shot 2021-07-26 at 5 10 04 PM](https://user-images.githubusercontent.com/26521966/127060099-01319dc7-e8c5-4874-af42-728b26bd511d.png)

Longer TLD:
![Screen Shot 2021-07-26 at 5 09 43 PM](https://user-images.githubusercontent.com/26521966/127060152-d2380d9b-d7ce-4bb4-b795-73d3739965de.png)

**Comment by ccontour** [comment]
Cannot replicate under the current formio.js version. The [regex]( ttps://github.com/formio/formio.js/blob/master/src/validator/rules/Url.js#L9) works fine with your url using regex testers, and when tested in the url component
