### ISSUE TITLE
Create Form from json schema

### ISSUE THREAD

**Issue by philbritton** [formio/formio#13]
I'd like to be able to 'bootstrap' a project by pointing to a json schema file, which contains all my fields and validations - then I can edit and add more specific information about form layout etc in the formio ui.  Do you see this as a plausible feature?

**Comment by travist** [comment]
I believe what you are asking for is achievable today using a ```project.json``` file within an application. As an example, here is the project.json file found within the Sales Quote application https://github.com/formio/formio-app-salesquote/blob/master/src/project.json.  This file contains all of the fields and validations for all the forms within a project. If you don't want to include "form layout" then you would just include the fields as a flat list within the ```components``` of that form definition. This project.json can easily be created by Exporting a project within a https://form.io project.

Next, to bootstrap, you simply need to just place that file within the root of your application using the ```docRoot``` within ```package.json``` if the document root of the application is different https://github.com/formio/formio-app-salesquote/blob/master/package.json#L11.  Then, you should be able to use your application by simply referring to your GitHub project path (example ```travist/myapp```).

Hope this helps.
