### ISSUE TITLE
[Question]How to calculate result based on all submissions in a form or resource with a formula?

### ISSUE THREAD

**Issue by cetsupport** [formio/formio#1336]
**How to calculate result based on all submissions in a form or resource with a formula?**

**Further question, how to do this cross forms?**

I'd like to sum up some fields in a resource/form with reactive behavior, for example I submit a submission to form with one field A= 4. and my formula is sum(Field A). Then total value will be 4(assume this is the first submission in this form).

Later, I add another submission with field A=6, then the total value will be 10.

The total value can be store in another form or the same form.

One solution I'm current thinking is write a new action to implement a new function. Appreciate if you can share idea or suggestion.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
