### ISSUE TITLE
Hyperlink in Text Field

### ISSUE THREAD

**Issue by jeevanpillai** [formio/formio#1339]
Hi there, I'm looking for a way to be able to have a hyperlink clickable within the form submission edit page. I already am able to generate the link (based on other form values) but when I have a text field with it's data type set HTML and it's data is set to something like

`<a href="http://www.google.com" target="_blank">Link</a>`

It doesn't seem to render the hyperlink, it instead displays the html above as text. Is there a way I can make to generate the html hyperlink correctly? Thanks!

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
