### ISSUE TITLE
[BUG] Tee HTML attributes on a select component it located in a wrong level. Should be one level above. 

### ISSUE THREAD

**Issue by ricardophone2b** [formio/formio#1344]
![image](https://user-images.githubusercontent.com/64840719/137486202-b0737cd5-cf8f-4202-917a-8d2b37c5348d.png)

## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
