### ISSUE TITLE
[BUG] eachComponent method skips over components inside of columns

### ISSUE THREAD

**Issue by 0liver** [formio/formio#1348]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 4.13.5
- Formio.js version: 4.13.5
- Frontend framework: plain JS
- Browser: Chrome
- Browser version: latest

## Steps to Reproduce
1. Create a form with a Column component.
2. Add 
3. 

## Expected behavior
- Components inside columns should be iterated over.

## Observed behavior
- Components inside columns are skipped.

## Example
https://jsfiddle.net/r1cp2bg3/2/

The following screenshot shows the mismatch between code and data:

![image](https://user-images.githubusercontent.com/164360/138081471-12951e0d-3894-42a0-85ca-2628e843a8f9.png)

The following code block expects each `column` to have a `components` property which contains its children:
```js
        component.columns.forEach(function (column) {
          return eachComponent(column.components, fn, includeAll, subPath(), parent ? component : null);
        });
```

But from the screenshot (or inspection) we can see that the columns **_are_** arrays themselves. This is inconsistent with the component definitions in the form schema itself, as you can see in the above fiddle.

Please fix this - many of the other component helpers actually use `eachComponent` under the hood, and those column children are always ignored.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
