### ISSUE TITLE
HTML tags are not interpreted by form builder widgets i.e. in input fields

### ISSUE THREAD

**Issue by tmdoit** [formio/formio#1349]
What version of form builder is used in this repo? It needs update?

Screenshot taken from form builder available [here](https://formio.github.io/formio.js/app/builder)
![Zrzut ekranu 2021-10-22 o 15 16 55](https://user-images.githubusercontent.com/85706044/138460176-84bdb959-bd60-468b-800a-3215b35dfaea.png)

Screenshot taken from form builder available via docker instance
![Zrzut ekranu 2021-10-22 o 15 16 27](https://user-images.githubusercontent.com/85706044/138460179-09853073-9e32-4787-b22f-cdf75f5d8594.png)

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
