### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by m-t-r** [formio/formio#135]
When passing an ' * ' into a filter field using formio-grid, server will crash with 
SyntaxError: Invalid regular expression: /*/: Nothing to repeat...

This was passed to the server from formio-grid;
http://localhost:3004/filter/submission?limit=25&skip=0&sort=null&data.filterId__regex=%2F*%2Fi

This event is not unique to an ( * ) being passed.  Other characters, such as ( + ), will generate the same result.

**Comment by travist** [comment]
```/*/``` is an invalid regular expression. Do you mean ```/.*/```?

**Comment by m-t-r** [comment]
No, * was passed and the server crashed.

**Comment by zackurben** [comment]
@m-t-r The regex filter capability is not designed for user input, so you're getting an error when providing invalid regex. The server however, is not crashing so I'm not worried about it. If you want users to be able to provide their own regex, you can wrap the user input in your app to ensure that the regex is always valid.

**Comment by zackurben** [comment]
@m-t-r looks like I was incorrect, @travist is looking into this now. Thanks for the report!

**Comment by m-t-r** [comment]
Ok thank you.

**Comment by travist** [comment]
Fixed with latest build. Thanks.
