### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bhanu-affinidi** [formio/formio#1353]
## Environment
Please provide as many details as you can:

- Hosting type

  - [X ] Local deployment
    - Version: 
- Formio.js version: latest
- Frontend framework:latest
- Browser:latest
- Browser version:latest chrome

## Steps to Reproduce
1. 
2. 
3. 

## Expected behavior
should run after unzimmping
## Observed behavior

Error: Cannot find module 'sendgrid'

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by almereyda** [comment]
Parts of a permanent resolution have been presented in https://github.com/formio/formio/issues/1359#issuecomment-968504616
