### ISSUE TITLE
How to create Multilingual form

### ISSUE THREAD

**Issue by elicec59** [formio/formio#1354]
I want my form to be in 2 languages but I am not sure what is the best approach.

1. I have tried with JSON language in a custom component but I keep getting this error: "all non layout form component must have a non empty api key" while all of my elements have API key.
2. 
2. I have tried this http://formio.github.io/formio.js/app/examples/language.html but I can't seem to have the Javascript code work (I am also unsure where I have to add it in the form).

3. I tried the Dynamic Translations using Resources but I don't know where to set up the Dynamic Language Controller nor how to connect the Resource with the form.

Thanks for your help

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
