### ISSUE TITLE
How to customize EditGrid

### ISSUE THREAD

**Issue by viorelhojda** [formio/formio#1358]
Hello. I'm using the omponent EditGrid in order to create a List of small forms with some fields.
For example, this is the form that can be tested in formIo SDK sandbox:
{
  "display": "form",
  "settings": {
    "pdf": {
      "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
      "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
    }
  },
  "components": [
    {
      "label": "Te rugǎm sa introduci date legate de administratori",
      "openWhenEmpty": true,
      "tableView": false,
      "addAnother": "Adauga",
      "saveRow": "Salveaza",
      "removeRow": "Renunta",
      "clearOnHide": false,
      "rowDrafts": false,
      "key": "administrators",
      "type": "editgrid",
      "displayAsTable": false,
      "input": true,
      "components": [
        {
          "label": "Nume",
          "labelPosition": "left-left",
          "tableView": true,
          "validate": {
            "required": true,
            "minLength": 2,
            "maxLength": 50
          },
          "key": "name",
          "type": "textfield",
          "input": true
        },
        {
          "label": "Telefon",
          "labelPosition": "left-left",
          "tableView": true,
          "validate": {
            "required": true,
            "minLength": 4,
            "maxLength": 20,
            "pattern": "^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\\s\\./0-9]*$"
          },
          "errors": {
            "pattern": "Câmpul trebuie sa reprezinte un numǎr de telefon valid."
          },
          "key": "phone",
          "type": "textfield",
          "input": true
        },
        {
          "label": "Email",
          "labelPosition": "left-left",
          "tableView": true,
          "validate": {
            "required": true,
            "pattern": "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"
          },
          "errors": {
            "pattern": "Câmpul trebuie sa reprezinte un e-mail valid."
          },
          "key": "email",
          "type": "textfield",
          "input": true
        },
        {
          "label": "Data naşterii",
          "labelPosition": "left-left",
          "format": "dd-MM-yyyy",
          "tableView": false,
          "enableMinDateInput": false,
          "datePicker": {
            "disableWeekends": false,
            "disableWeekdays": false
          },
          "enableMaxDateInput": false,
          "validate": {
            "required": true
          },
          "key": "dateOfBirth",
          "type": "datetime",
          "input": true,
          "widget": {
            "type": "calendar",
            "displayInTimezone": "viewer",
            "locale": "en",
            "useLocaleSettings": false,
            "allowInput": true,
            "mode": "single",
            "enableTime": true,
            "noCalendar": false,
            "format": "dd-MM-yyyy",
            "hourIncrement": 1,
            "minuteIncrement": 1,
            "time_24hr": false,
            "minDate": null,
            "disableWeekends": false,
            "disableWeekdays": false,
            "maxDate": null
          }
        },
        {
          "label": "Adresǎ",
          "labelPosition": "left-left",
          "autoExpand": false,
          "tableView": true,
          "validate": {
            "required": true,
            "minLength": 5,
            "maxLength": 250
          },
          "key": "address",
          "type": "textarea",
          "input": true
        }
      ]
    },
    {
      "label": "Continuă",
      "customClass": "rounded-pill",
      "showValidations": false,
      "disableOnInvalid": true,
      "tableView": false,
      "key": "submit",
      "type": "button",
      "input": true,
      "hideOnChildrenHidden": false,
      "width": 6
    }
  ]
}

I have several issues/questions:
1.is it possible to not show the TABLE header and have the little forms editable as is, that is in "expanded" mode; so when "Add new" button is pressed the new small form should be visible always, without save/cancel bottom buttons;
Something like this:
![image](https://user-images.githubusercontent.com/64518064/140501083-b4a402b4-7146-4fe2-a692-675e75e5a58f.png)

2.with this exact format the "date/time" field is not shown as a Table header, why?
3.can i make the bottom buttons "save/cancel" dissapear so that the big form is validated when the BIG bottom "save/continue" button is saved? That is basically not to have the form submitted with each small form?

Thanks again for all the support !

**Comment by viorelhojda** [comment]
I've managed to do the same functionality using a"Container" whit small form components in it put in a "DataGrid" component.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
