### ISSUE TITLE
Error: sendgrid not accessible from nodemailer-sendgrid-transport

### ISSUE THREAD

**Issue by bmcbride** [formio/formio#1359]
My environment is macOS Big Sur (11.6), node v16.13.0

I'm following the [docker-compose](https://github.com/formio/formio#run-with-docker-compose) directions and after downloading and unzipping [v2.2.6](https://github.com/formio/formio/releases/tag/v2.2.6), running `npm install` without any errors, I'm getting the following error when running `docker-compose up`:

`npm ERR! sendgrid not accessible from nodemailer-sendgrid-transport`

Any tips or suggestions on how to proceed or troubleshoot would be greatly appreciated, thanks!

**Comment by sethpjohnson** [comment]
I noticed the packages were still referencing `sendgrind` instead of `@sendgrid/mail`

`rm -r node_modules/` and `rm package-lock.json`

then `npm install` (I needed to do `--legacy-peer-deps` also) and then the docker install should work.

**Comment by bmcbride** [comment]
Thanks @sethpjohnson! I was able to get that to work!

**Comment by almereyda** [comment]
I was able to issue the sequence of commands from @sethpjohnson above without `--legacy-peer-deps` from within `/.npm-packages/` inside the container, and `node main` from `/app` would finally run.
