### ISSUE TITLE
[BUG] Cannot inject nunjuck macro into email template

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#1360]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 7.2.2
- Formio.js version: 4.14.0
- Frontend framework: Vuejs
- Browser: Chrome/Firefox 
- Browser version: Latest

## Steps to Reproduce
1. Create a simple form with one textfield
<img width="440" alt="image" src="https://user-images.githubusercontent.com/21692768/141846169-09ab494d-f73c-4c9f-839f-0e1f74d84936.png">

2.  Create an email action

<img width="423" alt="image" src="https://user-images.githubusercontent.com/21692768/141846230-a59b88f6-8e81-4367-aee3-66a8df902504.png">

3. Create a submission ==> Email is sent.
4. Add a macro to the message box:

```
{% macro double(field) %}
<h2> {{ field }} </h2>
<h2> {{ field }} </h2>
{% endmacro %}
```
5. Create a submission

## Expected behavior
Email is sent (at this point the macro is not even called yet)
## Observed behavior
No email is called.
Error message found in the log:

```
2021-11-15T19:55:22.942Z formio:email:nunjucksInjector (unknown path) [Line 1, Column 2736]
  unknown block tag: endmacro
```

The macros work fine in our Portal version 6 (emails are heavily customized using macros)

**Comment by xjia-lighthousehq** [comment]
fixed in formio-worker 1.16.2
https://github.com/formio/formio-workers/commit/938d4b1e8cddc55402514623bb4711a4207c8e78
