### ISSUE TITLE
[BUG] The formio token is having invalid signature

### ISSUE THREAD

**Issue by kurianbenoy-aot** [formio/formio#1362]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 2.0.0--rc.34
- Frontend framework: React
- Browser: Firefox
- Browser version:

## Steps to Reproduce
1. The generated formio token when logging in has a invalid signature when decoding with jwt.io is having an invalid signature

![image](https://user-images.githubusercontent.com/70306694/142162028-0f81d673-7ba4-4c94-b91c-e539d6b2dd95.png)
 

## Example

![image](https://user-images.githubusercontent.com/70306694/142162067-c6abefa4-27d4-4a34-a303-c7e1597be81e.png)

If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by kurianbenoy-aot** [comment]
@ccontour by jwt_secret up in API server, what exactly are you meaning in setup?  I have setup the logic to generate `formiotoken` as given below with secret key set up as `changeme`. What should I do to make my secret key verified?

```
jwt.sign(
    {
      external: true,
      form: {
        _id: USER_RESOURCE_FORM_ID, // form.io form Id of user resource
      },
      user: {
        _id: user, // keep it like that
        roles: roles,
      },
    },
    "changme"
  );
  ```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
