### ISSUE TITLE
Not able to add validation at dataGrid level, also not able to find means to show validation at specific index

### ISSUE THREAD

**Issue by sumitbaliyan** [formio/formio#1368]
## Environment
- Formio.js version: v4.10.2
- Frontend framework: JS Code
- Browser: chrome
- Browser version: Latest version

## Steps to Reproduce
1. Create a form with a DataGrid (API name: dataGrid) and add Text Field (Text Field: textField) inside it.
2. Add below validation at DataGrid level
_valid = (data.dataGrid[0].textField === 'test') ? true : 'Enter correct value';_
3. Add below validation at Text Field level
_valid = (data.dataGrid[1].textField === 'test') ? true : 'Enter correct value';_

## Expected behavior
- Validation error should be thrown if user enters any value other than 'test' in text field index 0 and tabs out (DataGrid level validation).
- Validation should be thrown if user enters any value other than 'test' in text field index 1 and tabs out (Text Field level validation)

## Observed behavior
- Validation applied at DataGrid level does not work when I enter any value other than 'test' in text field index 0 and tab out. 
- Validation applied at text field is displayed for all text field index irrespective of validation failing for whichever index. It's more of knowledge gap I would say as of now, as I am not sure how to apply validation for specific index if at all we can.  

Would appreciate if can get handle of methods that I can refer to work with DataGrids / EditGrids.

## Example
![EditGrid](https://user-images.githubusercontent.com/31531896/144016241-d64778d3-4309-4707-b2cb-9e876eef3f3f.png)

For code or form JSON, please enclose in a code block:
[jsonTemplate-formio.txt](https://github.com/formio/formio/files/7624330/jsonTemplate-formio.txt)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
