### ISSUE TITLE
[QUESTION]  How can you change a field value on 'saving' a form.

### ISSUE THREAD

**Issue by MarkGabb-Alcumus** [formio/formio#1369]
I've been following this example for setting a fields value when you 'save' a form.

What I'd like to do is change a field I've got called 'state' when I submit to 'pending'.

What I'm doing doesn't change a fields value on submission which is blocking any further investigation into whether form.io could work for the business case I'm looking at.

Here is a screenshot of the form with a 'Save' button and a 'status' field.
<img width="1426" alt="Screenshot 2021-12-07 at 20 25 52" src="https://user-images.githubusercontent.com/41109473/145101343-c974f85a-7b97-4884-9774-eeb3bd1d094f.png">

This shows the 'status' field.
<img width="1454" alt="Screenshot 2021-12-07 at 20 26 05" src="https://user-images.githubusercontent.com/41109473/145101349-d671d0df-ce82-4d1e-bf66-627ffe2c1f82.png">

This is the configuration for the 'save' button which to my knowledge should set the status field to 'pending' on saving?
<img width="1435" alt="Screenshot 2021-12-07 at 20 26 22" src="https://user-images.githubusercontent.com/41109473/145101351-00050bf8-8eeb-4b8d-8f4d-47458f36aad5.png">

Some other config on the save button that might help.
<img width="1444" alt="Screenshot 2021-12-07 at 20 26 15" src="https://user-images.githubusercontent.com/41109473/145101354-1919567e-f1c6-47e7-a411-24a2dcd26389.png">

Any help would be hugely appreciated! Let me know if extra information will help 

Username: markgarethgabb

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
