### ISSUE TITLE
[QUESTION] List Forms API by owner name / id

### ISSUE THREAD

**Issue by chrisfyk** [formio/formio#1380]
I am using the List From API to filter the forms created by owner name / id.  But I found that, I can't get the correct result from the query.

Any hints?  Or any proper way to do this?

API: 
projectUrl/form?owner=61c135289db96b586c01b015

**Comment by sdancer75** [comment]
Looking for the same thing but it returns empty []. Did you find any solution?

**Comment by sdancer75** [comment]
Anyway, I just found a solution for my case. 

I created a custom field ie "CustomOwnerID" that I fill at the form's creation time. Now the API url will look like

```projectUrl/form?customOwnerID=61c135289db96b586c01b015```

Take a look at the snippet below. Hope it helps.

```
const mapStateToProps = state => {
	const auth = selectRoot('auth', state);

	return {
		form: {
			display: 'form',
			properties: {
				customOwnerID: auth.user._id,
				customOwnerName: auth.user.data.name,
				customOwnerEmail: auth.user.data.email,
				customOwnerPhonenumber: auth.user.data.phonenumber,
				
				
			},
 ..........
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
