### ISSUE TITLE
[Question] Keeping custom metadata fields in sync for formrevisions

### ISSUE THREAD

**Issue by christophermurphy2-veradigm** [formio/formio#1381]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: formio/formio-enterprise:6.5.6 (docker image)
- Formio.js version: ~3.28.2
- Frontend framework: AngularJS for the builder
- Browser: Chrome
- Browser version: Version 96.0.4664.110 (Official Build) (64-bit)

## Question
So, our scenario is like this:
- We have a "settings" section on our forms which contains some extra metadata we care about. This seems like a field we were told it would be safe to keep our own stuff in, the original dev who did this isn't exactly around to ask.
- Updates to the settings section will update the section in "forms" in mongo, but NOT the value in the "formrevisions". From local testing it seems like only changes to the "components" will result in a version update and thus a new revision.
- When we later request a form by a specific version, it pulls from "formrevisions" and gives us the out of date "settings". Simply pulling the latest value from "forms" would be correct most of the time, but doesn't account for edge cases where a new version is published before we ask for the version of a form tied to a submission.

With this in mind, is there an existing way to get form.io to either:
- Update the value in "formrevisions".
- Bump the form version, which would also give us a new revision with the correct "settings".

I think we'd prefer to just keep "formrevisions" in sync if possible, so we don't break the existing scheme of only updating the version when components change and don't flood our capacity with new form versions for changes like "patient friendly title". Our version is also a bit older to work with v3 which we're still stuck on for now, but if there is a feature in newer versions only we need to upgrade anyways.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
