### ISSUE TITLE
[BUG] Build image failed with sendgrid

### ISSUE THREAD

**Issue by rickywu** [formio/formio#1385]
## Environment

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:2.3.3
- Frontend framework:
- Browser:Chrome
- Browser version:

## Steps to Reproduce
1. npm install
2. docker-compose up

## Observed behavior
npm ERR! sendgrid not accessible from nodemailer-sendgrid-transport

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-19T04_37_30_459Z-debug.log
ERROR: Service 'formio' failed to build: The command '/bin/sh -c npm ci --prefi                                                                                                           x=$NPM_PACKAGES' returned a non-zero code: 1

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
