### ISSUE TITLE
[BUG] Submit button disabled when EditGrid uses Choices and a required field

### ISSUE THREAD

**Issue by martym00se** [formio/formio#1388]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ X] Local deployment
    - Version:  3.8
- Formio.js version:  tested and broken in both 4.14.1-rc.4 and 4.15.0-rc.1

**This is NOT broken in v4.13.10** 

- Frontend framework:   javascript
- Browser:   Chrome
- Browser version:    97.0.4692.99

## Steps to Reproduce
1. Add a choices JS select (with Raw JSON) and another required field like a text field to en Edit Grid
2. Add a new row and save.
3.   Start to add another row, choose an item from the select.     The form submit button becomes disabled.
4. Cancel editing the row, the form submit button is still disabled even though there are other valid rows.    
## Observed behavior

When canceling a row edit, you should still be able to submit when there are already rows in the table.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
