### ISSUE TITLE
[QUESTION] should i use formio/formio and can i change it?

### ISSUE THREAD

**Issue by Amir-MP** [formio/formio#1396]
Hello , I have a problem with  Formio .
my team asked me to create a formio project locally and they want kind of all feature in formio, they say i should use https://github.com/formio/formio , this project , but i can't change anything in this project, like language , and datepicker (we use Shamsi/jalali Calendar ,it's totally different from Gregorian calendar),
should i use this project(https://github.com/formio/formio) and can i change it?  or can I use https://github.com/formio/angular? with https://github.com/formio/angular , i changed language and added a custom component datepicker.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
