### ISSUE TITLE
[Feature] Sentry Integration 

### ISSUE THREAD

**Issue by madflow** [formio/formio#1400]
- Hosting type
  - [x] Local deployment
    - Version: 7.3.1 Enterprise

Please consider providing an optional Sentry Integration of the Formio Enterprise Server.

We have server crashes after uncaught exceptions like 

```
Uncaught exception:
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Invalid alias".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

For us this is pretty much impossible to debug and send you as a Bug Report without any insights.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
