### ISSUE TITLE
Multiple Admin Resources

### ISSUE THREAD

**Issue by sdancer75** [formio/formio#1401]
Hi, I want to create a new role "_formbuilder_" as well as a resource that keeps users of that role **seperated** from the _admin resouce,_ that has the ability to create forms and of course the ability to manage only the forms that this role creates (not globally). 

Setting the key "admin:true" for the formbuilder role, it seems that after a new installation no one has the permission to create forms even the default admin role (creating a new form shows no authorization). 

Is that possible?

```
  "roles": {
    "administrator": {
      "title": "Administrator",
      "description": "A role for Administrative Users.",
      "admin": true,
	  "default": false				  
    },
    "authenticated": {
      "title": "Authenticated",
      "description": "A role for Authenticated Users.",
	  "admin": false,
      "default": false					  
    },
    "anonymous": {
      "title": "Anonymous",
      "description": "A role for Anonymous Users.",
	  "admin": false,			 
      "default": true
    },
    "formbuilder": {
      "title": "FormBuilder",
      "description": "A role for Form Builder Users.",
      **"admin": true,**
      "default": false	  
    }		
  },
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
