### ISSUE TITLE
Fom.io Extending Components in Angular 12

### ISSUE THREAD

**Issue by DivayMeta** [formio/formio#1406]
I'm trying to create a custom component that extends formIO select field in angular 12 application. How we can override existing select field functions and how to call a custom function when clicked on select field.
![Capture](https://user-images.githubusercontent.com/102352263/160083154-4ce04969-a231-493f-9710-da7a04e20c41.PNG)

Thanks and regards

**Comment by DivayMeta** [comment]
@Marc.Bertrand

**Comment by DivayMeta** [comment]
@Marc.Bertrand

**Comment by DivayMeta** [comment]
@Marc.Bertrand

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
