### ISSUE TITLE
[BUG] Can't migrate to DocumentDB because "partialFilterExpression" in index is incompatible with DocumentDB

### ISSUE THREAD

**Issue by CatBakun** [formio/formio#1409]
Are this indexes currently used? Can I drop them to make the migration?

## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: formio-enterprise:6.11.5
- Formio.js version: N/A
- Frontend framework: N/A
- Browser: N/A
- Browser version: N/A

## Steps to Reproduce
1. Having a formio backend deploy (formio-enterprise:6.11.5) running on MongoDB create (dump) an archive for restore purposes.
2. Use that archive to be restored on a DocumentDB host.

## Expected behavior
Migration runs successfully.

## Observed behavior
Migration fails, because formio MongoDB "submissions" and "forms" collections haves indexes using "partialFilterExpression" which is not supported by DocumentDB.
Error: `Failed: test.forms: error creating indexes for test.forms: createIndex error: Field 'partialFilterExpression' is currently not supported`

`db.forms.getIndexes()`

shows:

```js
...
        {
                "v" : 2,
                "key" : {
                        "deleted" : 1
                },
                "name" : "deleted_1",
                "ns" : "test.forms",
                "background" : true,
                "partialFilterExpression" : {
                        "deleted" : {
                                "$eq" : null
                        }
                }
        },
...
```

`db.submissions.getIndexes()`

shows:

```js
...
        {
                "v" : 2,
                "key" : {
                        "deleted" : 1
                },
                "name" : "deleted_1",
                "ns" : "test.submissions",
                "background" : true,
                "partialFilterExpression" : {
                        "deleted" : {
                                "$eq" : null
                        }
                }
        },
...
```

## Example
N/A

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
