### ISSUE TITLE
[Question] How to avoid using localStorage for storing jwt-tokens

### ISSUE THREAD

**Issue by hbobka** [formio/formio#1411]
Hi guys,

is it possible to avoid the localStorage for storing the jwt-tokens set by Formio.setToken()?
Can this be configured (sessionStorage, Cookie ...)?

Greetings

**Comment by amjmhs** [comment]
Storing tokens into localeStorage is considered as "bad practice". See:
- https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html#token-storage-on-client-side
- https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

So i would be nice to have an alternative for this.

**Comment by hbobka** [comment]
moved to: https://github.com/formio/formio.js/issues/4736
