### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dashu1999** [formio/formio#1412]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:
 throw new Error(`Could not connect to the given Database for server updates: ${dbUrl}.`);
                ^

Error: Could not connect to the given Database for server updates:
```js
// your code here
```

**Comment by Rebaz-balisani** [comment]
1. I downloaded the formio zip file and then I extracted it to my C drive after that i opened it then i clicked on an empty space the hold keyboard Shift key and selected OPEN POWERSHEL WINDOW HERE. 
2. inside the powersell I wrote "npm install", and it went all ok so after that i wrote "npm start" i waited a while then a messeged come up see the screenshot to have better view.
![formio](https://user-images.githubusercontent.com/84542451/219037859-88cc91d0-a3c8-4520-8719-59b014984c10.PNG)
