### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shuhaib-aot** [formio/formio#1420]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## more end points are exposed
1.  http://localhost:3001/form
2. http://localhost:3001/access
3. http://localhost:3001/form/formid/components
4. etc...

**Comment by 0liver** [comment]
1. Please give your issue a title.
2. Please add a version number.
3. Please describe what your expectations are, and what the behavior is you are seeing instead.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
