### ISSUE TITLE
[BUG] SSO Azure AD OpenID - Cannot read properties of undefined (reading 'toLowerCase'))

### ISSUE THREAD

**Issue by zyq524** [formio/formio#1421]
## Environment
Please provide as many details as you can:

- Hosting type
  -  Form.io 7.3.2 image deployed to App Service as a web app running on Linux

## Steps to Reproduce
1. Creating a new application through "App registrations" in the "Azure Active Directory".
2. Filling in the application details as below
![image](https://user-images.githubusercontent.com/1371040/167814243-052006c1-d895-4673-8896-8d3f5d0a6885.png)
3. Adding a new "SSO Login" button with "Remote Authentication" action

## Expected behavior
AD user can login by using the "SSO Login" button
## Observed behavior
Got the following error while the "sign-in logs" in Azure reported the AD user logged in success.
**Could not connect to API server (Cannot read properties of undefined (reading 'toLowerCase')):**
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1371040/167816450-130ee3f9-3ff4-4005-9c9e-737ec6ac286c.png">

**Comment by datapolitical** [comment]
I'm having the same issue. What was the resolution? @zyq524
