### ISSUE TITLE
[Question] How to register a custom component on the server?

### ISSUE THREAD

**Issue by Susccy** [formio/formio#1425]
I have created a custom component for my custom client editor with formiojs and registered it with `Formio.use()`. It works on the client and I can also save the form with the custom component to the locally hosted formio API server (cloned from this repo) but when I try to save a submission I get a BadRequest response due to a validation error on the component even though the entered data is fine.

Do I need to register the component via `Formio.use()` on the server as well or is that not required and I'm doing something wrong in my client editor? If I need to register it on the server, where in the code should I do that?

**Comment by harthorst** [comment]
What worked for me:
1) take https://github.com/formio/contrib as starting point
2) set "module": "commonjs" in tsconfig.json
3) build the package (e.g. npm pack)
4) import the package in formio server (e.g.: npm i <path_to_tgz>)
5) add the following lines in index.js:
`
const myPlugin = require('<module-name>');
util.Formio.Formio.use(myPlugin.default);
console.log('.....', util.Formio.Components); // this will show you the registered components
`
