### ISSUE TITLE
[BUG]  Unable to render form.io on Android 5

### ISSUE THREAD

**Issue by inai-girish** [formio/formio#1427]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.13.5
- Frontend framework: Vanilla Js
- Browser: Chrome 
- Browser version: Chrome 37

## Steps to Reproduce
1.  Boot an android emulator with API level 21, Android 5
2. Go to chrome and type the following URL - https://formio.github.io/formio.js/app/builder

## Expected behavior
form.io components should render and we should be able to drag and drop the builder components.

## Observed behavior
Unable to view form.io components.
![image_form](https://user-images.githubusercontent.com/86840548/169525279-8f6ae0bd-450f-4398-a5f8-69a5c31a0704.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
