### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by datapolitical** [formio/formio#1428]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Install form.io enterprise
2. set up Azure Saml SSO
3. Try to log in

## Expected behavior
successful log in
## Observed behavior
Redirection to error message: Cannot read properties of undefined (reading 'toLowerCase')
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

I'm having a version of the same issue as #1421

**Comment by wag110894** [comment]
@datapolitical, Can you provide feedback as to what version you are using?

**Comment by datapolitical** [comment]
7.3.2

**Comment by CHASESY** [comment]
@datapolitical are you still blocked on this?

**Comment by datapolitical** [comment]
No, Leslie helped me resolve it by email. The issue was email mappings not being set up correctly.

**Comment by CHASESY** [comment]
Sounds good. Closing issue.
