### ISSUE TITLE
bcrypt installation fails on windows 7

### ISSUE THREAD

**Issue by goinfolink** [formio/formio#143]
[npm-debug.txt](https://github.com/formio/formio/files/367751/npm-debug.txt)

**Comment by zackurben** [comment]
@goinfolink Thanks for the feedback, and more importantly the npm file! Hmm, it looks like this is a known issue with bcrypt on windows:

https://github.com/ncb000gt/node.bcrypt.js/issues/435
https://github.com/ncb000gt/node.bcrypt.js/issues/340

You can try to get around this by updating node or gyp, but it will take me some time to get my hands on a windows machine.

**Comment by zackurben** [comment]
This should be fixed now,

You can get all the ms build dependencies with `npm install --global --production windows-build-tools`

Then `npm install --msvs_version=2015`

Note: you may need to change the msvs, depending on what version of visual studios you have, additionally you will need python 2.7 for node-gyp to work correctly.
