### ISSUE TITLE
Simulating Formio post request

### ISSUE THREAD

**Issue by datapolitical** [formio/formio#1430]
I want to simulate a formio webhook POST request in postman, but I can't figure out what the parameters and the body should be.

I obviously know what the form data is, though I'm not entirely sure how to format a selectBoxes (set of checkboxes) correctly, but the rest of the form body is not clear to me.

If someone can provide a quick example of how you would mimic a simple formio webhook request in postman, that would be super helpful.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
