### ISSUE TITLE
Form Manager SSO

### ISSUE THREAD

**Issue by datapolitical** [formio/formio#1432]
Having successfully set up SSO for the portal, I'm not trying to do the same for four manager, problem is, the documentation is rather unclear about precisely what steps to take.

https://help.form.io/userguide/portalsso#form-manager-sso

I set up each stage of the project that I created with SAML SSO, and created the SAML login button according to the instructions, but it only appears when I visit the form manager using the slug formio rather than any of the project stage names (authoring or live).

Logging in with that link simply gives me the error "unauthorized". Using the administrative username and password, I get a very long database error which I attempted to solve by adding database indexes, but which did not fix the problem.

I've emailed Support, and hopefully will hear back soon from them, but I share this issue here because I think this documentation section needs meaningful improvement if you want people to be able to configure form manager SSO themselves. 

and just in case I was being uniquely obtuse, I also asked other people in my company to take a look at the section to see if they felt the same way I did, and they agreed that it was difficult to understand.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
