### ISSUE TITLE
Logic Tab Missing on Form Components

### ISSUE THREAD

**Issue by motherb2** [formio/formio#1442]
Just more of a general question than a bug, but what exactly is the Logic tab's functionality?

I see it on the Enterprise Form Builder:
![Screen Shot 2022-07-01 at 12 35 55 PM](https://user-images.githubusercontent.com/48922600/176935705-93354bd4-b92f-4d08-ae6e-0c2b7c812b0a.png)

But not on my local form builder:
![Screen Shot 2022-07-01 at 12 38 01 PM](https://user-images.githubusercontent.com/48922600/176935772-852aeabb-2bad-4b20-b010-37ba00f25c4f.png)

And I'm just wondering what the capabilities of this feature are? I'm trying to do backend validating of fields where their values are changed based on the validation against other field values etc. 

I first used the Conditional Component functionality to write conditional logic. I then ran my submission against the /validate/ API but I found that this doesn't return updated values but rather just will remove/keep values.

I was hoping the Logic tab would be where I'd be able to write logic to UPDATE values upon validation but I'm not really sure.

Some clarification on this would be greatly appreciated

**Comment by tabooo** [comment]
Confirm. It is missing on my local server also.

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
