### ISSUE TITLE
Custom Default Value for a field loads multiple times while loading the form

### ISSUE THREAD

**Issue by Stuti910** [formio/formio#1443]
Greetings,

We have a form in form io that had a text field on which we called ajax service and one more where we were calling database lookup. During testing we noticed that the service and database lookup are being called multiple times during the form load causing performance issues. To confirm this, we applied alert in the custom value field and saw the alert window around 4-5 times during the form load. Here are the images to demonstrate what we did here:

![image](https://user-images.githubusercontent.com/108784955/177482027-4997fab7-b1c4-40b0-8272-258f7ef23642.png)

![image](https://user-images.githubusercontent.com/108784955/177481695-e29a7d12-3878-4e80-ba61-97ea10724482.png)

![image](https://user-images.githubusercontent.com/108784955/177481833-7106863c-3b2e-4c75-aad1-b9444558c46a.png)

Above changes resulted in 4 alerts while form load. Are we missing something here or is this how its suppose to behave?

Thanks in advance.

**Comment by pulkit877** [comment]
I am also facing the same issue and have this concern. Can anyone help us understand this functionality

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
