### ISSUE TITLE
[BUG] defaults in resource are not respected when using API

### ISSUE THREAD

**Issue by peterhall-agrimetrics** [formio/formio#1444]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 3.0.0-rc.4

## Steps to Reproduce
1. Create a resource containing a checkbox `foo` with a default value of `false`
2. Use an API request to create a submission without `foo` on the payload
3. Retrieve the submission using the API

## Expected behavior

The returned submission has `foo: false`. This was the behaviour in a previous version (we were using 2.1.0-rc.12 before)

## Observed behavior

The returned submission does not have `foo` on it.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
