### ISSUE TITLE
[Question] Is it possible to create sub-forms and integrate them in different forms ?

### ISSUE THREAD

**Issue by Aminapoc** [formio/formio#1446]
Hello,

Is it possible to build "sub-forms" that are called in other forms.
Example:
Sub-form containing : Name, address, phone number .. 
I will need this sub-form in many forms and to avoid creating these fields as many forms as I have, I want to link it directly.

Thank you for your answers !

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
