### ISSUE TITLE
[BUG] Changing the title of the wizard through a logic

### ISSUE THREAD

**Issue by Gabrbra** [formio/formio#1447]
## Environment
Please provide as many details as you can:
In the panel logic, I defined the trigger when the select value is 1, and action "schema = {title: 'Test 1'};"

- Bug Video
https://user-images.githubusercontent.com/42838765/180861231-45937f2f-b54f-420a-8e9c-46cb1d56c6d3.mp4

- Form
![image](https://user-images.githubusercontent.com/42838765/180860198-abd12a87-5460-463c-b358-e6702a8f5db7.png)
-Trigger
![logictriggerselect](https://user-images.githubusercontent.com/42838765/180859926-2321845c-a4f4-41e7-bd2f-ee86206eb91b.png)
-Action
![logicactionselect](https://user-images.githubusercontent.com/42838765/180860068-fb0731d6-284d-40c7-8539-e471bf510d9c.png)

- Hosting type
  - [x] Form.io online
  - [ ] Local deployment
    - Version: 
- Browser: Chrome
- Browser version: 103

## Steps to play
1. Create a display wizard
2. Create a selector within the page 1.
3. Assign two options (Test 1 and Test 2) as values to select.
4. Include the logic mentioned in the images within the panel configuration on page 1.

## Expected behavior
Change page title according to select value
## Observed behavior
Changes the title only in the selection of the second value of the select.

## Example
- Form
![image](https://user-images.githubusercontent.com/42838765/180860198-abd12a87-5460-463c-b358-e6702a8f5db7.png)
-Trigger
![logictriggerselect](https://user-images.githubusercontent.com/42838765/180859926-2321845c-a4f4-41e7-bd2f-ee86206eb91b.png)
-Action
![logicactionselect](https://user-images.githubusercontent.com/42838765/180860068-fb0731d6-284d-40c7-8539-e471bf510d9c.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
