### ISSUE TITLE
[BUG] Number submission is not converted to number type on server

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#1453]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: {"version":"7.4.0","schema":"3.3.14"}
- Formio.js version: Renderer: 4.14.8
- Frontend framework: Vuejs
- Browser: Chrome/Firefox/Safari

## Steps to Reproduce
1. Create a form with following definition

```
  "components": [
    {
      "label": "Address",
      "tableView": true,
      "key": "address",
      "type": "textfield",
      "input": true
    },
    {
      "label": "Address number",
      "mask": false,
      "tableView": false,
      "delimiter": false,
      "requireDecimal": false,
      "inputFormat": "plain",
      "truncateMultipleSpaces": false,
      "calculateValue": "value = data.address.split(\" \")[0];",
      "key": "addressNumber",
      "type": "number",
      "input": true
    },
    {
      "label": "Submit",
      "showValidations": false,
      "tableView": false,
      "key": "submit",
      "type": "button",
      "input": true,
      "saveOnEnter": false
    }
  ]
```

2.  Create a submission with input "100 Zeppelin"
<img width="443" alt="image" src="https://user-images.githubusercontent.com/21692768/183130375-43f6f3bf-2776-4e91-b276-f86c167eb3b8.png">

3. Export Json data 

## Expected behavior
The data should be validated in the front-end, or casted to number type
addressNumber value should be `100`

## Observed behavior
addressNumber value is `"100"` (string type)

This issue does not happen on portal.form.io or next.form.io

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
