### ISSUE TITLE
[BUG] Formio EditGrid row delete and save functions 

### ISSUE THREAD

**Issue by iyyappanrock535** [formio/formio#1460]
## Environment
Formio EditGrid row delete and save functions 

I'm using react formio npm. The EditGrid row delete, add, edit events not available. How to handle the events functions?

**Comment by HariVamsiK** [comment]
Hi
I would like to contribute on this issue.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
