### ISSUE TITLE
[BUG] got “x-file-token is invalid.“ error when export pdf

### ISSUE THREAD

**Issue by kongxx** [formio/formio#1461]
## Environment
I export pdf file from https://portal.form.io/ , but I got the error "x-file-token is invalid."
Here is the url: https://api.form.io/project/62cd93a9a52f5eba15c62599/form/630633308e56151417ca8ef8/submission/630b22800925c9959186b5bc/download?token=KrtqSnrdcKIUJqIdtRFaGIzuVHj4pM&_ga=2.140703154.1035513660.1661671086-425062866.1661350980

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser: opera
- Browser version: 90.0.4480.54 (x86_64)

## Steps to Reproduce
1. logon https://portal.form.io/ 
2. navigate to forms -> "[myform]" -> use -> submit the form -> export pdf
3. got the error "x-file-token is invalid."

## Expected behavior
download/open pdf

**Comment by vikanirav** [comment]
Hello,

I am also getting same error at the time of click on PDF icon to view PDF file.

**Comment by brendanbond** [comment]
Are you on a "Basic" plan? At any time did you change the PDF server to another URL in your project settings?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
