### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by adityapathak026** [formio/formio#1467]
## How to add extra plugins in CKeditor for textArea

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by brendanbond** [comment]
Can you elaborate? Closing this for now
