### ISSUE TITLE
[OPEN SOURCE] Is there a way to use  Email Authentication with the open source version? 

### ISSUE THREAD

**Issue by calaf2** [formio/formio#1469]
## Environment
Please provide as many details as you can:
Hi, I've developed a Vue application with the open source version (hosted on my computers).
I'm trying to set up the [Email Authentication](https://help.form.io/developers/email-login) and [Password Reset](https://help.form.io/tutorials/password-reset), but the substitution only seems to work on the form.io platform.
Is there a way to use it with a local deployment?
Thanks

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: Latest
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. follow the recipe at https://help.form.io/tutorials/password-reset
2. test online
3. test on local deployment

## Expected behavior
[[token(data.email=user)]] is properly replaced by a temp token in the sent email
## Observed behavior
[[token(data.email=user)]] is kept as is in the generated url.
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by PrathyushaModala** [comment]
Hi @calaf2 ,
I would like to work on this.

**Comment by calaf2** [comment]
Hi, @PrathyushaModala
Much appreciated, thank you.
I haven't dug into the source yet, and wanted to ask prior to spending time in a software I'm not familiar with.
I've seen unanswered questions about this, but I don't really see any reason why this feature wouldn't be available.
Best
Eric

**Comment by calaf2** [comment]
#951 has just been updated: this feature is only available in the commercial version. It wold be great to have a way to implement it without patching the source.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
