### ISSUE TITLE
OAuth setup

### ISSUE THREAD

**Issue by lukuser** [formio/formio#1473]
I configured OAuth Authentication in Project settings and saved (by following this help link: [https://no-help.form.io/integrations/okta/#okta-app](onenote:#section-id={EEA49416-D045-4D44-BBCB-691FD137C341}&end&base-path=C:\Box\Lukasz%20Kustusz\Projects\AY%20Projects\Finance%20DM.one)), but when I want to add an Action (OAuth (Premium)) to the Login form, the OAuth Provider choices are empty.

**Comment by wag110894** [comment]
Here are the correct docs: 
https://help.form.io/developers/saml#okta-saml
