### ISSUE TITLE
Form IO require react with typescript example as current react-starterkit-app only work with .js not with typescript

### ISSUE THREAD

**Issue by aryanisml** [formio/formio#1475]
starter kit showing the onSubmit or onChange events of formbuilder. However while working in typescript we are getting the errors there is no events available .

Requesting to share the form io example or repo with react typescript project. 
It would help us.

**Comment by brendanbond** [comment]
Hi @aryanisml - can you post the errors you're getting from Typescript? We'll need more information to help you get to the bottom of your issue here.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
