### ISSUE TITLE
[BUG] Using translations I do not have any way of controling numeric and date formas. Or am I missing something?

### ISSUE THREAD

**Issue by torbjornlindstrom** [formio/formio#1483]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by brendanbond** [comment]
Can you provide a minimally reproducible example? Can't be sure whether or not you're missing something unless we know what you're trying, this is why we ask you to fill out the template.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
