### ISSUE TITLE
[BUG] MongoDB version

### ISSUE THREAD

**Issue by PatrikTrefil** [formio/formio#1485]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 3.0.0
- Formio.js version:-
- Frontend framework:-
- Browser:-
- Browser version:-

## Steps to Reproduce
0. `git clone <this repo>`
1. `npm install`
2. `docker compose up`

## Expected behavior

no warnings

## Observed behavior

```
formio-mongo-1   | 2022-11-03T15:44:18.557+0000 I  CONTROL  [initandlisten] ** NOTE: This is a development version (4.1.13) of MongoDB.
formio-mongo-1   | 2022-11-03T15:44:18.557+0000 I  CONTROL  [initandlisten] **       Not recommended for production.
```

**Comment by h20220025** [comment]
hi @PatrikTrefil , I'm interested in working on this issue. Can you please assign me this issue?

**Comment by PatrikTrefil** [comment]
> hi @PatrikTrefil , I'm interested in working on this issue. Can you please assign me this issue?

I can't be the one to assign this issue. Someone with higher privileges has to do it.

**Comment by brendanbond** [comment]
@PatrikTrefil you can use any version of MongoDB you'd like, simply edit the [docker-compose.yml](https://github.com/formio/formio/blob/f6705e5f6bcf6100a89e4cd9b46b050c290410ad/docker-compose.yml) file to pull in your preferred version
