### ISSUE TITLE
Premium component like Tagpad , Sketchpad are not available

### ISSUE THREAD

**Issue by aryanisml** [formio/formio#1486]
I am using formio/react formbuilder in react application. I am not able to see the two-premium component tagpad and sketchpad.
Is any way to enable or visible these two components??? Or we need to buy the form io for premium component?

**Comment by brendanbond** [comment]
Premium components are [not available unless you have access to our private modules.](https://help.form.io/userguide/forms/premium-components#instructions-for-use-of-form.io-premium-components).

**Comment by syberx** [comment]
Do you have to pay for it? Or can you also use this for free with the self-hosted version?
