### ISSUE TITLE
Changing the builder from Form to Wizard and back to Form does not recover the original form

### ISSUE THREAD

**Issue by pboucher1960** [formio/formio#1487]
From an empty form, the default creation mode is Form. By changing the creation mode from Form to Wizard and back to Form, the resulting layout as well as the JSON schema is now different from the original ones. When used in an application that detects modifications in order to activate a save button, it was expected that changing the form from state A to state B and back to A would not generate a modification in the original schema.

**Comment by brendanbond** [comment]
Can you provide us with a minimally reproducible example? It's hard to try and help without more information.

**Comment by pboucher1960** [comment]
**Step 1**: From the Form.io playground, I simply removed the "Submit" button from the sample form to obtain the simplest JSON schema I can get:

```
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": []
}
```

**Step 2**: Change the build type from "Form" to "Wizard" which produces the following JSON schema:

```
{
    "display": "wizard",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "title": "Page 1",
            "label": "Page 1",
            "type": "panel",
            "key": "page1",
            "input": false,
            "tableView": false,
            "components": []
        }
    ]
}
```

**Step 3**: Change the build type from "Wizard" back to its initial value of "Form", which produces the following JSON schema:

```
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "title": "Page 1",
            "label": "Page 1",
            "type": "panel",
            "key": "page1",
            "input": false,
            "tableView": false,
            "components": []
        }
    ]
}
```

We were expecting the JSON schema from Step 1 and Step 3 to be the same, which is not the case as you can see.

**Comment by brendanbond** [comment]
This is expected behavior. We need to maintain the ability for wizards to be rendered as forms (e.g. via the `display` property), so while changing a form to a wizard will add some sensible default components for a wizard, changing it back should not eliminate those components. The concern here is that users frequently customize a wizard's behavior beyond the default schema, and it would be a problem if changing the display time to `form` from `wizard` were to wipe those changes.

**Comment by brendanbond** [comment]
Thanks for clarifying. I'm not sure it would be a priority for us to handle this edge case, although we'd be more than happy to look at [a PR to the renderer](https://github.com/formio/formio.js)!
