### ISSUE TITLE
Link to jump to validation error does not work for "editgrid" input

### ISSUE THREAD

**Issue by chdonncha** [formio/formio#1489]
When the Validation catches errors into an alert and provides links to navigate to the field like so:
![image](https://user-images.githubusercontent.com/8567795/202496228-95ca1c8f-27f9-45b8-9ace-5cd55c4b2e3e.png)

The links for the First and Last Names work since they are inputs but the Items does not using the type editgrid

If I change items to use differnet inputs such as select or input then it works but I require the editgrid in this case

Does anyone know a workaround for this issue to make the jump to field on validation error link useable for any "type:editgrid"

My Code Looks as the following for the Items:
```JSON
{
  "label": "Items",
  "labelPosition": "left-left",
  "labelWidth": 30,
  "openWhenEmpty": false,
  "tableView": false,
  "rowDrafts": false,
  "key": "items",
  "type": "editgrid",
  "displayAsTable": false,
  "input": true,
  "templates": {
    "header": "<div>test</div>",
    "row": "<div>test</div>"
  },
  "validate": {
    "required": true
  },
  "components": [
    {
      "label": "Code",
      "labelPosition": "left-left",
      "labelWidth": 30,
      "widget": "choicesjs",
      "tableView": true,
      "dataSrc": "url",
      "data": {
        "url": "/api/..."
      },
      "validate": {
        "required": true
      },
      "key": "code",
      "template": "<span>{{ item.value }} - {{ item.label }}</span>",
      "type": "select",
      "input": true,
      "lazyLoad": false,
      "disableLimit": false
    },
    {
      "label": "Quantity",
      "labelPosition": "left-left",
      "labelWidth": 30,
      "mask": false,
      "tableView": true,
      "truncateMultipleSpaces": false,
      "validate": {
        "required": true
      },
      "key": "quantity",
      "calculateValue": "{ value }",
      "type": "textfield",
      "input": true
    }
  ]
}

```

**Comment by wag110894** [comment]
@chdonncha Can you provide version of where you are seeing this issue?

**Comment by chdonncha** [comment]
> @chdonncha Can you provide version of where you are seeing this issue?

I'm currently using version 4.14.7

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
