### ISSUE TITLE
End to end encryption

### ISSUE THREAD

**Issue by codedust** [formio/formio#1494]
Are there any plans to support end to end encryption between the frontend (browser of user's device) and clients that retrieve the form data via the API?

API clients could provide a public key for that purpose. This would allow the frontend to encrypt all form data before it is sent to the form.io backend. Hence, no plaintext data would reach the backend which minimizes attack surface and reduces the risk of data breaches.

**Comment by brendanbond** [comment]
TLS already does a good job of encrypting traffic from the client to the server, and our enterprise offering offers a host of further encryption options for data once it gets there.

**Comment by codedust** [comment]
That's something completely different than end to end encryption :(

**Comment by brendanbond** [comment]
Right, so maybe I’m misunderstanding what you’re asking? When I think “end-to-end encryption” I think “user to user,” which is out of scope for an API platform like Form.io.

**Comment by codedust** [comment]
Why not enable API clients to retrieve encrypted data and implement client-side encryption in the browser? This would allow end-to-end encryption from the user submitting a form to the user retrieving this data via an API client.

**Comment by brendanbond** [comment]
I guess I'm still a little confused here, but I want to make sure that I'm not missing something about what your use case requires. Setting aside that "implement[ing] client-side encryption in the browser" is not trivial (where does the key live?) and not entirely useful (we're encrypting the traffic anyway), let's say you somehow safely encrypt your submission data on the client with Key X such that anyone with Key X can decrypt the submission data. When you submit the form, the submission data is encrypted! 

Now to do anything useful with that data, (think webhooks, email actions, validation, etc. etc.) the API server will need to decrypt the data. Giving Key X to the server will enable the API server to decrypt, but now we've broken end-to-end encryption. In fact, we've really just double encrypted and decrypted the submission data seeing as how TLS already encrypted the traffic from the submitter's browser to the API server. 

I guess you could say, "well, I don't need any of the fancy stuff, I just want the API server to store the encrypted submission data in a database so an end user with Key X can pull it down and read it." The thing is, doesn't that just sound like S3 at the end of the day? 

Is there anything I'm missing here from what you're envisioning?

**Comment by codedust** [comment]
The attack scenario I'd like to protect against here is a corrupted server. When we encrypt data in the browser and **do not** allow the server to decrypt it, an attacker would not be able to access any data when compromising the server.

Instead of using symmetric cryptography, we need to use asymmetric crypto here: The API client receiving the submission data ("receiver") needs to hold an asymmetric key pair (possibly protected by a PKI) and uploads it's public key to the server. The frontend now encrypts submission data using the public key of the receiver. This restricts what can be done with the data on the server side (receiver, input validation is not possible), but of course, we can still trigger webhooks or email notifications.
