### ISSUE TITLE
disableMobile for flatpickr cannot be overwritten

### ISSUE THREAD

**Issue by 4ND-R34** [formio/formio#1504]
In the calendar component (https://github.com/formio/formio.js/blob/master/src/widgets/CalendarWidget.js#L448) the disableMobile option for flatpickr is always overwritten with "true", even if you try to set disableMobile to "false" as an option in the form.

Is there any way around this or do I need to create a custom component?

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
