### ISSUE TITLE
Adding dynamic fields should not rerender the entire form

### ISSUE THREAD

**Issue by arafatahmedtanimcsedu57** [formio/formio#1507]
## Environment
Bowser Crush 

- Hosting type
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.14.8
- Frontend framework: ReactJS
- Browser: Chrome
- Browser version: latest

## Steps to Reproduce
1. Create a datagrid with 15 input field 
2. To add a dynamic row, Press Add another button, and 
3. Continue it 100 times.

## Expected behaviour

- After adding a new dynamic row, the whole form shouldn't re-render.
- The browser shouldn't crush for any number of dynamic fields.  

## Observed behaviour

- Each time the whole form is re-rendering after a new dynamic field is added. 
- After adding 100 dynamic rows Browser is crushed.

###

**Comment by nazmul-prince** [comment]
I'm also facing the same issue. Our client wanting to add a dynamic row consists of 7 columns for thousands of time. He cant do any further actions after adding more than 100 dynamic rows, the browser either crashed or become irresponsive.

**Comment by VikkiAlenn** [comment]
@arafatahmedtanimcsedu57 We are not able to reproduce this issue on the latest versions of formioJS (4.18.2, 4.19.0, etc.). Please, try on the latest versions and let us know if it is still the issue for you.
