### ISSUE TITLE
[BUG] The layout HTML attributes cannot be set in the table component in formio builder

### ISSUE THREAD

**Issue by tlyau62** [formio/formio#1511]
For example, in https://formio.github.io/formio.js/app/builder.
When create a layout/table component with some HTML attributes set, the attributes cannot be created in the ```<table/>``` html tag in the output.

**Comment by brendanbond** [comment]
Hey @tlyau62 thanks for filing this. Can you provide more information so we can try to reproduce? Which attributes can't be created in a table component?

**Comment by tlyau62** [comment]
Those aria-attributes

**Comment by daneformio** [comment]
@tlyau62 Can you provide the component JSON that you are having issues with?
