### ISSUE TITLE
[Question] Is it possible to change the url assigned to the Help icon available in each component edit page?

### ISSUE THREAD

**Issue by pboucher1960** [formio/formio#1517]
We would like to redirect our users to our own help page for each component. Image shown for the Data Grid component.

![image](https://user-images.githubusercontent.com/12537370/212985607-914e7f19-bfed-4000-a88a-773eeccb631e.png)

**Comment by brendanbond** [comment]
This is not configurable via any UI that I'm aware of, but this value is interpolated via the [`helplinks` option](https://github.com/formio/formio.js/blob/73fc98fcd68b202b08c50f3436d23bf0dfab0973/src/Element.js#L55) and the component's [static builderInfo](https://github.com/formio/formio.js/blob/73fc98fcd68b202b08c50f3436d23bf0dfab0973/src/components/unknown/Unknown.js#L18)
