### ISSUE TITLE
Text not wrapping in a field

### ISSUE THREAD

**Issue by Doodles42** [formio/formio#1519]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
7.3.3 for the api server 
3.3.7 for the pdf server
- Browser: Chrome
- Browser version: 108.0.5359.126

## Steps to Reproduce
1. I have a form with a text field that is not wrapping an address onto the next line **when a PDF is created**. It just cuts the end of the address off on one line. I've tried using a text area and it is the same
2. The text Area JSON is attached showing parameters, but I suspect that wouldn't affect PDF fields??
3. Example of address cutting off postal code is below
<img width="293" alt="image" src="https://user-images.githubusercontent.com/122870249/213197456-e7208b70-21f1-4137-a829-edf8bf600589.png">

## Observed behavior - Address text doesn't wrap - it gets cut off

For code or form JSON, please enclose in a code block:

{
  "input": true,
  "tableView": true,
  "style": {
    "white-space": "wrap"
  },
  "overlay": {
    "height": 21,
    "page": 1,
    "width": 636,
    "left": 204,
    "top": 213
  },
  "label": "Address",
  "case": "mixed",
  "defaultValue": "os.siteAddress",
  "type": "textfield",
  "key": "address",
  "validate": {
    "required": true
  }
}

**Comment by olgabann** [comment]
@Doodles42 Have you tried to replicate the issue on the new versions? Please, let us know if you still encounter it on a new version

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond, and we can resume the triage process.
