### ISSUE TITLE
[BUG] Deleting a value already assigned to the Default Value in a Select component does not reset the Default Value

### ISSUE THREAD

**Issue by pboucher1960** [formio/formio#1523]
## Environment
Form.io playground

- Browser: Chrome
- Browser version: 109.0.5414.75 (Official Build) (64-bit)

## Steps to Reproduce
1. Add a "Select" component in a new form
2. In the "Data" tab, add three "Data source values"
3. Set the "Default value" to any of the three values added in step 2.
4. Remove the line from the "Data source values" that was selected in step 3

## Expected behavior
The default value should be blank since the selected value does not exists anymore in the list of values.

## Observed behavior
The default value now contains the value of the deleted entry (it contains the label before being removed).

## Example
![image](https://user-images.githubusercontent.com/12537370/213497072-29ba933a-3c61-4d6e-98ca-1e44c46f6063.png)

This is the current JSON schema from the playground to reproduce this behavior.
```
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Select",
            "widget": "choicesjs",
            "tableView": true,
            "defaultValue": "option1",
            "data": {
                "values": [
                    {
                        "label": "Option2",
                        "value": "option2"
                    },
                    {
                        "label": "Option3",
                        "value": "option3"
                    }
                ]
            },
            "key": "select",
            "type": "select",
            "input": true
        }
    ]
}```

**Comment by brendanbond** [comment]
Hey @pboucher1960 thanks for reporting. Just FYI this is likely a [formio.js](https://github.com/formio/formio.js) but we'll get it filed in any case.

**Comment by lane-formio** [comment]
After review, we believe this to be expected behavior.
