### ISSUE TITLE
[BUG] pageNumber in PDF submission display issue

### ISSUE THREAD

**Issue by joe-jia** [formio/formio#1530]
## Environment
V7.4 and V8.x

- Hosting type
  - [x] Custom hosting
- Formio.js version: v4.14.8 and above

## Steps to Reproduce
1. {{ pageNumber }} in the formIO PDF settings footer template
2. The page number is not displayed properly in form submission PDF.

**Comment by brendanbond** [comment]
Can you elaborate on "not displayed properly" in form submission PDF?

**Comment by joe-jia** [comment]
Hi @brendanbond,

The error scripts are shown in the pdf receipts when using pageNumber for form pdf template in the settings.

cheers

Joe

**Comment by daf-joej** [comment]
Hi @brendanbond,

I attach the screenshot of pdf pagination issue.
![Capture](https://github.com/formio/formio/assets/37521888/c7d90402-1bd1-4a32-b5bf-d22f3a025d9b)

`{{ pageNumber }}`

Cheers

Joe

**Comment by daneformio** [comment]
@daf-joej @joe-jia Can you provide a screenshot of your PDF Template?

**Comment by daf-joej** [comment]
Hi @daneformio,
![screenshot](https://github.com/formio/formio/assets/37521888/ff036570-0e0d-4b6b-8ea9-5442ae9b4ff4)

**Comment by daneformio** [comment]
Hi, @joe-jia .
This template actually takes HTML
Can you try something like this and see if it works?
`<div style="display: flex; justify-content: space-around;">
  <div style="margin-bottom: 2px;"><b>Page</b> <span class="pageNumber"></span> of <span class="totalPages"></span></div>
  </div>
</div>`

**Comment by daf-joej** [comment]
Hi @daneformio,
The style class name method is working in the PDF template.
![image](https://github.com/formio/formio/assets/37521888/f40a89ce-0c9e-4c2d-89b7-34cf73537f17)
Is it always working like this?
Cheers

Joe
