### ISSUE TITLE
[BUG] Small bug with date/time picker - value when typed is not saved (requires secondary trigger)

### ISSUE THREAD

**Issue by ensemblebd** [formio/formio#1534]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Local deployment
- Formio.js version: 4.14.10
- Frontend framework: react
- Browser: Chromium
- Browser version: latest as of 2023-02-24

## Steps to Reproduce
1. Create a date/time field for a form, set it to use AM/PM (likely doesnt matter)
2. When filling the form, if you type a value into the time box, then click away - the data is lost.

## Expected behavior
Value should be saved on-change, not require a secondary click on another unrelated field in order to commit change.

## Observed behavior
Value is lost. User must provide supplemental click elsewhere on the datetime component to trigger the commit/onchange operation, thus keeping the typed value.

## Example
https://drive.google.com/file/d/19cxFRAvCO3rO2b5pu6fHaNshmsSUxYJg/view

**Comment by wag110894** [comment]
Thanks for reaching out. This seems like the expected functionality for the Flatpicker technology. You will need to bring this up to Flatpicker.

Thank you.

**Comment by ensemblebd** [comment]
Understood, will do.
