### ISSUE TITLE
[Question]  How to add a text fields or any component dynamically on click of a button.

### ISSUE THREAD

**Issue by abhishek0196** [formio/formio#1539]
## Environment
Please provide as many details as you can:

I wanted to add a form io component dynamically on click of a button, I am able to add the payload JSON to the components array, although it is not getting rendered. Please help me on this.

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version:  4.13.0-rc.26
- Formio.js version:  4.13.0-rc.26
- Frontend framework: Angular v13
- Browser: Brave 
- Browser version: 1.49.120

## Steps to Reproduce
Create a new form, with a button of type custom event, on button click, try to add a new component for instance text field. 

## Expected behavior

Should render the new control in the form.

## Observed behavior

JSON is getting updated although not rendering in the UI.

**Comment by brendanbond** [comment]
We'll need more information here, I'm able to use a custom event to add a component just fine. Did you make sure to `formInstance.redraw()` ?

**Comment by daneformio** [comment]
@abhishek0196 Are you using `formInstance.redraw()`? This solves the issue for the developer.

**Comment by abhishek0196** [comment]
Thanks it helped
