### ISSUE TITLE
[BUG] docker-compose up returns "failed to solve: executor failed running [/bin/sh -c apk update &&     apk upgrade &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0]: exit code: 6"

### ISSUE THREAD

**Issue by sinannoureddine** [formio/formio#1546]
I am trying to run with Docker compose and following the steps in the repo:

when i run the "docker-compose up" command, i am getting the error
**"failed to solve: executor failed running [/bin/sh -c apk update &&     apk upgrade &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0]: exit code: 6"**

However, when i do the manual installation, formio works fine. 

Any idea why this is happening?

**Comment by brendanbond** [comment]
@sinannoureddine It's indicating that the build is failing during that layer, but there should be more logs - can you provide?

**Comment by daneformio** [comment]
@sinannoureddine Can you please provide more logs if you are still experiencing this issue with the latest versions?

**Comment by Tatsiana8** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
