### ISSUE TITLE
TypeError: Provider is not a constructor

### ISSUE THREAD

**Issue by informatlabo15** [formio/formio#1552]
Hi, 

I'm trying to upload a file (image) and  got the following error.

Sandbox Id: 6452e4c3354c3bbd0804b806
https://formio.github.io/formio.js/app/sandbox

![formio_sandbox](https://user-images.githubusercontent.com/28658021/236065900-e841ca71-5505-4061-87d1-559dcd3062d3.png)

**Comment by amirreza58** [comment]
i have this error too

**Comment by Tvde1** [comment]
Same issue as https://github.com/formio/formio.js/issues/5230

**Comment by daneformio** [comment]
This looks like it's resolved in v5.0.0-rc.32: https://github.com/formio/formio.js/commit/19b1e4fd3dde9c8c60139c7f82e5e075e743b14d

Please try again with this version of formio.js

**Comment by Sidiro23** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
