### ISSUE TITLE
Error response from daemon: bad parameter: link is not supported

### ISSUE THREAD

**Issue by federico-ntr** [formio/formio#1558]
I'm trying to use `docker-compose` with podman, as I cannot use Docker Desktop for licensing reasons.

Problem is I run into the error in the subject whenever I run `docker-compose up`.

It seems it's because podman doesn't support the link feature, which has actually been deprecated by Docker anyway. Is it possible to rework Docker stuff so the project doesn't rely on that deprecated feature?

Thanks

**Comment by brendanbond** [comment]
@federico-ntr there's not much to rework, you should just be able to remove the "links" parameters (assuming Docker Compose 3.x) and still get the built in network provided by the docker-compose file.

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond, and we can resume the triage process.
