### ISSUE TITLE
Edit Grid not rendering some components correctly. [help-needed] [bug]?

### ISSUE THREAD

**Issue by karansantani** [formio/formio#1574]
Hi,

We're facing issues with the Edit Grid. Trying to describe the issue, alongwith screenshots to make reproduction of the issue easier.

Use Case : 
We have tried using Edit Grid in our form, which in turn will contain a Data Grid component inside of it. This means both the components, Edit Grid and Data Grid have the option to duplicate themselves and add to the form builder. It looks something like this :

![Edit Grid with a Data Grid embedded (form builder phase)](https://github.com/formio/formio/assets/18198648/424e2efe-6993-4d72-8860-32549db0544c)

So far so good. Now when we try to view the component we just created, it looks something like this :

![Edit Grid with Data Grid embedded (form preview phase)](https://github.com/formio/formio/assets/18198648/359b3885-9177-4998-85b2-ad40d2e1b680)
 
On clicking of the Add Another button visible on the screen above, we see this : (Please note that this is the actual way we thought the data will be displayed, which is not the case)
 
![Edit Grid with Data Grid embedde (Add Another clicked for Edit Grid)](https://github.com/formio/formio/assets/18198648/06f3fc34-5e06-4c4a-84dc-833f04e46252)
 
Finally, on clicking of Save in the screen above, we see this :
 
![Edit Grid with Data Grid embedded (Saving the new layer on Edit Grid)](https://github.com/formio/formio/assets/18198648/8dca8045-4ad3-4346-987f-3cff282c128f)
 
The issue is what we build, we don’t see that (Ideally, the end user should be seeing what we’re creating.)
Also, the embedded Data Grid component has no presence on the screen, even after putting values in the input fields inside of it.
I’ve gone through the codebase for EditGrid.js file, and I see that we’re trying to flatten the components (see flattenComponents) before rendering them on the preview screen. Is there another way of displaying the correct form created on the form builder screen? Please advise.

**Comment by DeekshithRajBasa** [comment]
I've noticed a similar issue @karansantani, and I would appreciate assistance from @travist to address it. 

@mariolinguito, have you encountered this issue before? Your insights would be greatly appreciated.
