### ISSUE TITLE
Support for Readonly and Disabled Fields/components

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#160]
Building on a conversation in Gitter about Formio support for Read-Only/Disabled Fields:

Configurations:
1. Ability to set a field as "disabled" and readonly (HTML properties) so that when it is rendered the field is disabled (greyed out) or readonly (un-editable, but not greyed out).

---
- Scenario 1: the field is marked as disabled/readonly, and the value of the field is submitted during POST
- Scenario 2: the field is marked as disabled/readonly, and the value of the field is **not** submitted during POST
- Scenario 3: the field is marked as disabled/readonly, and the value of the field is validated server-side to ensure the disabled field as not edited by client. 
- Scenario 4: The field is marked as disabled/readonly and is pre-populated.  On POST the values of the readonly/disabled fields are sent to server. (persistent)
- Scenario 5: The field is marked as disabled/readonly and is pre-populated.  On POST the values of the readonly/disabled fields are _not_\* sent to server. (persistent)

**Comment by zackurben** [comment]
@StephenOTT Are you wanting more documentation about this?

**Comment by PiyumiSnd** [comment]
need clarification on above scenarios
