### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by krixerx** [formio/formio#161]
Would like to have page-flow (wizard) future in edit mode like ngBuilder demo: http://codepen.io/travist/full/xVyMjo/

Could you give some ideas how to implement it?

**Comment by travist** [comment]
Hello @krixerx,

Everything you see in that codepen is Open Source and the source code is available within the actual codepen. Here is a different view that shows the code implementing that..

http://codepen.io/travist/pen/xVyMjo

Hope this helps.
