### ISSUE TITLE
Simple condition definition

### ISSUE THREAD

**Issue by krixerx** [formio/formio#162]
Would be very convenient if end-user could define easily condition form using "and", "or", "bigger", "lower", "in" conditions.

Advanced conditions panel is simple for programmers but not for end-users. 

Thanks!

**Comment by zackurben** [comment]
@krixerx thanks for the suggestion. While I don't see and/or being added in the near future, due to the added complexity, the case for less/greater than are compelling. I'll pass the suggestion on, thanks.
