### ISSUE TITLE
How to clear dropdown box selected value in Custom Validation

### ISSUE THREAD

**Issue by MadhanKarnam** [formio/formio#1628]
If selected value is not valid then clear the selected value

**Comment by daneformio** [comment]
@MadhanKarnam can you provide an example in https://jsfiddle.net/ or a form json?

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
