### ISSUE TITLE
Hangs on Installation

### ISSUE THREAD

**Issue by Bebu1985** [formio/formio#163]
Hello,

i try to install the application on debian jessie. After starting with node everything comes up. When the dbs schema updates starts the application hangs on the first update. Any solution?

Thanks for your help
Bernhard

**Comment by zackurben** [comment]
@Bebu1985, do you have an npm log for the install? Can you send it to `zack@form.io`

**Comment by taoyuan** [comment]
It seams like in src/db/index.js:

```js
...
498        // No private update was found, check the public location.
499        debug.db('_update:');
500        debug.db(_update);
501        if (_update === null) {
...
```

` debug.db(_update);` will output `3.0.5`, and `_update` type is string.

So in line 521

```js
_update(db, config, tools, function(err) {
...
}
```
throws `_update` is not a function.

I changed line 501
```js
if (_update === null) {
```
to
```js
if ((_update === null) || (typeof _update !== 'function')) {
```

It works.

**Comment by zackurben** [comment]
This should be fixed with: https://github.com/formio/formio/pull/185
