### ISSUE TITLE
Stage dropdown displays Project name for Live stage

### ISSUE THREAD

**Issue by jaliyaudagedara** [formio/formio#1656]
In the Form.io Portal, the stage dropdown displays the Project name for the Live stage. Instead shouldn't it be displaying the stage name which is `Live`? 

I believe it can confuse the user.
![image](https://github.com/formio/formio/assets/5653381/e07ad07a-7b01-4695-a339-937941b85544)

**Comment by daneformio** [comment]
This is expected behavior for Tenants - The tenant always shows the title of the tenant for the live stage.
