### ISSUE TITLE
Move form submission from one resource to another resource through API endpoint.

### ISSUE THREAD

**Issue by jmast02** [formio/formio#1667]
Hi everyone, 

I was wondering if there was a way to move existing form submissions from one resource to another, without having to recreate a submission? 

Ex):

Resource group "Admin" and Resource group "Employee"

I want to remove a submission from the "Admin" resource group and move it into the resource group "Employee". I am looking to keep the same submission `_id` , therefore I am not looking to delete, and recreate the entry.

I have gone through documentation and have become familiar in regards on how to create resources, add new submissions to a resource, etc. 

https://apidocs.form.io/#2b553c0c-f857-4bfc-8023-1ddd0fc216e9

Thank you in advance for any assistance!

**Comment by brendanbond** [comment]
You could accomplish this very easily via API by resubmitting the submission to the proper resource. 

*However*, if you want to keep the _id property the same (which is a database concern and not created or governed by the formio server) you'll have to accomplish this at the database level, there's no way to do this via API. Something like

```
// pseudocode
const submissionId = <submission I want to associate with a new form or resource>
const currentFormId = <the form or resource it's currently associated with>
const destinationFormId = <the form or resource I want to associate it with>
db.submissions.updateOne({_id: submissionId, form: currentFormId}, {$set: {form: destinationFormId}})
```
