### ISSUE TITLE
Render Multiple Builder Schema At Once

### ISSUE THREAD

**Issue by Chirag0406** [formio/formio#1668]
Hi Team,

I needed quick help in understanding as how to render multiple forms builder schema on a page at once.
Please check the below screenshot for better understanding.

![image](https://github.com/formio/formio/assets/40192944/194f7fde-c080-483b-91cb-29d0e3a1d03f)

I have a button on top and I need the builder schema of all forms at once and pass it to a API call.
I am unable to get the builder schema object on that click event.

How can this be achieved?

**Comment by RainerRaebiger** [comment]
What is the sense behind splitting the components into different forms?

**Comment by brendanbond** [comment]
For some reason the JSFiddle link I shared was stale, try this one: https://jsfiddle.net/brendanbond/rem29n5c/2/

**Comment by brendanbond** [comment]
> what I want is the builder schema which will be saved in database on clicking of a button created outside form called saved

I'm not quite sure what you mean, but your original query was "how to render multiple forms builder schema on a page at once", see the JSFiddle and let me know if that is what you're looking for
