### ISSUE TITLE
Table View is not checked by default for some components

### ISSUE THREAD

**Issue by koteshgangavarapu** [formio/formio#1678]
Hi,
Table View is checked by default for some components like Text Field, Text Area, Select, Email, Time, etc whgen adding them to a form. However it is not checked by default for some components like   Number, Checkbox, Currency, Day, etc.   
Is there specific reason for this?  

We are using Table View flag in our reports to decide whether to include the field in report or not. But as we noticed that some of them are not checked by default, we are unable to use.

It would be nice if the Table View is checked by default for all components and the user can uncheck if they want to hide that field in reports like Sosical Security Number. 
[FormIo Table View.docx](https://github.com/formio/formio/files/13787429/FormIo.Table.View.docx)

**Comment by brendanbond** [comment]
Hi @koteshgangavarapu thanks for the issue. Defaults in the form builder would be covered in the [formio.js](https://github.com/formio/formio.js) repository, which covers the Javascript renderer. Further, I believe that the components that have table view unchecked by default do so for specific reasons. In any case, PRs to that repository are welcome!
