### ISSUE TITLE
!!! IMPORTANT !!! = Critical Security Advisories in dependency vm2

### ISSUE THREAD

**Issue by Justman100** [formio/formio#1680]
Hi, when installing the dependencies, this pokes me in the eye:

> formio-workers > vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.

For more details, see [here](https://deps.dev/advisory/osv/GHSA-cchq-frgv-rjh5) and [here](https://deps.dev/advisory/osv/GHSA-g644-9gfx-q4q4)
<br>
So, it will be recommed, to migrate vm2 code to [isolated-vm](https://deps.dev/npm/isolated-vm)

**Comment by Justman100** [comment]
@brendanbond @lane-formio @mikekotikov

**Comment by lane-formio** [comment]
@Justman100 
Thank you for your vigilance. This is a very high priority vulnerability for us and we have a development effort dedicated to resolving this as soon as possible.

**Comment by RachelAmbler** [comment]
Any update on this?

**Comment by brendanbond** [comment]
Hi @RachelAmbler the next major release of our enterprise server product should have the required changes to our javascript execution contexts, we expect it very soon - thanks for your patience!

**Comment by travist** [comment]
There are 2 pull requests to watch for this resolution.

 - https://github.com/formio/formio/pull/1682
 - https://github.com/formio/formio/pull/1684

We understand that this is a long time coming, but it did require us to refactor our server-side data processing system to make it work in a way that was performant and extensible. It is our #1 priority to resolve this issue so it is coming very soon.

**Comment by mgttt** [comment]
https://github.com/patriksimek/vm2/issues/533#issuecomment-2027887015
