### ISSUE TITLE
Component content not show all text inside

### ISSUE THREAD

**Issue by Jacopops** [formio/formio#1709]
![image](https://github.com/formio/formio/assets/152607068/be904da0-71e2-4278-af54-6dd42b6172f7)

![image](https://github.com/formio/formio/assets/152607068/3cb456ee-c348-4501-9be5-decf687b3a35)

![image](https://github.com/formio/formio/assets/152607068/fe5f9de3-2f42-4845-9430-26fa3296788c)

I have no idea why.

But if i check the json i can see all the text and i can edit it

**Comment by lane-formio** [comment]
What version are you using?

**Comment by Jacopops** [comment]
the latest

**Comment by lane-formio** [comment]
I am unable to reproduce using our latest release here: https://formiojs.test-form.io/4.19.0

I also couldn't reproduce in our SAAS portal at portal.form.io.

Could you provide any more information to assist in reproducing?

**Comment by lane-formio** [comment]
Can you try updating formiojs to 4.19.0

**Comment by Jacopops** [comment]
hi, i update the code an now it works ! 

![image](https://github.com/formio/formio/assets/152607068/33b8cdf1-151f-46ea-99a4-036b19530acc)
