### ISSUE TITLE
formio depends on vm2 package, which has been deprecated due to security vulnerabilities

### ISSUE THREAD

**Issue by fwextensions** [formio/formio#1715]
**Describe the bug**
The package.json file [lists vm2](https://github.com/formio/formio/blob/3.5.x/package.json#L59) has a dependency.  vm2 has been [deprecated](https://github.com/patriksimek/vm2/issues/533) due to security vulnerabilities:

- https://github.com/advisories/GHSA-g644-9gfx-q4q4
- https://github.com/advisories/GHSA-cchq-frgv-rjh5

**Version/Branch**
3.5

**To Reproduce**
N/A

**Additional context**
The [readme](https://github.com/patriksimek/vm2?tab=readme-ov-file#vm2-----) talks about the deprecation.

**Comment by lane-formio** [comment]
Resolved with https://github.com/formio/formio/pull/1693

**Comment by mgttt** [comment]
https://github.com/patriksimek/vm2/issues/533#issuecomment-2027887015
