### ISSUE TITLE
Unable to upload any file with File component 

### ISSUE THREAD

**Issue by jiaweichong** [formio/formio#1718]
**Describe the bug**
Unable to upload any file with File component 

**Version/Branch**
Latest version, https://formio.github.io/formio.js/app/builder.html

**To Reproduce**
1. Add a File Component with Form Builder on https://formio.github.io/formio.js/app/builder.html
2. Set Base64 as storage, leave everything else as default
3. Upload a file on the component here
![image](https://github.com/formio/formio/assets/87287974/3b1091e0-66c8-4aed-8d41-bbca6fbaa2f8)
4. The error below is shown
![FormIO Issue](https://github.com/formio/formio/assets/87287974/31bb5c4b-cb90-4643-ae2c-ad04bcf50b9e)

**Expected behavior**
The file (document or image) can be uploaded successfully and able to see the preview
![image](https://github.com/formio/formio/assets/87287974/49e9ce1b-2d2a-49ec-ae01-d67dce9fa2e1)

**Screenshots**
![FormIO Issue](https://github.com/formio/formio/assets/87287974/31bb5c4b-cb90-4643-ae2c-ad04bcf50b9e)

**Additional context**

**Comment by vassilidev** [comment]
some news ?

**Comment by daneformio** [comment]
This component does not work in the sandbox. Have you tried using it in your own app?

**Comment by lane-formio** [comment]
@jiaweichong @vassilidev 
I have just updated the sandbox environment and it should be working now.
https://formio.github.io/formio.js/app/builder.html
https://formio.github.io/formio.js/app/sandbox.html
