### ISSUE TITLE
Add ability to have hotspots on tagpads

### ISSUE THREAD

**Issue by johnj33** [formio/formio#1724]
**Is your feature request related to a problem? Please describe.**
When a clinician chooses a location on a bodymap I would like to know where they have clicked so I can ask specific questions based on the location. 

**Describe the solution you'd like**
Be able to specify areas within a tagpad that can set a value within the nested form so I can apply conditional logic into follow up questions.
i.e. if the clinician chooses the head on a body map I can ask head specific questions.

**Describe alternatives you've considered**
I am currently investigating how to add conditional logic into the tagpad to be able to set field values based on their parent node but this will not be a thing we could let non technical staff do as it will involve writing js

**Comment by lane-formio** [comment]
I will get this idea in front of our planning meeting on Monday.

**Comment by lane-formio** [comment]
@johnj33 
This is related to a premium component and this feature functionality would be considered a customer-driven platform enhancement. 
Please contact support@form.io for this request and feel free to reference FIO-8093.
