### ISSUE TITLE
Can't run docker compose

### ISSUE THREAD

**Issue by LoisDuplain** [formio/formio#1733]
**Describe the bug**
Impossible to run docker compose

**Version/Branch**
Branch: 3.5.x

**To Reproduce**
Node: 21.1.0
- git clone https://github.com/formio/formio.git
- npm install
- docker-compose-up

Error:
![image](https://github.com/formio/formio/assets/23696933/fb61658c-4e58-445d-9298-29820b5e7915)

**Expected behavior**
Should work?

**Comment by lane-formio** [comment]
Please see issue: https://github.com/formio/formio/issues/1717
