### ISSUE TITLE
[FR] - Support flatpickr date range

### ISSUE THREAD

**Issue by MiguiTE** [formio/formio#1735]
**Is your feature request related to a problem? Please describe.**
I want to use de Date / Time component as a date range selector

**Describe the solution you'd like**
When setting the flatpickr `mode` option to `range` you can select a range between two dates. In flatpicker this stores an array with the start and end dates selected. In formio it just saves the start date.

**Describe alternatives you've considered**
I've used two Date / Time components for start and end dates, but it is more user-friendly to select a date range.

**Comment by daneformio** [comment]
This is not functionality we intend to implement at this time. Closing this thread.
