### ISSUE TITLE
How to load Select values from within Next.js/React

### ISSUE THREAD

**Issue by kachmul2004** [formio/formio#1744]
I have created a form using the form builder and added a select field. The list of options for the Select field must come from an API endpoint that requires authentication and authorisation, and also filters the available options based on the user who makes the request. 

I am able to generate this list of options within my Next.js application, so there's no need for me to do it again via the form builder. Therefore, I would like to know how I can pass this JSON, that I already have in my application, into the form's select field. How would I do that? 

NOTE: I'm using formio-react to display the form (using the src prop of the form component).

Also, I looked at the documentation on Select data source options, but I don't think any of the examples there cover this scenario

**Comment by lane-formio** [comment]
<div>Agent Tatsiana Ivashevich linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/51664">51664</a> for this issue.</div><br/>

**Comment by brendanbond** [comment]
You'd access the form instance (see the @formio/react README, you can use the `onFormReady` prop to access the form instance) to inject your values into the select component.
