### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by KBasher** [formio/formio#176]
I have successfully installed the project in my local windows computer. But when I browse the url http://localhost:3001, it takes me in the Login page. 

From where I get the Email and Password? Do I need to create any database in my local MongoDB database?

**Comment by zackurben** [comment]
When you first started the server, it asks for a root user email/password, those are the credentials you need to use. If you dont remember them, you can get there again by removing all the documents from mongo and starting at `npm start` again.

**Comment by sdancer75** [comment]
> When you first started the server, it asks for a root user email/password, those are the credentials you need to use. If you dont remember them, you can get there again by removing all the documents from mongo and starting at `npm start` again.

Can I only delete/edit a specific document inside the mongodb instead of drop the whole database?
