### ISSUE TITLE
Unable to use "async" function while setting "Advanced Logic" for a component

### ISSUE THREAD

**Issue by AlekhyaParamkusham** [formio/formio#1762]
**Describe the bug**
Shows the warning "async functions is only available in ES8 (use 'esversion: 8')" 

**Version/Branch**
v8.5.0: formiojs@4.19.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a text component
2. Go to Advanced Logic > Add Logic > Type - Javascript
3. In Text Area, tried making a fetch request and awaiting the result using async/await.
4. Below warning is being seen.

**Screenshots**
![Screenshot 2024-06-26 112449](https://github.com/formio/formio/assets/80091914/255e161a-23c9-4991-8d3e-94f77a5cb5e5)
![Screenshot (68)](https://github.com/formio/formio/assets/80091914/d2787808-e42d-464e-96c2-b6f93f7b4ad9)

**Comment by heather-formio** [comment]
@AlekhyaParamkusham Please send all issue reports to support@form.io. This is the OS library for the Form.io API Server and is not the correct channel for issue reports pertaining to the Enterprise version of Form.io.
