### ISSUE TITLE
Dynamically Appending/Adding Formio Components on button click

### ISSUE THREAD

**Issue by chdonncha** [formio/formio#1777]
I've a problem in my current set up.

I'm using a formio JSON template for the FE and grabbing the form data via the JS.

Now what I want to do is to be able to dynamically append or add more Components onto a existing one at the Click of the button.

I've an example below I'd need to be able to add a new "Entity" template on clicking a button beside the radio buttons in arounds that. Then for each input name of the Entity I want the Tab name to be updated.

![image](https://github.com/user-attachments/assets/3830bbe7-6fb6-437b-a2e2-a8aae9e26990)

Is this feasible in formio?

**Comment by lane-formio** [comment]
<div>Agent Jeriah Henley linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/49519">49519</a> for this issue.</div><br/>

**Comment by lane-formio** [comment]
What you are trying is not something we support by default in Formio unless you create a custom component. But there are multiple components like data grid and editgrid that you can dynamically add more rows to the form with any field inside.
