### ISSUE TITLE
Is it possible to enable virus scanning on the file component?

### ISSUE THREAD

**Issue by jwr03** [formio/formio#1794]
We are looking to use the File component and do have an enterprise license.  Was just curious if there was any way to implement virus scanning?  We do have Symantec Scan engine and can be called using API.  Or any other options?  The plan was to use S3 bucket for storage.

thanks

**Comment by lane-formio** [comment]
We don't currently offer this or have it on our roadmap anywhere. As an enterprise user I suggest contacting support@form.io with a feature request and they can give you a quote and at the very least get it into our backlog for future consideration.
