### ISSUE TITLE
Tabbed Data Grids

### ISSUE THREAD

**Issue by dickertjn** [formio/formio#1809]
Clients we work with love tabs within forms, it would be helpful to be able to add additional tabs similar to how you add rows to a DataGrid.

**Describe the solution you'd like**
Either the ability to place a templated tab in a data grid similar to a panel or other container or a configuration within the Tab to allow additional tabs.

**Describe alternatives you've considered**
Anything that would allow the tabbed layout style with the ability for the user to add additional content

**Additional context**
![image](https://github.com/user-attachments/assets/d006d56f-3b32-4180-83cf-c710904d24fc)

If this functionality already exists I apologize but I could not find anything in the documentation.

**Comment by daneformio** [comment]
@dickertjn Can you help me understand this use case better? Are you trying to get your data grid entries to be on their own individual tab, instead of in the table?

**Comment by daneformio** [comment]
I have created a ticket for our product team to review this request. Ticket for internal tracking: FIO-9322

**Comment by daneformio** [comment]
We offer the Data Table component, which would serve this function. This component has pagination, sorting, and filtering, which would allow large sets of data to exist in the component and fit in your form. The Data Table component is available as part of an enterprise subscription. For more information please send an email to sales@form.io.
