### ISSUE TITLE
@formio/premium - uses deprecated dependency tooltip.js

### ISSUE THREAD

**Issue by stefanseeger** [formio/formio#1857]
**Is your feature request related to a problem? Please describe.**
`Tooltip.js is not supported anymore, please migrate to tippy.js`

```
"node_modules/tooltip.js": {
            "version": "1.3.3",
            "resolved": "https://artifactory.sofa.dev/artifactory/api/npm/npm-virtual/tooltip.js/-/tooltip.js-1.3.3.tgz",
            "integrity": "sha512-XWWuy/dBdF/F/YpRE955yqBZ4VdLfiTAUdOqoU+wJm6phJlMpEzl/iYHZ+qJswbeT9VG822bNfsETF9wzmoy5A==",
            "deprecated": "Tooltip.js is not supported anymore, please migrate to tippy.js",
            "dependencies": {
                "popper.js": "^1.0.2"
            }
        },
```

**Describe the solution you'd like**
Tooltip.js is not supported anymore, please migrate to tippy.js

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by lane-formio** [comment]
As this is related to the premium library please contact support@form.io.
