### ISSUE TITLE
Role validation Error on installation

### ISSUE THREAD

**Issue by Bebu1985** [formio/formio#186]
Thank you for fixing #163 during the time of my vacation :)
Sadly i have the next issue. During the installation i got an error during the Importing template step:
![errorformio](https://cloud.githubusercontent.com/assets/10262590/18946585/d7aa1322-862f-11e6-8eae-ebe1c8ac0514.JPG)

Im sorry, for only giving a picture, but i use a virtual debian installation where no network connections are configured.
What i already tried is: deleting the old databases from mongo, reinstalling node_modules, but i always end at that point. Im still on debian jessie

**Comment by travist** [comment]
I just tested this and it seems to be working now. Please test the latest version.
