### ISSUE TITLE
Cannot upload file with template app

### ISSUE THREAD

**Issue by fxp** [formio/formio#191]
I'm trying to create a form with file uploading, this is what I did.
```
git clone https://github.com/formio/formio.git
cd formio
npm install
node main
...
Are you sure you wish to install? (y/N):  y
GitHub repository or selection?:  (1) https://github.com/formio/formio-app-servicetracker

```
Then the app get started
```
 > Serving application at http://localhost:8080
 > Serving the Form.io API Platform at http://localhost:3001
```

Logged in with administrator and edit dealer's form, and add a File components under "Special Components". I set the storage to Url and set Upload Url to a local server "http://127.0.0.1:3000/api/user/uploads/". The preview form on the right works well (I can see the upload request when I choose a file to upload).

After these I can see the file upload component in dealer's form in http://127.0.0.1:8080/#/create/dealer
But the problem is that it did nothing when I choose a file. No error, no network request, only a line of read word "1674014776-6a724136-205f-4a85-bf6a-602e70a23005.jpg".

Is there any difference between the form in app(:8080) and in dashboard (:3001)? Why it works differently?

**Comment by travist** [comment]
The file upload capability (where the files are signed using Amazon S3) is only available on our hosted solution where your API's are either pointing to our platform or using our Enterprise Docker deployment.

**Comment by fxp** [comment]
@travist If we use the on-site plan, is that possible to store file on our server?

**Comment by travist** [comment]
Hello, it should be possible yes. Our S3 component allows for any S3 compatible file server, which means you can point the URL to another location and it should work.

As an example, these should work, but we have not tested it.  

https://github.com/scality/S3
https://github.com/jamhall/s3rver
