### ISSUE TITLE
how to show a chart

### ISSUE THREAD

**Issue by Liza86** [formio/formio#198]
Hi,
is there a way to add a chart (e.g. line chart, pie chart) to a form?
Maybe integrating a js lib as Highcharts?
thanks

**Comment by zackurben** [comment]
Hi @Liza86, this can be accomplished with a [Custom Component](https://help.form.io/userguide/#custom).

For an example of this, check out https://github.com/formio/formio-question. I added graphing capabilities using [NVD3](http://krispo.github.io/angular-nvd3/#/)
