### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by christianjul** [formio/formio#215]
The `package.json` states `"node": ">=4.2.0"`, but I wasn't able to run npm install with a 4.5.9, I had a number of unmet dependencies. I guess it could be a question of the version of the npm that comes bundled with it

Node v 6.9.1 with npm v3.10.8 installs without errors

**Comment by zackurben** [comment]
@christianjul Thanks for the heads up, can you let me know what os you're on? I'm using 4.6.1 on osx without issues, lmk and I'll try to investigate.
