### ISSUE TITLE
Javascript error on form submit

### ISSUE THREAD

**Issue by LeMamin** [formio/formio#228]
Hello,

I have a javascript error when I submit a form and the button stay disabled. But the data is saved.

```
Error: t[f](...).success is not a function
[46]</t.exports/<.controller</e.onSubmit@http://localhost:8080/scripts/vendor-067709754b.js:231:15213
anonymous/fn@http://localhost:8080/scripts/vendor-067709754b.js line 34 > Function:2:226
Da[t]</<.compile/</</r@http://localhost:8080/scripts/vendor-067709754b.js:35:20042
On/this.$get</g.prototype.$eval@http://localhost:8080/scripts/vendor-067709754b.js:33:12965
On/this.$get</g.prototype.$apply@http://localhost:8080/scripts/vendor-067709754b.js:33:13197
Da[t]</<.compile/</<@http://localhost:8080/scripts/vendor-067709754b.js:35:20092
oe.event.dispatch@http://localhost:8080/scripts/vendor-067709754b.js:25:751
oe.event.add/h.handle@http://localhost:8080/scripts/vendor-067709754b.js:24:30906

http://localhost:8080/scripts/vendor-067709754b.js
Line 32
```

I use your service tracker app.

Screenshot in attachment
![chrome](https://cloud.githubusercontent.com/assets/1374967/21419761/ed3f56a2-c829-11e6-8f75-ab860ef5ace4.JPG)
![firebug](https://cloud.githubusercontent.com/assets/1374967/21419759/ed3e0310-c829-11e6-87da-36aae9d03f25.JPG)
![form](https://cloud.githubusercontent.com/assets/1374967/21419760/ed3e0c5c-c829-11e6-85a4-dee8d61056d7.JPG)

**Comment by zackurben** [comment]
Hello @LeMamin, can you tell me your OS, Node Version,  and Browser Type/Version? Thanks

**Comment by travist** [comment]
This is an issue with angular 1.6. What app are you using?

**Comment by LeMamin** [comment]
OS : Windows
Node : 4.3.1
Browser : Chrome 55.0.2883.87 or Firefox 48.0

I am using "service tracker" app. But for "human resources" app is the same.

**Comment by travist** [comment]
I will take a look. We probably just need to update these apps to use the latest version of dependencies.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
