### ISSUE TITLE
cannot enter Title, name ,path and form labels using multiple languages

### ISSUE THREAD

**Issue by hank123** [formio/formio#232]
I installed the formio on readhat linux, I can create forms in English, but, if I try to create a from using Chinese character for the Title, name and form label, it will not create the form,  the chrome console show errors:
vendor-38270813e2.js:39 TypeError: Cannot read property 'errors' of undefined
    at Object.n [as onError] (vendor-38270813e2.js:491)
    at a (vendor-38270813e2.js:40)
    at vendor-38270813e2.js:40
    at g.$eval (vendor-38270813e2.js:40)
    at g.$digest (vendor-38270813e2.js:40)
    at vendor-38270813e2.js:40
    at r (vendor-38270813e2.js:37)
    at vendor-38270813e2.js:37

but, the interesting thing is that , if I edit an existing form, I can update the form labels and rename them to Chinese, except the Title field.  is there a way to solve this problem and allow me to create the form using Chinese directly, including the title of the form ? I check the online documentation, the angular-translates seems only translate the existing messages, not for creating form using different language, correct me if I am wrong, and please show me the right way to do this.

Regards !

hank123

**Comment by zackurben** [comment]
@hank123 Thanks for the report, I'll look into it.

**Comment by hank123** [comment]
Dear zackurben, 
Any plan on following up on this issue ? 

Hank123

**Comment by zackurben** [comment]
@hank123 as soon as I get some free time I will, I am quite bogged down atm - sorry.

**Comment by hank123** [comment]
this is due to some validation, problem solved.

**Comment by zackurben** [comment]
@hank123 thanks for the follow up, sorry I couldnt get to it earlier.
