### ISSUE TITLE
Wizard form support

### ISSUE THREAD

**Issue by SheriefAlaa** [formio/formio#242]
Hi,

I am kinda new to Angular and I might be missing something, I also realise this might not be something to ask on Github (sorry).

I installed formio and noticed it's missing resource/form creation with the display:'wizard' type. However, I did notice that ngFormBuilder has that built-in. Why Formio is missing that.

Also, is there a plan for a ngFormBuilder in Angular 2?

Thanks.

**Comment by zackurben** [comment]
There are a few questions here:

1) If Formio is missing wizard building, its an issue with the default formio app. This library is fundamentally a backend platform, but when you start it alone, it pulls in a simple app that allows for limited functionality of the online [https://form.io](https://form.io/#/) platform

2) ngFormBuilder is the drag-n-drop form builder library and ngFormio is the form renderer. We are in the process of making ngFormBuilder angular 2 compatible

I think that answers your questions..?

Let me know if I missed anything,
Zack
