### ISSUE TITLE
How to manually validate JSON schema

### ISSUE THREAD

**Issue by MocanuMarius** [formio/formio#244]
Hi, what if i want to validate the JSON schema server-side and i just want to use the builder from here, is there any way i could manually validate against the schema using a generic json-schema validator ? Because i've tried to match the data against the schema and it turns out as a false positive everytime. Is there any way i can get strictly the validation code working on some schema and data i input for that schema ? 

Thank you :)

**Comment by MocanuMarius** [comment]
No way to do this apparently, validation is built within the components..i'm closing this.

**Comment by zackurben** [comment]
@MocanuMarius this project has both frontend and backend validation. Are you asking how you can use the backend validation in your own custom way - without this server?

**Comment by MocanuMarius** [comment]
Yes that is what i was asking :)

**Comment by zackurben** [comment]
Is there a reason you don't want to use the baked in [Validator](https://github.com/formio/formio/blob/master/src/resources/Validator.js)?

By chance are you just trying to do some *additional* validation?

**Comment by MocanuMarius** [comment]
Well i don't need the whole service, especially not the storage for forms and things like that. On the back-end ,i only treat them as data and validate the received "userInputData" from the renderer against it's projected schema from the builder. All i need to build is a node middleware that does this given these two things.

**Comment by travist** [comment]
You can hit any of the submission API's with a special ```dryrun=1``` query parameter. This does both a permission and data validation, but does not execute the actions.

**Comment by travist** [comment]
Hopefully this resolves this issue. let me know otherwise.

**Comment by MocanuMarius** [comment]
Thx a lot travist 👍 . Once/If i'm back to that.. i will let yo know how i solved it after all :)

**Comment by multinerd** [comment]
How would i append `dryrun=1` to the instance method `saveSubmission`


```
                  var formio = new Formio(formUrl);

                  formio.saveSubmission(data).then(function (didSubmit) {
                            console.log('Did submit', didSubmit);
                            abp.notify.info(app.localize('SavedSuccessfully'));
                            _modalManager.close();
                            abp.event.trigger('app.createOrEditPmnyUrlModalSaved');
                        });
```

**Comment by randallknutson** [comment]
formio.saveSubmission(data, {params: {dryrun: 1}})
