### ISSUE TITLE
Installation error on db configure

### ISSUE THREAD

**Issue by rmartinezvillar** [formio/formio#262]
Hi,

I've cloned the repository, but when I try to install it, I get an error with the bcrypt module: 

>npm ERR! Linux 2.6.32-642.13.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /opt/formio/npm-debug.log
 
[npm-debug.txt](https://github.com/formio/formio/files/723241/npm-debug.txt)

I've switched from "bcrypt": "^0.8.7", to "bcryptjs": "2.4.0" (I've googled the error and this apparently works). I have also changed all the references from bcrypt to bcryptjs in the code (src/authentication/index.js and src/util/encrypt.js). Now when I try the `npm install` command, it works, but when I try to start the app, I get this: 

`node main`

>Checking for db install.
 > No install found. Starting new install.
 > Performing install.
 > Install complete.

>Checking for db schema updates.
 > No updates found.

>Initializing API Server.
 > Mongo connection established.
>Installing...
>prompt: Are you sure you wish to install? (y/N):  y

>Which Github application would you like to install?
  1.) None
  2.) https://github.com/formio/formio-app-servicetracker
  3.) https://github.com/formio/formio-app-todo
  4.) https://github.com/formio/formio-app-salesquote
  5.) https://github.com/formio/formio-app-basic

>Or, you can provide a custom Github repository...

>prompt: GitHub repository or selection?:  (1)
>Importing template...
>{ ValidationError: role validation failed
    at MongooseError.ValidationError (/opt/formio/node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/opt/formio/node_modules/mongoose/lib/document.js:1499:32)
    at /opt/formio/node_modules/mongoose/lib/document.js:1375:17
    at validate (/opt/formio/node_modules/mongoose/lib/schematype.js:705:7)
    at /opt/formio/node_modules/mongoose/lib/schematype.js:736:11
    at /opt/formio/src/models/Role.js:53:16
    at /opt/formio/node_modules/mongoose/lib/model.js:3419:16
    at /opt/formio/node_modules/kareem/index.js:212:48
    at /opt/formio/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  errors:
   { title:
      { ValidatorError: Role title must be unique.
          at MongooseError.ValidatorError (/opt/formio/node_modules/mongoose/lib/error/validator.js:24:11)
          at validate (/opt/formio/node_modules/mongoose/lib/schematype.js:704:13)
          at /opt/formio/node_modules/mongoose/lib/schematype.js:736:11
          at /opt/formio/src/models/Role.js:53:16
          at /opt/formio/node_modules/mongoose/lib/model.js:3419:16
          at /opt/formio/node_modules/kareem/index.js:212:48
          at /opt/formio/node_modules/kareem/index.js:127:16
          at _combinedTickCallback (internal/process/next_tick.js:67:7)
          at process._tickCallback (internal/process/next_tick.js:98:9)
        message: 'Role title must be unique.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'user defined',
        path: 'title',
        value: 'Administrator' } },
  message: 'role validation failed',
  name: 'ValidationError' }
role validation failed

And the process remains opened until I quit it with `ctrl+c`.

Thanks for your support!

**Comment by zackurben** [comment]
@rmartinezvillar - The bcrypt issue is known, this means that you are missing some crypto libs; on osx these come with the cli tools (I believe), on *nix from crypto packages, and windows with some .net addons.

If you are missing them node-gyp should figure out what to do, but it looks like your node-gyp failed (possibly a python issue).

As for the role issue, its possible that the first time it ran, it partially bootstrapped the server and thats why you're getting role issues. You can clear the db, by connecting `mongo formioapp` and then `db.db.dropDatabase()` - once the mongo collection is empty, try again and lmk if the roles issue is fixed.

1) What version of python do you have?

**Comment by rmartinezvillar** [comment]
Hi, I'm using CentOs, with Python 2.6, with all the crypto packages installed. 

I've tested the `dropDatabase()` method, but it is still the same result...

Regards,

**Comment by zackurben** [comment]
@rmartinezvillar clear the db again, and try another template - its possible something is wrong with that specific template.

**Comment by mehrdadarvin** [comment]
Having the same issue. Tried all the templates, dropping the db every time and no luck.

**Comment by rmartinezvillar** [comment]
I've solved the bcrypt problem, I've updated the c++ to a newer version and now `npm install` works with the default configuration.

I've tried the other templates, and I get the same errors.

**Comment by zackurben** [comment]
@mehrdadarvin @rmartinezvillar thanks for the feedback guys, I'll try and check it out when I get a free minute. Sorry for the delay.

**Comment by rmartinezvillar** [comment]
Hi!
It's been a while from this issue was opened. Has been any update on it?

Thanks in advance

**Comment by A-Pradeep** [comment]
@rmartinezvillar 

 Hi , can you suggest me the changes you did to install the form.io in the CentOS . 
Even i'm not able to install due to bcrypt 3.0.0 installation failed. and node-gyp error.
Even tried the gcc update but list huge pile of errors during the installation.

My package details are:
CentOS 6.10 x86_64
# node -v
v8.11.4
# npm -v
6.4.0

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
