### ISSUE TITLE
Adding fields dynamically

### ISSUE THREAD

**Issue by AvadheshChoudhary** [formio/formio#267]
Is there any way we can add fields dynamically on the form?

**Comment by travist** [comment]
That is what the Form builder is for @ https://github.com/formio/ngFormBuilder

**Comment by AvadheshChoudhary** [comment]
Travis, I mean I want to add a field which can be repeated any times with a plus more button on the form. how can we add that component to form?

**Comment by zackurben** [comment]
@AvadheshChoudhary It sounds like you are looking for the [Data Grid Component](https://help.form.io/userguide/#data-grid)

**Comment by AvadheshChoudhary** [comment]
Thanks @zackurben , I was looking for this only.

**Comment by lsimrsi** [comment]
New link:
https://help.form.io/userguide/data-components/#datagrid

**Comment by bishnoijaii** [comment]
new link
[https://help.form.io/userguide/form-building/data-components#data-grid](https://help.form.io/userguide/form-building/data-components#data-grid)
