### ISSUE TITLE
How can I make “Ordinary User” see other ordinary user's submission data?

### ISSUE THREAD

**Issue by JenifferWuUCLA** [formio/formio#292]
Hi,
  After I created two “Ordinary User” from “form.io” website, I created the form or application from the website. Then, the two users login to the system separately, and fill the form. But, they cannot see the data of each other's submission.
  So, would you pls help to give me some suggestions about how I can make “Ordinary User” see other ordinary user's submission data?

Thanks!

**Comment by travist** [comment]
You will need to utilize the "Resource Access" permissions to do this, and from what I know this capability is only provided with our hosted solution @ https://form.io. The way this works is it allows you to "assign" someone the submission of another person. This would allow for you to have someone provided access over someone else based on their assignment (using a resource field) within that form. We provide this within the hosted platform so you can try it out there.
