### ISSUE TITLE
How to add middleware handler to send data to external data storage e.g. elastic search?

### ISSUE THREAD

**Issue by JenifferWuUCLA** [formio/formio#293]
How to add middleware handler to send data to external data storage e.g. elastic search?
If we want the data always be sent to another storage, how to implement it？
So, would you pls help to give me some code demos to follow?

Thanks!

**Comment by travist** [comment]
The way to do this is to create your own custom Action and model it after the other actions you see here... https://github.com/formio/formio/tree/master/src/actions

You can then implement the hook.alter('actions') to register your action as a possible Form action that can be added to any form. 

This would work like so....

```
let formio = require('formio')();
formio.init({
  alter: {
    actions: (actions) => {
      actions.custom = require('./customAction');
      return actions;
    }
  }
}).then(() => {
  ...
  ...
});
```

**Comment by JenifferWuUCLA** [comment]
Thanks! But additionally, how to get data from dropdown list or other form data using NodeJS in formio? (The form's data is used to send to Elastic search.)

**Comment by mdennisa** [comment]
@JenifferWuUCLA not sure if you still need answer for this, but I notice from JS SDK library there is one sample for this purpose.
https://formio.github.io/formio.js/app/examples/externalload.html

you can check the available event to handle your external data async-ly.
hope this helps other people who are looking for solutions.
