### ISSUE TITLE
How to capture the form data using the middleware programs?

### ISSUE THREAD

**Issue by JenifferWuUCLA** [formio/formio#302]
I need to capture all form data field and send to Elasticsearch.
But, how to capture the form data using the programs in https://github.com/formio/formio/tree/master/src/middleware?
So, could you pls help to give me some suggestions? (Which codes can I follow?)
Thanks!

**Comment by zackurben** [comment]
Hey @JenifferWuUCLA, I believe you're looking for how to make express middleware. You can find the majority of that information here: http://expressjs.com/en/guide/writing-middleware.html

As for the Form.io side of the equation, if you make a new endpoint with your middleware (or add the middleware to an existing endpoint) you can access the request data using `req.body` and use that data with the [elasticsearch](https://www.npmjs.com/package/elasticsearch) module.
