### ISSUE TITLE
When the function "getSubmissionResourceAccess" will be called in the "src/middleware/permissionHandler.js" file?

### ISSUE THREAD

**Issue by JenifferWuUCLA** [formio/formio#304]
I would like to make “Ordinary User” read all other ordinary user's submission data. So, I added two lines in the function "getSubmissionResourceAccess".
But, when I debug the formio app using node-inspector, the program always cannot step into the function "getSubmissionResourceAccess". Why?
So, could you pls help to give me some suggestions? Thanks!
![bb1cd984-0a5e-11e7-9b70-e1cad2376816](https://cloud.githubusercontent.com/assets/25890017/24187213/fb78bb58-0f16-11e7-9305-d4fa65bed8da.png)

**Comment by zackurben** [comment]
Is an `Ordinary User` an anonymous user?

**Comment by JenifferWuUCLA** [comment]
The "Ordinary User" is an Authenticated user, so how to make an Authenticated user can view the data submitted by others? Could you pls help to give me some suggestions? Thanks!
![1](https://cloud.githubusercontent.com/assets/25890017/24286266/67fa9258-10af-11e7-8300-3a737c90a30c.png)

![2](https://cloud.githubusercontent.com/assets/25890017/24286271/6f3ca0f6-10af-11e7-861d-6ac383c0ba08.png)

![3](https://cloud.githubusercontent.com/assets/25890017/24286278/7821bb70-10af-11e7-9241-cb6ad1a7974b.png)

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
