### ISSUE TITLE
Export of forms

### ISSUE THREAD

**Issue by nodeGarden** [formio/formio#309]
I'd like to migrate to another server, and have also forgotten my credentials for localhost. Is there a way to cleanly export the forms and import again in a new instance?

**Comment by sonicos** [comment]
This isn't really a form.io specific response, but if you have access to the hard drive (or virtual disk) you can mount it up and transfer all your data that way. You'd want to back up your form.io config file in addition to the raw db, since the salts are in there.

**Comment by AlexeyNikipelau** [comment]
Closing as the answer was given, reopen if needed.
