### ISSUE TITLE
How to search the mongodb data on page using "mongoose"?

### ISSUE THREAD

**Issue by JenifferWuUCLA** [formio/formio#329]
I have added the "Patient Records" on "form.io" website, but I am not sure how to show the mongodb data on my page.
![patient records](https://cloud.githubusercontent.com/assets/25890017/25265307/ee618c20-269e-11e7-8dee-8eaa60dbf1e6.png)
![db submissions](https://cloud.githubusercontent.com/assets/25890017/25265325/0a57b9a4-269f-11e7-8065-4d7f4f763977.png)

I found "src/resources/Submission.js" file, but I don't know where to call it.

So, would you pls give me some suggestions about how to search the mongodb data on page using "mongoose" in form.io? Thanks!

**Comment by heather-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
