### ISSUE TITLE
Hierarchy Based Permissions

### ISSUE THREAD

**Issue by Glazzarino** [formio/formio#331]
Hello, Is there a way of configuring hierarchy based permissions? From the [groups help page](https://help.form.io/userguide/groups/), I see I can setup a group resource so that users of the group can access all other group users submissions, but I don’t see a way to setup a group that only has access to a specific subset of users submissions.

I other words, how would I setup a group such that it has admin rights over another groups submissions?

For example,  I might have some groups DepartmentX, DepartmentY, MangersOfX, MangersOfY, Directors. Members of DepartmentX should have read only access to submissions of all other members of the group they belong to (I understand how to do that, and thank you for good documentation!), MangersOfX should have admin access to submissions created by members of DepartmentX.  None of the users in DepartmentX or MangersOfX have any access to anything from DepartmentY. Directors have access to all submissions created by anyone in the other groups but are not full system admins.

Thanks in advance.
Gian

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
