### ISSUE TITLE
replace mongodb with mariadb or postgres

### ISSUE THREAD

**Issue by gavieritei** [formio/formio#341]
Is there a tutorial or a simple way or replacing mongodb with mariadb or postgres database for formio?

In order to minimize the tech stack deployed for our app I was interested in moving from mongodb to mariadb. I didn't find any resource on that so far, is there anyone who did it, who can share some info about this?

**Comment by juanitomint** [comment]
You could tray to have a look at: http://anneblankert.blogspot.com.ar/2015/06/node-authentication-migrate-from.html
but AFAIK mongodb is useb for its schemaless capabilities

**Comment by zackurben** [comment]
@gavieritei We don't officially support replacing MongoDB with another storage solution, but you can ask around in the [Gitter Chat](https://gitter.im/formio/formio).
