### ISSUE TITLE
Need help on Ngformbuilder

### ISSUE THREAD

**Issue by arajsh03** [formio/formio#342]
Hi All,
I'm new to form.io. i'm trying to setup the environment in my local(on windows). I've downloaded the code as per the instructions (below url). I don't see the clear instructions like how to complete the setup and run ngformbuilder . 

https://github.com/formio/ngFormBuilder/blob/master/README.md

It would be great if some one can provide the detailed steps.  

Thanks,
Raj

**Comment by zackurben** [comment]
Please open an issue in the ngFormBuilder repo.
