### ISSUE TITLE
How to add a new tab in formio

### ISSUE THREAD

**Issue by Kolanravinder** [formio/formio#344]
Hi Team, 

I am new to formio, I have a requirement to add a new tab to the "Layout Components" section.
for eg: After adding a textbox to the formio, a popup model is being populated with few tabs. I want to add a new custom tab for that model popup.
It would be great if any one can share their experience. 
for reference please find the enclosed screenshot.

Regards
Raveendar Reddy Kolan
![mytab](https://cloud.githubusercontent.com/assets/28542957/25821416/fd9ef486-3402-11e7-9b74-e140c262986c.png)

**Comment by zackurben** [comment]
This should be a question in the [Form Builder](https://github.com/formio/ngformbuilder). You need to override the $templateCache for the component.
