### ISSUE TITLE
 Could not connect to API server error

### ISSUE THREAD

**Issue by sijomc** [formio/formio#346]
I have installed form.io on local Ubuntu 14.04 VM. While accessing localhost:3001 from the browser, following error shows. 

TypeError: Could not connect to API server (NetworkError when attempting to fetch the resource.) 

Please help me to solve the issue.  Thanks in advance...

**Comment by Roudaille77** [comment]
I had the same problem. Resolved by installing Yarn

**Comment by longdratech** [comment]
If you are running Formio on a different server/PC, you need to search for all URLs with the name localhost and replace them with the IP address of the server/PC running Formio. This is because Formio is using its own component to upload view on site

**Comment by AlexeyNikipelau** [comment]
Closing as the answer was given. Reopen if needed.
