### ISSUE TITLE
Invalid HTML: No tag given

### ISSUE THREAD

**Issue by grukov** [formio/formio#351]
Hello Everyone. I build forms with formIo wizzard in `<form-builder form="form"></form-builder>`.
Expectantly i view the result in `<formio form="form"></formio>`. But some times, randomly i get this error: 
**Invalid HTML: No tag given**, or it show's me "broken" small button with no text instead of text field or etc. In wizzard (`<form-builder form="form"></form-builder>`) everything looks allright, but in result view (`<formio form="form"></formio>`) things are not the same!

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
