### ISSUE TITLE
shortDate 'a' breaking time format 

### ISSUE THREAD

**Issue by AleitaT** [formio/formio#357]
When choosing the 'shortDate' time format, formio is automatically adding an 'a' which appears to be supposed to signify the am/pm marker.  However, this seems to be breaking the time format producing odd displaying results in the formio interface and live.  

It does not appear that the oddities appear live until one 'saves' a form after the 'a' has been automatically added, however the 'a' displays irregardless of deletion.   

![image](https://cloud.githubusercontent.com/assets/12263415/26471976/f3ca925e-4158-11e7-8d78-b5f705ab67b3.png)

![image](https://cloud.githubusercontent.com/assets/12263415/26472105/79827cae-4159-11e7-9949-dd0ee8792d6e.png)

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
