### ISSUE TITLE
is there is any limitation of using number of layout components in a form?

### ISSUE THREAD

**Issue by Kolanravinder** [formio/formio#358]
Hi Team, 
Can you guys please let me know if there is any limitation of using a certain number of layout components like table and columns. 
I was trying to design a form with more number of tables and columns, it was good till some point. but after that the form is not saving if I add a table/column.
Please guide me in this regard.

Thanks 
Kolan

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
