### ISSUE TITLE
No resource on  CSV export 

### ISSUE THREAD

**Issue by LeMamin** [formio/formio#364]
Hello,

I have a  form with a resource field.
On the csv extraction of the form submissions there is no data in the column.
The problem come from this line CSVExporter.js : (the column.path is not good)
```
if (typeof data === 'object' && !!data) {
   return coerceToString(_.get(data, column.path, ''), column);
}
```

Thanks

**Comment by jhen1422** [comment]
@LeMamin 

Jeriah here from the support team. Just sending you a quick update you on the issue you notified us about.

The issue:
'CSV export is not showing values for Select Resource / Select URL / Select JSON.’ has passed our tests and was released to our production environment last Friday.

Ensure you are on the latest version of the platform, version 4.1.6, and you should be good to go! Please let me know if you have any questions. You can reach me at jeriah@form.io.

**Comment by LeMamin** [comment]
@jhen1422
Thanks, it works.
