### ISSUE TITLE
Minor Documentation

### ISSUE THREAD

**Issue by jockthekiwi** [formio/formio#376]
On https://help.form.io/userguide/actions/ the title and description for SQL Query Action do not match

SQL Query Action
The email action allows sending an email when an event occurs on a form.

**Comment by alexvoloshyn** [comment]
Can you also add into documentation how to use event action in button component [https://help.form.io/userguide/form-components/#button](url)

**Comment by AlexeyNikipelau** [comment]
Closing as outdated.
