### ISSUE TITLE
Error in package.json prevents start on Windows

### ISSUE THREAD

**Issue by todduk** [formio/formio#380]
When trying to run `npm start` from a Windows 10 command prompt an invalid comparator TypeError is thrown in semver.js.

The problem seems to be that line 11 in package.json uses single quotes to contain the version number. Replacing the single-quotes with escaped double-quotes allow the check to complete.

`"version": "check-node-version --node '>=6.0.0'"`
to
`"version": "check-node-version --node \">=6.0.0\""`

![quotes](https://user-images.githubusercontent.com/1766553/28254579-1b1c84de-6b02-11e7-91e4-cb1fb718f13b.png)

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
