### ISSUE TITLE
Form action conditions cannot be removed

### ISSUE THREAD

**Issue by todduk** [formio/formio#382]
I added a condition to a form submission action that depended on a checkbox value being true. Later I removed the checkbox but am unable to remove the condition, which is preventing the form from being submitted. 

I can replace the condition with something that will always be true, but I cannot find a way to remove the condition using the UI.

In the attached image 'agreeLegal' was the name of the removed control. It doesn't appear in the dropdown list, and it cannot be removed, only replaced with something else from the list.
![condition](https://user-images.githubusercontent.com/1766553/28341993-3a307074-6c6a-11e7-9d06-3882e35375a1.png)

![condition2](https://user-images.githubusercontent.com/1766553/28342108-bf8291da-6c6a-11e7-8795-721406d643ad.png)

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
