### ISSUE TITLE
API's submissions pagination

### ISSUE THREAD

**Issue by BlueInt32** [formio/formio#387]
The way to manage pagination of the submissions list API, using [the standard "Range" HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) does not seem to work. In the [documentation](https://documenter.getpostman.com/view/684631/formio-api/2Jvuks), the only mention I found of this capability is the following one : 

> To read multiple submissions at once, perform a GET request against a resource's submission URL. The submission URL has an additional querystring to limit the number of items and a Range header to iterate over multiple pages.

Given a form named "exampleform" and, say, 51 submissions associated to this form, the following HTTP request 

`GET {{appUrl}}/exampleform/submission`

will return by default the 10 first results correctly along with the 206 HTTP status. We can also see the `Content-Range` header having the value `0-9/51`.

I tried to change the pagination using the `Range` header and the value `10-15` without any success. This param seems to be consistently ignored and the response `Content-Range` header keeps having the value `0-9/51`.

Am I missing something or is it an actual issue ?

**Comment by forhad559** [comment]
Hello,
   i faced the same problem when i needed to read all the submission of my form.But it kept giving me total 10 submission only.
The form i used on my app may have maximum 200-300 submission,then i used this and getting all of the results
GET {{appUrl}}/exampleform/submission?limit=500

**Comment by SchalkKotze** [comment]
Could you guys resolve this? I Am having this issue as well.

**Comment by sathiz1993** [comment]
+1 . Form.io APIs doesnot respond with Range headers. It always send first 10 items, Whatever may be the Range

**Comment by PatrikTrefil** [comment]
Did you try using the limit and skip query parameters?
