### ISSUE TITLE
Automatic login via email not working with local version

### ISSUE THREAD

**Issue by erikv93** [formio/formio#409]
I tried using [automatic login via email](https://help.form.io/developer/info/emaillogin/) with a local version of form.io.
However instead of sending back a token it just send `  [[token(data.email=user)]]` as plain text.

I then recreated the exact situation on the online version of form.io and it worked immediately.

Is this because automatic login is not supported in the local version or is there something else that might be causing this problem?

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
