### ISSUE TITLE
Issue with 'node server' command.

### ISSUE THREAD

**Issue by np97190** [formio/formio#42]
Hi There,

Facing issue in setting up formio on centos.
I am following steps given on https://github.com/formio/formio. on running command 'node server' I am getting following error:

readline.js:74
    terminal = !!output.isTTY;
                       ^
TypeError: Cannot read property 'isTTY' of undefined
    at new Interface (readline.js:74:24)
    at Object.exports.createInterface (readline.js:40:10)
    at Object.<anonymous> (/formio/formio/server.js:14:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by zackurben** [comment]
Hey @np97190, I just installed fresh and everything seems to be working on my end. Can you let me know what version of Node/Mongo/OS you're currently experiencing this issue with?

**Comment by rahatarmanahmed** [comment]
Possibly [this issue](https://github.com/jashkenas/coffeescript/issues/1078#issuecomment-99462078) if you are running <= 0.10.

**Comment by travist** [comment]
Pretty sure that would cause this problem. Just as an FYI, we only support Node.js 0.12 and above (which includes 4.x and 5.x).

**Comment by np97190** [comment]
@zackurben following are my specifications.
Mongo Version: 3.2.0
node : v0.10.41
CentOS release 6.5 (Final)

So as per @travist  I need to update my node version.

**Comment by zackurben** [comment]
@np97190 that is correct. An update to node >= 0.12.x should fix your issue. Let me know if you still encounter issues with an upgrade.

**Comment by np97190** [comment]
@zackurben after updating node its now even worse.
looked at already posted issues but dont know what component am I struggling with.


> bcrypt@0.8.5 install /formio/formio/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/formio/formio/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from /root/.node-gyp/5.4.0/include/node/node.h:42,
                 from ../../nan/nan.h:24,
                 from ../src/bcrypt_node.cc:1:
/root/.node-gyp/5.4.0/include/node/v8.h:336: error: expected unqualified-id before ‘using’
/root/.node-gyp/5.4.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/5.4.0/include/node/v8.h:353: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/5.4.0/include/node/v8.h:360: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/5.4.0/include/node/v8.h:364: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/5.4.0/include/node/v8.h:430: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h: At global scope:
/root/.node-gyp/5.4.0/include/node/v8.h:469: error: expected unqualified-id before ‘using’
/root/.node-gyp/5.4.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/5.4.0/include/node/v8.h:794: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/5.4.0/include/node/v8.h:819: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/5.4.0/include/node/v8.h:831: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h: At global scope:
/root/.node-gyp/5.4.0/include/node/v8.h:856: error: expected unqualified-id before ‘using’
/root/.node-gyp/5.4.0/include/node/v8.h:1093: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h:1099: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/5.4.0/include/node/v8.h:3204: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/5.4.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/5.4.0/include/node/v8.h:7154: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:184,
                 from ../src/bcrypt_node.cc:1:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:65: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:70: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:77: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:84: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:92: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:99: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:109: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:115: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:119: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:126: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:131: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:136: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:140: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:146: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:151: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:157: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:163: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:169: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:175: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:181: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:187: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:195: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:202: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:206: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:210: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:214: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
In file included from ../../nan/nan.h:189,
                 from ../src/bcrypt_node.cc:1:
../../nan/nan_converters.h:14: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../../nan/nan_converters.h:14: error: expected ‘;’ before ‘<’ token
../../nan/nan_converters.h:16: error: ISO C++ forbids declaration of ‘Maybe’ with no type
../../nan/nan_converters.h:16: error: expected ‘;’ before ‘<’ token
../../nan/nan_converters.h:26: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:27: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:28: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:29: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:30: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:31: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:32: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:42: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:43: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:44: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:45: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:46: error: ‘return_t’ does not name a type
In file included from ../../nan/nan_converters.h:59,
                 from ../../nan/nan.h:189,
                 from ../src/bcrypt_node.cc:1:
../../nan/nan_converters_43_inl.h:18: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Boolean>’ does not name a type
../../nan/nan_converters_43_inl.h:19: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Number>’ does not name a type
../../nan/nan_converters_43_inl.h:20: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::String>’ does not name a type
../../nan/nan_converters_43_inl.h:21: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Object>’ does not name a type
../../nan/nan_converters_43_inl.h:22: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Integer>’ does not name a type
../../nan/nan_converters_43_inl.h:23: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Uint32>’ does not name a type
../../nan/nan_converters_43_inl.h:24: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Int32>’ does not name a type
../../nan/nan_converters_43_inl.h:34: error: ‘return_t’ in class ‘Nan::imp::ToFactory<bool>’ does not name a type
../../nan/nan_converters_43_inl.h:35: error: ‘return_t’ in class ‘Nan::imp::ToFactory<double>’ does not name a type
../../nan/nan_converters_43_inl.h:36: error: ‘return_t’ in class ‘Nan::imp::ToFactory<long int>’ does not name a type
../../nan/nan_converters_43_inl.h:37: error: ‘return_t’ in class ‘Nan::imp::ToFactory<unsigned int>’ does not name a type
../../nan/nan_converters_43_inl.h:38: error: ‘return_t’ in class ‘Nan::imp::ToFactory<int>’ does not name a type
In file included from ../../nan/nan.h:190,
                 from ../src/bcrypt_node.cc:1:
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
../../nan/nan_new.h:21: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Int32]’:
../../nan/nan_new.h:28: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Uint32]’:
../../nan/nan_new.h:35: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h: At global scope:
../../nan/nan_new.h:43: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../../nan/nan_new.h:43: error: expected ‘;’ before ‘<’ token
../../nan/nan_new.h:75: error: ‘return_t’ does not name a type
../../nan/nan_new.h:141: error: ‘return_t’ does not name a type
../../nan/nan_new.h:147: error: ‘return_t’ does not name a type
../../nan/nan_new.h:148: error: ‘return_t’ does not name a type
../../nan/nan_new.h:160: error: ‘return_t’ does not name a type
../../nan/nan_new.h:161: error: ‘return_t’ does not name a type
../../nan/nan_new.h:162: error: ‘return_t’ does not name a type
../../nan/nan_new.h:163: error: ‘return_t’ does not name a type
../../nan/nan_new.h:165: error: ‘return_t’ does not name a type
../../nan/nan_new.h:166: error: ‘return_t’ does not name a type
../../nan/nan_new.h:182: error: ‘return_t’ does not name a type
../../nan/nan_new.h:183: error: ‘return_t’ does not name a type
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:190,
                 from ../src/bcrypt_node.cc:1:
../../nan/nan_implementation_12_inl.h:56: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Date>’ does not name a type
../../nan/nan_implementation_12_inl.h:209: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
../../nan/nan_implementation_12_inl.h:228: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../../nan/nan_implementation_12_inl.h:234: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../../nan/nan_implementation_12_inl.h:266: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:274: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:280: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:287: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:293: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:298: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:359: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
../../nan/nan_implementation_12_inl.h:366: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
In file included from ../../nan/nan.h:190,
                 from ../src/bcrypt_node.cc:1:
../../nan/nan_new.h:291: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:297: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:303: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:309: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:315: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:321: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:327: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::Error(const char*)’:
../../nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowError(const char*)’:
../../nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::RangeError(const char*)’:
../../nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowRangeError(const char*)’:
../../nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::ReferenceError(const char*)’:
../../nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowReferenceError(const char*)’:
../../nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::SyntaxError(const char*)’:
../../nan/nan.h:644: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowSyntaxError(const char*)’:
../../nan/nan.h:644: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::TypeError(const char*)’:
../../nan/nan.h:645: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowTypeError(const char*)’:
../../nan/nan.h:645: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: At global scope:
../../nan/nan.h:653: error: expected initializer before ‘<’ token
../../nan/nan.h:675: error: expected initializer before ‘<’ token
../../nan/nan.h:691: error: expected initializer before ‘<’ token
../../nan/nan.h:704: error: expected initializer before ‘<’ token
../../nan/nan.h:721: error: expected initializer before ‘<’ token
../../nan/nan.h:727: error: expected initializer before ‘<’ token
../../nan/nan.h:735: error: expected initializer before ‘<’ token
../../nan/nan.h:742: error: expected initializer before ‘<’ token
../../nan/nan.h:748: error: expected initializer before ‘<’ token
/root/.node-gyp/5.4.0/include/node/v8.h: In member function ‘void Nan::Callback::SetFunction(const v8::Local<v8::Function>&)’:
/root/.node-gyp/5.4.0/include/node/v8.h:3019: error: argument dependent lookup finds ‘class v8::Set’
../../nan/nan.h:1368: error:   in call to ‘Set’
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1490: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../../nan/nan.h:1508: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In member function ‘virtual void Nan::AsyncWorker::HandleErrorCallback()’:
../../nan/nan.h:1542: error: no matching function for call to ‘New(const char*)’
../../nan/nan.h: In function ‘void Nan::SetMethod(const T&, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../../nan/nan.h:1832: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::SetPrototypeMethod(v8::Local<v8::FunctionTemplate>, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../../nan/nan.h:1845: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h: In function ‘void Nan::Export(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../../nan/nan.h:2116: error: no matching function for call to ‘New(const char*&)’
/root/.node-gyp/5.4.0/include/node/v8.h:3019: error: argument dependent lookup finds ‘class v8::Set’
../../nan/nan.h:2117: error:   in call to ‘Set’
../../nan/nan.h: In constructor ‘Nan::Tap::Tap(v8::Local<v8::Value>)’:
../../nan/nan.h:2124: error: no matching function for call to ‘To(v8::Local<v8::Value>&)’
../../nan/nan.h: In member function ‘void Nan::Tap::ok(bool, const char*)’:
../../nan/nan.h:2137: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In member function ‘void Nan::Tap::pass(const char*)’:
../../nan/nan.h:2143: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/formio/formio/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /formio/formio/node_modules/bcrypt
gyp ERR! node -v v5.4.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN optional Skipping failed optional dependency /nunjucks/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm WARN mongodb-core@1.2.30 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /formio/formio/npm-debug.log

**Comment by np97190** [comment]
apologies for hurrying up. Issue is resolved with gcc upgrade.
Thanks everyone for the guidance.

**Comment by zackurben** [comment]
@np97190 All good, no worries.
