### ISSUE TITLE
Setup 

### ISSUE THREAD

**Issue by chlserver** [formio/formio#421]
Please I am a beginner and fresh student in web development, I came across this project on Codepen while I was searching for a form bulilder to implement of my Php web based project. I am so much interested in this project to implement on on my project because it's so prefect. The problem I have is, I am conversat with PHP and WAMP server implementation, this looks very different. Please is it possible to get this implemented on a php website, if "Yes", Please how can I get this setup  and implemented. My question may seem somehow, please I'd appreciate guide lines. Thanks.

**Comment by AlexeyNikipelau** [comment]
Please read the development docs to figure out how to embed Form.io forms into your website: https://help.form.io/developers/introduction
