### ISSUE TITLE
Offline file upload fails on mobile devices

### ISSUE THREAD

**Issue by bradswanson1** [formio/formio#423]
Using the Angular front end, if the browser is offline and users attach files to form, we find that on mobile devices that sometimes the file upload does not succeed while the browser is offline. It seems to fail more often when the user selects the file from any source other than the 'standard' for the device (camera roll on iOS or gallery/recents on Android).   The file object will be missing from the indexedDB, and then when the browser is online again, and the app tries to submit the form to the server, it fails.  Our troubleshooting possibly points to this library: https://github.com/danialfarid/ng-file-upload/releases

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
