### ISSUE TITLE
User or password was incorrect (root user)

### ISSUE THREAD

**Issue by Arifi** [formio/formio#431]
It's just not working, tryed many passwords, always can't login to API... 
See #428

it's now about a year i'm trying to use Form.io and now i feel like wasting my time on a broken Opensource trap :(

**Comment by AochiToxx** [comment]
I know it's been a while since you created this issue report, but I was having a similar [issue (Unable to use credentials. (Setup to be used under a local domain)](https://github.com/formio/formio/issues/638) and this might be what you where needing?

**Comment by A-Pradeep** [comment]
can you re-install the Form.io  by giving the new database name for the backend ( in config/default.json).
Or any Errors you are facing when you try to login ?

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
