### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by nalfalasi** [formio/formio#433]
is there a way to create RTL forms in Form io?

**Comment by pageza** [comment]
Hi nalfasi,Thank you for checking out Form.io Unfortunately, we do not currently support RTL forms.  We offer development services if this is something you would like us to quote for you.

Let me know if you would like a quote or if there is anything else you need. 

--Zach

**Comment by pummy-kanhasoft** [comment]
Can anyone help me out from getting DefaultValue from DATA section in custom component. 
![form io](https://user-images.githubusercontent.com/91519891/170030461-9c5d4a0f-acf1-4d82-8b60-8d0af4288103.png)

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
