### ISSUE TITLE
Currency Component Issues

### ISSUE THREAD

**Issue by mkrienke** [formio/formio#437]
1. After removal of the $ Prefix, it resets to $.
2. The comma separator saves in the data making it inoperable in simple numerical calculations.  Seems like this should be strictly a numerical field because currency is numeric.  The comma separator is great for currency and should only be in the display, not the data, in my opinion.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
