### ISSUE TITLE
[Feature request] Conditional disable

### ISSUE THREAD

**Issue by aialenti** [formio/formio#471]
Hi, I've been using formio and formiojs in a web application. I would like to have a "conditional disable" capability, that is the possibility of applying some kind of logic in order to disable or enable a particular field (I think it would be more or less the same as the "conditional display", which is already implemented).

Do you have this feature in your roadmap? Where do I start if I want to contribute and implement it by myself?

Thanks

**Comment by travist** [comment]
We definitely have this on our roadmap, and we welcome your help. This would probably be first implemented within the renderer found @ https://github.com/formio/formio.js. Form there, you would probably make a change to the Validator within this library @ https://github.com/formio/formio/blob/master/src/resources/Validator.js.

**Comment by suportecaso052020** [comment]
you actually implemented this feature?

**Comment by sumitbaliyan** [comment]
Hi Team,

May you confirm if conditional disable feature is implemented now ?

**Comment by echo-liang** [comment]
Also looking for the 'disable' feature, what's the current status on that?

**Comment by wag110894** [comment]
Hello,

Conditional disable is available using our logic tab. https://formio.github.io/formio.js/app/examples/conditionalwizard.html,https://formio.github.io/formio.js/app/examples/conditions.html,https://formio.github.io/formio.js/app/examples/external.html

**Comment by bilogic** [comment]
@wag110894 

Your examples only show how a component can be hidden, not disabled.

**Comment by katrinrodkina** [comment]
You can put custom disabled logic on the component.

Lets say **Trigger**: type simple, when some component has certain value and then in **Actions** name - disabled, Type - property, component property - disabled , true

**Comment by bilogic** [comment]
@katrinrodkina thanks it is quite rigid in setting up, but does work. Offhand, I think it can support any use cases.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
