### ISSUE TITLE
Replace MongoDB with Postgres 

### ISSUE THREAD

**Issue by liyuankui** [formio/formio#478]
MongoDB has drawbacks compared to Postgres in terms of Resource Consumption and Operation Friendly. 

Hope to make form.io running on Postgres.

**Comment by AlexeyNikipelau** [comment]
We currently don't have plans on migrating to PostgreSQL, but you can use SQL Connector to benefit from PostgreSQL features. Please read the corresponding docs: https://help.form.io/developer-tool-ecosystem/sql-connector
