### ISSUE TITLE
Can not share form to public ?

### ISSUE THREAD

**Issue by ensean** [formio/formio#485]
After start the server at port 3001, I created a demo form with only **Create Own Submissions** enabled to anonymous。   
And then here goes the problem, I can not find tabs like **Embedded** or **Launch** . How should I open my form to the end users for submission?

**Comment by vsile** [comment]
The same error!

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
