### ISSUE TITLE
Local installation 1000 limit issue

### ISSUE THREAD

**Issue by codewithrajranjan** [formio/formio#500]
I have installed the formio server locally and it was running fine. 
I have created multiple forms and resources in it. 
Now I am able to login in the formio application but I am not able to create new forms or resources
I checked in browser console and it is giving me error as 

GET http://172.16.111.88:3001/role?limit=1000 401 (Unauthorized)

Is the 1000 limit applies to local server installation also

**Comment by sathiz1993** [comment]
Hello @self-tuts . Could you share the screenshot of your form access tab?

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
