### ISSUE TITLE
Disable specific components

### ISSUE THREAD

**Issue by JonnyHeavey** [formio/formio#520]
Is it possible to add the ability to disable certain components from the form builder?

There are some components which we do not want users to be able to add to a form. 

A configuration file / option to select whether a component is enabled / disabled would be very useful.

**Comment by shervud** [comment]
Yes, it would be very convenient. Faced with this problem too.

**Comment by shervud** [comment]
> Is it possible to add the ability to disable certain components from the form builder?
> 
> There are some components which we do not want users to be able to add to a form.
> 
> A configuration file / option to select whether a component is enabled / disabled would be very useful.

Try this one
http://formio.github.io/formio.js/app/examples/custombuilder.html
