### ISSUE TITLE
How to implement custom validation in server side before form save submission ? 

### ISSUE THREAD

**Issue by fuzonmedia** [formio/formio#531]
@travist ,

I am trying to implement google recaptcha in one of my contact us form . 

I have done the client side validation & passing a captcha token in a form hidden field to the API . Now i need to validate that token from the google server(https://developers.google.com/recaptcha/old/docs/php) with some custom validation code in server side / form io . 

I found in form.io save submission - > form action(edit) page where i can put my javascript custom condition http://prntscr.com/ia9ehu . 
I tried to run some http request both in javascript & Nodejs code as action condition (before Handler ) . But none of the code seems to working there . 

Do we have any control to put our custom validation before it actual save the submission ? Or can you please point me out where i can put custom logic inside the form io core files so that i can contribute that code ? Its a very essential feature i believe 

Thanks 
Nil

**Comment by fuzonmedia** [comment]
Hi ,

Anyone can assist me here from the support team  ? 

thanks

**Comment by krixerx** [comment]
We extended the Validator.js file with jsdom library (in formio server). This enables to use window object like in browser.

const jsdom = require('jsdom');
const dom = new jsdom.JSDOM('<!DOCTYPE html>');
var $ = require("jquery")(dom.window);

Then need to inject jquery into sandbox:
const sandbox = vm.createContext({
      	$,
        data,
        row
      });

Now the validation is able to use jquery in server side. You can make REST calls for example inside validation.

**Comment by travist** [comment]
@krixerx great suggestion.
