### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by AlameerDev** [formio/formio#535]
Dears,

let's say that I have exist system that has his own user/permission/roles , and I want to used Form.io inside that system using angular-formio. I don't want to make the submission permission in form.io for anonymous, so is there any way to authenticate the login in users in main system to access form.io api ?

I tried to follow this [https://help.form.io/developer/info/sso/](https://help.form.io/developer/info/sso/) but no luck .

**Comment by travispence** [comment]
I was playing around with this the other week and was able to get it working. The strategy I used was to create a JWT within my system encoded with the Mongo ID of  of the _authenticated_ user role that has submission permissions. I then send that to the browser and store it in the localstorage to be retrieved later on. 

Some of the fields in the token may be redundant. 

```
var jwt = require('jsonwebtoken');
var token = jwt.sign({
  allow:'GET:/form/*,POST:/form/*,PUT:/form/*', 
  form: {
    _id: '5a6a45dd63893604266a50ee'
  },
  user: {
    id: '5a53dc41728dc5165023c6e2', // from my system
    _id: '5a53dc41728dc5165023c6e2',
    role: '5a6a112c1af059ce53098b8c',  // Authentiacated User
    roles: [
      '5a6a112c1af059ce53098b8c'
    ]
  }
}, '--- super secret ---');

// We now have a token!
console.log(token);

```

**Comment by AlameerDev** [comment]
@travispence  thanks so much. it is working now. I used almost the same payload that you use it but the mistake was in the form Id, anyway for anyone try to authenticate using an external system, you need the following payload : 

`// We now have a token!

var jwt = require('jsonwebtoken');
var token = jwt.sign({
  form: {
    _id: '5a8298b1227b6a295400935c' // form.io form Id
  },
  user: {
    _id: 'external', // keep it like that
    roles: [
      '5a80367bd21623401c7c50ec' // form.io authenticated role Id
    ]
  }
}, 'secret'); // JWT secret key

// We now have a token!
console.log(token);`

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
