### ISSUE TITLE
Unable to use cosmos mongo api for form.io

### ISSUE THREAD

**Issue by jasonchester** [formio/formio#539]
When configuring form.io to use cosmos mongo api, the application fails when attempting to list collections...

    /**
     * Test to see if the application has been installed. Install if not.
     */
    var checkInstall = function(next) {
      formio.util.log('Checking for db install.');
      db.listCollections().toArray().then(function(collections) {
        debug.db('Collections found: ' + collections.length);

https://github.com/formio/formio/blob/01501250a667eef0a445031d8bd70beebb887ec6/src/db/index.js#L151

Repro steps: 
1. git clone https://github.com/formio/formio
2. update connection in /config/default.json with cosmos connection string
3. npm i
4. npm start

I opened the following issue with the azure cosmos db team.
https://github.com/Azure/azure-documentdb-dotnet/issues/436

**Comment by lbcgitadmin** [comment]
I had an issue when using Cosmos with Form.io after the version on Mongoose was updated.  There was a change in Mongoose where it no longer liked the auto-generated password generated by Cosmos resulting in an authentication error.  E.g. the auto-generated password might look something like this:

6QupMFwUEdUop5pF4KdTwiPSrhmELZ5btAaVxTHGrcUAEQKN7Bnn3p59RiJi5pTa5ixRFoA2XXjstMoFLB0byQ==

To fix the issue, the "==" needs to be encoded and replaced with "%3D%3D" resulting a password that looks like this:

6QupMFwUEdUop5pF4KdTwiPSrhmELZ5btAaVxTHGrcUAEQKN7Bnn3p59RiJi5pTa5ixRFoA2XXjstMoFLB0byQ%3D%3D

**Comment by jasonchester** [comment]
Thanks a bunch @lbcgitadmin, this saved us a ton of time managing mongo instances.

URL Encoding the key worked great!

here's a relevant snippet of the formio config.

```
{
  "port": 3001,
  "appPort": 8080,
  "host": "localhost:3001",
  "protocol": "http",
  "domain": "http://localhost:3001",
  "basePath": "",
  "mongo": "mongodb://mongodb01:8v<snip>tA%3D%3D@mongodb01.documents.azure.com:10255/formio?ssl=true",
  "mongoSecret": "",
```
