### ISSUE TITLE
didn't have mongod running when ran npm install

### ISSUE THREAD

**Issue by tedx** [formio/formio#564]
I didn't have mongo d running when I did npm install and now when I run npm start I get the following error. Is there some db configuration that didn't happen and if so how can I fix it?

Welcome to the Form.io application server!

  - Help: https://help.form.io
  - Code: https://github.com/formio
  - Love: https://form.io

/home/tedx/formio-master/node_modules/mongodb/lib/mongo_client.js:792
          throw err;
          ^

Error: Could not connect to the given Database for server updates: mongodb://localhost:27017/formioapp.
    at /home/tedx/formio-master/src/db/index.js:123:17
    at unlock (/home/tedx/formio-master/src/db/index.js:76:14)
    at /home/tedx/formio-master/src/db/index.js:122:9
    at err (/home/tedx/formio-master/node_modules/mongodb/lib/utils.js:414:14)
    at executeCallback (/home/tedx/formio-master/node_modules/mongodb/lib/utils.js:403:25)
    at /home/tedx/formio-master/node_modules/mongodb/lib/mongo_client.js:270:21
    at connectCallback (/home/tedx/formio-master/node_modules/mongodb/lib/mongo_client.js:940:5)
    at /home/tedx/formio-master/node_modules/mongodb/lib/mongo_client.js:789:11
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.26.6 start: `npm run version && node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the formio@1.26.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tedx/.npm/_logs/2018-03-09T03_20_22_892Z-debug.log

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
