### ISSUE TITLE
Table not working in a form submission view

### ISSUE THREAD

**Issue by KuanyshOlzhabay** [formio/formio#577]
I tried several ways to work with the table, but in the submission view does not display a table with data. Several screenshots of my problem
![sc2](https://user-images.githubusercontent.com/10281864/38133128-b5738644-342f-11e8-9c13-c34479a51eaa.png)
![sc1](https://user-images.githubusercontent.com/10281864/38133129-b595de92-342f-11e8-9a34-16326f8f1a30.png)

**Comment by bolatk** [comment]
@travist , @YuryRybakSoftensity any ideas, guys?

**Comment by A-Pradeep** [comment]
try to update the 'ng-formio' , I solved this issue by doing the bower install. Currently i've installed "ng-formio": "^2.33.0", and its working fine.

**Comment by tapanbavaliya** [comment]
i have version of `ng-formio` is `2.33.0` but still not display table 

![screen shot 2018-11-13 at 6 05 11 pm](https://user-images.githubusercontent.com/1378636/48413763-b7bf8180-e76e-11e8-81cd-0babf4a264cd.png)

**Comment by wag110894** [comment]
Hello,
 
Could you please provide the json of the form so we can reproduce this issue?
Please let me know if you have any further questions or concerns.
Thanks!

**Comment by tapanbavaliya** [comment]
Here is the form json

```

**Comment by RubiCom007** [comment]
Hi, Have you ever got it sorted? I have the same issue.

**Comment by rickjohnson22** [comment]
I have this same issue. I logged out of the newest platform,  next.form.io,  and logged into the old platform, platform.form.io, and I was able to see all my data.  

Of course, you should see your submission data on the Next platform, but this is a simple workaround until they get that bug fixed.
