### ISSUE TITLE
[Information] Formio Docker Container

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#591]
Just letting you know, we have release our docker image for the formio-api (single project) [unfao/formio](https://hub.docker.com/r/unfao/formio/).  The docker-compose of the image has also been published and you can check it at our [github repo](https://github.com/un-fao/fast-docker).

The container forces the API over https and it comes with it own self-signed certificate for https://lvh.me (which resolves to 127.0.0.1) for local development. IF you wish to install your own certificate, then clone the repo to build your own image modified to your needs.

This is still a work in progress so it could change in the feature.

> Don't forget to read the instructions.  For any problem, just raise an [issue](https://github.com/un-fao/fast-docker/issues).

**Comment by NeoTheThird** [comment]
Any chance we could get an official docker image on the hub? The [formio](https://hub.docker.com/u/formio) organization would be a good place, and it'd make the docker-compose file a little more durable and flexible.

**Comment by travist** [comment]
The "official" build from Form.io is our enterprise docker container which is our Enterprise solution (paid). We do not have plans for adding the Open Source api server as a docker image, so we are appreciative of community members like @airarrazaval who offer it to the community and also maintain it.
