### ISSUE TITLE
Application slow: Angular infinite digest loop

### ISSUE THREAD

**Issue by basvandepol** [formio/formio#60]
![screen shot 2016-02-25 at 09 50 38](https://cloud.githubusercontent.com/assets/17470067/13315418/d98cfd92-dbaa-11e5-9bed-58e8192d606b.png)
![screen shot 2016-02-25 at 09 50 45](https://cloud.githubusercontent.com/assets/17470067/13315421/dd0534b2-dbaa-11e5-8230-f156da7a2300.png)

_**Sorry this is a duplicate from my issue on Formio.js**_

Hi Zack,

i'm trying to use Form.io to build beautiful forms. I've downloaded the repository and have it up and running with MongoDB. 
One of my needs is to build a form with a table. For example the table has 9> rows and 5 columns, each column has a different input. This works (as the only form builder i've found) like a charm. 
I face only one issue. For example when I reach row 6 and drag and drop a number form control into one of the columns the application gets real slow. I've checked and this is for both the local version as the cloud version on Form.io.

When i check the console Angular is giving errors (which also slows down the console real bad). 
The error: 
`Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! Watchers fired in the last 5 iterations` 

I've also added screenshots for my example table and the total console logs. 

I hope you could help.
Thanks in advance,

Bas van de Pol

**Comment by zackurben** [comment]
Hey @basvandepol, I've duplicated your issue and I'm working on a fix now. Thanks for reporting this!

- Zack

**Comment by basvandepol** [comment]
Hey @zackurben , thanks in advance. If you  need more info please let me know, i'm looking forward to be hearing from you.

Bas

**Comment by basvandepol** [comment]
Hi @zackurben i was wondering if you, by any chance, had time to look into this error yet? 
Bas

**Comment by zackurben** [comment]
@basvandepol sorry for the delay, I've been fixing other bugs. Just for a heads up, this is still on my radar screen and another developer is actually going to look into this bug, and some other issues with the data grid component.

If you cant wait, and need to fix it yourself, the best place to start is with the form renderer: https://github.com/formio/ngFormio

**Comment by travist** [comment]
We have made some big improvements to our renderer. I believe this is fixed, but would like verification.
