### ISSUE TITLE
Fix Initial Role ID's

### ISSUE THREAD

**Issue by pixie79** [formio/formio#600]
Hi,

When starting the FormIO API server you supply a list of roles by name which get created. However, if you export your forms as json for backup's these are exported with the ID's.

Is there a way to force the ID's of the roles when the API server starts so that these can map back to the roles or switch the import/export of Forms to allow role names instead?

Thanks

Mark

**Comment by harthorst** [comment]
Any news here?

**Comment by brendanbond** [comment]
@harthorst what's your specific use case here? I believe that this problem is solved via the templating system, but I could use a little insight into what you're trying to do

**Comment by harthorst** [comment]
@brendanbond I'd like to export forms from instance A and import them into instance B via REST api. Right now I have to change the role ids in the form before import. But maybe there is a better way?

A use case could be a custom editor which copies a form to a different stage (e.g. from dev to test).

BTW: I'm using the free version of formio.

**Comment by brendanbond** [comment]
Yeah, in open source the only way to do this is as you've described, programmatically updating the Role IDs to fit the new instance. Our Enterprise product offers a number of ways to import/export projects/forms/actions as template files which will automatically be installed in a new instance, and as far as I know, there are no plans to port this to the open source core at this time.
