### ISSUE TITLE
SQL Action Update not executing because of Formio Cache

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#623]
When executing a SQL Action, only post methods (i.e.: submission create) or delete method (submission delete) are being executed.  If a submission is updated, Formio uses its cache and fails to update the submission in the SQL server:

https://github.com/formio/formio/blob/b9d191c8de07dbc43f402779e8c11db9f3a9aa28/src/actions/SQLAction.js#L277-L289

To fix this, only get methods (i.e.: submission read) should be fetched with Formio Cache.  The following code achieves that:

```js
if (method !== 'get' && req.body) {
  onSubmission(method === 'delete' ? currentResource.item : req.body);
}
else {
  router.formio.cache.loadCurrentSubmission(req, function(err, submission) {
    if (!err && submission) {
      onSubmission(submission);
    }
  });
}
```

**Comment by travist** [comment]
Here is the pull request. We will pull this in before our next release.

**Comment by ZenMasterJacob20011** [comment]
The pull request has been merged. Closing this thread. Thank you for your contribution!
