### ISSUE TITLE
[Enhancement] Create Entity or Abstract Resource without the HTML-specifics

### ISSUE THREAD

**Issue by ahmedabuabdou** [formio/formio#630]
Hello,

It would be great to be able to first model the **entities** in a more abstract way away from any HTML-specifics; the resources for instance still have in their schema HTML-specific attributes, but if the base resource/entity is describing only the domain entity similar to any POJO or POCO; like id, name, type, validation ....etc. and this entity becomes available for both the Form or Resource to link to, then this concept could make form.io become a place to also model your domain entities and link them with external systems like BPM for example.
See for instance the [Jhipster Studio](https://start.jhipster.tech/jdl-studio), where you can model your domain entities in a very abstract way.

**Comment by wag110894** [comment]
Hello thanks for reaching out,
 
This is William with the Form.io support team.  Great to hear from you!
 
Is this something that you would be willing to look into and contribute to our library?
 
Please let us know. 
 
Please let me know if you have any further questions or concerns.
 
Thanks,
William Gay

**Comment by ahmedabuabdou** [comment]
Hello,

My team, Adib and Abdulmajeed for instance, are contributing to form.io and has sent some pull requests already.
To answer your question, yes, we might be and I guess the core.js library could take some attributes and move them first to a parent class called entity for instance; just an idea and similarly, the UI experience should be reflected accordingly.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
