### ISSUE TITLE
Prefill user data from database

### ISSUE THREAD

**Issue by duartegarin** [formio/formio#637]
Hi,
I am currently evaluating form.io for our company.

One of the important requirements for us is that it's seamless to the user that the forms are part of the application workflow.

This means when they are logged in and open a form, their details should be pre-filed from the user profile.

Is there any way to achieve this? Maybe using some sort of replacement token mechanism?

Thanks!

**Comment by android-cq** [comment]
Hi,

Have you find any solution for this feature?

I also have similar request, trying to find out solution.

Thanks!

**Comment by jhen1422** [comment]
Hello Chuan,

This is Jeriah from the Form.io support team. Thank you for reaching out!

You are able to pre-fill data on a form based on external data by following the documentation linked below.

http://formio.github.io/formio.js/app/examples/externalload.html

On another note, we would love to connect with you and hear more about the project you’re working on! Form.io offers support packages as well as development services to help with your application. These services connect you directly with a Form.io developer and can be a huge help jump starting your app. Please let me know if you’re interested, I’d be more than happy to send you additional information.

In the meantime, feel free to reach out with any other questions.

**Comment by bshivam1** [comment]
@duartegarin use it in this way ! <formio [form]="formSpec" [submission]="formData" ></formio>

**Comment by rwplazz** [comment]
Hi,
I think it should be possible to use the "Custom Default Value" field to prepopulate the fields from your user data.
BR
