### ISSUE TITLE
File Component render error

### ISSUE THREAD

**Issue by bshivam1** [formio/formio#640]
Hello Sir/Ma'am, @travist  @jhen1422 
I'm working on ng-formbuilder to create formSpec and using angular-formio in angular 6 to render and get data filled in.
The problem I'm facing is in FILE component, when I give a URL suppose https://anyposturl.com/here
So in formSpec I get something like this.....
{
    "autofocus": false,
    "input": true,
    "tableView": true,
    "label": "TEST",
    "key": "undefinedTest",
    "image": false,
    "imageSize": "200",
    "placeholder": "",
    "multiple": false,
    "defaultValue": "",
    "protected": false,
    "persistent": true,
    "hidden": false,
    "clearOnHide": true,
    "filePattern": "*",
    "fileMinSize": "0KB",
    "fileMaxSize": "1GB",
    "type": "file",
    "labelPosition": "left-left",
    "labelWidth": 20,
    "labelMargin": 3,
    "tags": [],
    "storage": "url",
    "url": "https://anyposturl.com/here",
    "conditional": {
      "show": null,
      "when": null,
      "eq": ""
    },
    "properties": {},
    "prefix": "",
    "customClass": "",
    "suffix": "",
    "unique": false,
    "dataGridLabel": false,
    "description": "",
    "errorLabel": "",
    "tooltip": "",
    "hideLabel": false,
    "tabindex": "",
    "disabled": false,
    "dbIndex": false,
    "customDefaultValue": "",
    "calculateValue": "",
    "validateOn": "change",
    "validate": {
      "required": false,
      "custom": "",
      "customPrivate": false
    },
    "uploadOnly": false,
    "id": "e4fb1n"
  }

and I hope that looks fine, but when this spec is rendered using <formio [form]="formSpec" > </formio> we get this (see below img)
image.png

and then while uploading we get an error which is as below.
ERROR TypeError: Cannot read property '0' of null
    at new e (main.d4b90065702806497f95.js:1)
    at t.get (main.d4b90065702806497f95.js:1)
    at main.d4b90065702806497f95.js:1
    at Array.forEach (<anonymous>)
    at t.value (main.d4b90065702806497f95.js:1)
    at HTMLInputElement.onChange (main.d4b90065702806497f95.js:1)
    at e.invokeTask (polyfills.c32a63fec35f498527b2.js:1)
    at Object.onInvokeTask (main.d4b90065702806497f95.js:1)
    at e.invokeTask (polyfills.c32a63fec35f498527b2.js:1)
    at t.runTask (polyfills.c32a63fec35f498527b2.js:1)
I'm not able to figure out what the problem is, please help.

**Comment by bshivam1** [comment]
This same error is also thrown when I choose Base64 @jhen1422

**Comment by jhen1422** [comment]
Hello,

Jeriah here from support team.

When setting the form definition via <formio [form]=formDef /> you may need to set the url attribute to the form url as well. You can try this and see if it fixes the issue for you. 

On another note, we would love to connect with you and hear more about the project you’re working on! Form.io offers support packages as well as development services to help with your application. These services connect you directly with a Form.io developer and can be a huge help jump starting your app. Please let me know if you’re interested, I’d be more than happy to send you additional information.

**Comment by arif12979** [comment]
> Hello,
> 
> Jeriah here from support team.
> 
> When setting the form definition via <formio [form]=formDef /> you may need to set the url attribute to the form url as well. You can try this and see if it fixes the issue for you.
> 
> On another note, we would love to connect with you and hear more about the project you’re working on! Form.io offers support packages as well as development services to help with your application. These services connect you directly with a Form.io developer and can be a huge help jump starting your app. Please let me know if you’re interested, I’d be more than happy to send you additional information.

@jhen1422 ( you may need to set the url attribute to the form url as well) mean we need to set file control url as form url is?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
