### ISSUE TITLE
DataGrid single type elements

### ISSUE THREAD

**Issue by justjuank** [formio/formio#641]
Hello, I have a datagrid with a single field of type email, where the user can add a list of email addresses. 
The current output of this is:
![image](https://user-images.githubusercontent.com/989828/44814432-45dd9000-aba2-11e8-94fa-99eed08a4d70.png)
Is it possible to have the output only as an array of strings instead?
Something like `EmailList: ["test@mail.com", "test2@mail.com"]`

Thanks in advance,
Juan.

**Comment by denisekay** [comment]
Yes. Use the "Multiple" setting ont he email field instead of a datagrid.

**Comment by justjuank** [comment]
That's exactly what I needed, thank you!
