### ISSUE TITLE
How to modify the owner of a query

### ISSUE THREAD

**Issue by Marchf** [formio/formio#649]
How to make a query before setting the owner, I need to query all the submission information in the same group.

![image](https://user-images.githubusercontent.com/36831441/45334891-6567b600-b5af-11e8-91ec-6b21741bf3b3.png)

**Comment by wag110894** [comment]
Hello, 

This is William with the Form.io support team. Thanks for reaching out!

I would highly discourage modifying the core library to hard-code your owner into the query. With that said, the query is incorrect where it is adding the owner filter twice. This should be getting the "owner" from the JWT token that is provided to the application.

On another note, Form.io offers support packages as well as development services to help with your application. These services connect you directly with a Form.io developer and can be a huge help with your app. Please let me know if you’re interested, I’d be more than happy to send you additional information.

Please let me know if you have any further questions or concerns. 
Thanks, 

William Gay 
Form.io Developer Support

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
