### ISSUE TITLE
How is the combined and minified js for the app getting generated ?  

### ISSUE THREAD

**Issue by biswanaths** [formio/formio#66]
I wanted to run the modified code on local and could not find where the app.<hash>.js and vendor.<hash>.js is getting generated. Can you folks be kind enough to point how these js files are getting generated ? 

Thank you in advance.

**Comment by randallknutson** [comment]
You are probably seeing the code from https://github.com/formio/formio-app-formio which gets downloaded as the frontend to the formio server. You can see the gulp commands and such within it.

**Comment by travist** [comment]
What you need to do is clone the repo @ https://github.com/formio/formio-app-formio, then type the following.

```
npm install;
bower install;
gulp build;
```

This will create the ```dist``` folder which contains the app.js and the vendor.js files.

**Comment by biswanaths** [comment]
Thanks for help. 

How you guys maintain local dependencies during the development across the projects? I assume bower works against the github.
