### ISSUE TITLE
Issue with URL storage provider

### ISSUE THREAD

**Issue by ghost** [formio/formio#665]
The URL storage provider is not functioning the same as it does with hosted form.io. It is supposed to accept a response back from the url endpoint which can dictate the location of the file that was uploaded to be saved in the form submission. When using a hosted form.io instance, this works correctly. But when using the open source server, it does not accept the response object and therefore does not store the correct location of the uploaded file in the submission.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
