### ISSUE TITLE
add role action - existing account

### ISSUE THREAD

**Issue by gismomtl** [formio/formio#668]
Hi,
with formio version: 1.33.5, if we have a new role (ex. Approver) manually created in the mongo DB, we can see that "add role" action can see correctly the new role.
However, if we want to add the new role to an existing account (which has already Authenticated role), the role array associated to this user is not changed after applying the action.. still 1 item in the list and the one already there.

**Comment by gismomtl** [comment]
If i create a new Resource (Manager) and create 2 actions, 1 to assign role to Authenticated, the 2nd to be Approver Role.
It's creating a new submission with the 2 roles. 
However if a user is already registered, how to do a form which will permit to add/remove "Approver" role.... 
- without having to provide the user password in the form
- which will keep the same ID to avoid having 2 distinct submissions for the same user (one user submission.. and for Approver).

**Comment by wag110894** [comment]
Hello again,

Please find below information on the items you reported:

How to do a form which will permit to add/remove "Approver" role.without having to provide the user password in the form?

If you don't provide a password in a password field it will keep its existing value.

How to do a form which will permit to add/remove "Approver" role.which will keep the same ID to avoid having 2 distinct submissions for the same user (one user submission.. and for Approver)?

You can edit an existing user without generating a new id.

Thanks, 

William Gay 
Form.io Developer Support
