### ISSUE TITLE
how to inject a module as a dependency in formio?

### ISSUE THREAD

**Issue by hossein69** [formio/formio#670]
i want to add ADM-dateTimePicker as a custom component to formio. i added the component and set the directive to show up when the component drags to the view. 
i add the ADM-dateTimePicker to index.html in the src folder and hit gulp default in client folder.but there is a error as shown below in the console.i add the module dependency in src/app/index.module.js
the error

> Uncaught Error: [$injector:modulerr] Failed to instantiate module formioApp due to:
Error: [$injector:modulerr] Failed to instantiate module ADM-dateTimePicker due to:
Error: [$injector:nomod] Module 'ADM-dateTimePicker' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by hossein69** [comment]
i copied the minified version of ADM-dateTimePicker in src/app/index.module.js above the dependency's and the problem solved but it looks ugly.is there place for introducing new module to formio as a dependency . now i added persian / georgian date to formio.

**Comment by hossein69** [comment]
by adding the ADM-dateTimePicker.js script tag in above the config.js problem solved more clearly.

**Comment by wag110894** [comment]
Hello, 

William here with Form.io support. Thanks for reaching out!
This seems like an issue with gulp and angular.js and getting dependency management correct. 

It seems like you found a workaround but thank you for letting us know.

Please let us know if you have any further questions or concerns. 

Thanks,
William Gay 
Form.io Developer Support

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
