### ISSUE TITLE
NestedForm Default calculated value?

### ISSUE THREAD

**Issue by imadbakir** [formio/formio#677]
hello, 
can someone please shed some light on how to pre-populate a nested form Component?
Such as in setting a calculated default value for a textField component.
Thanks.

**Comment by wag110894** [comment]
Hello, 
This is William with the Form.io support team. Thanks for reaching out! 
 
Nested forms have a seperate data object than the parent form so you cannot use parent data in the calculated value of the nested form by default. Besides that, the calculated values should work the same.
 
If you to pass the data from a parent form into a nested form for calculation, here is an example to help you: In this example, you can see the injection of the “total” value that is calculated from the parent into the child via the default Values. http://formio.github.io/formio.js/app/examples/multiform.html 
 
Please let me know if you have any further questions or concerns. 
 
Thanks,

**Comment by imadbakir** [comment]
Hello William, @wag110894 
thanks for your help!
this seems to work in formio platform but not with the renderer? 

Thanks.

**Comment by orqldon** [comment]
Hello @wag110894 or @travist the example linked above (http://formio.github.io/formio.js/app/examples/multiform.html) is no longer available.  Can you point to a more up-to-date reference for how to use data from "parent" form in a calculated value in a "child" nested form?  Is this still possible?

Basically I want to have several nested forms in the pages of a Wizard, with one field that is common to all the nested forms.  I would like the Wizard end user to set enter this field only once, on the first page of the wizard (the parent form) and then have a custom calculated value reflect this for the same field on each of the child nested forms.

**Comment by orqldon** [comment]
Actually I think I figured it out: I set the value of "myfield" on the child/nested form using
`value = instance.root.root.data.myfield;`
where the wizard (parent) form has a field also called "myfield".

Please comment if there is a better way otherwise I think this will work.
