### ISSUE TITLE
Groups/GroupAssignment 

### ISSUE THREAD

**Issue by marxus** [formio/formio#679]
i was trying to follow these instructions with the open source version 
https://help.form.io/userguide/groups/
created all the resources and such. 
is this even applicable?

**Comment by wag110894** [comment]
Hello Amit, 

Groups is a feature of our commercial platform along with a lot of other features that are outlined below:

1. OAuth - OpenID Connect
2. LDAP Authentication
3. Advanced Webhooks
4. Team management
5. Multi-tenant management
6. Email Templates (coming soon)
7. Temp tokens & Email based authentication
8. Report API (aggregated reports)
9. Staging and Deployment (SDLC)s
10. Form Submission Collections (saving submissions to different collections for indexing)
11. Form Versioning
12. PDFs
13. Encrypted Fields
14. Offline Forms
15. File Uploads
16. CORS Configuration
17. SQL Connectors
18. Kickbox integration
19. Google Sheets
20. Atlassian (JIRA) integration
21. Office 365 integration
22. Hubspot integration
23. CCS templating 
24. On Premise Deployment 


We would love to set up a short call to hear more about your specific requirements and answer any additional questions at your convenience.

Please let me know if you are interested.

Thanks!

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
