### ISSUE TITLE
how to give custom values in select field

### ISSUE THREAD

**Issue by piyush94** [formio/formio#680]

**Comment by wag110894** [comment]
Hello,
 
Thanks for reaching out!  We have support packages available for training and development services if you would like to work with someone on our team.  
 
In the meantime, here is a link to our help documentation regarding the select component:
https://help.form.io/userguide/form-components/#select
 
Thanks!

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
