### ISSUE TITLE
Application self references

### ISSUE THREAD

**Issue by pixie79** [formio/formio#682]
Hi

We have noticed some of the URL do not seem to respect either through APP_URL or the API_URL be instead just call /.

This seems most evident when you have the API pointing to example.com/formioapi and APP pointing to example.com/formio . An example of this is a call to /current

Also if the APP URL and the API URL are on different domains where can we override the CORS restrictions to allow access from both domains. This is using the docker image with the inbuilt form builder.

Thanks

Mark

**Comment by wag110894** [comment]
Hello Mark,
 
Thanks for reaching out!
 
The current endpoint should use the project url endpoint. When using our open source server, I believe that APP_URL and API_URL should be the same. This will help it correctly calculate the correct project url endpoint.
 
Here is where this occurs in the formio code.
https://github.com/formio/formio.js/blob/master/src/Formio.js#L1078-L1079
 
Please let me know if you have any further questions or concerns.
 
Thanks!

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
