### ISSUE TITLE
Multiple Errors 

### ISSUE THREAD

**Issue by A-Pradeep** [formio/formio#683]
Hi , in the new Version of the Bootstrap 4 ,  tooltips are not working/showing in the `Form Renderer` (using [formiojs](http://formio.github.io/formio.js/) .
while creating a form , if we give the `tooltip` for a component , while in rendering the tooltip won't show , not even icon also.

**Comment by A-Pradeep** [comment]
@travist @randallknutson  Hi  along with the above mentioned error , im facing a new error with the `JSON` particularly with the `Date / Time Component`  .
I have made changes so that it only show the `date` rather than the `time`.
But if give the date `example 21-11-2018` in the  `JSON response  console.log`  ill get the date as `20-11-2018` ,  whatever date , it  will get minus by the 1 day and return the `date`. 

Any solution to these problems !

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
