### ISSUE TITLE
How to trigger custom validations on OnBlur or OnFocus events instead of on change event?

### ISSUE THREAD

**Issue by shivlila01** [formio/formio#684]
1. Currently custom validations are triggered only on change event. Can we trigger it on other events as well(e.g. OnBlur or OnFocus etc)?
2. How to handle the form load and form exit events of form.IO? We need to execute some JavaScript on form load and form exit event.

**Comment by wag110894** [comment]
Our beta portal beta.form.io allows you to switch the validation trigger.  There are events for form load and submit. https://github.com/formio/formio.js/wiki/Form-Renderer#events

**Comment by shivlila01** [comment]
Thank you for your reply. We checked beta portal. It has "validation on" field with values "Change" & "Blur". Can we add "Focus" value as well? 
We need to trigger validation when user enters in the textbox. Please let us know how to add new value to "Validation on" field ?

**Comment by shivlila01** [comment]
Hi Team,
Please let us know the steps to add custom events in formio directive and let us know when this event get trigger. <formio (customEvent)=""> </formio>

**Comment by jhen1422** [comment]
Hello,
 
Custom events are triggered by the button component. You can set the action on the button to "Event" and specify what event to trigger.
