### ISSUE TITLE
How to determine whether a field is hidden by a condition

### ISSUE THREAD

**Issue by naitken** [formio/formio#686]
How can I determine from the submission data whether a field was hidden as the result of a condition on its container? I need to distinguish hidden fields from fields with no value.

In the newest release, the hidden fields are still part of the submission. In a previously release, they were not.

**Comment by wag110894** [comment]
Hello,

There is a JavaScript API called "conditionallyVisible" which will allow you to determine if a component is conditionally hidden.
https://formio.github.io/formio.js/docs/class/src/components/base/Base.js~BaseComponent.html#instance-method-conditionallyVisible

Please let us know if you have any further questions on this.

Thanks!

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
