### ISSUE TITLE
form.io does not start without Internet acess

### ISSUE THREAD

**Issue by diego-maravankin** [formio/formio#692]
Hello team,

I am running form.io with the client app in a server in our DC in a secure network that has no Internet access. I noticed that the service does not start if it cannot access Google APIs (which is my case). As a workaround, I provided temporary internet access to the server.

 Is there a way to disable this check and have the service start with no internet?

Thanks in advance.

Diego

**Comment by randallknutson** [comment]
Do you know which requests are being made to the google apis? I don't believe the server is designed to make requests to google apis. If you can help us locate where this is, we can remove that code or you can make a pull request.

**Comment by diego-maravankin** [comment]
@randallknutson I think I openned the issue in the wrong repo, since the problem is with the form.io client app. I will re-open it in the formio-app-formio project since I think it belongs there and not here.

**Comment by randallknutson** [comment]
No problem. We can continue there.
