### ISSUE TITLE
Possible to disable Wizard breadcrumb, next, cancel if Wizard is nested in non-wizard

### ISSUE THREAD

**Issue by nowickimt** [formio/formio#693]
I have a wizard form embedded in a non-wizard form.  I'm passing in wizard related settings, and those settings don't appear to propagate down to the nested form.  Here's how I'm instantiating the base (non-wizard) form:

```
Formio.createForm(document.getElementById('formio'), 'https://ias.form.io/claimsentry', {
  breadcrumbSettings: { clickable: false },
  buttonSettings: { showCancel: false, showPrevious: false }
});
```

**Comment by randallknutson** [comment]
We probably aren't currently passing the options down to the nested wizard. Is that something you could add a pull request to fix?

**Comment by nowickimt** [comment]
I could, but don't have time to do so.  To me this is a bug, but if it'll help get it fixed sooner, you can use some of the money in our support bucket to get it fixed.

**Comment by nowickimt** [comment]
This appears to be fixed -- not sure if a PR went in or what, but it's working for me now.
