### ISSUE TITLE
New Project and Stage  not creating using the Postman

### ISSUE THREAD

**Issue by A-Pradeep** [formio/formio#694]
HI , following the API docs in the [link](https://apidocs.form.io/#a7ca9883-4ec4-5226-f36c-a6dd0d0727f3) , i'm not able to create a new Project or stage in the Form.IO server. 
Even after providing the details such as the `JWT token` and url `http://localhost:3001/project`  , ill end up with the error 
```
There was an error in evaluating the test script:  JSONError: Unexpected token 'I' at 1:1 Invalid alias ^
``` 
 in the test panel of the postman & the code as follows For `New Stage`
```
var response = JSON.parse(responseBody);
postman.setEnvironmentVariable('stageId', response._id);
```

For `New Project`
```
var response = JSON.parse(responseBody);
var url = environment.protocol;
url += '://';
url += response.name;
url += '.' + environment.host;
postman.setEnvironmentVariable('appUrl', url);
postman.setEnvironmentVariable('projectId', response._id);
```

Any ways to solve this issue.

**Comment by travist** [comment]
Projects and stages are only supported with our enterprise platform and not available in the open source server.
