### ISSUE TITLE
Huge form optimization in backend

### ISSUE THREAD

**Issue by krixerx** [formio/formio#701]
We have form schema, which is huge and when we load it to browser, browser gets extremely slow and not usable.

So we need to optimize the form schema (using existing user data) in backend side already, filter out all schemas what is not needed.

So far, we tried it using RestHeart aggregations. We send user data (json) to backend. If field "howoldareyou" < 18 then backend will not give back any schema.
https://bpa-lesotho-dev.eregistrations.org/restheart/registrations/7e00f4b7-f6dc-11e8-9736-0242ac120014/_aggrs/get_mandatory_list?avars={"howoldareyou":1}

If "howoldareyou" >= 18 then componens schemas are in response:
https://bpa-lesotho-dev.eregistrations.org/restheart/registrations/7e00f4b7-f6dc-11e8-9736-0242ac120014/_aggrs/get_mandatory_list?avars={"howoldareyou":19}

Does formio team has ideas ot thinking about server side schema optimization when using huge forms?

**Comment by randallknutson** [comment]
If you use the Form class's schema property it will return the minimized version of the form schema. 
https://github.com/formio/formio.js/blob/master/src/Webform.js#L715-L720
new Form('').then(form => {
  form.schema
});

**Comment by krixerx** [comment]
Can we think about solution that form schema can be always in change (not a static)?

**Comment by randallknutson** [comment]
If I understand correctly, you are recommending that we send the schema on the change event instead of the full form definition, correct? 

I think we'd be open to this change since the schema should fully represent the form but is much smaller.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
