### ISSUE TITLE
Min/Max validation not checked for Text Area Component

### ISSUE THREAD

**Issue by Blackbaud-ScottBaumann** [formio/formio#703]
With text area component, the minimum length and maximum length validations are not being checked on the form. The validation is being checked once I submit but I would of expected it to act similar to the text field where I get a error message under the component.

Repo steps:
1. Insert Text Area component to a form and set the min/max validations to any number,
2. With in the form enter text in this new component that is either under the min validation or over the max validations.
3. No error message appears under the component stating the value is invalid

NOTE - During the submission of the form I will be informed of the invalid form.
example
![image](https://user-images.githubusercontent.com/17148253/49527005-9be36300-f876-11e8-886b-fc0cf3725fd1.png)

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
