### ISSUE TITLE
Ability to set Select options values from data array & choose Value property? 

### ISSUE THREAD

**Issue by imadbakir** [formio/formio#706]
Hello, 
I tried to use the custom data option and selected an array of objects, the template works fine but, the selected value is an object, I guess it is needed to be able to choose value property, it is available when setting from URL but not when setting from Data

**Comment by randallknutson** [comment]
Yes you need to set the value property. It may be that the field has not been added to the form builder yet. You can switch to a data source that has the value property, set it, and then switch back to custom.

**Comment by imadbakir** [comment]
@randallknutson thanks that can do the trick !

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Thank you for your contribution!
