### ISSUE TITLE
Validation to dates with moment

### ISSUE THREAD

**Issue by bigjorjao** [formio/formio#716]
In my form i have 2 Date/Time Component. I dont use time.

dataPrevistaInicio |   dataPrevistaFim.

In element End Date I have one validation 
valid = moment(input).isSameOrAfter(row.dataPrevistaInicio)
? true
:  "Data deve ser maior que "+  moment(row.dataPrevistaInicio).format('DD-MM-YYYY');

Validation works correctly.
When i do the submission and I indicate a dataPrevistaInicio greater than the dataPrevistaFim the form is alert: "Data deve ser maior que ...."

But when I do the submission and I indicate a dataPrevistaFim greater than the dataPrevistaInicio gives me this error:
![erro](https://user-images.githubusercontent.com/46224388/50519772-62d49200-0ab4-11e9-98a0-cdef810236c8.png)

Can i help me what i do wrong?

**Comment by travist** [comment]
This may be an issue with the Validator not having an instance of moment available.

We will investigate and add to our backlog if it turns out to be an issue.

**Comment by sl45sms** [comment]
i confirm the same issue,
as workarount i check if moment exists

```javascript
valid=true;
if (typeof moment  === "function") { 
var m = moment().subtract(1,'day').subtract(3,'months');
var p = moment(input);
valid=m.isSameOrBefore(p);
}
```

also when using Native, the following always false on submit.
```javascript
var m = new Date();
m.setDate(m.getDate() -1);
m.setMonth(m.getMonth() - 3);
var p = input;
if (p>m) valid=true; else valid="not valid date";`
```
but as workarround i use (and works)
```javascript
valid=true;
var m = new Date();
m.setDate(m.getDate() -1);
m.setMonth(m.getMonth() - 3);
var p = input;
if (m>p) valid=false;
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
