### ISSUE TITLE
View Submissions with Data-Grid 

### ISSUE THREAD

**Issue by olsn** [formio/formio#719]
This is probably just a minor issue, as it is not causing any visible effects:

### First issue:
The DataGrid in the View-Table is not completely visible:
![image](https://user-images.githubusercontent.com/1181905/50660383-e3f1c480-0f9f-11e9-9e8b-9a2e3f9e1f3a.png)
I guess we could fix this locally pretty easy but adding some basic css:
![image](https://user-images.githubusercontent.com/1181905/50660518-4e0a6980-0fa0-11e9-9937-fd7abea9b9f2.png)

### Second issue (the bigger issue):
When the Data-Grid contains a select-input with a Resouce as data-source and set to `save as reference`, then there will be no data shown under "View Data" **and** instead of only 2 entries, I now see 6 entries (one for each sub-entry in the data-grid) even though none of the fields in the data-grid are set to "show in table".
![image](https://user-images.githubusercontent.com/1181905/50660645-d4bf4680-0fa0-11e9-8ff7-1d55ab6e9936.png)

When I remove the checkbox for `save as reference` everything works fine.
This seems not like a frontend-issue, more like a backend-/query-issue, here is the response of the submission-read-request, and the dataGrid does not contain an array (as it should) but is actually an object:
![image](https://user-images.githubusercontent.com/1181905/50660895-9d9d6500-0fa1-11e9-860c-488bc05f84d6.png)

When I remove the flat for `save as reference`, it looks fine:
![image](https://user-images.githubusercontent.com/1181905/50660951-ca517c80-0fa1-11e9-8193-d144793f9e6f.png)

Tested with version: 1.37.5
Browser: Chrome (71)
OS: Windows 10

**Comment by travist** [comment]
Is the UI that you are showing here the Open Source form manager application? This may be fixed with the latest version of our builder/renderer and we just need to build a new version of the manager application. We will add that to our list.

**Comment by travist** [comment]
Ok thanks. We probably need to run a new build of that application with the latest versions of our renderer. It may take a while to get this done, so if you want a sooner response, then feel free to create a pull request at the following library since this is the portal used in open source. https://github.com/formio/formio-app-formio

**Comment by randallknutson** [comment]
The dependency is actually ng-formio and ng-form-builder in bower.json. If you update to the latest 3.x versions it should work properly.

**Comment by travist** [comment]
It should probably not get updated to 3.x since that implements the core builder and renderer, and I am not sure if that is compatible with the formio/formio-app-formio application. I would make it the latest version of 2.x.
