### ISSUE TITLE
Load all forms

### ISSUE THREAD

**Issue by laemmlem** [formio/formio#724]
Hi there,

i was trying to load a list of all available forms, to provide access over a Nav-Bar on angular 6. I found following function: FormManagerIndexComponent.service.loadForms(). It responded an zoneawarepromise which included my Forms. Is this the correct way, or how should i get a list of the forms?

Greeetz
Michael

**Comment by randallknutson** [comment]
Sounds like you are using the angular-formio module. With that module you can do it that way. You can also use a generic approach with the Formio library from formio.js with something like this:

```
const formio = new Formio('https://myproject.form.io');
formio.loadForms({type: 'forms'}).then(function(forms) {});

**Comment by laemmlem** [comment]
Correct, thats Angular Module. Wrong issue board :( Well looks like the generic approach is more straightforward.
