### ISSUE TITLE
Minio Intergration

### ISSUE THREAD

**Issue by multinerd** [formio/formio#725]
Using the open source version, how would I implement minio for file storage?

In the file component, i set storage to `S3` but i dont see any options to set anything else, like bucket, key, or even the S3 storage endpoint (https://s3.amazonaws.com/{bucket_name}/).

It would appear i would have to create a custom provider in the `formio.js` library.

Is that the correct path or is there some way to configure s3 that i'm just not seeing.

**Comment by randallknutson** [comment]
S3 support is only in the hosted or enterprise server. This is because there is a callback that takes the file information and signs the request to aws s3 (or minio). You are welcome to re-create the endpoint in the open source version or you can use our commercial systems.
