### ISSUE TITLE
angular-formio-node-mysql connection

### ISSUE THREAD

**Issue by Haris-584** [formio/formio#727]
how i connect formio with backend and MySQL , i start 0 to mean app there MongoDB connection requires, I use formio starter kit there not database exists, i use  MySQL-connection but didn't understand, my project is to fill form store data in a database , form.io form backend should be node and database MySQL , i am confused to I connect all these, need help

**Comment by travist** [comment]
Form.io requires that you use MongoDB as your main backend database, but you can connect to a SQL database using the SQL Query action (in open source server), or in our Enterprise we have a SQL connector that does allow more advanced SQL connection between a form and the database.

**Comment by ZenMasterJacob20011** [comment]
Thank you for taking the time to post this issue. Our Enterprise offering includes a powerful SQL Connector tool, let us know if you are interested in hearing more about this offering by sending an email to sales@form.io.
