### ISSUE TITLE
Save Action Button  not working / Disabled 

### ISSUE THREAD

**Issue by A-Pradeep** [formio/formio#728]
@travist  Hi , the `Save Action` is not working to any action of the forms.
![save action](https://user-images.githubusercontent.com/37439293/51927018-9d657d80-2418-11e9-923c-cb925e5bfda8.png)

The Button is disabled from the click.  Regardless to any form of any action.

The Picture is from the newly installed form.IO Open source.

**Comment by travist** [comment]
OK, we will investigate.

**Comment by travist** [comment]
Turns out this is caused by this issue with latest version of Angular 1.7.6

https://github.com/angular/angular.js/issues/16814

Apparently they will have an update this week, but in the meantime we will pin to 1.7.5

**Comment by ZenMasterJacob20011** [comment]
Thank you for taking the time to post this issue. The new Angular update has resolved this issue.
