### ISSUE TITLE
Edit grid - option cancel

### ISSUE THREAD

**Issue by bigjorjao** [formio/formio#729]
The element Editgrid have um button to save.
There is a way to set another button to cancel (not save)
It can be useful when the user only wants to consult what he has written or has been wrong about something and does not want to record.
Is possible?

**Comment by travist** [comment]
Yes, this can be done by setting the Cancel button text.

![](https://monosnap.com/file/6dHXduljwOSUAuz8GJ19TQYUpKBYhd)

**Comment by bigjorjao** [comment]
thanks a lot....
