### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by kmgilbert100** [formio/formio#73]
Is this tested in node 5?

**Comment by travist** [comment]
I briefly tested it in node 5 when it first came out and ran into some problems with dependent libraries. I have not tested since, but it is worth a shot.

For now, we recommend using node 4.

**Comment by kmgilbert100** [comment]
Great just wondering, I wouldn't of recommended relying on Node 5 yet even though I belie its on a stable release now?

**Comment by kmgilbert100** [comment]
I generally always use Node 5 to develop but all production environments are running 4 / 0.12*

**Comment by zackurben** [comment]
@kmgilbert100 just a heads up, this is developed around the LTS version (currently 4.4.0) rather than the latest stable (currently 5.9.0).

**Comment by kmgilbert100** [comment]
Yup not disagreeing.
