### ISSUE TITLE
CSV Export Incorrect for 2 records

### ISSUE THREAD

**Issue by bacon1986** [formio/formio#730]
**Expected Result:** All records are included in the CSV export.

**Actual Result:** When there are only 2 records, only the 2nd record is included in the CSV export.

**Reproduction Steps:**
1. Setup a new resource with just one text field.
2. Enter a data record with the field set to "1"
3. Export to CSV - The one data record is included in the export
4. Enter another data record with the field set to "2"
5. Export to CSV - Only the newly added data record with the field set to "2" is included in the export.
6. Enter another data record with the field set to "3"
7. Export to CSV - All three data records are included in the export,

**Files:**
- [export1.csv.txt](https://github.com/formio/formio/files/2821305/export1.csv.txt)
- [export2.csv.txt](https://github.com/formio/formio/files/2821306/export2.csv.txt)
- [export3.csv.txt](https://github.com/formio/formio/files/2821307/export3.csv.txt)

**Environment:**
Commit 5b28259 in docker running on Ubuntu

**Comment by travist** [comment]
We will add this to our planning to investigate. Seems like it may be a bug with the CSV parser.
