### ISSUE TITLE
Use form.io without Node.js Server

### ISSUE THREAD

**Issue by laemmlem** [formio/formio#732]
Hi there!

My team and me are wondering if it would be possible to use form.io without node.js as server backend. e.g. Web App in Front and simple Backend Server on Spring Boot. So we would create a form with builder. Post it to an own SB-server and save it in a DB whatever we like. Create an endpoint that ships json forms...
For Posting data we think we have to provide another Endpoint?

We would handle Auth and data viewing on our own. 
U think this would be possible?

**Comment by kaleguy** [comment]
This might help:
https://github.com/kaleguy/formiojs-client

**Comment by laemmlem** [comment]
Thats great! We will try it this way

**Comment by almereyda** [comment]
[SurveyJS](https://surveyjs.io) is explicitly built that way.

**Comment by randallknutson** [comment]
You can see an example of how to do this here: http://formio.github.io/formio.js/app/examples/customendpoint.html

**Comment by dgerbe** [comment]
> This is exactly how formio.js is designed. Our Renderer and Builder allow you to create your own form jsons and render them wherever you want. You can store and load those JSON form definitions wherever you want including the submission data. Here is an example of one way to capture the submission request and use your own endpoints. http://formio.github.io/formio.js/app/examples/customendpoint.html

@randallknutson  Is there any easy way to implement validation of the submission data on the backend, other than writing a custom validator? My backend is spring boot.

**Comment by brendanbond** [comment]
@dgerbe I believe you'll need to roll your own if you need validation beyond what the formio.js renderer provides on the client (for instance, the Form.io API server installs a copy of the formio.js renderer in the node environment for just this purpose)
