### ISSUE TITLE
Datagrid and hide 'Add another' button

### ISSUE THREAD

**Issue by aminmc** [formio/formio#734]
Hello

We have a data grid that is populated by data and was wondering if there was a way to hide the 'Add another' button? Items cannot be added or removed from the collection.

Any help would be appreciated.

Thanks

**Comment by travist** [comment]
This can be done by setting the Max number to the same as the Min number within the validation settings. I believe for now this will only work within the "core" renderer so the default manager application that sits on top of this project may not show it working correctly, but it will work if you embed the form within your project using the "core" renderer @ https://github.com/formio/formio.js
