### ISSUE TITLE
displaying image in data grid

### ISSUE THREAD

**Issue by aminmc** [formio/formio#735]
Hello,

Is it possible to display an image in a data grid? we have a base64 encoded image and need to display it in the grid. Is this possible?

Thanks

**Comment by travist** [comment]
You can with the HTML Element component. Let us know if that works for your use case.

**Comment by aminmc** [comment]
Thanks @travist I'm not sure i quite understand. I create an html element of type and add attribute 'src' but what needs to go in the value? Will it automatically be set?

**Comment by travist** [comment]
The url to the image you wish to add should go in the value of the "src". You will, therefore, need to host this image somewhere but that should work.

**Comment by aminmc** [comment]
Hi @travist this image inside the data collection is a base64 encoded string.  How do i reference the string inside the value attribute of src for that component?

**Comment by randallknutson** [comment]
Set the src attribute of the html component to {{ data.whereverTheDataIs }}

**Comment by aminmc** [comment]
@randallknutson I'm afraid we've tried {{data.picture}} and {{picture}} but no luck. It renders the src value as 'image...{{picture}'. Our data structure for the grid looks like this:
```
 [ objectKey: {
   picture: base64encoded string
}]
```
Just not sure how you reference the picture that's inside the collection

**Comment by randallknutson** [comment]
As travis mentioned, you can use an html component. Inside that html component set the HTML tag to "img", then set an attribute with "src" and value of "{{data.objectKey.picture}}".

**Comment by pixie79** [comment]
![screenshot 2019-02-27 at 14 59 18](https://user-images.githubusercontent.com/534416/53499561-80b47800-3aa0-11e9-8308-c35fbb61efa0.png)
![screenshot 2019-02-27 at 15 00 17](https://user-images.githubusercontent.com/534416/53499578-8447ff00-3aa0-11e9-9b0e-94ed3e2b6a44.png)

Hi Randall,

As you can see from the attachements this is what we have done however, it seems to be failing to translate the image into the form. Instead it is trying to load it as the URL.

The content of the src attribute is : data:image/png;base64,{{data.XXXX.picture}}
(we have also tried without "data:image/png;base64")

Any other ideas?
Thanks

Mark

**Comment by randallknutson** [comment]
Can you look at what is inside data.XXXX.picture? You can do this by looking at the loaded submission in the network tab. If the data looks correct then this should work. Otherwise it may help understand what you need to do to get the src to work.

**Comment by pixie79** [comment]
The image is in the submission data, I think part of the problem is that this is part of a datagrid. 
So we have multiple rows, each row with an image. All the other data is appearing correctly it is just the base64 image (not a link to the image) that is failing to show.

**Comment by randallknutson** [comment]
Ah, if it is in a datagrid, use "row" instead of "data". Row will refer to the current row.
