### ISSUE TITLE
this.auth.is.administrator or any role is undefined in component but works in html with boolean value

### ISSUE THREAD

**Issue by mayurmamoria** [formio/formio#742]
I want to show different home pages to different roles. So, after login, we get FormioAuthService object in which there are many attributes. One is `this.formioAuthService.is` which gives the access name in which data is saved like I have given resource to access by administrator then I am getting after login `this.formioAuthService.is.administrator`. But it gives undefined when consoled. And also if used in .html in some tag then results boolean value.

**Comment by A-Pradeep** [comment]
@mayurmamoria
 ```
<div *ngIf="auth.is.administrator">
<h1> Admin Logged IN </h1>
</div>
```

The name should be the "camel-case" version of your role name, so if you have a Manager role, it would look something like this.


```
<div *ngIf="auth.is.manager">
<h1> Manager Logged IN </h1>
</div>
```

based on this you can show / display based on the User Role. 

Hope this helps.

**Comment by mayurmamoria** [comment]
> @mayurmamoria
> 
> ```
> <div *ngIf="auth.is.administrator">
> <h1> Admin Logged IN </h1>
> </div>
> ```
> The name should be the "camel-case" version of your role name, so if you have a Manager role, it would look something like this.
> 
> ```
> <div *ngIf="auth.is.manager">
> <h1> Manager Logged IN </h1>
> </div>
> ```
> based on this you can show / display based on the User Role.
> [formio/angular-app-starterkit#13 (comment)](https://github.com/formio/angular-app-starterkit/issues/13#issuecomment-458186427)
> Hope this helps.

@A-Pradeep 
Yes, I agree. I am getting this in .html file. But suppose I want to have this in my angular-2 component.ts file say `console.log(this.auth.is.administrator)` then it gives undefined.

**Comment by travist** [comment]
Need to make sure that you also use the ```this.auth.ready``` promise to determine when the user is ready before writing code that checks their roles.

```
this.auth.ready.then(() => {
  if (this.auth.is.manager) {
    console.log('The user is a manager.');
  }
});
```
