### ISSUE TITLE
Upload bulk data to form.io

### ISSUE THREAD

**Issue by mayurmamoria** [formio/formio#743]
For migration, is there a simple way to upload data to Form.io other than a cli or api submission? By a simple way, I mean, could we simply use an excel or csv to upload via Form.io interface?

**Comment by randallknutson** [comment]
We don't currently support any bulk upload mechanisms. The best way to do this to iterate over each row and call the API to create the submission. We have a script that makes it easier to do this if you want to try it. https://github.com/formio/formio-cli#migrate

In addition, if you have access to the database, you can directly import to the database but this is not the recommended process.

**Comment by mayurmamoria** [comment]
Closing
