### ISSUE TITLE
Documentation On Mail Transport Configuration

### ISSUE THREAD

**Issue by lnorton89** [formio/formio#751]
I'm not seeing anywhere that details where to configure mail transport for self-hosted formio. There are no project settings in the web app for self-hosted and the configuration template has no clues on how to configure it (`client/dist/config.template.js`).

**Comment by almereyda** [comment]
It seems you can use an `EMAIL_OVERRIDE` environment variable which takes a Nodemailer `options` object.

Found via #591

**Comment by travist** [comment]
Thanks for your help @almereyda!

You are right that you can use EMAIL_OVERRIDE, but this is normally used within a test environment where you want to point all your emails to a separate provider, such as MailTrap. You can configure the email settings within the ```config/default.json``` file as well.

**Comment by ZenMasterJacob20011** [comment]
Thank you for taking the time to post this issue. Due to the amount of time this issue has stayed up, we are assuming that this is resolved. If you are still having this issue please re-open
