### ISSUE TITLE
Validation error label is not correct

### ISSUE THREAD

**Issue by krixerx** [formio/formio#757]
When validating the data in formio-server, the feedback is without correct label:

  "details": [
    {
      "type": "number.base",
      "path": [
        "t40h0ob96x3a"
      ],
      "context": {
        "key": "t40h0ob96x3a",
        "label": "t40h0ob96x3a",
        "value": ""
      },
      "message": "\"t40h0ob96x3a\" must be a number"
    },
    {
      "type": "number.base",
      "path": [
        "tl51p74uwu5g"
      ],
      "context": {
        "key": "tl51p74uwu5g",
        "label": "tl51p74uwu5g",
        "value": ""
      },
      "message": "\"tl51p74uwu5g\" must be a number"
    }
  ]

Could we get real label value?
Thanx!

**Comment by wag110894** [comment]
Thank you for reaching out!
We have created a ticket (FOR-2173) and have added this to our planning document to be discussed in our planning session on Monday.

We will let you know the priority level of this item then.

Thanks!

**Comment by wag110894** [comment]
Hello,

Thank you for your patience regarding this issue. After discussion with our developers, we view this issue as a medium priority. We do offer a chance to expedite this issue. Our developers have estimate this fix at 8 hours. Please let us know if you are interested and I can send you a formal quote.

Please let us know if you have any further questions or concerns. 

Thanks!

**Comment by krixerx** [comment]
Yes please send us a formal quote.

**Comment by wag110894** [comment]
Please send an email at support@form.io so we can send you the formal quote.  

Thanks!

**Comment by wag110894** [comment]
Hello Krixerx,

Just reaching out to see if you were still interested in the formal quote. Please provide an email that we can send the formal quote if you are.

Thanks!
