### ISSUE TITLE
docker-compose, viewing json for form

### ISSUE THREAD

**Issue by nekapoor** [formio/formio#773]
hey all! thanks for this amazing open source product. 

I used docker-compose to get setup. I logged in and I created a form. 

But in order to setup some of the conditional logic, I'd like to be able to see the JSON that this form generates. I don't see anywhere where I can do that. Am I missing something?

**Comment by travist** [comment]
Just remove the ```/#/``` from the url without any ```edit``` or ```view```. That is the API of the form.
