### ISSUE TITLE
DocumentDB instead of Mongo

### ISSUE THREAD

**Issue by pixie79** [formio/formio#776]
Can we connect the API server with DocumentDB (with TLS and Auth) instead of using Mongo. This would be more secure for us and also a lot more resilient.

I know it does say on AWS that it is Mongo 3.6 compliant the bigger issue i guess would be the connection. https://aws.amazon.com/documentdb/features/

**Comment by travist** [comment]
Yes, DocumentDB is supported and we have productions customers using Form.io + DocumentDB. Here is some examples.

https://help.form.io/tutorials/deployment/aws/#aws-db
