### ISSUE TITLE
Other persistence models available for form.io 

### ISSUE THREAD

**Issue by chanchaimwpp** [formio/formio#777]
Does form.io support storage/persistence only to NoSQL databases, or does it support storage of form schema and data to SQL databases?

**Comment by travist** [comment]
The commercial platform does support a SQL connector so that you can attach the API to a SQL database record of submissions.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
