### ISSUE TITLE
s3 and stripe in docker-compose

### ISSUE THREAD

**Issue by nekapoor** [formio/formio#778]
I'm using docker locally to get setup and had a couple of questions: 

1. When using s3, I saw these instructions - https://help.form.io/integrations/filestorage/#s3- but there's no where to input any of the s3 keys in local setup. Is there a way to do this or is this only available on the hosted form.io service? 

2. Locally, there isn't an option to include a Stripe payment component. How can I add that component other than manually editing the JSON?

**Comment by randallknutson** [comment]
Are you using the open source version of our server? Our enterprise server has a place in the project settings to enter the s3 information.

**Comment by nekapoor** [comment]
@randallknutson sorry for the delay in getting back to you. We aren't using the enterprise server. Is it not possible to configure this if we are just using the docker setup? Thanks!

**Comment by randallknutson** [comment]
The s3 functionality is only in our enterprise server as the file component is a premium component.

**Comment by mauricios** [comment]
@nekapoor Did you find a solution to support S3 file storage in the open source version? is there a plugin from the community for S3 support?

**Comment by nekapoor** [comment]
@mauricios unfortunately, I didn't find any solution here. Sorry :(

**Comment by mauricios** [comment]
@nekapoor if you are in AWS and want staless installation of Form.io you can use EFS for shared storage.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
