### ISSUE TITLE
Strange Html Element behavior in submission

### ISSUE THREAD

**Issue by mermerkaya** [formio/formio#779]
I am trying to use html element inside the form to create some html content. however html element dont read submission data. interestingly if i put html element inside datagrid, it read submission data. 

Here is the js fiddle 
https://jsfiddle.net/n1eb7zp8/

![image](https://user-images.githubusercontent.com/1280721/57567766-d4b7d300-73e6-11e9-8e04-d4bfca51c0f1.png)

**Comment by wag110894** [comment]
Hello,
 
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
