### ISSUE TITLE
Home page bug

### ISSUE THREAD

**Issue by HenryDev** [formio/formio#78]
I donno if it's just me but the "Watch video" and "Get started" buttons don't work on the home page.

**Comment by travist** [comment]
I just tried it and it seems to be working for me. What browser are you using?

**Comment by HenryDev** [comment]
Google Chrome Version 49.0.2623.110 (64-bit)
Resolution 2560 x 1440
It seems that the horizontal tree picture right below the text is getting clicked on instead of the buttons.

**Comment by travist** [comment]
This has been fixed.  Thanks.
