### ISSUE TITLE
Errors in submission query filters

### ISSUE THREAD

**Issue by dirtysoap9** [formio/formio#780]
Hi,

It seems there is a problem with the api when you try to get search results using some query filters described here: 

https://documenter.getpostman.com/view/684631/formio-api/2Jvuks?version=latest#1f207caa-9d04-3e81-2973-e4bf82ee5190

The api simply returns nothing when using the "in", "nin" and "regex" filters on **number** fields. For example: `/submission?data.number__in=111` , and returns nothing and spins until connection timeout. An error is logged in the process mentioning an uncaught promise rejection:

`(node:68137) UnhandledPromiseRejectionWarning: Error: Callback was already called.
    at /dev/formio/node_modules/async/dist/async.js:966:32
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:68137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:68137) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Is it a known issue?

**Comment by wag110894** [comment]
Hello,
 
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by wag110894** [comment]
Hello,
After discussion with the team, we have estimated this fix at 4 hours to expedite. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
