### ISSUE TITLE
docker-compose up fails with "ERROR: unsatisfiable constraints"

### ISSUE THREAD

**Issue by vandrijevik** [formio/formio#783]
When I follow [the instructions for Run with Docker Compose](https://github.com/formio/formio#run-with-docker-compose), the command `docker-compose up` fails with the following error:

```
$ docker-compose up
Creating network "formio-1460_default" with the default driver
Creating volume "formio-1460_mdb-data" with default driver
Building formio
Step 1/11 : FROM node:lts-alpine
 ---> 56bc3a1ed035
Step 2/11 : WORKDIR /app
 ---> Using cache
 ---> 06986813e392
Step 3/11 : RUN apk update &&     apk upgrade &&     apk add python=2.7.15-r3 &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0
 ---> Running in 918180a1e852
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
v3.9.4-1-g3c20033f75 [http://dl-cdn.alpinelinux.org/alpine/v3.9/main]
v3.9.4-2-g58b26b850f [http://dl-cdn.alpinelinux.org/alpine/v3.9/community]
OK: 9766 distinct packages available
OK: 7 MiB in 16 packages
ERROR: unsatisfiable constraints:
  python2-2.7.16-r1:
    breaks: world[python=2.7.15-r3]
ERROR: Service 'formio' failed to build: The command '/bin/sh -c apk update &&     apk upgrade &&     apk add python=2.7.15-r3 &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0' returned a non-zero code: 1
```

This happens on both the `master` branch, and the latest release v1.46.0.

I believe the problems is that the Dockerfile [tries to add a very specific version of python](https://github.com/formio/formio/blob/master/Dockerfile#L14), but after an `apk update`, there is no guarantee that that exact version number exists. In this case, the python version available, `2.7.16-r1` is newer than the demanded version `2.7.15-r3`.

**Comment by qodrinzo** [comment]
It occurs also for this version, because of new python version 2.7.17

**Comment by Xstoudi** [comment]
Same problem occur again because of python 2 EOL.

**Comment by srinathganesh1** [comment]
I did not face a problem couple of months back, but fresh builds are failing with this error

**Comment by travist** [comment]
@srinathganesh1 are you able to submit a pull request to this repo to resolve the issue?

**Comment by sascha-schieferdecker** [comment]
I cannot confirm #899 is a fix to this issue, I had to set python 2.7.16-r2 to succeed in building the master branch:

```bash
# "bcrypt" requires python/make/g++, all must be installed in alpine
# (note: using pinned versions to ensure immutable build environment)
RUN apk update && \
    apk upgrade && \
    apk add python=2.7.16-r2 && \
    apk add make=4.2.1-r2 && \
    apk add g++=8.3.0-r0
```

**Comment by srinathganesh1** [comment]
> @srinathganesh1 are you able to submit a pull request to this repo to resolve the issue?
> 
> It looks like this pull request resolves the issue. #899 Will you please confirm?

I will first add more clarity on the workaround, I dont consider it to be production grade (because I removed version dependencies and am getting the latest package).

IF you are fine with it, I will surely raise a PR

**Comment by rg2609** [comment]
`Docker build` common for building the image is giving the same error

**Comment by terryhowelljr** [comment]
I just changed the Docker file python to r2 and it worked.  

`RUN apk update && \
    apk upgrade && \
    apk add python=**2.7.16-r2** && \
    apk add make=4.2.1-r2 && \
    apk add g++=8.3.0-r0`
