### ISSUE TITLE
user login issue after upgrade through webinterface

### ISSUE THREAD

**Issue by gismomtl** [formio/formio#786]
Hi,

I've an existing 1.41 Formio version.
After upgrading to 1.46 based on clean github version and applying custom configuration (mongo, root_password and root_email):
- upgrade is working fine
- serveur listening on 3001 fine
- form is still Anonymous

access through the API to get UserLogin form isn't working ({{formioUrl}}/user/login)

however:
- accessing in incognito mode the weburl (formio.local:3001/user/login?live=1) is displaying banner but form is nothing: "unauthorized" , and I find no cookie and only 1 item (formioAppRole) in LocalStorage
- on remaining chrome session (which was initiated on 1.41 version) is still working and I can navigate to ressources, form, submission... and I see the cookies

on a clean mongo/formio the issue doesnt exist

**Comment by gismomtl** [comment]
just to clarify, issue occurs when I try to access %formiourl%/#/auth/login.
and access & submissionaccess is linked to the right OID Anonymous for userlogin form.

any clue? anyone is facing the same issue?

**Comment by gismomtl** [comment]
if I switch back the code without altering Mongo content, access is working back.. so there is no DB issue..

**Comment by travist** [comment]
What are the "access" configurations for the form that is giving you "Anonymous"? It may be possible that the "Read Form Definition" access is not set correctly.

**Comment by gismomtl** [comment]
issue was due to a custom role added to the 3 existing. and the one added was with field "default" set to "true". issue was not occurring in previous version update.
setting back the extra role to "default=false" solved the issue
