### ISSUE TITLE
Is formio scalable for large enterprises

### ISSUE THREAD

**Issue by megarg** [formio/formio#787]
Is anyone using formio for scalable applications in production?

**Comment by randallknutson** [comment]
We have many enterprise level customers using our platform in production. If you are looking at that level though we do recommend contacting support about our enterprise platform and getting on a support plan.

**Comment by megarg** [comment]
Can you provide some references to the scale it is able to handle ? What
volume of users / transactions it is able to handle at a client or if there
is any performance test done?

**Comment by megarg** [comment]
I am currently in evaluation phase. If we choose formio, then it would make sense to buy the support plan. Though, I am not able to fund out if formio will scale? Any insights!!

**Comment by randallknutson** [comment]
Let me put you in touch with our sales staff who can get you some references. Could you email denise@form.io?

**Comment by megarg** [comment]
Hello Denise
I am writing this email as per reference from Randall (see below email
trail). I am evaluating formio and want to understand its capability for
scaling for large volumes (for enterprise customers). I am not looking to
talk to any of your customers yet but want to know if any of your customers
are using it for high volume and some details of the volume supported.

This will help me evaluate if we should select Formio to move forward.
Please let me know if you have any questions. Let me know if it is easier
to talk and I can provide my phone number.

regards
-Ashish
