### ISSUE TITLE
How to edit a calculated text field and change the value ? (prevent refresing on data change)

### ISSUE THREAD

**Issue by gag29** [formio/formio#789]
@travist , can you help me out with this , 
we have a textfield --->text 1  , which takes an  input  ,
we also have one more textfield--->text 2 , whose calculated value= data['text1'] ,
So if text 1 contains ------>Form.io
text 2 value will be calculated as --->Form.io
is their any way that i can edit text 2 field ?

**Comment by gag29** [comment]
Is their any way that we can manually override the calculated value ?

**Comment by randallknutson** [comment]
Yes, if you use the beta.form.io portal, you can set "Allow Manual Override of Calculated Value" so that users can modify the calculated value.

**Comment by gag29** [comment]
Thank you @randallknutson

**Comment by gag29** [comment]
is their any way we can do this in old version of form.io , "allowCalculateOverride" doesn't work in older version of form.io.

**Comment by randallknutson** [comment]
There is not. This is one of the features in our newer version of the renderer.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
