### ISSUE TITLE
Slow Performance of the browser due to the large multiple forms[BUG] 

### ISSUE THREAD

**Issue by akhilesh-sharma168** [formio/formio#790]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 2.0.0-rc.3
- Frontend framework: Angular 6
- Browser: Chrome 
- Browser version: 74

## Steps to Reproduce
1. Create a form having more than 15 pages with scrollable controls 
2. Move to the last page of the form. Click the submit button.
3. Observe the behavior of the next form. Browser throws an error.

## Observed behavior: error is being thrown and slow performance of the form followed.

I expect this is due to the below events which might get triggered during the form initialization.

Box metrics
elem.offsetLeft, elem.offsetTop, elem.offsetWidth, elem.offsetHeight, elem.offsetParent
elem.clientLeft, elem.clientTop, elem.clientWidth, elem.clientHeight
elem.getClientRects(), elem.getBoundingClientRect()
Scroll stuff
elem.scrollBy(), elem.scrollTo()
elem.scrollIntoView(), elem.scrollIntoViewIfNeeded()
elem.scrollWidth, elem.scrollHeight
elem.scrollLeft, elem.scrollTop also, setting them
Focus
elem.focus() can trigger a double forced layout (source)
Also…
elem.computedRole, elem.computedName
elem.innerText (source)
getComputedStyle
window.getComputedStyle() will typically force style recalc (source).

Please look into the issue,
 if you need any other data will provide it.
![Screen Shot 2019-05-30 at 11 26 23 AM](https://user-images.githubusercontent.com/45589364/59011257-9f6d9c00-8851-11e9-8ff3-102ef6dfc406.png)

**Comment by dVp007** [comment]
Any updates in this issue?

**Comment by ccontour** [comment]
Can you attach an exported form that our test team can use to replicate your issue? That will help us make sure this gets resolved more quickly. You can also send it into support and link this issue if you would like to keep it private

**Comment by ccontour** [comment]
Closing issue, this is from 2019 and is against version 2 of formio.js which is no longer supported
