### ISSUE TITLE
Formio.setBaseUrl not defined

### ISSUE THREAD

**Issue by adamhrosenberg** [formio/formio#792]
Hello! While installing form.io for us on our app we ran into this issue.
setBaseUrl is not found in Formio.
While debugging the Formio object contained a 'default' object which contained all of the functions. 

 It was fixed by us doing:
`Formio = Formio.Formio` in the auth-service.js. But i'd rather not make changes within the node_modules of our project, does this sound familiar at all? Or maybe some sort of installation error? 

Thanks.

**Comment by travist** [comment]
If you are using ```require``` to include Formio into your application, then you need to do the following.

```js
const Formio = require('formiojs/Formio').default;
```

**Comment by reggiejones7** [comment]
yes, `const Formio = require('formiojs/Formio').default;` worked for us temporarily. however, we had to make the change in `node_modules\ng2-formio\src\modules\auth\auth.service.js` where the error was being thrown in the constructor. this didn't seem like a long term solution.

**Comment by reggiejones7** [comment]
After scrapping things and starting over it appears we no longer run into this problem. not sure what happened. please close. thanks travis!
