### ISSUE TITLE
[BUG] Unable to drag component in builder

### ISSUE THREAD

**Issue by aminmc** [formio/formio#794]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [] Local deployment
    - Version: 
- Formio.js version: 4.0.0-beta.50
- Frontend framework: formio-react 4.0.0-beta.31
- Browser: chrome
- Browser version:

## Steps to Reproduce
1. Drag any component onto builder area

## Expected behavior
Component to added
## Observed behavior
Unable to add component to builder

![Screenshot 2019-06-21 at 06 54 40](https://user-images.githubusercontent.com/290639/59900916-7a506000-93f1-11e9-86f5-dc55be9f49b2.png)

![Screenshot 2019-06-21 at 06 51 59](https://user-images.githubusercontent.com/290639/59900884-69075380-93f1-11e9-95b4-27663788b288.png)

**Comment by randallknutson** [comment]
This should be fixed in the latest version (beta.51)

**Comment by aminmc** [comment]
@randallknutson I'm afraid seeing the below issue on trying to save a component:

<img width="1305" alt="Screenshot 2019-06-21 at 16 06 45" src="https://user-images.githubusercontent.com/290639/59932255-b1009780-943e-11e9-9c4e-18f756835bdd.png">

This is happening when dropping a simple component and then clicking on the save button.

**Comment by randallknutson** [comment]
That issue is in the dragula library. Is there a new version or something causing the issue?

**Comment by aminmc** [comment]
Not changed anything except for the formio lib. Will take a look

**Comment by aminmc** [comment]
@randallknutson Sorry didn't release I created this issue in the wrong project. Do you want me to move this to Formio.js?  The version of dragula is 3.7.2 and looks like it hasn't changed. I can only assume that some other change is causing this.

**Comment by aminmc** [comment]
@randallknutson I'm closing this in here. Will raise an issue in react-formio. Seems as though bumping react-formio version is causing this issue.
