### ISSUE TITLE
Textarea visual editor not working in IE10

### ISSUE THREAD

**Issue by Jefreesujit** [formio/formio#796]
Hi, I m using formio's textarea editor in my application. There is a requirement for us to support IE10 and the editor is not working in that. While searching i figured it out that both visual editors that formio provides, `Quill `and `CKEditor 5` doesnt support IE10 as of now.  Seems like `CKEditor 4` supports IE10, but formio doesnt use it anymore.

Is there any way i can use someother editor/version as part of formio?  I have already hooked up my validation within formio, so it would be much easier if i could someother editor in place of them.

**Comment by randallknutson** [comment]
I believe older versions of our renderer supported CKEditor 4. You can try that out. In addition, you can extend the textarea component to implement CKEditor 4. This would require some customization and programming. If you'd like some help with that you can contact our support team at support@form.io and we can get you some professional services support.

**Comment by Jefreesujit** [comment]
@randallknutson thanks for responding. If you can let me know which version of Formio supports CKEditor 4 that would be of great help.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
