### ISSUE TITLE
Issue :: Custom css classes are not reflecting on Form Creation

### ISSUE THREAD

**Issue by ssurajita** [formio/formio#801]
## Environment

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:3.16.2
- Frontend framework: Angular
- Browser: Chrome
- Browser version:  75.0.3770.100

## Steps to Reproduce
1. Create Form - Drag few items to create a form. For each item on drag specify css classes in the popup component configuration window. Now save the Form.
2. Load the Form.
3. Now do inspect element on the components you have added custom css classes to check if the classes are added to elements or not.

## Expected behavior
Custom css classes should appear on inspect element when populating/loading the forms after creation.

## Observed behavior
Custom css classes are not visible on developer console for the configured components

## Example
While creating forms/resources we are dragging and dropping items from form-builder. For each item on drag , component configuration pop up comes which allows us to provide all required details. We are trying to add classes to custom css field in the configuration. Once I save the form ideally the newly added custom classes should save with the json.  And on next time the same form should load these css on developer console. But we cant see any  css classes added to any of the components.

Also need help how to pass theme to the json on form creation. With the launch URL theme works, but is there any way to do it using json? thanks!

**Comment by gag29** [comment]
How can i add a event listner to a component ?

**Comment by gag29** [comment]
"customClass": "form-group has-error",



i want to apply the above class only when a certain value is entered in the field


 {
                                    "autofocus": false,
                                    "input": true,
                                    "tableView": true,
                                    "inputType": "text",
                                    "inputMask": "",
                                    "label": "Temperature",
                                    "key": "page1Temperature",
                                    "placeholder": "",
                                    "prefix": "",
                                    "suffix": "",
                                    "multiple": false,
                                    "defaultValue": "",
                                    "protected": false,
                                    "unique": false,
                                    "persistent": true,
                                    "hidden": false,
                                    "clearOnHide": true,
                                    "spellcheck": true,
                                    "validate": {
                                        "required": false,
                                        "minLength": "",
                                        "maxLength": "",
                                        "pattern": "",
                                        "custom": "",
                                        "customPrivate": false
                                    },
                                    "conditional": {
                                        "show": "",
                                        "when": null,
                                        "eq": ""
                                    },
                                    "type": "textfield",
                                    "labelPosition": "top",
                                    "inputFormat": "plain",
                                    "tags": [],
                                    "properties": {
                                        "color": "#f4bbbb",
                                        "background": "#f4bbbb"
                                    },
                                  
                                    "customClass": "form-group has-error",    // apply this only on input >5
                                    "errorLabel": "please enter",
                                    "isNew": false
                                },

**Comment by aiwebb** [comment]
@ssurajita, do you have an example form JSON and CSS stylesheet that you could supply?

**Comment by ssurajita** [comment]
@aiwebb 
I am saving the form json to database and fetching it later to load the form in UI. This is the JSON.

{"_id":"5d20512d70f93571db494e93","type":"form","tags":[],"owner":"5ccc12fa91c60773250ba608","components":[{"input":true,"tableView":true,"label":"Text Field","key":"textField2","defaultValue":"","validate":{"required":false},"conditional":{"show":"","when":"","eq":null},"type":"textfield"},{"input":true,"tableView":true,"label":"Submit","key":"submit","type":"button","disableOnInvalid":true,"theme":"primary"}],"revisions":"","_vid":0,"title":"form2","name":"form2","path":"form2","submissionAccess":[],"access":[{"roles":["5d1eee769cf7199952a0fe5e","5d1eee769cf719242fa0fe5f","5d1eee769cf7193c84a0fe60"],"type":"read_all"}],"machineName":"tmihamherqpcgjh:form2","project":"5d1eee769cf71972c2a0fe5d","created":"2019-07-06T07:43:41.474Z","modified":"2019-07-06T07:43:41.477Z"}


And using above json to load the form I am using formio tag, here formSelected is the above JSON.
 <formio [form] = "formSelected" ></formio>

**Comment by ssurajita** [comment]
While saving the form only custom classes are not getting added to the published JSON.

**Comment by wag110894** [comment]
Thanks for sending over the JSON.
We are still unable to replicate this issue. Try upgrading to the latest version (3.23.0), and see if the issue still occurs.

Thanks.

**Comment by ssurajita** [comment]
@aiwebb , @wag110894 

Thanks! Now I am able to add custom classes to the individual components. I have added customClass property to the Component definition.

But theming is still not working. Any bootswatch theme seems to work from form launch url when sent as query param. ex :
https://formview.io/#/zmkvudcietfmxch/form3?header=1&**theme=cosmo**


But I wanted to pass theme to json attribute while loading any form. At component level theme attribute is available but not at form level. Refer below json.
{"_id":"5d308de66bd5237e826ffd7d","type":"form","tags":[],"owner":"7","**components**":[{"input":true,"tableView":true,"label":"Submit","key":"submit2","customClass":"email-test-abc","defaultValue":"false","validate":{"required":false},"conditional":{"show":"","when":"","eq":null},"type":"button",**"theme":"cosmo"**},{"input":true,"tableView":true,"label":"Submit","key":"submit","type":"button","disableOnInvalid":true,"theme":"primary"}],"revisions":"","_vid":0,"title":"Form3","name":"Form3","path":"form3","submissionAccess":[],"access":[{"roles":["5d2f2e0121c26aee2ecee969","5d2f2e0121c26a6d46cee96a","5d2f2e0121c26a006acee96b","5d2f2e02af3dd323744ea9e6"],"type":"read_all"}],"machineName":"zmkvudcietfmxch:Form3","project":"5d2f2e0121c26a7733cee968","created":"2019-07-18T15:19:02.226Z","modified":"2019-07-18T15:19:02.228Z"}




Please help me to fix this issue. Please let me know if yor are clear on my requirements or I need to provide any further details. Thanks in advance!!

**Comment by aiwebb** [comment]
@ssurajita, the [`theme` property is specific to Button components](https://help.form.io/userguide/form-components/#theme) and maps directly to [Bootstrap button classes](https://getbootstrap.com/docs/3.4/css/#buttons).

We don't support specifying the overall display theme in the form JSON, since high-level theming decisions are more the domain of the renderer than the form itself - we try to keep the form JSON as decoupled from display logic as reasonably possible in order to provide lots of flexibility in how they're rendered.

**Comment by ssurajita** [comment]
@aiwebb 

Thanks for the reply. But is there any plan to implement the overall theming of form through JSON in near future? If there is any plan can you please help me with the timeline..

**Comment by randallknutson** [comment]
The reason we don't plan on supporting this is that the form definition is in JSON. The rendering of the form may occur on multiple different webapps, mobile devices and other places. Due to this the rendering could be quite different between them. We don't want to add customizations specific to only one place in the form definition.

What we recommend doing is adding the css class that is added to the component. Inside your website/app you can then target that class with custom css to make the app specific changes you want.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
