### ISSUE TITLE
Issue :: Populating resource dropdown with the list of resources 

### ISSUE THREAD

**Issue by ssurajita** [formio/formio#802]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 3.16.2
- Frontend framework: Angular
- Browser: Chrome
- Browser version: 75.0.3770.100 

## Steps to Reproduce
1. Drag Resource
2. Check resource dropdown for the values if populated in configuration popup options

## Expected behavior
Mapping list of resources to resource dropdown - resource dropdown should auto populate the values on resource creation.

## Observed behavior
I have added list of available resources to the config so on drag of resource it is available in the event object.  But could not map it to the resource dropdown. Added resource list to the builder groups as shown below.
this.formio.builder.resources.groups[resource.name] = group;

## Example
While creating resources we have multiple options - Advance, Layout, Data, Resource Fields and Basic Components. In Advanced we have an option to create resource by dragging resource component. While dragging we get a popup for configuration to provide necessary details. We need to populate the resource dropdown with all the available resources. Binding is not happening. Followed the below link.

https://github.com/formio/formio.js/issues/1103

**Comment by wag110894** [comment]
You can do this by customizing the builder. When you customize the builder you can change the edit forms however you want including adding predefined sets of data. Here is an example of how to customize the builder. http://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by ssurajita** [comment]
@wag110894 
But we already have a resource component which is a having resource dropdown in form-builder advanced section. 
Please let me know if we can populate values to the same.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
