### ISSUE TITLE
How to add customcss only for certain values entered into the field ?

### ISSUE THREAD

**Issue by gag29** [formio/formio#805]
"customClass": "form-group has-error",

i want to apply the above class only when a certain value is entered in the field

{
"autofocus": false,
"input": true,
"tableView": true,
"inputType": "text",
"inputMask": "",
"label": "Temperature",
"key": "page1Temperature",
"placeholder": "",
"prefix": "",
"suffix": "",
"multiple": false,
"defaultValue": "",
"protected": false,
"unique": false,
"persistent": true,
"hidden": false,
"clearOnHide": true,
"spellcheck": true,
"validate": {
"required": false,
"minLength": "",
"maxLength": "",
"pattern": "",
"custom": "",
"customPrivate": false
},
"conditional": {
"show": "",
"when": null,
"eq": ""
},
"type": "textfield",
"labelPosition": "top",
"inputFormat": "plain",
"tags": [],
"properties": {
"color": "#f4bbbb",
"background": "#f4bbbb"
},
    "customClass": "form-group has-error",    // apply this only on input >5
       "errorLabel": "please enter",
        "isNew": false
  },

**Comment by randallknutson** [comment]
You may be able to do this with the Logic tab (only on beta right now). You can set up your trigger and then add a class with an action.

**Comment by gag29** [comment]
Thank you @randallknutson

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
