### ISSUE TITLE
Webhook action doesn't give option to forward headers?

### ISSUE THREAD

**Issue by arvyy** [formio/formio#806]
## Environment

Using local deployment, version 1.46 from https://github.com/formio/formio/archive/v1.46.0.tar.gz 

## Steps to Reproduce
1. Create form
2. Add Webhook action

## Expected behavior
Webhook action form has an option to forward headers as per https://help.form.io/userguide/actions/#forward-headers

## Observed behavior
No such option appears

## Example
![image](https://user-images.githubusercontent.com/15849668/61055876-1111aa80-a3fb-11e9-946a-95d043470601.png)

**Comment by randallknutson** [comment]
Hello Arvyy. This feature is currently implemented in our Enterprise server only. You are welcome to implement it and/or contribute it to our open source server.

**Comment by arvyy** [comment]
I see. Is there a simple way to see whether a feature is enterprise only or whether it's available for free?

**Comment by wag110894** [comment]
Hello Arvyy,

Here is a list of features that are only available in Commercial:

1. PDF’s
2. OAuth - OpenID Connect
3. FormviewPro
4. LDAP Authentication
5. SAML Authentication
6. Form Manager: Customizable Form-builder Interface tor non-developer users and groups. 
7. Advanced Webhooks
8. Team management
9. Collaboration on Forms
10. Audit Logging
11. Multi-tenant management
12. Email Templates (coming soon)
13. Temp tokens & Email based authentication
14. Report API (aggregated reports)
15. Staging and Deployment (SDLC)s
16. Form Submission Collections (saving submissions to different collections for indexing)
17. Form Versioning
18. Encrypted Fields
19. Offline Forms
20. File Uploads
21. CORS Configuration
22. SQL Connectors
23. Kickbox integration
24. Google Sheets
25. Atlassian (JIRA) integration
26. Office 365 integration
27. Hubspot integration
28. CCS templating 
29. Docker Containers with updates
30. External JWT tokens
31. Private File Uploads
