### ISSUE TITLE
Select component with data source - allow custom input?

### ISSUE THREAD

**Issue by z47co** [formio/formio#810]
Hi,

We are evaluating Form.io as a solution for mobile/offline data collection. One of the scenarios I haven't been able to map cleanly is pre-populating a select component with a Data Source while also allowing custom input.

For example, this select component has three options. A user may need to provide custom input, but the field automatically clears when the input does not match an existing option.

![Screenshot from 2019-07-16 08-47-37](https://user-images.githubusercontent.com/13539117/61309224-a5d32a00-a7a6-11e9-9d47-22175df51b59.png)

![custom input example](https://user-images.githubusercontent.com/13539117/61335249-ae952180-a7e1-11e9-8c80-9ab2002099e3.png)

Is this possible to implement without adding a conditional text field to allow "other" input?

Keep up the great work!

**Comment by zcuneo** [comment]
Dug a little deeper - looks like the Choices.js lib is close to adding support!

https://github.com/jshjohnson/Choices/pull/525

**Comment by randallknutson** [comment]
We currently don't have support for this. One of the primary reasons why is that the underlying data behind a select option is often an object. Users can only enter strings so it doesn't work correctly to map the string to an object. For now the best solution is to use a conditional field as you describe.

**Comment by zcuneo** [comment]
@randallknutson Thank you for your expeditious reply. 

> One of the primary reasons why is that the underlying data behind a select option is often an object. Users can only enter strings so it doesn't work correctly to map the string to an object.

Forgive my naivety, but I don't quite follow your reasoning. Handling a custom input seems like it could be implemented by simply replacing the default "No results found" with an href that invokes a custom function to apply the inputted string, perhaps with dynamic text such as "Add %input."

![Screenshot from 2019-07-16 15-51-33](https://user-images.githubusercontent.com/13539117/61335249-ae952180-a7e1-11e9-8c80-9ab2002099e3.png)

After all, the value of an HTML option element is a string at the end of the day?

**Comment by zcuneo** [comment]
> One of the primary reasons why is that the underlying data behind a select option is often an object. 

Forgive me if I'm wrong, but another thought came up while grokking on this: isn't the stored value literally always a string whether it's a reference or not? The aforementioned object argument seems only to apply to filtering.

I'll try to find a reasonable workaround in the meantime, but I don't think I could get our end-customer to sign up for the hosted service with this trade-off/restriction requiring a fork.

**Comment by randallknutson** [comment]
These aren't HTML option elements but choices.js rendered selects. There is an item template that renders the object down to a string. Thus the actual value stored in the database quite often is the object with lots of extra data in it, not just the value string. 

We are definitely open to adding some functionality like this but the reason we haven't yet is that it is actually remarkably tricky to implement in a way that supports all the ways our select can be configured. If the select was just a simple key/value pair that stored as a string it would be easy.

**Comment by z47co** [comment]
Thank you for the information!

**Comment by franke-mc** [comment]
@randallknutson : This is currently being discussed in [Choices PR#594](https://github.com/jshjohnson/Choices/pull/594#pullrequestreview-318312230). Also relevant: alternative [Choices PR#525](https://github.com/jshjohnson/Choices/pull/525) / [Choices issue #39](https://github.com/jshjohnson/Choices/issues/39).
