### ISSUE TITLE
[BUG] File Field Documentation

### ISSUE THREAD

**Issue by lnorton89** [formio/formio#812]
## Environment
Debian 10
mongoDB 4.0.9
formio 1.42.0
formiojs 3.22.10

Where can the documentation be found to configure file storage for hosted instances of formio? Seems like the distinction between hosted/self-hosted formio could be a bit better in the documentation. 

An option to configure storage on a local resource would be nice for smaller projects that are not using docker.

**Comment by randallknutson** [comment]
You can find the file documentation at https://help.form.io/userguide/form-components/#file-1

The server side must be compatible with https://github.com/danialfarid/ng-file-upload#server to upload a file. Unfortunately the file upload capability out of the box including s3, Azure and other storage providers is only supported on our hosted and on premise commercial server. You can write your own custom file upload endpoint using that documentation though.

**Comment by lnorton89** [comment]
Maybe I'm missing something here but if there is no ability to process uploaded files out of the box or even document how one could implement their own setup why is the file field included with the self-hosted version? 

Using the documentation provided for `ng-file-upload` doesn't really explain what your software is sending via the file upload form. Their PHP example is the following:

```$filename = $_FILES['file']['name'];
  $meta = $_POST;
  $destination = $meta['targetPath'] . $filename;
  move_uploaded_file( $_FILES['file']['tmp_name'] , $destination );
``` 
Will this work with what your application is sending? Sorry if this should be self-evident but it really feels like there could be at minimum a page dedicated to documenting the basics of how to handle this.

**Comment by randallknutson** [comment]
The file is a multipart upload form request with a file field attached to it. It is fairly standard.

We use the same renderer for both the open source and enterprise versions of our platform but in the hosted/enterprise version you'll see the file component under "Premium" components. You are still able to use the file component for free but the server side upload parts are the stuff we don't provide for free. You can develop this without too much effort if you want to stay on the free version of our platform.

**Comment by lnorton89** [comment]
I was able to get something setup without too much trouble, thank you for your help.
