### ISSUE TITLE
[BUG] Missing components like Tags, recaptcha etc in formio main frontend application

### ISSUE THREAD

**Issue by shai93** [formio/formio#816]
Components like Tags and Recaptcha are missing in formio main frontend application. This components already been implemented in formiojs and angular-formio but not in formio for angular 1.
What are the steps to use those components into formio main frontend application?

**Comment by randallknutson** [comment]
These are new components that only exist in our newer renderers. We are working hard to get these released to our production portal and other apps. You can use them in your own angularjs applications by updating to ngFormio 4.x which should have some releases for it. If you are using any other frameworks there should also be 4.x versions available.
