### ISSUE TITLE
Not able to apply conditions for differnet rows in datagrid 

### ISSUE THREAD

**Issue by BhagyaUnvired** [formio/formio#818]
## Environment
Please provide as many details as you can:
Hello,
I have a table inside a DataGrid. We have texfield and a HTML element inside that table. Initially the html element is hidden. When I type particular character (i.e. 'H' or 'T-') inside the texfield then only the html element should show for that particular row.But the Html element will show for every other rows when I type characters in first row.
![FormIODatagrid](https://user-images.githubusercontent.com/52695685/62191622-7d941f80-b391-11e9-80c6-fb15c7848b46.PNG)

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by randallknutson** [comment]
What version of formio.js are you using where you are experiencing this?

**Comment by BhagyaUnvired** [comment]
I got solution for this issue. Thank you

**Comment by gismomtl** [comment]
can you share the found solution?

**Comment by BhagyaUnvired** [comment]
I just changed the code data["key_name"] to row["key_name"].
