### ISSUE TITLE
[BUG]  Save as reference

### ISSUE THREAD

**Issue by rchgonzaga** [formio/formio#822]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.0.0-rc.21
- Frontend framework: 4.0.0-rc.11
- Browser: Chrome
- Browser version: 76+

## Steps to Reproduce
1. Saving something as reference

## Expected behavior
See the record with Object(ID)

## Observed behavior
It's not happening

## Comment
The feature was removed since you guys removed the Resource Element ? I'm asking because if i use the old webapp, i am able to add a resource element and save it as reference. But when i try to do this in the new React App for instance, it still saving only the values ... am i doing something wrong ?

**Comment by travist** [comment]
The "Save as Reference" feature is currently only available within our enterprise or hosted platform.

**Comment by rchgonzaga** [comment]
WoW ... thanks
