### ISSUE TITLE
[BUG] File upload component no longer working

### ISSUE THREAD

**Issue by ghost** [formio/formio#827]
https://github.com/formio/formio/commit/a0ba77bfb67b17d6943f758eafd4621a7b499c35

this commit breaks the file upload component. instead of the API returning the file upload component data, it instead returns "YES".

**Comment by wag110894** [comment]
Another customer was asking to have this changed. We are currently in the process of reverting this back to the way it initially was.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
