### ISSUE TITLE
Is it possible to duplicate edit grid rows?

### ISSUE THREAD

**Issue by Marmalade118** [formio/formio#838]
I'm looking for a way to duplicate/clone an existing row in an edit grid, but I can't seem to find a reliable way of accessing the row data. Currently I'm just reading the dom, but this is flaky at best, and I was hoping there is some way of just directly accessing the required row in the submission data?

Can anyone point me in the right direction for this? 

Thanks

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
