### ISSUE TITLE
Loop through and sum nested panel items (number components) using JavaScrip Calculated Value

### ISSUE THREAD

**Issue by duledjurasevic** [formio/formio#846]
Is there a way to loop through all nested panel items and get sum value?

Structure:
-Parent Panel

---Child_1 Panel
------ Child_1 Panel Number Component_1
------ Child_1 Panel Number Component_2

---Child_2 Panel
------ Child_2 Panel Number Component_1
------ Child_2 Panel Number Component_2

How to loop through and get sum of all Number Components?

**Comment by wag110894** [comment]
Hello @duledjurasevic ,

You looking for something like this? https://customcalculation.form.io/multipleoutsidepanels

**Comment by duledjurasevic** [comment]
@wag110894 Your example is more adding it one by one using key value. I was looking to loop through. Here is some pseudo code (I couldn't find the right syntax to get it to work):
var sum = 0;

for (var i = 0; i <= Panel_1.length; i++)
{
	if (!!Panel_1[i] && Panel_1[i].hasOwnProperty(numberComponent))
	{
		sum = sum + parseInt(Panel_1[i][numberComponent]);
	}
}

value = sum;

**Comment by travist** [comment]
This would be easier if you place a Container component within the Panel component and then add the values in there.  This way you have the ability to calculate by adding up all the numbers within the container as follows.

```js
value = _.reduce(data.container, function(sum, val) {
  return (sum + val);
}, 0);
```

**Comment by duledjurasevic** [comment]
@travist Hi, thanks! Do you have an example with full json object?

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
