### ISSUE TITLE
[BUG] Long text overflows select component

### ISSUE THREAD

**Issue by tmdoit-zz** [formio/formio#848]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 1.59.0
- Frontend framework: Pure JS
- Browser: 
      Safari Version 12.0 (14606.1.36.1.9)
      Brave Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

## Expected behavior
Should be visible text in one line which will fit in component, rest should be hidden

## Observed behavior
Long text exceed select component

## Example
![Screenshot 2019-09-20 at 23 19 09](https://user-images.githubusercontent.com/26081817/65360054-b5377f00-dbfe-11e9-9bd2-80d0327780bb.png)

**Comment by tmdoit** [comment]
I added below custom css to resolve this issue
```
.has-feedback .form-control {
        padding-right: 40px;
}
.form-control.ui.fluid.selection.dropdown {
      overflow: auto;
}
```

**Comment by randallknutson** [comment]
Thanks. We'll look into adding that css to the formio.js library so it will be fixed for everyone.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
