### ISSUE TITLE
View Data in parent/child form hangs

### ISSUE THREAD

**Issue by dmenne** [formio/formio#850]
-- formio Version 1.60 downloaded today, but also with previous version.

- Use any parent/child form.

In my example: 

-  Resource __Patient__
- Form: __Endo Base__ without parent
- Form: __Endo__ with __Patient__ als Select Box/Resource (same result the old way using resource directly)

Entering/Deleting in Patient/Endo works fine

View Data __Endo Base__ works fine, gives grid view. In my example, the query as given in XHR/Chrome was:
`http://localhost:3001/form/5d88dd6ddb34c2b629d7e2fb/submission`

View Data __Endo__ (Parent/Child) hangs, Spinner does not stop. Query returns `204/No content`.
No error message in console.

`http://localhost:3001/form/5d88e24d8a77777e90914c58/submission`

**Comment by dmenne** [comment]
This is a bug in formiojs 3.27.3, which still is the default in formio. Ok in 4.2.1 of formiojs. This issue can be closed when formiojs is updated in package.json.

**Comment by jhen1422** [comment]
@dmenne Thank you for the update. the latest 4x version should be pulled in when updating the package json to latest.

**Comment by dmenne** [comment]
Package formio still has
  "formiojs": "^3.27.3",

**Comment by jhen1422** [comment]
@dmenne 
You're correct, we need to update our open source to pull in the latest.

**Comment by jhen1422** [comment]
@dmenne This should resolved.
