### ISSUE TITLE
Different Edit Form interfaces with formiojs 4.2.1

### ISSUE THREAD

**Issue by dmenne** [formio/formio#852]
I switched to build formiojs 4.2.1 because of issue #850. When I access localhost:3100 now, I get the expected default component menu for the open-source version:
![grafik](https://user-images.githubusercontent.com/506275/65690638-c99cd100-e06f-11e9-9d1e-b858e5a51c01.png)
When I use the form editor via angular-formio (e.g. http://localhost:4200/#/form/5d88e24d8a77777e90914c58/edit), I get the well known Premium menu which was also presented in the MEAN-App video.

![grafik](https://user-images.githubusercontent.com/506275/65691031-76774e00-e070-11e9-83c9-67e38afbb2fd.png)

- I the Premium menu going to stay, or is this a runaway push?
- Why do I get different menus at all?

**Comment by randallknutson** [comment]
Those fields are the new layout that is available in 4.x. The premium fields still exist in partial form in the open source but we don't recommend using them as many of them depend on server side functionality that is only available in our enterprise server.

**Comment by dmenne** [comment]
This is highly confusing. "It's there but does no work" policy makes development risky. 

There is a `Nested Form` in the Premium edition. There is a "Form" only in open source edition which I probably should use, but it is not displayed in the menu.
I do fully understand that you have Premium features, but they should be greyed out or hiddne to avoid surprises.

**Comment by travist** [comment]
Agreed. Really the only "premium" feature that does not work completely in Open Source is File component, but this CAN be configured to work in Open source if you either A.) Use Base64 or B.) Use a custom file endpoint to store your file. What we may look into doing is just remove the options that are not available for our Open Source versions so there is no confusion. Nested form components should work just fine in Open Source. The discrepancies in names of components comes primarily from the fact that our Open Source portal is still using our AngularJS renderer which was completely re-written with formio/formio.js.
