### ISSUE TITLE
Add custom field to a form 

### ISSUE THREAD

**Issue by flo130** [formio/formio#856]
Is there a way to add custom fields when creating a form ?
IE. if I POST the json below (which is the same as the register form, but with a "foo" field) on "/form", "foo" field is not persist in the database : 
```
{
    "title": "Register2",
    "foo": "bar",
    "display": "form",
    "type": "form",
    "name": "register2",
    "path": "register2",
    "components": [{
        "input": true,
...
}
```
I'd like to add a description, an offer id, ...

**Comment by randallknutson** [comment]
There is a settings that can be used for that. For example:

```
{
  "title": "Register",
  "settings": {
    "foo": "bar",
  }
}

**Comment by flo130** [comment]
Thanks !
