### ISSUE TITLE
Actions repository

### ISSUE THREAD

**Issue by flo130** [formio/formio#860]
Hi, 

Here is my case: in the builder, administrators will create subscription tunnels. These tunnels will often have 2 steps: customer registration and then payment.
I would like to make available a repository of the possible actions, global to **all** the forms and use either on the passage to another step, or on the form submit (example : page 1 : check customer, register customer - page 2 : save payment, register subscription, ...).

Several questions in this issue:
- The Actions API is used to retrieve actions related to a form : I understand that there is no inter-form action repository. Would the use of a "Formio Resource" be the right solution to this problem (it would be a Resource that does not have fields) ? Do you see another solution ?
- Is it possible to usethe actions's mechanism other than on the submit (here: on the passage to a following page) ?

Thank you in advance for your answer.

**Comment by randallknutson** [comment]
Currently the actions system only responds to requests to the server which are POST/PUT/PATCH/GET/DELETE. It would get very tricky to trigger actions based on separate pages apart from actual forms. 

One way you may be able to manage this is to make each page of a wizard into a form by using the form component and then trigger each of those sub form into the action you want to happen.
So for example, have on the first page a form component pointing to the registration form and the second one pointing to a payment form. As you navigate to the next page it will submit the form and trigger whatever actions are on that sub form.
