### ISSUE TITLE
[Patch Forms is not possible] 

### ISSUE THREAD

**Issue by AudreyCb** [formio/formio#871]
Could you provide the right to **PATCH** form please ?

**Comment by randallknutson** [comment]
We are interested in adding this but it is pretty far down our backlog right now. Is this something you would be interested in making happen either through either a Pull Request or sponsoring the development?

**Comment by AudreyCb** [comment]
Thanks for the answer, 
how much would it cost to sponsor the development of this feature ?

**Comment by jhen1422** [comment]
@AudreyCb 
Hi, our dev team estimated this feature @ 16 hours  with a rate of $200 hr.

Please feel free to contact support@form.io for a formal quote. Thank you!

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
