### ISSUE TITLE
How to run formio in dev mode

### ISSUE THREAD

**Issue by narkhedetushar** [formio/formio#878]
I have used `docker-compose up` command to run code it's running in prod mode is there a command for a run this in dev mode. As I need to solve the below error when I add a condition for hiding/showing fields on other fields' data.

<img width="1440" alt="Screen Shot 2019-11-25 at 6 53 17 PM" src="https://user-images.githubusercontent.com/5755145/69544338-83071c80-0fb5-11ea-96a6-347dae6dbf7d.png">

**Comment by randallknutson** [comment]
You can run this in dev mode by not using docker. If you clone the repo directly and then run ```npm run start``` you will be running in dev mode.

**Comment by narkhedetushar** [comment]
Thanks, @randallknutson  got it :)
