### ISSUE TITLE
[BUG] How can a User change their own password?

### ISSUE THREAD

**Issue by srinathganesh1** [formio/formio#879]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: Community Latest Master

## Steps to Reproduce
1. Create a User (not admin)
2. Login as User
3. Try to change their own password. (Cannot find a button for it)

## Expected behavior
Ability to change password

## Observed behavior
Cannot find a button for it

**Comment by randallknutson** [comment]
We may not have added this functionality to the client application due to a lack of time. You can do this by adding a link in the header to the user form which will contain the password field where they can set their password.

**Comment by srinathganesh1** [comment]
Ok thanks
