### ISSUE TITLE
You are not authorized to perform the requested operation

### ISSUE THREAD

**Issue by HubSaul** [formio/formio#88]
Installed the app using the instructions provided.

When I run it, and and select Add New Resource, it show 
"You are not authorized to perform the requested operation."
at the top of the page twice.

If I try create it's not saving.

Any ideas on how to solve this?

![formiopng](https://cloud.githubusercontent.com/assets/12196395/15010650/1e1c32be-11e5-11e6-824f-5c5ceb37ed0e.png)

**Comment by travist** [comment]
This may be because you are not logged in as an administrative account for the application. We will try on our end, but the reason for this is because your role assigned from the application to your user does not have access to create the form.

**Comment by HubSaul** [comment]
I got it working. There are two things that I did:

1, I think its because when running npm install it gave the following error:
Jade has been renamed to pug, please install the latest version of pug instead of jade

When I ran npm install pug, it must have installed something that was needed.

2. Afterwards, the error stopped appearing, but the forms where not saving. Switching from Microsoft Edge to Chrome solved this.
