### ISSUE TITLE
How can manually call form validation?

### ISSUE THREAD

**Issue by monkeysmart** [formio/formio#880]
I'm trying to manually call form validation. I'm setting custom action in button component by code below:
`form.checkValidity(data)`
But it always returns true.

**Comment by randallknutson** [comment]
Try form.checkValidity(data, true). The second operation forces the dirty flag to true. If a component isn't dirty then the validator will skip it.

**Comment by monkeysmart** [comment]
Method `form.checkValidity(data)` checks validity of current page components when wizard is using.
For chek validity in other pages you may use code
`var pages = form.getPages();
for (var index in pages) {
    var page = pages[index];

    page.checkValidity(data, true);
}`
