### ISSUE TITLE
 How to arrive on a particular step

### ISSUE THREAD

**Issue by flo130** [formio/formio#881]
Hi, 
I have created a form with several steps and I would like to arrive directly on a particular step (according to a "#" in the URL or other ?). For exemple, on the 3d step.
I read the examples in the documentation, including the "conditional wizard" and the "multiform" (which come closest to what I want to do). I note that in each case we arrive at the 1st stage. It is only from there that it is possible to condition the display of the next wizard.
I would just like to get a particular wizard (depending on a parameter outside the form, I am digging on the side of "customConditional")
Is there a way to do that ? If yes, how ? :-)

Thank you in advance.

**Comment by randallknutson** [comment]
If I understand the question correctly you'd like to start at a page other than the first page. We have always assumed that users would start at the first page of the wizard so we don't have anything built in to start at a different page than the first. We do have conditional next page that can calculate what the next page should be but that won't work for the first page. One thing you could do is manually call wizard.setPage(3) to go to the third page immediately after the form is rendered. This will move the wizard to the third page.

**Comment by flo130** [comment]
That was what I meant !
Your answer answers my question. 
Thank you so much !

**Comment by flo130** [comment]
Another question to complete the answer : how is it possible to detect that a form is rendered? Is there a hook or event to report it ?
I see in the doc (https://github.com/formio/formio.js/wiki/Form-Renderer#hooks) the hooks "beforeSubmit" and "beforeNext" but they do not meet my needs. I see also the events (https://github.com/formio/formio.js/wiki/Form-Renderer#events) but the "render" event is never triggered (for information I use view-formio).

`<formio src="myform" v-on:render="doSomething" />`

**Comment by randallknutson** [comment]
The render event should be correct. We did fix that a month or two ago so all the events get triggered. The event may be on the root element though, something like this:

```
const formio = Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example', {
    readOnly: true
  }).then(function(form) {
  });
formio.on('render', (data) => {
   console.log('render');
});

The reason for this is that the render event occurs before the ready resolves so it will never fire within the "then" function. It has already fired by the time you get there.

**Comment by flo130** [comment]
Ok, thanks, I understand. 

But I can not make your example work: the "formio" variable is a Promise.

And do you know how to do this with "vue-formio" ? 
I try something like: 
`this.$refs.formio.on('render', () => console.log('render');`
But it did not. There may be another way to do it ?

**Comment by randallknutson** [comment]
You are right, it should be something like:

```
const formio = Formio.Form(document.getElementById('formio'), 'https://examples.form.io/example', {
    readOnly: true
  })
```

In vue it should be exposing the top level object but it looks like it isn't here: https://github.com/formio/vue-formio/blob/master/src/components/Form.ts#L87

**Comment by fabien-feat** [comment]
I've tested from my firts jsFiddle your script here is [the result](http://jsfiddle.net/fabienfeat/05p62u91/49/)

Your solution doesn't work...

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
