### ISSUE TITLE
How to set input value using javascript?

### ISSUE THREAD

**Issue by monkeysmart** [formio/formio#882]
I want to set the input value when clicking a button. I have an access to value of the input by such variables as `data `and `form`, but how can I set this value? Is there any method?

**Comment by marcus-at-localhost** [comment]
`form.getComponent("name").setValue("value i need to send");` 

https://github.com/formio/formio.js/issues/1194#issuecomment-485232975

**Comment by monkeysmart** [comment]
I solved the problem. This code is working:
`data['test_field'] = 'VALUE'; form.triggerRedraw();`
