### ISSUE TITLE
[BUG] Panel component - hide label not working

### ISSUE THREAD

**Issue by gismomtl** [formio/formio#884]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 1.60.8
- Formio.js version:
- Frontend framework: Angular-Formio 4.3.3
- Browser: Chrome

## Steps to Reproduce
1. create simple form (in form not wizard)
2. add a panel component and specify to hide label
3. Panel Label is not hidden....

**Comment by jhen1422** [comment]
@gismomtl 
Thank you for the report. We are aware of this option not working properly. The option was actually deprecated in our 4x renderer. After further review with our team we have decided to reintroduce this configuration in our 4x renderer. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by gismomtl** [comment]
do you have any expected date when the new version will be available ?
I've tested with : http://jsfiddle.net/rguich/byoLtqcm/4/ and it's still not working with latest version...

**Comment by jhen1422** [comment]
@gismomtl While this issue is on our 4x backlog list, we do not have an expected ETA on a fix. As mentioned before, if you would like an estimate on expediting this issue, please contact support@form.io.

Thank you
