### ISSUE TITLE
Showing space for hidden fields in form

### ISSUE THREAD

**Issue by vinay22** [formio/formio#887]
I created a form with 5 columns and in which three middle columns have hidden fields. Fileds are hidden but space remains between two fields. How to hide this space is there any solution for this?
this is JSON I used to create the form. I am using formio version 4.7.8.

    `{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Columns",
            "columns": [
                {
                    "components": [
                        {
                            "label": "Text Field",
                            "spellcheck": true,
                            "tableView": true,
                            "validate": {
                                "unique": false,
                                "multiple": false
                            },
                            "key": "textField",
                            "type": "textfield",
                            "input": true,
                            "hideOnChildrenHidden": false,
                            "internal": true
                        }
                    ],
                    "width": 12,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                },
                {
                    "components": [
                        {
                            "label": "Checkbox",
                            "hidden": true,
                            "tableView": false,
                            "validate": {
                                "unique": false,
                                "multiple": false
                            },
                            "key": "checkbox",
                            "type": "checkbox",
                            "input": true,
                            "defaultValue": false,
                            "hideOnChildrenHidden": false,
                            "internal": true
                        }
                    ],
                    "width": 12,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                },
                {
                    "components": [
                        {
                            "label": "Checkbox",
                            "hidden": true,
                            "tableView": false,
                            "validate": {
                                "unique": false,
                                "multiple": false
                            },
                            "key": "checkbox1",
                            "type": "checkbox",
                            "input": true,
                            "defaultValue": false,
                            "hideOnChildrenHidden": false,
                            "internal": true
                        }
                    ],
                    "width": 12,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                },
                {
                    "components": [
                        {
                            "label": "Checkbox",
                            "hidden": true,
                            "tableView": false,
                            "validate": {
                                "unique": false,
                                "multiple": false
                            },
                            "key": "checkbox2",
                            "type": "checkbox",
                            "input": true,
                            "defaultValue": false,
                            "hideOnChildrenHidden": false,
                            "internal": true
                        }
                    ],
                    "width": 12,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                },
                {
                    "components": [
                        {
                            "label": "Text Area",
                            "autoExpand": false,
                            "spellcheck": true,
                            "tableView": true,
                            "validate": {
                                "unique": false,
                                "multiple": false
                            },
                            "key": "textArea",
                            "type": "textarea",
                            "input": true,
                            "hideOnChildrenHidden": false,
                            "internal": true
                        }
                    ],
                    "width": 12,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                }
            ],
            "tableView": false,
            "key": "columns",
            "type": "columns",
            "input": false,
            "validate": {
                "unique": false,
                "multiple": false
            },
            "path": "columns"
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false,
            "validate": {
                "unique": false,
                "multiple": false
            }
        }
    ]
    }`

**Comment by randallknutson** [comment]
This pull request from 2 weeks ago should fix the issue. https://github.com/formio/formio.js/pull/2093

You can either update your renderer or implement this css inside your application.

**Comment by vinay22** [comment]
not showing these classes formio-component-hidden, formio-component-datasource in div element

       <div ref="component"
            class="row formio-component formio-component-columns formio-component-column1  formio-component-label-hidden"
            id="e4591wf">
            <div ref="column-e4591wf" class="col-md-8
            col-md-offset-0
            col-md-push-0
            col-md-pull-0">
                <div ref="component"
                    class="form-group has-feedback formio-component formio-component-checkbox formio-component-SendBeforeDueDate"
                    id="elt7gz">
                </div>
            </div>
        </div>

**Comment by randallknutson** [comment]
I misunderstood your original question. I thought you were talking about the hidden component, not fields that are hidden within a column. Unfortunately the columns component does not hide columns based on whether or not the fields within it are visible. We may have had a setting about this at some point but I don't think it is working anymore as very few people ever used the setting.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
