### ISSUE TITLE
Content component not working

### ISSUE THREAD

**Issue by HubSaul** [formio/formio#89]
The content component is not working in this release

I tested by installing on 2 different machines, and the same results.

When you add the content component, it asks for the property name, and once you click ok, it doesn't give you the editor

Any ideas?

**Comment by travist** [comment]
Wanted to let you know that we are looking into this. We will get back with you shortly.

Thanks.

**Comment by travist** [comment]
We just pushed up a fix for this in the latest builds. Try again with a new install.
