### ISSUE TITLE
Country List limited to 4 results

### ISSUE THREAD

**Issue by steramirez** [formio/formio#891]
On behalf of Hemen Estefaie:
We are facing an issue in one of the dropdowns that contains the list of countries.
The issue is when user enters a part of the country name to filter the list, the list of the results always contains 4 items.

Before filter:
![before-filter](https://user-images.githubusercontent.com/54654935/70964741-15946a80-20e1-11ea-8b32-915a35bb918a.jpg)
After filter:
![after-filter](https://user-images.githubusercontent.com/54654935/70964749-188f5b00-20e1-11ea-8892-23ad8cb9a40c.png)
We tried Use tab in formio UI to make sure it’s not a custom css issue and result is still the same.

**Comment by jhen1422** [comment]
@steramirez 
Our select component utilizes the Choices.js library which can be configured by the user. By default, the filtered search result is limited to 4. You can add "searchResultLimit = -1" to change the result limit. In addition, you can set many other configurable options which can be found here https://www.npmjs.com/package/choices.js/v/7.0.0.

**Comment by steramirez** [comment]
thanks, will pass this on.

**Comment by steramirez** [comment]
On behalf of Hemen Estefaie:: @jhen1422 How can this be done in formio? We tried to set an attribute in Layout -> Add Attribute of the component and also API -> Custom Properties. Though neither worked.

**Comment by jhen1422** [comment]
@steramirez This setting configuration is offered on our next portal found at https://next.form.io/#/. Simply access the Select settings from the mentioned portal and you will find a JSON editor to add the Choices.js configurations.

**Comment by steramirez** [comment]
On behalf of Hemen Estefaie: @jhen1422 I put in the configuration in the component json as directed. Though it did not reflect on the rendered component and it didn’t work.

![json](https://user-images.githubusercontent.com/54654935/71133390-873df700-224e-11ea-8cfa-e381ea4bc143.png)

**Comment by jhen1422** [comment]
@steramirez On the next portal, edit the select field setting. Click the 'Data' tab and scroll down until you get to the 'Choices.js' javascript editor. Apply the javascript there. https://lfjbgeaqypzfwyy.form.io/tabindex
