### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by lailapfit** [formio/formio#892]
Question: I am trying to add reCaptcha to a form, and it seems like either the reCaptcha is a custom component I have to build or I have to render the entire form as a json?

According to [this link](https://help.form.io/userguide/form-components/#recaptcha) it seems as though there is a reCaptcha component that is available to add to the form builder.

**Comment by gp1234** [comment]
Did you find any solution to this issue? @lailapfit

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
