### ISSUE TITLE
Select Multiple  Images from Gallery

### ISSUE THREAD

**Issue by gag29** [formio/formio#893]
unable to upload Multiple number of images on one go from the file system

## Steps to Reproduce
1. Open the form
2. Upload images from gallery (for a multiple true image field)
3. Try Selecting Multiple number of images (doesnt allow this operation).

##json of the component
{
      "input": true,
      "label": "Image",
      "key": "Images_Photo_",
      "defaultValue": "",
      "type": "file",
      "clearOnHide": false,
      "image": true,
      "storage": "base64",
      "multiple": true
    }

##image of how the form component looks like 
![Capture](https://user-images.githubusercontent.com/40608248/71231495-3e507600-2314-11ea-856b-697b6e397eb9.PNG)

##Please check out the videolink  below for more details
https://gofile.io/?c=ATy9lD

**Comment by wag110894** [comment]
Hello @gag29. We are not able to replicate this issue. Can you confirm that you have added the multiple values checkbox checked located inside the file settings? 

Hope that this helps.

Thank you.

**Comment by gag29** [comment]
hi @wag110894 , Hope you saw this video , https://gofile.io/?c=ATy9lD , i was unable to select multiple images from the gallery .
I was able to do that modifications in the form.io.min.js file !

**Comment by wag110894** [comment]
What browser are you able to replicate this on? I was unable to replicate this using Safari.

**Comment by gag29** [comment]
Di you take a look at this video https://gofile.io/?c=ATy9lD

**Comment by wag110894** [comment]
We did review the video and are unable to replicate it using the Safari browser on iphone. What browser are you using so we can replicate this issue?

**Comment by gag29** [comment]
Chrome !

**Comment by wag110894** [comment]
Thank you for clarifying which browser you are using. I am still unable to replicate this issue on the latest version of Chrome on the iPhone. Could you provide the Form URL that you are able to replicate this issue on so we can take a look at it on our side?

Thank you.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
