### ISSUE TITLE
[Question] How to get SelectComponent return items based on unique field

### ISSUE THREAD

**Issue by gismomtl** [formio/formio#894]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X ] Local deployment
    - Version: latest

we create a Select component which connect to ressource (directly or via URL path).
ressource format is for instance:
[projectName, Service]
[ ProjA, IT]
[ ProjB, IT]
[ ProjC, HR]
[ ProjD, Sales]

How to do so the Select component display only unique Service Values ??
[IT]
[HR]
[Sales]

Even if we specify data.Service, the result will contain multiple [IT]

If not already available, will it be possible to have new "filter" __unique as we have for __gte, __regex, sort,select ... ??

**Comment by travist** [comment]
You will need to use our Report API to accomplish this https://apidocs.form.io/?version=latest#fbef20ac-e9bc-c898-d7b6-fc8fa167d7f1.

This would provide a way to use pipeline modifiers to merge like records. Be advised that this is only available on our Commercial product. If you do not want to use our commercial api, then you will need to build your own api that performs this query.
