### ISSUE TITLE
[BUG] Does form.io has any ways to filter options in one drop down, based on the selection or value from another field

### ISSUE THREAD

**Issue by gag29** [formio/formio#903]
#Form Assumption:

Lets assume we have 2 Components in the form ,
Component 1  - Select with options A,B
Component 2 -  have values 1,2,3,4 as its select options

#Question:
Can we filter the options in Component 2 based on the value of Component 1
Eg: Component 2 displays only 1,2 on selection of A in Component 1
    Component 2 displays only 3,4 on selection of B in Component 1

**Comment by randallknutson** [comment]
You can do this two ways. 

First, you can use a url with a filter value from the first field to pass to the api that returns the filtered results. An example is here: http://formio.github.io/formio.js/app/examples/external.html

Second, you can use Data Source Type of "Custom" on the second field and use javascript to return the filtered results. The javascript code has access to data.component1 (or whatever the first field's property key is) and can return different results based on the value of the first field.

**Comment by gag29** [comment]
Thanks @randallknutson got it !

**Comment by gag29** [comment]
@randallknutson Do you mean that we need to write a javascript code separately apart from  json and fetch those values to the drop down
