### ISSUE TITLE
[BUG] after installation can't authenticate

### ISSUE THREAD

**Issue by aermike** [formio/formio#905]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:latest
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. install npm and mongodb, start mongo db
2. clone git repository
3. npm install and npm start(try with an git repo and blank (option1)
Checking for db schema updates.
 > No updates found.

Initializing API Server.
 > Mongo connection established.
Installing...
prompt: Are you sure you wish to install? (y/N):  y

Which Github application would you like to install?
  1.) None
  2.) https://github.com/formio/formio-app-humanresources
  3.) https://github.com/formio/formio-app-servicetracker
  4.) https://github.com/formio/formio-app-todo
  5.) https://github.com/formio/formio-app-salesquote
  6.) https://github.com/formio/formio-app-basic

Or, you can provide a custom Github repository...

prompt: GitHub repository or selection?:  (1) 6
Downloading app...
  downloading [==================================================] 100% 0.0s
Extracting contents...
Downloading client...
  downloading [==================================================] 100% 0.0s
Extracting contents...
Importing template...
(node:12073) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#-findandmodify-
Creating root user account...
prompt: Enter your email address for the root account.:  mike@gmail.com
prompt: Enter your password for the root account.:
Encrypting password
Creating root user account
Install successful!
 > Serving application at http://localhost:8080
 > Serving the Form.io API Platform at http://localhost:3001

<img width="625" alt="formio" src="https://user-images.githubusercontent.com/4247309/72452444-36c2a680-37c6-11ea-8a6e-3eb776564933.PNG">

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by phorumdm** [comment]
how is this solved??

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
