### ISSUE TITLE
[BUG] how to trigger subform update

### ISSUE THREAD

**Issue by gismomtl** [formio/formio#907]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

I want to be able to generate summary of a form live without waiting the submission.

the main form (FormA) contain multiples components + 1 subform "summary"
this subform "summary" contains a text component "mySummary" which should be updated automatically if parent form FormA has any of its data updated.
calculated value of "mySummary" isn't automatically triggered when FormA is updated event if the script is parsing the FormA components (excluding itself).

How to solve that?

**Comment by travist** [comment]
You should be able to do this with a custom wizard. See the following.

https://formio.github.io/formio.js/app/examples/customwizard.html

Each page could also be a sub-form as well.
