### ISSUE TITLE
Form.io Wizard

### ISSUE THREAD

**Issue by chandranalini** [formio/formio#910]
HI,

We have following requirement. Can someone help us how to achieve this?

There is a wizard with 3 steps called as account , account information, Review

STEP 1(account) has 3 forms, STEP 2 (account information) has 3 forms and STEP 3 has one form. 

Here is my workflow in the wizard. 
I want be on STEP 1 from step 1 form 1 to step 1 form 3. 

When click on NEXT button in step 1 form 3(last form in STEP 1) then we want to move to STEP 2 in the wizard and we want to be on STEP 2 from step 2 from 1 to  step 2 form 2....

When click on NEXT button in step 2 form 2 (last form in STEP 2) then we want to move to STEP 3.

STEP 1 --- step 1 form 1 -> step 1 form 2 -> step 1 form 3
STEP 2 --- step 2 form 1 -> step 2 form 2 
STEP 3 --- step 3 form 1

**Comment by travist** [comment]
This can be achieved using a "custom" wizard implementation. See https://formio.github.io/formio.js/app/examples/customwizard.html

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
