### ISSUE TITLE
[BUG] Unable to install following docker-compose instructions.

### ISSUE THREAD

**Issue by marcbria** [formio/formio#927]
## Environment
- OS: 
    - DEV:Ubuntu 19.04
    - PROD: Debian 9
- Docker 19.03.5
- Docker-compose 1.25.4
- Python 2.7.17

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: master branch

## Steps to Reproduce
Follow docker-compose installation process as described in the README.md
1. git clone https://github.com/formio/formio.git
2. cd formio
3. npm install
4. docker-compose up

## Observed behavior
When running "npm install" some warning raised:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

updated 1 package and audited 3839 packages in 6.274s

17 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (1 low, 2 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

The real error appears with "docker-compose up" that is unable to run the containers and throws:

```
ERROR: unsatisfiable constraints:
  python2-2.7.16-r2:
    breaks: world[python=2.7.16-r1]
ERROR: Service 'formio' failed to build: The command '/bin/sh -c apk update &&     apk upgrade &&     apk add python=2.7.16-r1 &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0' returned a non-zero code: 1
```

**Comment by travist** [comment]
We will take a look.  This seems to be a node version issue.

**Comment by garywong-bc** [comment]
This appears to be a dup of https://github.com/formio/formio/issues/931#issuecomment-590564987 (and a workaround is there too).

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
