### ISSUE TITLE
[BUG] Unique field says submission exists but API won't return it

### ISSUE THREAD

**Issue by NiMusco** [formio/formio#929]
Hey,

I'm trying to create a new submission of a resource with a field "ip" that is unique.

When I fill the form using "192.168.125.252" as IP, it fails saying:

` "IP" must be unique.`

----------------------

But if I query the API looking for that particular IP, I get nothing
`apigw/host/submission?data.ip=192.168.125.252`

Result:
`[]`

---------------------

In Mongo...
`db.submissions.find({"data.ip": "192.168.125.252"});`

Result: (I cropped the data part to make it short and clear):
```
{ "_id" : ObjectId("5e04faa31691e8001ff8f9eb"), "owner" : ObjectId("5dbc34b2742d960023466ec5"), "deleted" : null, "roles" : [ ], "data" : { ip" : "192.168.125.252" ...

{ "_id" : ObjectId("5e44146f643f74001f1825a3"), "owner" : ObjectId("5dbc34b2742d960023466ec5"), "deleted" : 1581520174592, "roles" : [ ], "data" : {ip" : "192.168.125.252" ...

{ "_id" : ObjectId("5e4416fd643f74001f1825a7"), "owner" : ObjectId("5dbc34b2742d960023466ec5"), "deleted" : null, "roles" : [ ], "data" : { ip" : "192.168.125.252" ...
```

So... what happened here?

Why are three of them? How is it possible for two non-deleted submissions with the same unique field to coexist?
And why's the API retrieving me an empty array? Any guesses?

Thank you.

**Comment by travist** [comment]
The query may be getting messed up because of the periods. Try using the url encoded period instead.  ```data.ip=192%2E168%2E125%2E252```

**Comment by NiMusco** [comment]
Hi Travist, thanks for answering,

Querying by IP was just for debugging purposes, to demonstrate that that submission is not retrieved by API. I tried encoding it anyway and got same result. (an empty array)

If I don't specify a data.ip filter and ask for the full list of submissions, 192.168.125.252 is just not there. But, again, if a try to create it with that value... "IP must be unique".

Please note Mongo results above, It's there... somehow.

**Comment by travist** [comment]
Here is the unique validator. I would put a break point here to figure out why the query is not what it should be to determine the uniqueness of values. https://github.com/formio/formio/blob/master/src/resources/Validator.js#L378

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
