### ISSUE TITLE
Not able to start server.

### ISSUE THREAD

**Issue by YogendraCreatiosoft** [formio/formio#93]
I have used the installation steps mentioned. I am getting error while running server. Below is the error 

root@Node:~/formio# node server.js

readline.js:72
    terminal = !!output.isTTY;
                       ^
TypeError: Cannot read property 'isTTY' of undefined
    at new Interface (readline.js:72:24)
    at Object.exports.createInterface (readline.js:38:10)
    at Object.<anonymous> (/root/formio/server.js:14:30)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:124:16)
    at node.js:807:3

Can anyone help me out

**Comment by zackurben** [comment]
@YogendraCreatiosoft did you do an `npm i`

I just cloned the latest version, did a npm install, and was able to start the server with no issues.

**Comment by houmanb** [comment]
I got it too, but I found out that my node.js version is outdated. Please update your node installation and try it again. I hope that helps.

**Comment by zackurben** [comment]
@houmanb Thanks for the feedback! This project is set to follow the current Node LTS build, so anything from 4.2.0 - 4.4.4 should work without any issues.

There is a package.json variable for the node version (currently set to 4.2.0 >=: https://github.com/formio/formio/blob/master/package.json#L14)

So if you did `npm i` with another version, there should have been a warning, albeit less pronounced then it should be..
