### ISSUE TITLE
[BUG] unsatisfiable constraints: python2-2.7.16-r2 breaks world[python=2.7.16-r1]

### ISSUE THREAD

**Issue by michelfigueiredojava** [formio/formio#931]
## Environment
Please provide as many details as you can:
Ubuntu 19.10
![image](https://user-images.githubusercontent.com/45941874/74603772-e84b4500-50ae-11ea-99c9-1c7d4917ca1a.png)

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: anything in master branch at 16/02/2020

## Steps to Reproduce
1. git clone https://github.com/formio/formio.git
2. cd formio/
3. npm install
4. docker-compose up

## Observed behavior
Creating network "formio_default" with the default driver
Creating volume "formio_mdb-data" with default driver
Pulling mongo (mongo:4.1)...
4.1: Pulling from library/mongo
7413c47ba209: Pull complete
0fe7e7cbb2e8: Pull complete
1d425c982345: Pull complete
344da5c95cec: Pull complete
3c705a3e5fce: Pull complete
f6508c5fc358: Pull complete
1798ab2eeee4: Pull complete
aa98b7988869: Pull complete
c3407a29f56d: Pull complete
97df9363920d: Pull complete
adab802cb21b: Pull complete
32e764769299: Pull complete
98184930f8ea: Pull complete
Digest: sha256:8005da1dcf3d2ff800f9ccb339012522e3c93c12e1394edab54336991ddc8a1a
Status: Downloaded newer image for mongo:4.1
Building formio
Step 1/11 : FROM node:lts-alpine3.10
lts-alpine3.10: Pulling from library/node
4167d3e14976: Pull complete
88e051f8b785: Pull complete
0b99f66d422a: Pull complete
6f8dbab757a5: Pull complete
Digest: sha256:c4d08dcba34e7ac0a1f6d914cfc975c5f0d168d9cacadab123a24efca3ee86dc
Status: Downloaded newer image for node:lts-alpine3.10
 ---> 48ae9395145d
Step 2/11 : WORKDIR /app
 ---> Running in 43b6cba5a1ed
Removing intermediate container 43b6cba5a1ed
 ---> aaf5d1090011
Step 3/11 : RUN apk update &&     apk upgrade &&     apk add python=2.7.16-r1 &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0
 ---> Running in 2198f24366df
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
v3.10.4-15-g5600c80ab9 [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.4-7-g6ee081a8fb [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
OK: 10343 distinct packages available
OK: 7 MiB in 16 packages
ERROR: unsatisfiable constraints:
  python2-2.7.16-r2:
    breaks: world[python=2.7.16-r1]
ERROR: Service 'formio' failed to build: The command '/bin/sh -c apk update &&     apk upgrade &&     apk add python=2.7.16-r1 &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0' returned a non-zero code: 1

## Solution:
In Dockerfile, line 14, change the line:
    apk add python=2.7.16-r1 && \
to 
    apk add python=2.7.16-r2 && \

run docker-compose up again, it is done.
I will tried  to create a PR but I think I don't have permission to create a branch.

**Comment by afewellvmware** [comment]
I ran into this same problem, after I made the change you suggested above, I can docker build the container, but still getting dependency errors on docker-compose up:

```
afewell@ip-172-31-5-55:~/git/kampfires/formio$ sudo docker-compose up
/usr/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/lib/python2.7/dist-packages/compose/cli/errors.py", line 11, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python2.7/dist-packages/docker/api/client.py", line 6, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/lib/python2.7/dist-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 47, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```

**Comment by afewellvmware** [comment]
I confirmed @michelfigueiredojava solution does work for me. The other urllib3 error I was getting went away when I upgraded from docker-compose 1.17 to 1.23. 

Thanks!

**Comment by remster85** [comment]
Same issue and same resolution when running from windows docker-tools.

**Comment by thiagomeireless** [comment]
I had to change the line to `python=2.7.18-r0` to solve the problem, `python=2.7.16-r2` was still giving me errors.

So far, no problems with this version.
