### ISSUE TITLE
DataGrid

### ISSUE THREAD

**Issue by chandranalini** [formio/formio#933]
How to trigger row select event on Datagrid. Please let me know how to do it.

**Comment by randallknutson** [comment]
Do you mean the Datagrid form component or the Datagrid that displays submissions (We call this the submission grid to disambiguate). What front end library are you using?

**Comment by chandranalini** [comment]
Datagrid form component. We are using angular app. My requirement is 
on row select of first datagrid, fire event and get data from external API and disply on second datagrid.

**Comment by randallknutson** [comment]
What does it mean to select the first row? There are no events for the component outside of any focus events for components within a row of the datagrid.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
