### ISSUE TITLE
[BUG] 400 "Invalid alias" after delete and resave form

### ISSUE THREAD

**Issue by jntghub** [formio/formio#934]
## Environment
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 1.63.11
- Formio.js version: 4.8.1
- Browser: Chromium
- Browser version: 80.0.3987.87

## Steps to Reproduce
1. Create a form in formio.js builder and save it a in local form.io server.
2. Delete form previously created.
3. Create and save a new form with same path than previously deleted form.

## Expected behavior
Form is saved succesfully and is shown in the Forms list of form.io server frontend:
![image](https://user-images.githubusercontent.com/61198879/74754010-4162d680-5271-11ea-8288-b20e41d36db8.png)

## Observed behavior
Save form for the first time and delete work as spected.
Save form for the second time returns:
    responseText: "Invalid alias"
    status: 400
    statusText: "Bad Request"
New form is not in the Forms list of form.io server frontend.

This is my save function:
`
function saveForm(pathExists) {
    postObject = builder.instance.schema;
    postObject['type'] = $('#type')[0].value;
    postObject['path'] = $('#path')[0].value;
    postObject['title'] = $('#title')[0].value;
    postObject['name'] = $('#name')[0].value;
    postObject['submissionAccess'] = [{'roles':[],'type':'create_all'},{'roles':['5e33ec6c0109219ca2a668bd'],'type':'read_all'},{'roles':['5e33ec6c0109219ca2a668bd'],'type':'update_all'},{'roles':['5e33ec6c0109219ca2a668bd'],'type':'delete_all'},{'roles':['5e33ec6c0109219ca2a668bf'],'type':'create_own'},{'roles':['5e33ec6c0109219ca2a668be'],'type':'read_own'},{'roles':['5e243a26643fc51d1b5aa36a'],'type':'update_own'},{'roles':['5e243a26643fc51d1b5aa36a'],'type':'delete_own'}];
    postObject['access'] = [{'roles':['5e33ec6c0109219ca2a668bd','5e33ec6c0109219ca2a668be','5e33ec6c0109219ca2a668bf'],'type':'read_all'}];
    delete postObject['_id'];
    delete postObject['owner'];
    delete postObject['machineName'];
    delete postObject['created'];
    delete postObject['modified'];

    return $.ajax({
        url: host + url,
        method: method,
        contentType: 'application/json',
        headers: {
            'Content-Type': 'application/json',
            'x-jwt-token': restToken
        },
        data: JSON.stringify(postObject),
        success: function(data, textStatus, jqXHR) {
            builder = new Formio.FormBuilder($('#builder')[0], {
                display: data.type,
                components: data.components,
                settings: {}
            }, {});
        }
    });
}
`

This is my delete function:
`
function deleteForm() {
    url = $('#path')[0].value;

    return $.ajax({
        url: host + url,
        method: 'DELETE',
        contentType: 'application/json',
        headers: {
            'Content-Type': 'application/json',
            'x-jwt-token': restToken
        },
        success: function(data, textStatus, jqXHR) {
            builder = new Formio.FormBuilder($('#builder')[0], {
                display: data.type,
                components: data.components,
                settings: {}
            }, {});
        }
    });
}
`

Anybody else with this bug?
Thanks.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
