### ISSUE TITLE
Displaying an Image on Form

### ISSUE THREAD

**Issue by abccustom1** [formio/formio#935]
I'm trying to display an images on my form. The form is used to submit a design for a customized product. When a user chooses a certain color from my dropdown element, I want the associated image I created of the color swatch to appear. How do I add an image to the form?

**Comment by randallknutson** [comment]
You can add an image to a form by using the content or html element components. They will both allow you to embed a url to the image into your form.

**Comment by abccustom1** [comment]
Right. I’ve read that on the support pages. But is the url a shareable google drive or Dropbox link to the image?

**Comment by randallknutson** [comment]
Those don't actually host the image anywhere. You need to place the image on a server (or as part your app/website). Then once you have a url to the image you can use it in the content or html element components.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
