### ISSUE TITLE
[BUG] Webhook error triggered on PATCH request

### ISSUE THREAD

**Issue by Javo-blip** [formio/formio#939]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: latest
- Formio.js version: latest
- Frontend framework: React
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Create form
2. Add webhook
3. Make PATCH request

## Expected behavior
Success message on success

## Observed behavior
response:
{"status":400,"message":"Could not match request method: patch"}

__Note: PATCH request itself is performed correctly.__

File that needs to be fixed
`formio/src/actions/WebhookAction.js`

line:200
```
switch (req.method.toLowerCase()) {
          case 'get':
            rest.get(url, options).on('success', handleSuccess).on('fail', handleError);
            break;
          case 'post':
            rest.postJson(url, payload, options).on('success', handleSuccess).on('fail', handleError);
            break;
          case 'put':
            rest.putJson(url, payload, options).on('success', handleSuccess).on('fail', handleError);
            break;
          case 'delete':
            options.query = req.params;
            rest.del(url, options).on('success', handleSuccess).on('fail', handleError);
            break;
          default:
            return handleError(`Could not match request method: ${req.method.toLowerCase()}`);
        }
```
The above switch statement is not handling PATCH requests

**Comment by randallknutson** [comment]
Looks like we haven't updated the webhook action since we have added patch. Is this something you could add to the library via a pull request?
