### ISSUE TITLE
[BUG] Field Set cannot be "Collapsible" or "Collapsed"

### ISSUE THREAD

**Issue by qodrinzo** [formio/formio#941]
Checking "Collapsible" or "Collapsed" boxes on Field Set component does not work on portal.form.io

**Comment by wag110894** [comment]
Hello @qodrinzo ,

Thank you for reaching out!

This functionality is currently working on our Next Portal (https://next.form.io).  You can log onto our Next Portal by using the same login credentials as you use on Next Portal.
