### ISSUE TITLE
[BUG] Submit button not shown

### ISSUE THREAD

**Issue by qomhmd** [formio/formio#942]
## Environment

- Hosting type
  - [ ] Local deployment
    - Version: 2.0.0-beta.4
- Formio.js version: 4.1.0
- Frontend framework: Default (ng?)
- Browser: Google Chrome
- Browser version: 80.0.3987.132 (Official Build) (64-bit)

## Steps to Reproduce
After updating from version 1.63.4 to this version, the submit button below the form is hidden by default; however, the form could be submitted by pressing Enter.

## Example
![image](https://user-images.githubusercontent.com/9105400/76691965-a12c8180-6665-11ea-91c0-44f15de6a4f9.png)

**Comment by wag110894** [comment]
Can you try upgrading to the latest version of our Core Renderer (4.9.0-rc.10) and see if you are still seeing this issue?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
