### ISSUE TITLE
[BUG] Corrupted limiting loaded data on Select box, & selected option not shown well on Edit Submission page

### ISSUE THREAD

**Issue by qomhmd** [formio/formio#943]
## Environment

- Hosting type
  - [ ] Local deployment
    - Version: 2.0.0-beta.4 (updated from 1.63.4)
- Formio.js version: 4.1.0
- Frontend framework: Default (ng?)
- Browser: Google Chrome
- Browser version: 80.0.3987.132 (Official Build) (64-bit)

## Steps to Reproduce
1. Add a **Select** component to your form. Make it get data from a **URL**, choosing an item,key as it's value.
2. Check the **Unique** and **Required** on Validation tab.
3. Set a **limit**.
4. Edit a submission of the form.

## Observed behavior
3. Nothing limited on response from URL, though _limit_ and _skip_ defined in the source file. **Load more...** button replicates the whole items when clicked.
4. The option _shown_ on the Select box is not what has been submitted,
2. The field is not unique on my submissions.

## Example
4. ![image](https://user-images.githubusercontent.com/9105400/76692239-ea320500-6668-11ea-92e8-92ebdfa90fb0.png)

![image](https://user-images.githubusercontent.com/9105400/76692242-02a21f80-6669-11ea-8cef-fa8dc5211890.png)

2. ![image](https://user-images.githubusercontent.com/9105400/76692428-bc9a8b00-666b-11ea-84c7-15633831ebdf.png)

**Comment by wag110894** [comment]
Hello @qodrinzo, can you provide a JSFiddle for this item so that we can replicate on our side?

Thank you.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
