### ISSUE TITLE
[BUG] Create inputs

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio#945]
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version: 4.8.1
- Browser: Chrome
- Browser version: 80.0.3987.132

## Steps to Reproduce
1. Create two inputs with "Multiple Values" option

## Expected behavior
Two inputs with their buttons
## Observed behavior
Just one input tag
## Example
Replicated on "https://formio.github.io/ngFormBuilder/"
![bug1](https://user-images.githubusercontent.com/22855299/76843966-4487bd00-6845-11ea-9fd6-91c9519f670d.PNG)
Cause in map renderRow function by dataValue
![bug 2](https://user-images.githubusercontent.com/22855299/76844077-739e2e80-6845-11ea-8463-a21f85e194fe.PNG)

**Comment by wag110894** [comment]
Hello @homashevchenko,

We are able to replicate this issue in the version that you described, but not on our latest version of formio.js (4.9.0-rc.10). Can you upgrade to 4.9.0-rc.10 and see if the issue still occurs?

**Comment by homashevchenko** [comment]
On 4.9.0-rc.10 looks nice.

**Comment by homashevchenko** [comment]
Thank You
