### ISSUE TITLE
[BUG] Change submission in "Data Grid" component

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio#947]
- Hosting type
  - [ ] Form.io
  - [x ] Local deployment
- Formio.js version: 4.8.1 || 4.9.0-rc.10
- Browser: Chrome
- Browser version: 80.0.3987.132

## Steps to Reproduce
1. Create "Data Grid" component with few rows
Submission was generated something like that: 
![image](https://user-images.githubusercontent.com/22855299/76966901-56de2580-692f-11ea-91d3-9ac21fa6f99d.png)

2. Update submission just with one row something like that: 
![image](https://user-images.githubusercontent.com/22855299/76967336-f7344a00-692f-11ea-8053-af0f6f686cf5.png)

## Expected behavior
Just one row with new submission data
## Observed behavior
Three rows. First with new data, second and third with old data 
When we delete on of old row - all old rows are deleted

Thanks

**Comment by jhen1422** [comment]
@homashevchenko 
Can you try using the latest version of formio.js (4.9.5) to see if this is resolved?

**Comment by homashevchenko** [comment]
Not resolved on version 4.9.5.

**Comment by wag110894** [comment]
@homashevchenko, could you provide a jsfiddle of this issue occurring on the latest version of formio.js (4.9.6) as we are unable to replicate this issue on our side?

**Comment by homashevchenko** [comment]
"https://jsfiddle.net/83ghsf6o/"
Add few (>2) row with data.
Click Submit.

Thanks
