### ISSUE TITLE
[BUG] Unable to use Azure AD as Open ID connect authentication

### ISSUE THREAD

**Issue by mibjg** [formio/formio#949]
## Environment
- Hosting type
  - [x] Form.io
- Formio.js version: latest
- Frontend framework: Stand alone forms
- Browser: Chrome
- Browser version: 80.0.3987.149

## Steps to Reproduce
1. Setup Login button in form.io
2. Add Action to login using OpenID
3. Create App registration in Azure AD, allow ID_token, redirect_url = https://formview.io
4. Create Form with Auth=1

## Expected behavior
When I hit the login button, I expect to be logged in, and returned to the form

## Observed behavior
The login-dialog opens, I can login, but the spinner keeps spinning, dialog is never closed

## Example
https://formview.io/#/hhfhxzlonwudvrv/mikkelstest?header=1

![image](https://user-images.githubusercontent.com/56539680/77165589-e8c26b80-6ab2-11ea-810b-b872d57fcd2b.png)

**Comment by randallknutson** [comment]
Can you try this on pro.formview.io instead of formview.io? OAuth authenticated was not supported in the formview.io app but should work in pro.formview.io.

**Comment by mibjg** [comment]
Then I end up in a window looking like this after I login
![image](https://user-images.githubusercontent.com/56539680/77344771-f5a1c200-6d33-11ea-89b6-7949d2c1e7b8.png)

**Comment by fabianedl777** [comment]
hello guys any progress form this?

**Comment by wag110894** [comment]
@fabianedl777, have you tried this using pro.formview.io?

**Comment by fabianedl777** [comment]
@wag110894 yes

**Comment by travist** [comment]
We can confirm that it works fine using our SAML provider. It should work with OpenID Connect, but we are aware of an issue with OpenID and our https://pro.formview.io application, so that may be what is causing the trouble. Is it possible to switch to Azure AD SAML configuration?

**Comment by fabianedl777** [comment]
hello @travist 

Thank you for your help, at the moment i can't change openid to saml.

**Comment by travist** [comment]
We have this in our backlog but from looking at where it is located, it seems it may be first quarter 2021 before we can get to it. Of course, it could be paid to expedite if you need it sooner.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
