### ISSUE TITLE
Question on the license change for form.io

### ISSUE THREAD

**Issue by srinisubramanian** [formio/formio#950]
This is regarding the recent change of licensing of Form.io core to OSL-v3 license for the form.io core.  

Can you please clarify/confirm that while the core license changes, the formio.js and angular-formio projects will continue to be MIT licensed?  Reason the question is coming up is that while core licensing change to OSL-v3 to protect formio, the libraries in MIT will ensure adoption.

Thanks in advance.

**Comment by randallknutson** [comment]
We are only relicensing the formio/formio repository. The formio.js and angular-formio libraries (along with other frontend libraries that are currently MIT) will remain MIT licensed. Only our server side libraries will be OSL 3.0 licensed.

**Comment by srinisubramanian** [comment]
Thanks for the clarification, that helps.  Any writeup on the rationale behind the license change?

**Comment by maulik-modi** [comment]
@travist or @randallknutson , If we are hosting this for internal users protected by Azure AD, Is it okay if we provide a link in footer saying - Powered by Form.io or we need to do something else? We are not bundling/distributing for commercial use.
