### ISSUE TITLE
Is there difference between paid subscription and open source offering? 

### ISSUE THREAD

**Issue by Joanstapleton** [formio/formio#951]
Is there a difference between a paid subscription and open source offering? 
I understand that a paid subscription is for a cloud solution. How about the difference between on-premise paid offering and open source? Are there any restrictions on use or functionality?

**Comment by denisekay** [comment]
The Form.io platform is built upon a strong OSS “core” consisting of an OSS form builder, and OSS Form renderer, and an OSS API server which can be used (and the associated helper modules like tables) to create your own system.  These three OSS components are utilized within the Form.io commercial platform which provides many additional pre-built features and capabilities that are not included within the OSS offering.  The major commercial features consist of the following:
 
**The Form.io “Developer Portal” application**
This is the main developer interface where projects are opened, and Forms and Resources are built within them.
 
**The Form.io “Non Developer Portal” application**
The Non-Developer Portal application serves as an extension of the Developer Portal application and provides an interface for  groups of non-developers to build and manage their own forms.
 
**Multi-Tenanted SaaS platform projects**
Form.io enables the ability to solution Multi-tenanted platform applications with individual management of forms, embedded form-building, and submission data management on a per tenant basis. 
 
**PDF Form-Building and Printing**
Form.io enables the ability to build PDF forms that can be presented as PDF or digital web forms, as well as printing digital web forms to PDF file outputs.
 
**Offline Forms**
Form.io enables the ability to build form-based workflow applications that operate with “Offline Mode” capability fot use cases with limited or no internet or corporate network access.
 
**User Authentication Integration**
Form.io supports the use of integrated User authorization schemes including OAuth, OpenID, SAML, LDAP and external JWT tokens
 
Developer-centric Features
Docker Container Remote Deployments of the API Server
Form Staging capabilities for Dev/Stage/Prod
Form Versioning
Audit logging
Encrypted fields
Advanced Webhooks 
SQL Database Interfaces
CORS Configuration
Report API (aggregated reports)
Developer Teams and Collaborative Team Management
 
Advanced Form-building Features
File Upload Components / Private File Uploads
Advanced Form Actions
Integrated 3rd-party API services
CSS Templating
 
If you are interested in learning more about our Enterprise Level offering, I would be pleased to schedule a 30-minute intro call to learn more about your requirements and answer and questions you have about Form.io.  Please email me at denise@form.io if you are interested in setting up a call.

**Comment by Joanstapleton** [comment]
Thank you, Denise, for the comprehensive response. One more questions:
Are we able to use the following in open source?
- offline forms
- file attachments
- digital signatures

**Comment by wag110894** [comment]
Hello @Joanstapleton 

Please find below the information you requested:

**offline forms**

Our open source has limited support for file upload as it only works when you use the URL upload mechanism that requires you to have your own proxy in order to interface with other providers. 

**file attachments**

​In order to upload to File Providers such as S3, Azure Blob, etc, this does require our Enterprise Server 

**digital signatures**

​You are able to use our Open Source libraries to use our digital signature component. 
I hope that this information helps.


Thank you,

William Gay

**Comment by walkerblackwell** [comment]
> **file attachments**
> 
> ​In order to upload to File Providers such as S3, Azure Blob, etc, this does require our Enterprise Server
> 

Does that include the Url component with the open source formio-upload server? And if Url (/file) is available for open source users how does this work now that the "private download" option no longer exists in the formio upload form component? Authentication is no longer possible. Am I missing something? Private download authenticated upload/download is nowhere to be found.

best regards,
Walker

**Comment by randallknutson** [comment]
The url file storage does not require the enterprise server. You can implement your own file storage provider and use it.

**Comment by walkerblackwell** [comment]
> The url file storage does not require the enterprise server. You can implement your own file storage provider and use it.

Thank you for the response. As it currently stands (and for the past several months) formio (docker, hosted etc) does not properly implement authentication with file/url upload with formio-upload. See bug: https://github.com/formio/formio-upload/issues/2

This commit: https://github.com/GrantStreetGroup/formio-upload/commit/dd2ae06730ffef67bbcd5bb43bb7963a722f573f did not fix the issues present and there has been no work to fix the issue or even acknowledge the issue since then. 

A looksy would be greatly appreciated as (IMO) file uploads have been broken for more than half a year as presently documented.

-Walker

**Comment by Joanstapleton** [comment]
Hi Denise,

Is PDF Form-Building and Printing included as part of open sourcing offering? What is the cost of commercial solution?

Thank you,

Joan Stapleton

Program Manager
(T):  800-859-5407 
www.planstreetinc.com
Street Smart Project Planning and Collaboration

**Comment by cmcortez** [comment]
Pricing fro our commercial offering can be reviewed here https://www.form.io/pricing. Additionally, we offer a dedicated PDF Server that you can integrate with our open source for additional details and pricing please contact support@form.io.

**Comment by calaf2** [comment]
Hi,
On the same topic, is "Email Authentication" available for open source projects? I haven't been able to get the  [[token(data.email=user)]] substitution to work.
What did I miss?
Thanks
Eric

**Comment by wag110894** [comment]
The Email Authentication is only available using on commercial offering.

**Comment by DonAmit197** [comment]
Hi,
Apologies for opening this closed one.
We are integrating your Open Source version into our application. 
Our application is based on a BPM tool and has its own database provider which is hosted in the s3 bucket. 

Now we feel about going for your commercial version after reading your above comments. 

Would be happy if we have 1:1 call to understand the enterprise version specific features.
My email : amitabhaghosh197@hotmail.com
