### ISSUE TITLE
[BUG] Export CSV in UTF-8 encoding

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#952]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 7.0.0-rc.64
- Formio.js version: :  4.9.0-rc.2

## Steps to Reproduce
1. Submit a record with special character (eg: céleri)
2. Export CSV

## Expected behavior
The data should be: céleri
## Observed behavior
The data displayed in Excel is converted to ANSI character; cÃ©leri

I am just wondering if export to default ANSI would be available from the Portal since Excel is our most common used application to read csv reports?
We have a lot of French form and we would have to convert all of the reports.

**Comment by jhen1422** [comment]
@phucduong86 
This issue seems to be isolated to Excel as other applications used to read CSV exports are displaying the correct characters.

**Comment by phucduong86** [comment]
Thanks @jhen1422 
I understand it is an Excel issue. Does formio have anything on the roadmap that would implement it as a feature? In our corporate environment it is the primary application for reviewing submissions.

**Comment by randallknutson** [comment]
If I understand correctly, we are exporting to CSV using UTF-8 which is how it should work. Excel may not be importing this correctly and that's not likely something we would change at this time. Is there something we can do without changing the format from UTF-8 to make this work?

**Comment by phucduong86** [comment]
So in our old application, we user a fairly simple Perl script to transcode the UTF-8 input into ANSI characters (cp1252)  and save into the spreadsheet. This makes sense for us because our users outside of IT wouldn't be using Notepad or VSCode to read reports.
I think it is more of a desireable feature than changing the current feature on your portal.

**Comment by randallknutson** [comment]
Thanks. At some point we could add an Excel specific export but we prefer to have more generic standards based implementations like CSV and UTF-8. We'll keep that on our backlog in case it becomes a priority.

**Comment by phucduong86** [comment]
Thank you @randallknutson.
Please let me know if you want me to close this one or just leave it for your backlog.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
