### ISSUE TITLE
[BUG] Export CSV - Does not display any data for file upload

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#953]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 7.0.0-rc/64
- Formio.js version: 4.9.0-rc2

## Steps to Reproduce
1. Create a form with fileupload field and "table view" checked
2. Create some submission
3. Review on Data tab
4. Export CSV

## Expected behavior
3. File column shows original file name
4. CSV file column should show the file name (either new or original)
## Observed behavior
3. File column shows original file name (same as expected)
4. Empty data in the file column ( empty quotes "")

![image](https://user-images.githubusercontent.com/21692768/77681557-dee5b000-6f6b-11ea-8d39-1e1704318ebd.png)

**Comment by jhen1422** [comment]
@phucduong86 Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our developer backlog. We will review this item during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by VennilaCity** [comment]
@jhen1422 Any update on this?

**Comment by VennilaCity** [comment]
@wag110894 Any update?

**Comment by wag110894** [comment]
This item still needs to be merged. We will let you know once this has been added to a build and resolved.
