### ISSUE TITLE
Keycloak Connector

### ISSUE THREAD

**Issue by srinathganesh1** [formio/formio#956]
Here is a keycloak connector to NodeJS. (IF i understand it correctly formio core is in NodeJS)
https://github.com/keycloak/keycloak-nodejs-connect/tree/master/example

Has any one tried to connect formio (Open Source) with keycloak? Using this or someother plugin?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
