### ISSUE TITLE
[Question] Custom Component

### ISSUE THREAD

**Issue by yongxue0701** [formio/formio#960]
Hi, I want to create a custom component which can be dropped and dragged from the form builder. Is it possible? 

I have cloned the form.io project from github. Is there any way to register the custom component and make it show on the form.io platform. 

I read a few solutions. But for those solutions, it seems like the custom component is registered in the client app. I want it to register in the form.io app, which can be reused/drag/drop next time. 

Please advise how I should do that. Thanks a lot.

**Comment by jhen1422** [comment]
@yongxue0701 
The following documentation should help you along 
https://formio.github.io/formio.js/app/examples/custombuilder.html
https://formio.github.io/formio.js/app/examples/customcomponent.html

**Comment by yongxue0701** [comment]
@jhen1422 

Thanks for your reply. 

I have read through the documentation earlier. From my understanding, custom builder is done within my client app. Is it possible to integrate with the current form.io application? 

It means the custom component will show up in the form.io platform. 

Or I must build my own application with my own form builder and components.

**Comment by randallknutson** [comment]
It is possible to add custom components to the hosted form.io portal but it is not yet easy to do so. We are currently working on a way of making this much easier.

First, if you go to your project settings there is an option for Custom Javascript which would like to a file. In order to use this method, you need to compile the components down into a browser ready javascript file and host this file somewhere. Then you can link to it in the project settings. 

For on premise, we are about half way through having a way to add modules (including custom components) be added to our on premise server so that the portal app and all other apps automatically include the modules from the server. This will make it a lot easier to add components but it isn't ready yet.

**Comment by yongxue0701** [comment]
@randallknutson Hi Randall, Thanks for your reply. Ok, I got it.

**Comment by yongxue0701** [comment]
@randallknutson Hi Randall, I am still working on the custom component creation. I am really new for formio. I am trying to understand the structure. Please let me know if I understand wrongly. 

I read the code of formio and I found the UI components are populated from formiojs. So from my understanding, if I can add new component in the formiojs app, then install the formiojs app with the new UI component to the formio app. In this way, the new component can be shown in the formio app. I am not sure if it is working. 

If it is working, then how can we install the formiojs with the custom component to the formio app? I tried to fork formiojs and made some changes in my own branch. Then I used "npm install username/reponame#branchname" to install the formiojs to the formio app.

But I found the module installed is different from the original one. For example, if I run "npm install", then I checked the module formiojs in the node modules, there are five files called abcde. If i run "npm install username/reponame#branchname", then there are only three files called abc inside the formio folder. That is just an example of how they are different. 

I don't think it is because I made changes to the formiojs. Even if I tried to install from the master branch, it is still different. 

Could you please give some advice? Thanks a lot!

**Comment by yongxue0701** [comment]
@randallknutson Hi Randall, I am still a bit confused. How can I integrate it with formio locally since I want to do everything locally instead of using the online formio portal? 

After we create a new module, how can we register it with formio server? I want to use formio to handle the server-side. The solution is to use the form.contrib.js file in the form builder. But how does it link back to formio server-side? So I can run the formio app and then render the custom component.

**Comment by randallknutson** [comment]
The server uses the formio-app-formio application to serve the UI. You simply need to add the module to that app and it will show up in the app.

**Comment by yongxue0701** [comment]
@randallknutson Hi Randall, thanks for the clarification. I installed the module to the formio-app-formio application by running "npm install --save @formio/contrib". It seems like it did not show up. I also tried to add the js file in the HTML file. It does not work either. Could you please point out where I misuse the module? Thanks!

**Comment by travist** [comment]
formio-app-formio is still running our legacy renderer/builder in AngularJS which is not compatible with the custom component found @ formio/contrib. We would need to upgrade this application to use the latest version of our AngularJS renderer (I believe the version is 4.x) which includes the core renderer. Then it will work with the contrib module.

**Comment by yongxue0701** [comment]
@travist Is there any application using version 4.x? Then I can test the custom component.

**Comment by travist** [comment]
Any of the Angular demos are running 4.x like this one.

https://formio.github.io/angular-demo/#/

**Comment by yongxue0701** [comment]
@travist Thanks for your reply. Does it mean currently I cannot add a custom module to formio locally?

**Comment by travist** [comment]
What do you mean "locally"?  I showed a demo application that is also available on Github. You can download that locally and add your custom component to it, so yes, it can be added locally.

**Comment by yongxue0701** [comment]
@travist Sorry, I didn't explain clearly. I want to use formio to handle the server-side. So I am confused if there is any angular app which can serve the UI of formio.

**Comment by randallknutson** [comment]
https://github.com/formio/angular-app-starterkit is a good starting place.

**Comment by yongxue0701** [comment]
Hi, Thanks for your reply. Sorry, I still have some doubts. Basically, I am trying to build a custom framework with custom components. This framework supports all the features which formio currently supports. It is just like an extension of formio. So it is supposed to allow drop and drag the custom components in the form builder. Then I hope everything can be handled by formio server app and client app. 

However, I am confused about how I can register the custom components to the formio app. 

For example, I got a custom component "A". Currently, I have known "formio-app-formio" is to serve the UI of formio. Ideally, if I can add the component "A" to "formio-app-formio", then I am able to drop and drag component "A" to build form. But "formio-app-formio" does not use the latest version of AngularJS renderer. So I cannot build on top of "formio-app-formio". 

My question is, is there any angular app with the latest version JS, which can serve the UI of formio. Or alternatively, is there any way which I can add custom UI components on top of "formio-app-formio". I would appreciate if you can give some advice on the feasibility of this idea?

**Comment by yongxue0701** [comment]
Hi, could you please give some advice on the issue above? Thanks a lot.

**Comment by travist** [comment]
I believe it would be easier to just upgrade the formio-app-formio to use the 4.x branch of the ngFormio renderer @ https://github.com/formio/ngFormio which is released off of master. This also includes the Form Builder library from our core as well and also supports all of the custom components. That being said, there is still a lot of work needed here to get this application up-to-date and we would hope that the Open Source community would assist with this effort.

**Comment by yongxue0701** [comment]
Thanks for your advice. I will go try.

**Comment by Josephalexantony-aot** [comment]
Hi there,
how to get the form._submission in formio custom component
I was trying to create a custom submission button. I have to take the from._submission._Id from  as I am using the custom submit button in the task page where the previously submitted form come for the next step through the camunda workflow.
I need to access the form and thus the submission id

const submissionId = form._submission._id;
const formDataReqUrl = form.formio.formUrl+'/submission/'+submissionId;
this is how I tried. how can I avail the form in the custom component's jsx
