### ISSUE TITLE
[BUG] Docker build error: Cannot find module '/app/main'

### ISSUE THREAD

**Issue by bohan** [formio/formio#961]
## Environment
Windows 10 Enterprise

- Hosting type
  - [] Form.io
  - [x] Local deployment (Docker version 19.03.8, build afacb8b)

- Formio.js version: 2.0.0-beta.4

## Steps to Reproduce
1. Install Docker tools. Enter formio directory 
2. From the terminal run, **docker build -t dockerid/formio-server .** 
3. Then run **docker run -it --rm dockerid/formio-server**

## Expected behavior
Expected to see:
```
Initializing API Server.
 > Mongo connection established.
 > Serving the Form.io API Platform at http://localhost:3005
```

## Observed behavior
```
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/app/main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```
## Example:
![Capture-docker](https://user-images.githubusercontent.com/977910/78652710-9b673c00-78b1-11ea-9986-fc9369445741.PNG)

**Comment by heltum** [comment]
have you found the solution ?

**Comment by bohan** [comment]
> have you found the solution ?

@heltum Not yet

**Comment by nihalmrashed** [comment]
i get the same error when am deploying to heroku post if you the solution

**Comment by heltum** [comment]
I think the problem in dockerfile. I tried to comment the WORKDIR and the error is just /main not /app/main.  I guess '/main' come from ENTRYPOINT in docker file

**Comment by kidatsy** [comment]
I was able to work around this using the following steps. It's a little hacky, but worked for me!

1. Don't use the docker container for the stack/framework (`heroku stack:set heroku-18`).
2. You will be using the regular heroku stack, so add the nodejs buildpack.
3. Heroku pipes in the port it's set up for your app in the `PORT` env variable. So in `server.js`, add the following line: `config.port = process.env.PORT || config.port;` after the line where we pull in `config` (which should look like `const config = options.config || require('config');`).
4. Set up your mongo DB somewhere and get the URL. You'll need it for the next step.
5. Set the `NODE_CONFIG` env var to: `{"mongo": "<MONGOURL>","host":"<APPNAME>.herokuapp.com","protocol":"https","domain":"https://<APPNAME>.herokuapp.com"}`, replacing `<MONGOURL>` with the mongo url you got from step 4 and `<APPNAME>` with the name of your app.

**Comment by bohan** [comment]
Hi @kidatsy , 
Thanks for the suggestion, I'll try this out and revert shortly.

**Comment by Ankit-sagar32** [comment]
Did it work? I am facing the same issue.. and how does the above solution even related to not finding '/app/main'

**Comment by bohan** [comment]
Didn't work.

**Comment by Ankit-sagar32** [comment]
OK, It seems the dockerfile is not created to support docker-compose and docker build both.
Like Step 1 would be to add the following line to copy the contents in the container:

`COPY . .`

This line of code needs to be added after the following:

`RUN npm ci --prefix=$NPM_PACKAGES`

But since it's a multi-container scenario, it's better to use docker-compose to build the mongo and formio images.

`docker-compose build`

**Comment by sinannoureddine** [comment]
> OK, It seems the dockerfile is not created to support docker-compose and docker build both. Like Step 1 would be to add the following line to copy the contents in the container:
> 
> `COPY . .`
> 
> This line of code needs to be added after the following:
> 
> `RUN npm ci --prefix=$NPM_PACKAGES`
> 
> But since it's a multi-container scenario, it's better to use docker-compose to build the mongo and formio images.
> 
> `docker-compose build`

This worked for me! thanks.

But i had to comment the following lines from Dockerfile

> RUN apk update && \
    apk upgrade && \
    apk add make=4.2.1-r2 && \
    apk add g++=8.3.0-r0

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
