### ISSUE TITLE
License change to OSL 3.0 due to Unqork?

### ISSUE THREAD

**Issue by goldsmithjim** [formio/formio#963]
It's pretty clear the no-code enterprise platform, Unqork, is primarily based on form.io

Was that the reason for the license change?

**Comment by travist** [comment]
While I can neither confirm or deny that Unqork is based on Form.io (wink), what I am willing to disclose is our motivation for the change.

Form.io's mission statement is really the origin of this library... "To become the Industry Standard for Forms and API's within Progressive Enterprise Applications"

To achieve this goal, we recognized very early on that we must have a VERY robust and powerful Open Source offering that should be non-restrictive, hence creating widespread adoption. Therefore, the chosen license must adhere to the following criteria (even if it is commercially at odds with Form.io Enterprise Product)

The license must do the following:
 - Be an OSI approved license (https://opensource.org/).
 - Allow anyone to use the platform for Free.
 - Allow anyone to use the software within a Commercial product, without also requiring them to Open Source their code that uses it, like GPL requires. Even if this means a competitive product.

What we DO NOT want the license to allow:
 - Allow a company to utilize this platform, make modifications to it or extend it, and then NOT disclose those changes or make attribution to Form.io.

OSL provides the users of this platform a good balance of freedom while also ensures that our mission statement can be achieved. With OSL, you can still create your own commercial product on this software. You can even create a competitive product. You don't even need to Open Source any proprietary code that uses this product (like GPL requires). What you cannot do, however, is extend this software and not disclose the use of Form.io as well as the source of those extensions. If this is still too restrictive, then we have a Commercial license available that does allow more flexibility. 

I hope this clears things up.
