### ISSUE TITLE
[BUG] Select Component showing value as label when option is selected

### ISSUE THREAD

**Issue by przzz27** [formio/formio#966]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: formiojs v4.10.0-beta.3.1
- Frontend framework: Vanilla Javascript
- Browser: Google Chrome
- Browser version: 80

## Steps to Reproduce
1.  Add a select component to your form
2.  Configure the data source as URL
3.  Set a limit of 10 records
4. Set search parameter name as "search"
5. Configure the value property (ex: id)
6. Configure the item template to show another field (ex: `<span> {{item.name}} </span>` )
7. Either select an option by using the search input or from the infinite scroll

## Expected behavior
Select component should show the name/label of the option selected

## Observed behavior
Let's say we used the infinite scroll or the search input to find the following option
`<option value="123">ABC</option>`
When the option is selected, it should show a label "ABC" with a value "123" on the component, but instead it shows "123" for both. `<option value="123">123</option>`
## Example
Added [JSFiddle](https://jsfiddle.net/am8yc5s7/) example, search for "Blake Kunze"
![image](https://user-images.githubusercontent.com/61523021/79004136-f8106400-7b08-11ea-96bf-032097c56e99.png)

![image](https://user-images.githubusercontent.com/61523021/79004152-00689f00-7b09-11ea-9094-fca782ec8ea4.png)

**Comment by wag110894** [comment]
Hello Josue,

You have Value Property set to id. Take this out and then it will work correctly.

**Comment by przzz27** [comment]
> Hello Josue,
> 
> You have Value Property set to id. Take this out and then it will work correctly.

Hi William
Maybe i'm misunderstanding something, the inner text of the option selected and the value should be two different things, but it seems like the value property overrides the item template, why is that?

Removing the id value property as suggested appends an object to the value, and in the submission data we can see the text of the option selected, but i want to save the value property, which must be an id.
![image](https://user-images.githubusercontent.com/61523021/79258696-62ded980-7e40-11ea-8d9c-ada60c17886a.png)
![image](https://user-images.githubusercontent.com/61523021/79259015-e00a4e80-7e40-11ea-9d7b-6600efe66adb.png)


As i said, this issue only happens when the option selected came either by using the infinite scroll feature, or by searching it with the input.

Selecting "Abbigail schneider" or any of the first 10 records of the dropdown results in the expected behaviour.

![image](https://user-images.githubusercontent.com/61523021/79256804-7d638380-7e3d-11ea-90b8-e220f7cd1f8f.png)

![image](https://user-images.githubusercontent.com/61523021/79259420-8a827180-7e41-11ea-892c-8106c426aa2b.png)


But searching for "Blake Kunze" or scrolling down to that option causes this unexpected behaviour
![image](https://user-images.githubusercontent.com/61523021/79257717-e1d31280-7e3e-11ea-9abd-2dab767b2801.png)

This behavior can be replicated in the jsfiddle i provided.
as a note, the endpoint returns an array of objects like this:
`[ {"id": 123, "name": "Some name"}, { ...n}]`
Thanks for responding, hope this helps

**Comment by randallknutson** [comment]
This is a tricky case for the select component that we don't have a good solution to right now. The issue is that if you set the value property to "id" then the only thing that is stored in the submission is the ID. The problem comes where we need to render the template since the only data available at that time is the id and not the full object. This happens especially when using urls and picking a value on the second page. This is difficult to fix since if all we have is an id, how do we look up the rest of the object values? The only url we have is the index url and we don't know what page it is on. We would have to start querying the url and try to find the id which would be really slow.

The better solution is to save the whole object and not just the id so that all the data is available to render. Either that or be content with only rendering whatever is stored in the database when viewing the data.

**Comment by przzz27** [comment]
> This is a tricky case for the select component that we don't have a good solution to right now. The issue is that if you set the value property to "id" then the only thing that is stored in the submission is the ID. The problem comes where we need to render the template since the only data available at that time is the id and not the full object. This happens especially when using urls and picking a value on the second page. This is difficult to fix since if all we have is an id, how do we look up the rest of the object values? The only url we have is the index url and we don't know what page it is on. We would have to start querying the url and try to find the id which would be really slow.
> 
> The better solution is to save the whole object and not just the id so that all the data is available to render. Either that or be content with only rendering whatever is stored in the database when viewing the data.

Hi Randall,
I downloaded the submission data for that specific form as JSON and you're right, the ID and the value are stored in the form submission when there's no value property set. Downside to this is that there's no way on the dashboard to take a look at the object data stored to it.

My issue was mainly with the front-end, when the users are just looking at the form, i can clearly see that the label is working correctly before selecting it, see:
![image](https://user-images.githubusercontent.com/61523021/79286196-b9660b00-7e74-11ea-81b6-043cb7b324a6.png)



but the moment an option is set then the label its replaced with the value instantly, personally i don't mind looking at just the id in the submitted form data, i don't know if that's the case for everybody.

Do you think it would be viable to manually edit the label by adding a method on the "onChange" event of the form? Just to achieve my desired functionality
Thanks for responding

**Comment by randallknutson** [comment]
The view should not be replaced with the value when selected. That seems like a bug but we haven't seen anything like that recently though.

**Comment by przzz27** [comment]
I was looking at the code, the select component uses two files to work:

- Select.js
- Choices.js

On select Js there's a function called "addCurrentChoices" it recieves 3 parameters

- **values**: An array of selected values, can retrieve more than one if componet is used as multiselect
- **items**: An array of items that will become options
- **keyvalue**: Might be a boolean/integer value, didnt find a line of code that sets it


When selecting an option it checks if the selected option exists on the **items** parameter (Strange enough this item list only has the first 10 options, not the other ones that came by the search input or infinite scroll, sometimes infinite scroll works, sometimes doesnt), if the item exists it adds the option with the configured template and value.
If not, the option is added but it uses the "value" for both the option value and item.

![image](https://user-images.githubusercontent.com/61523021/79394875-4f5d6c80-7f2d-11ea-8616-0cfb573547c2.png)

**Comment by wag110894** [comment]
Can you try this using version 4.10.0-beta.6 and see if the issue still persists. 

Looking forward to your feedback.

**Comment by przzz27** [comment]
> Can you try this using version 4.10.0-beta.7 and see if the issue still persists.
> 
> Looking forward to your feedback.

Modified jsfiddle, problem still persist

**Comment by wag110894** [comment]
We are now not seeing the issue with the new version of the JSFiddle, which looks like it is running latest: 4.9.20.

**Comment by przzz27** [comment]
My bad, updated the fiddle to use the beta version, here is a recording of the issue

![issue](https://user-images.githubusercontent.com/61523021/79767539-580fc300-82de-11ea-9b0a-b32c1ec087eb.gif)

**Comment by tnorthcutt** [comment]
@randallknutson @wag110894 Any updates on this? This is a showstopper bug for us, since we have a long list that users need to be able to search through.

The jsfiddle that @przzz27 posted above shows a clear reproduction of this happening. Could you perhaps point us to a correct way of doing this that doesn't introduce this bug?

**Comment by wag110894** [comment]
@tnorthcutt @przzz27 We have had reports of issues with running our 4.10x builds with the select components. This item has been resourced. We will let you know once the issue has been resolved.

**Comment by waterbuckit** [comment]
Any news on this? I'm running 4.12.7 and I'm still seeing this issue, I'm just getting the value (id) when the option is selected from a long list.

**Comment by wag110894** [comment]
This issue has been resolved. Please upgrade to latest version of formio.js.

Thank you.
