### ISSUE TITLE
[SECURITY] request package has been deprecated

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#972]
NPM request package has been deprecated since February 11th, 2020.  A new library must be used in its place (alternatives are discussed here: https://github.com/request/request/issues/3143). `node-fetch` could be the obvious alternative due to the fact that  the Form.io SDK uses the Fetch API, this way consistency is maintained between repos.

Changes need to be done in the following files:

---

### src/actions/EmailAction.js

Download email template

https://github.com/formio/formio/blob/be8e837f03f0dbd7abdfc4e28a6ad556485090cb/src/actions/EmailAction.js#L207

---

### install.js

Download custom project

https://github.com/formio/formio/blob/be8e837f03f0dbd7abdfc4e28a6ad556485090cb/install.js#L52

---

### src/db/index.js

Download mongo SA certificate

https://github.com/formio/formio/blob/be8e837f03f0dbd7abdfc4e28a6ad556485090cb/src/db/index.js#L111

---

### src/util/util.js

Utilities request denodeify function

https://github.com/formio/formio/blob/be8e837f03f0dbd7abdfc4e28a6ad556485090cb/src/util/util.js#L495

---

### src/middleware/recaptcha.js

Request for Google ReCaptcha challenge

https://github.com/formio/formio/blob/be8e837f03f0dbd7abdfc4e28a6ad556485090cb/src/middleware/recaptcha.js#L15

---

### src/resources/LegacyValidator.js

Remote resource validation request

https://github.com/formio/formio/blob/be8e837f03f0dbd7abdfc4e28a6ad556485090cb/src/resources/LegacyValidator.js#L339

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
