### ISSUE TITLE
[BUG] Login requires encrypted text value instead of password

### ISSUE THREAD

**Issue by przzz27** [formio/formio#975]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: Apache (httpd-2.4.35-win64-vc15)
- Formio.js version: 4.9.21
- Frontend framework: Vanilla JS
- Browser: Google Chrome
- Browser version: 81.0.4044.113 (Official Build) (64-bit) (cohort: 81_Win_92)

## Steps to Reproduce
1. Create a new user
2. Setup reset password forms on form.io, [see this article](https://help.form.io/tutorials/walkthroughs/authentication/#portal-email-reset)
3. Setup a login form for the user resource, [see this article](https://help.form.io/userguide/actions/#authentication-action)
4. Request a password reset for your user (You should get an email with a token)
5. Reset your password
6. Try to log in using your new password 

## Expected behavior
1. Sign in using the existing user with a new password

## Observed behavior
1. Can't sign in using the new password
2. You can sign in using the encrypted value of the password

## Example
Here's an example of the code used for the reset password functionality, [based on this example.](https://help.form.io/tutorials/walkthroughs/authentication/#password-reset-app)

After submitting the reset form the password and verify password fields get overriden by something that i can assume is the encrypted version of the password i just set.

Reset password code:
```javascript
  window.onload = function() {
 	Formio.createForm(document.getElementById('formio'), 'https://<YOUR FORMIO PROJECT URL>/<USER RESOURCE NAME>').then(function (formio) {
 	    let query = {}
	    location.search.substr(1).split("&").forEach((item) => {
	      query[item.split("=")[0]] = item.split("=")[1] && decodeURIComponent(item.split("=")[1]);
	    });

	    //GET TOKEN
	    const hasToken = localStorage.getItem('formioToken');
	    if (query['token'] && !hasToken) {
	      Formio.setToken(query['token']);
	      localStorage.removeItem('formioAppUser');
	      localStorage.removeItem('formioUser');
	    }

	    //RESET PASSWORD
	    formio.on('submit', function (submission) {
	    	Formio.currentUser().then(function (user) {
	    		Formio.setUser(user)
	    		user.data.password = submission.data.password
	    		const userFormio = new Formio('https://<YOUR FORMIO PROJECT URL>/<USER RESOURCE NAME>/submission/' + user._id);
	    		userFormio.saveSubmission(user).then(function (userSubmission) {
	    			window.location = "<URL TO REDIRECT AFTER PASSWORD CHANGE>"
	    		})
	    	})
	    })
 	});
  };
```

Here is a gif with an example of me using "abc@1234" as a password.
![password issue](https://user-images.githubusercontent.com/61523021/79926552-0d7f6b00-83f2-11ea-860e-a31336e04334.gif)

trying to login in with the new password (abc@1234):
![image](https://user-images.githubusercontent.com/61523021/79926593-2f78ed80-83f2-11ea-9b6c-daef45e54149.png)

trying to login using the encrypted/hashed password ($2a$10$m3LuSBWse/RxSFB6uPPd9ezNlLcdDAt9MWP27M010fI1P8DGAIfBe)
![image](https://user-images.githubusercontent.com/61523021/79926650-4c152580-83f2-11ea-83c1-bc586c9c60cd.png)

**Comment by przzz27** [comment]
I found a few workarounds for this, number one is to render the form programatically using a JSON object, as explained in [here](https://github.com/formio/formio.js/wiki/Form-Renderer).

```javascript
Formio.createForm(document.getElementById('formio'), {
          components: [
            {
              type: 'password',
              key: 'password',
              label: 'Password',
              placeholder: 'Password',
              input: true
            },
            {
              type: 'password',
              key: 'verifyPassword',
              label: 'Verify password',
              placeholder: 'Repeat your password',
              input: true
            },
            {
              type: 'button',
              action: 'submit',
              label: 'Submit',
              theme: 'primary'
            }
          ]
        }).then(function (formio) {
        	formio.on('submit', function(submission) {
		    	Formio.currentUser().then(function (user) {
		    		Formio.setUser(user)
		    		user.data.password = submission.data.password
		    		const userFormio = new Formio('<YOUR PROJECT URL>/<YOUR RESOURCE />' + user._id);
		    		userFormio.saveSubmission(user)
		    	})
        	})
        });
```

The other is to do this logic inside a beforeSubmit hook, i don't like this approach but it worked
```javascript
Formio.createForm(document.getElementById('formio'), '<YOUR FORM URL>', {
 		hooks: {
 			beforeSubmit: (submission, next) => {
		    	Formio.currentUser().then(function (user) {
		    		Formio.setUser(user)
		    		user.data.password = submission.data.password
		    		const userFormio = new Formio('<YOUR SUBMISSION URL>' + user._id);
		    		userFormio.saveSubmission(user)
		    	})
				next()
 			}
 		}
 	}).then(function (formio) {
 		let query = {}
	    location.search.substr(1).split("&").forEach((item) => {
	      query[item.split("=")[0]] = item.split("=")[1] && decodeURIComponent(item.split("=")[1]);
	    });

	    const hasToken = localStorage.getItem('formioToken');
	    if (query['token'] && !hasToken) {
	      Formio.setToken(query['token']);
	      localStorage.removeItem('formioAppUser');
	      localStorage.removeItem('formioUser');
	    }

	    formio.on('submit', function (submission) {
	    	alert('user updated')
	    })
 	});
```

**Comment by wag110894** [comment]
Thanks for reaching out!

We are unable to replicate this issue in regard to resetting passwords not allowing you to type in the new password. You may need to refresh the page. If the encrypted text value is working, once you log in, you can go into your User Settings at the top to retype your password there.  We do offer Support Packages that are for training, support, or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. Please let us know if you are interested by contacting support@form.io.

Thank you,

William Gay

**Comment by przzz27** [comment]
> Thanks for reaching out!
> 
> We are unable to replicate this issue in regard to resetting passwords not allowing you to type in the new password. You may need to refresh the page. If the encrypted text value is working, once you log in, you can go into your User Settings at the top to retype your password there. We do offer Support Packages that are for training, support, or development services. The hours can be used in one-hour increments at your convenience over a 90 day period. We will assign one of our senior developers to work directly with you in online sessions. Please let us know if you are interested by contacting [support@form.io](mailto:support@form.io).
> 
> Thank you,
> 
> William Gay

Hi William
I'm changing the user/resource password on the "submit" event/trigger.
the issue is that when submitting a form using password components, their values get overriden by what i assume it's the encrypted/hashed value of the text, and that is the value being passed to the submission.
 
That happens if the form comes from the dashboard.

Rendering the form programatically doesn't cause this behaviour.

I'll keep in mind the offer.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
