### ISSUE TITLE
[BUG] CSV Exporter not working properly with Edit Grid, Data Map and Tree components

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#980]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: `any`
- Formio.js version: `any`
- Frontend framework: `any`
- Browser: `any`
- Browser version: `any`

## Steps to Reproduce

> This can be reproduced in both `formio/formio` and `formio/formio-enterprise` (commercial).

1. Create a new form with an **Edit Grid**, **Data Map** and **Tree** component with a **Text Field** component in each.
2. Submit data to that form
3. Export the data in CSV format
4. (bonus) Export the data in JSON format

## Expected behavior

CSV exporter should ignore the nested component column (i.e. `editgrid`, `dataMap` and `tree` should not be a column header). 

The **Data Map** component should be transformed in two columns: `datamap.keys` and `datamap.values`, both of them treated as **Text Field** component with the `mutliple` flag.  **Data Map** values may evolve in the future to provide data value type (which is somehow implemented but not available in the builder dialog).  In that case, `datamap.values` should be treated as the corresponding values data type.

The **Tree** component is currently still presenting some bugs (even in the next portal data is not saved). A flatten tree representation will require to calculate the maximum structure depth, which will cause variable columns between different exports.  Even more, for each depth level, there will be as many columns as components. 

## Observed behavior

A column with the **Edit Grid** component key is generated with no usable information (nested component columns are generated correctly).

An empty column is generated for the **Data Map** component.

For the **Tree** component there is not much to do as the data it is not stored anyways (check output from step 4).

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
