### ISSUE TITLE
[Question] Help: Documentation: how can i hide unused form elements

### ISSUE THREAD

**Issue by sayanamanikanta** [formio/formio#983]
I'm using formio in my angular 7 application 
Is there any way to hide the unused form elements that means i'm not using file upload control in my entire app how can i hide that form control.
Can any one suggest me is there any way to do that

**Comment by randallknutson** [comment]
Here is an example of hiding components: http://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by sayanamanikanta** [comment]
> Here is an example of hiding components: http://formio.github.io/formio.js/app/examples/custombuilder.html

Thanks for the help.

is there any way to hide some of the options for the components similarly.
In the bellow image if i want to hide the 'Prefix' and 'Suffix' from the 'Text Field Component'

![Capture](https://user-images.githubusercontent.com/60693788/80795318-c6476600-8bb9-11ea-9a4c-f1d800266f9b.PNG)

**Comment by randallknutson** [comment]
In that example you can see the changes to editForm where you can set ignore on parts of the edit form. You can do that for the prefix and suffix fields.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
