### ISSUE TITLE
[QUESTION] Is it possible to implement an API preflight check (trasnactions)?

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#985]
Bulk imports have always been an issue, mainly because when you are importing a lot of data you want to make sure all data is consistent and valid.  MongoDB puts another challenge in the sense that it lacks the full capabilities of relational databases transactions, which could make rollbacks easier.

### The case is the following:

- The user wants to import multiple submissions at once.
- The user wants to know if all of the submissions are valid before writing to database
- The user wants to know all validation errors (or at least which submissions are invalid)
- The user wants data to be saved only if all submissions are valid

### How could this be achieved?

A query string parameter or header `x-query` could be used to indicate the API server to skip committing to database.  This way the server will return an empty 200 response if valid or the standard 400 response otherwise.  This way, the user may fire multiple API request, one per submission and wait for all responses.  With them, the user can check which submissions are invalid, without saving any data to the database.

### Workarounds

The current workaround consists on creating a "headless" form and trigger form validation with each submission.  The caveat of this approach is that it requires a lot of memory which could not be available in client applications (such as browsers).

### Questions

- Is there any kind of benchmark on how many requests (validations) can the formio API server handle (per standard unit of server resources - fixed cpu / memory)?
- Is bulk import being considered in the feature? (if not, why?)
- Is there a way to optimize the use of resources with what is available?

**Comment by airarrazaval** [comment]
Can the `dryrun` query string parameter be used for this? 

https://github.com/formio/formio/blob/9d4863d9474d147b0c16d9cdd5c417ac9dba56e8/src/middleware/submissionHandler.js#L146

**Comment by airarrazaval** [comment]
> Can the `dryrun` query string parameter be used for this?
> 
> https://github.com/formio/formio/blob/9d4863d9474d147b0c16d9cdd5c417ac9dba56e8/src/middleware/submissionHandler.js#L146

yes it can

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
