### ISSUE TITLE
[BUG] Select Boxes default value does not update properly in Panel (Wizard Mode)

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#989]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 6.9.31 (Application: 7.0.3, Renderer: 4.9.22)
- Formio.js version: 4.9.26

## Steps to Reproduce
1.  Create a new Wizard form
2.  Add a Select Boxes Component
![image](https://user-images.githubusercontent.com/21692768/81448176-f5c31900-914b-11ea-98b8-838fe281b2de.png)

3.  Check the form definition:

![image](https://user-images.githubusercontent.com/21692768/81448938-3b341600-914d-11ea-99af-3641f15f65c3.png)

4. Create a submission and check submitted data:

```
selectBoxes1: {1: false, 2: false, "": false}
```

5. Go back to the form and update the Select Boxes Component with different label/value:

![image](https://user-images.githubusercontent.com/21692768/81448521-7da92300-914c-11ea-9128-208048cabe2d.png)

5. Check the form definition (note the defaultValue has changed) :

![image](https://user-images.githubusercontent.com/21692768/81448637-b517cf80-914c-11ea-8a6c-6097d9414f4c.png)

6. Create a submission and check submission data:

```
selectBoxes1: {1: false, 2: false, 3: false, 4: false, "": false}
```

## Expected behavior
1. Default value should be updated according to component Data.
2. Submission data should be
before update

```
selectBoxes1: {1: false, 2: false}
```
or
after update

```
selectBoxes1: {3: false, 4: false}
```

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
