### ISSUE TITLE
[QUESTION] Making call to URL based on data in another field

### ISSUE THREAD

**Issue by bryanpost** [formio/formio#990]
Hello,

I have a form where I would like several secondary fields to populate based on a primary field entry. The primary field is populated by URL call, and the secondary fields will use the primary field data as a parameter is their own URL calls.

## Environment
- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: I think 1.60.3?  Not really sure where to see this, either in the web GUI on in the EC2. I launched this container in October of 2019. I am not sure if I need to update or upgrade anything. We use that server for multiple live forms, so I'm scared of losing our existing forms and data.
- Formio.js version: I think 4.3.3? Same as above. Not sure where to check, terrified of updating anything.
- Frontend framework: Vue.js
- Browser: Vivaldi
- Browser version: 3.0.1874.38 (Stable channel) (64-bit)

Is it possible/safe for me to "upgrade" my deployment without losing our forms and data? I'm pretty new to containers, but have decent AWS networking experience. I have a public link of the steps I took to configure this environment that I could share via DM. 

## Steps to Reproduce
1. I have a field "employee_badge". To make this field pull a list of current employees, it is a "SELECT" field. The configuration is as so (this URL returns fake data, the URL is available over DM):
![formio_API_issue_1_badge_select_config](https://user-images.githubusercontent.com/8421608/81749966-426f6280-9472-11ea-8748-85a95fe184f6.png)

2. One that field is set, I would like to pass that value to other fields to use for their API calls. Please note that I primarily use the GUI for form.io, and do not have strong custom JS for making custom form and backend elements.

## Expected behavior
1.) I expected to be able to enter this "data.employee_badge" field into other "Select" form components. Or be able to create a "Resource" that grabs live data from a URL via the GUI. 

## Observed behavior
1.) We were able to use this example  https://github.com/formio/formio.js/issues/1321 to get it to work, but it was quite cumbersome. The final working code was:
```js
var makeRequest = function (url, method) {
	// Create the XHR request
	var request = new XMLHttpRequest();
	// Return it as a Promise
	return new Promise((resolve, reject) => {
		// Setup our listener to process compeleted requests
		request.onreadystatechange = () => {
			// Only run if the request is complete
			if (request.readyState !== 4) {return;}
			// Process the response
			else if(request.status >= 200 && request.status < 300) {
				// If successful
				resolve(request);
			} else {
				// If failed
				reject({
					status: request.status,
					statusText: request.statusText
				});
			}
		};
		// Setup our HTTP request
		request.open(method || 'GET', url, true);
		// Send the request
		request.send();
	});
};

const url='MY_URL/ReturnEmployeeInfo?badge=' + data.employee_badge;

console.log('got here');
show = (data.employee_badge !== null && data.employee_badge !== '');

if(show){
	console.log('asking for a name');
	makeRequest(url)
	.then((posts) => {
		console.log('Success!', JSON.parse(posts.response));
		instance.updateValue(JSON.parse(posts.response).last_name);
	})
	.catch((error) => {
		console.log('Something went wrong', error);
	});
}
```
## Questions
Is this the only way to accomplish this task? Is it not possible through the GUI in any way? Would this have been possible to do using Resources? And finally, is there a way for me to upgrade my environment without losing my form data?

**Comment by randallknutson** [comment]
You can use the data from the first select by referencing it within the datasource url of the second select.

Set it to something like: https://MY_URL/employees?filter={{data.firstSelect}} and it will replace the value from first select. You then want to set "Refresh Options On " to the first select so that it will trigger the request whenever the first select value changes.

**Comment by bryanpost** [comment]
Thank you @randallknutson! This is helpful. I'm able to (I think) pass the variable successfully with the URL field set to `https://MY_URL/Prod/ReturnEmployeeInfo?badge={{ data.employee_badge }}`.

I'm not able to isolate a particular field for the SELECT items, however. The resulting API call is:
`{
  "badge": "50010",
  "first_name": "B.J.",
  "last_name": "Armstrong",
  "location": "Iowa",
  "seniority_date": "1967-09-09"
}`

I'd like just "Armstrong" to be available in the select. I've tried several configurations, including:
![formio_API_issue_1_last_name_select_config](https://user-images.githubusercontent.com/8421608/81838535-dd684b00-950b-11ea-9029-b592f9b697e4.png)


But this results in all results being available through the select:
![formio_API_issue_1_last_name_select_results](https://user-images.githubusercontent.com/8421608/81837572-a3e31000-950a-11ea-844c-04ef64fa2f07.png)

Is something wrong with my confiuguration? I don't fully understand the "Data Path" and "Value Property" fields. I've read the docs [here](https://mwh2vaq9p3.execute-api.us-east-1.amazonaws.com/Prod/ReturnEmployeeInfo?badge=), but my options don't match the example.

Finally, I'd like to have this select field display the option it retrieves from the URL call. Is this possible? Or is the above Text Field Calculated Value code the only way to do that? 

P.S. Can you use {{ data.some_field }} anywhere in the Formio GUI? I apologize if I missed that in the docs.

**Comment by travist** [comment]
The issue is that the select component expects that the results returned from the api is an array of entries, and you are just returning an object, and it is iterating over the keys of that object. We would recommend that you could also use the Data Source component to pull information into an object based on the values of another field. This component can be found @ https://next.form.io

**Comment by navateja424** [comment]
This is what I am trying as well, in the form when a select an item from the dropdown it should call an API and it should populate the label below that dropdown. I can call that API from postman and I do get the response but not sure how to populate the value I need in the input field. @travist Thanks in advance!

**Comment by MarcelAleza1** [comment]
I'm having same issue, i'm calling and API that returns an object, the object contains an array.
FormIo graphical user interface doesn't find the array to populate in the dropdown

Here is the result of my API 
`
{
    "status": "OK",
    "statusCode": 200,
    "data": [
        {
            "id": 1,
            "name": "Item 1",
        },
        {
            "id": 2,
            "name": "Item 2",
        },
        {
            "id": 3,
            "name": "Item 3",
        },
        {
            "id": 4,
            "name": "Item 4",
         }
    ]
}
`
Here is how i'm telling FormIo GUI to find the array in path 'data'
Data Path 
`
response.data
`

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
