### ISSUE TITLE
[Question] What are the differences between the different release numbers(v1.79.0 vs v3.0.0-m.15)?

### ISSUE THREAD

**Issue by davidkohcw** [formio/formio#997]
Hi!

I see in the past few days there have been recent releases based on v1.79.0 and v3.0.0-m.15.

I'm a bit confused as to what are the main differences between them and what is the recommended version?

Thanks so much for the library!

**Comment by randallknutson** [comment]
v1.79.0 is the officially released version the x-m.x versions are milestone builds of new versions and are only for testing out new functionality but are works in progress, not even ready for alpha.

**Comment by davidkohcw** [comment]
Thanks so much for the quick reply and the clarification of the different version numbers :) @randallknutson
